### ISSUE TITLE
Grundpaket: Epic Basissystem für SAC

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_sac_cas#1]
Ziel: Aufbau Grundpaket/Umgebung für den SAC

Inhalt:

- [x] Neues Repo erstellen: hitobito_kunde About ergänzen
- [x] Hauptbranch ist zur Zeit `main` ggf noch umbenennen
- [x] Wagon erstellen #4 
- [x] Setup der Integrationsumgebung #2 
- [x] Gruppenstruktur, Rollen, Berechtigungen #5 
- [x] Visuelle Anpassungen #6 
- [x]  Resourcen bestellen bei /sys
- [x] Mehrsprachigkeit #7 
- [ ] ~~Produktionsumgebung #3  ~~
- [x] Github Actions
- [ ] ~~DNS Einstellungen Kundenseite~~
- [ ] ~~Wartung und Support~~
