### ISSUE TITLE
EVENTS: Preis auf Teilnahme bearbeiten

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#1006]
Als Kursadmin möchte ich die Preiskategorie einer Teilnahme bearbeiten können.

- [x] Neu soll im Bearbeiteformular oberhalb "Effektive Tage" ein Dropdown mit den konfigurierten Kurspreisen angezeigt werden. Label "Kosten". Zur Auswahl stehen alle Preise des Kurses, welche nicht leer sind, in der Form "Mitgliederpreis CHF 499.00". Es gibt ausserdem eine leere Option, falls kein Preis gesetzt ist (Leitungsteam). Das Feld ist ebenfalls bei der Neuerstellung einer Teilnahme vorhanden.

- [x] Der gewählte Preis und die gewählte Preiskategorie werden auf der Teilnahme gespeichert. Falls Preise auf dem Kurs nachträglich angepasst werden, soll dies keinen Einfluss auf die Preise der bereits vorhandenen Teilnahmen haben.

- [x] Falls beim Bearbeiten der Preis auf der Teilnahme nicht mit dem Preis der Kurskategorie auf dem Kurs übereinstimmt, wird zuoberst im Dropdown eine weitere Option mit dem aktuellen Preis der Teilnahme hinzugefügt.

- [x] In der Teilnahme Show Ansicht wird der Preis oberhalb "Effektive Tage" mit Label "Preis" und Wert in der Form "Mitgliederpreis CHF 499.00" angezeigt.

# ToDo

- [x] View/Controller anpassen
- [x] Specs schreiben
- [x] Mit angemessener Rolle "durchklicken"

**Comment by tobiasstern** [comment]
### Notizen zu meinen Testfindings (Bitte nicht gleich umsetzen :) )

Bei Kurskader-Anmeldungen braucht es noch die Option, keine Kosten zu haben, vgl. Spez. oben:
>`Es gibt ausserdem eine leere Option, falls kein Preis gesetzt ist (Leitungsteam). Das Feld ist ebenfalls bei der Neuerstellung einer Teilnahme vorhanden.`
Am besten bei Kurskader (Leitung/Hauptleitung) eine Option "Keine Kosten" ins Dropdown einfügen.

Die nachträglichen Preisänderungen wurden gut umgesetzt. Ich möchte aber eine Textanpassung der Option "Ehemaliger Mitgliederpreis" zu "Bisheriger Preis", weil "ehemalige" auch mit ehemaligen SAC-Mitgliedern in Verbindung gebracht werden kann.
![Image](https://github.com/user-attachments/assets/890c8e78-1c8d-401e-ac34-5a4f821aa5d8)

**Comment by tobiasstern** [comment]
> > Ich möchte aber eine Textanpassung der Option "Ehemaliger Mitgliederpreis" zu "Bisheriger Preis", weil "ehemalige" auch mit ehemaligen SAC-Mitgliedern in Verbindung gebracht werden kann.
> 
> @tobiasstern Sollte die bisherige Option immer "Bisheriger Preis" heissen oder weiterhin `Bisheriger + Bezeichnung` (zb. "Bisheriger J&S P-Normalpreis") behalten?

Weiterhin `Bisheriger + Bezeichnung` (zb. "Bisheriger J&S P-Normalpreis") ist gut.

**Comment by tobiasstern** [comment]
Sehr schön, danke!
