### ISSUE TITLE
PEOPLE: `cleanup1_emails` bereinigt Personen Emails

### ISSUE THREAD

**Issue by openscript** [hitobito/hitobito_sac_cas#1009]
## Anpassungen in `nav1-1_people`

wird mit https://github.com/hitobito/hitobito_sac_cas/issues/1079 umgesetzt

## Umsetzen von `cleanup1_emails`

**VORERST NICHT UMSETZEN!**

Während dem `nav2-1_roles` Import wird die Familienhauptperson die Haupt-Emailadresse bekommen und für alle anderen Familienmitglieder, sollte die E-Mail gleich sein, wird die Emailadresse unter `additional_emails` abgelegt.

Bsp.:
 - Es wird eine Person mit der E-Mail Adresse `hans.kanns@example.com` als Haupt-Emailadresse importiert.
 - Später wird versucht eine weitere Person mit der E-Mail Adresse `hans.kanns@example.com` zu importieren. Diese E-Mail Adresse wird unter `additional_emails` abgelegt.
 - Familienhauptperson bekommt Hauptemailadresse gesetzt.

Zudem gibt es Fälle, bei dem es mehrfache Emails in Kombination von Personen und Firmen gibt. Dabei sollen die Personen jeweils die Hauptemail zugewiesen bekommen.

Falls mehrere Personen die gleiche E-Mail besitzen, obwohl Sie nicht in einer Familie sind, soll ein Fehler im Report ausgegeben werden.

### Ablauf

1. Alle `additional_emails` mit dem Label `Duplikat` finden
1. Alle zugehörigen Hauptemail finden
1. Hauptemail nach folgenden Prioritäten (höchste Priorität zuerst) neu setzen:
    1. Verifizierte Personen
    1. Familienhauptperson
    1. Natürliche Personen
1. Falls eine Hauptemail vergeben werden kann, sollen alle Duplikate davon in `additional_emails` gelöscht werden.
1. Falls mit diesen Prioritäten keine Hauptemail vergeben werden kann, muss ein Fehler ausgegeben werden.

# Idee

- Familienhauptperson bekommt die E-Mail Adresse

# Tech-Spec

- `hitobito_sac_cas/app/domain/sac_imports/person_entry.rb` auf E-Mail Duplikate prüfen einbauen
- `hitobito_sac_cas/app/domain/sac_imports/people_importer.rb` zusätzliche `warnings` Spalte einbauen

# ToDo

- [ ] `nav1-1_people` Import anpassen, damit Duplikate in `additional_emails` abgelegt werden
- [ ] `cleanup1_emails` Aufräumen umsetzen
- [ ] `cleanup1_emails` Report umsetzen
- [ ] Specs schreiben

**Comment by rnestler** [comment]
Update von Andreas Gurtner: Es soll nur der erste Teil umgesetzt werden, also anstatt einen Fehler eine neue Person als Duplikat erfassen mit `additional_email`.
