### ISSUE TITLE
PEOPLE: Registrierungsformular Zusatzdaten

### ISSUE THREAD

**Issue by tobiasstern** [hitobito/hitobito_sac_cas#101]
### Eintrittsdatum angeben
Bei der Neuanmeldung muss das neue Mitglied auswählen, per wann es eintreten will. Grund ist, dass es Vergünstigungen geben kann, wenn das Mitglied spät im Jahr eintritt, und je nach dem möchte man diese Vergünstigung bereits früher im Jahr nutzen.

Die genaue Logik wird noch abgeklärt. Hypothese für den Moment:
Wenn der 1. Juli des aktuellen Jahres bereits vorbei ist, ist die Option 1. Juli deaktiviert.
Wenn der 1. Oktober des aktuellen Jahres bereits vorbei ist, ist die Option 1. Oktober deaktiviert.

### Eintrittsgrund angeben
Bei der Neuanmeldung beim SAC muss das neue Mitglied einen Eintrittsgrund angeben. Gemäss https://saccas.atlassian.net/browse/HIT-146 soll:

- Die Auswahl des Eintrittgrunds per Radio Button -Auswahl möglich sein 
- Die Eintrittsgründe werden zentral unter den Globalen Einstellungen verwaltet und sind mehrsprachig (de, fr, it, en)

### Weitere Angaben
Siehe Mockup. Genaue Optionen sind noch zu klären, aber Newsletter und Privacy Policy kommen sicher mal hierhin. Fürs MVP können die Statuten, Beitragsreglement und Datenschutzerklärung auch in ein einziges Privacy Policy PDF kombiniert werden.

### Mockup
![Screenshot 2023-11-30 at 18-18-18 SAC Hitobito Balsamiq-Mockups pdf](https://github.com/hitobito/hitobito_sac_cas/assets/7566995/d094266b-2f7c-4a03-9ba5-5f7e27f33088)

Quelle: https://raw.githubusercontent.com/hitobito/hitobito_sac_cas/master/doc/SAC%20Hitobito%20Balsamiq-Mockups.pdf#page=7

Anmerkung Tobi s.: Aus User-Sicht wäre es besser, wenn man auch gar keinen Grund angeben könnte, also wenn dies kein Pflichtfeld ist.
-> Antwort aus Diskussion mit Stefan: Sie können einfach im hitobito UI einen weiteren Grund "Sonstiges" erfassen, dieser ist dann als Radio Button verfügbar, ohne Freitextfeld.

# ToDo

- [ ] Attribute auf Person ergänzen (Migration, view, nicht manuell bearbeitbar)
  - [ ] self_registration_reason_id, belongs_to zu self_registration_reason
- [ ] Im Selbstregistrierungsformular den Schritt "summary" zu Zusatzdaten umbenennen
- [ ] Wenn wir schon dran sind, Schritt 1 "Haupt-Email" gleich zu "E-Mail" umbenennen und in den Übersetzungen auf dieser Maske überall von E-Mail statt von Haupt-E-Mail reden
- [ ] "Eintrittsdatum per" als Radio Buttons
  - [ ] Wenn der 1. Juli des aktuellen Jahres bereits vorbei ist, ist die Option 1. Juli deaktiviert.
  - [ ] Wenn der 1. Oktober des aktuellen Jahres bereits vorbei ist, ist die Option 1. Oktober deaktiviert.
  - [ ] Beim [Erstellen der Rolle(n)](https://github.com/hitobito/hitobito/blob/master/app/models/self_registration.rb#L70) ggf. das "Eintrittsdatum per" als create_on der Rolle(n) verwenden
- [ ] Eintrittsgründe aus der self_registration_reasons Tabelle als Radio Buttons rendern, und auf Person speichern
- [ ] Je nach dem ob eine Einzelmitgliedschaft oder eine Familienmitgliedschaft erfasst wird einen anderen Text anzeigen (Texte werden vom SAC geliefert)
- [ ] Bemerkungen-Feld von Main Person Partial in dieses Partial verschieben
- [ ] Feature Specs schreiben
- [ ] manuell Testen
- [ ] CHANGELOG entry

**Comment by mtnstar** [comment]
@carlobeltrame 

- Bemerkung: wer schaut dieses Feld dann wann an? also wird diese Bemerkung überhaupt irgendwo ausgewertet? ggf. einfach Notiz auf der Person hinterlegen? Zusätzliche Angaben auf der Person habe ich mal auf einer Prod umgebung analysiert. Es ist total wirr was dort alles eingetragen wird ...
- In den ToDo hat es noch ein pending Todo?! dieses evtl. auslagern in ein eigenes Ticket?

**Comment by carlobeltrame** [comment]
> könnte man den Core ggf. so erweitern das man beliebig viele Dokumente definieren kann

Also man kann schon ein beliebiges Dokument pro Ebene definieren, und auch einen custom Titel für dieses Dokument angeben (glaube sogar übersetzbar). Meinst du damit, dass man pro Ebene auch mehrere Dokumente definieren kann? Ist das wirklich MVP?
