### ISSUE TITLE
EVENTS: Annullationskostenrechnung bei Kursabmeldung

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#1014]
blocked by #1008 

Bei einer Abmeldung eines TN von einem Kurs soll automatisch eine Annulationskostenrechnung erstellt werden.

- [x] Neu soll im `SacCas::Event::ParticipationsController` ein `after_cancel` Callback registriert werden. Dort wird folgendes ausgeführt:
  - Alle bestehenden ExternalInvoices der Teilnahme (via link) werden storniert. Dies erfolgt über `Invoices::Abacus::CancelInvoiceJob.new(invoice).enqueue!`.
  - Die Methode `ExternalInvoice::Course.invoice_participation(participation)` wird aufgerufen.

- [x] In der bestehenden Klasse `Invoices::Abacus::CourseInvoice` wird die Erzeugung der Rechnungsposition angepasst. Falls die Teilnahme gecanceled ist, wird die Position wie folgt erzeugt:

  - Die Anzahl Tage des Abmeldedatums (canceled_at) bis zum Kursbeginn werden berechnet
    - Anzahl Tage > 30: Preis 80.00, Beschreibung "Bearbeitungsgebühr"
    - Anzahl Tage >= 20: Preis participation.price * 0.5, Beschreibung "50% Annullationskosten"
    - Anzahl Tage >= 10: Preis participation.price * 0.75, Beschreibung "75% Annullationskosten"
    - sonst: Preis participation.price, Beschreibung "100% Annullationskosten"
  - Name der Position: "{Beschreibung} für {participation.event.kind.level}" (entsprechend mit I18n)
  - Amount: oben berechneter Preis
  - alle anderen Felder sind gleich wie bisher

# ToDo

- [x] Specs schreiben
- [x] Mit angemessener Rolle "durchklicken"

**Comment by tobiasstern** [comment]
Analog meinem Kommentar hier https://github.com/hitobito/hitobito_sac_cas/issues/1008#issuecomment-2373345624

Falls kein Titel für diese Rechnungen definiert ist bitte wie folgt umsetzen:

- Titel: Annulation - {Kursname} ({Kursnummer})
- Beispiel: "Annulation - Lawinen Ski + Snowboard (2025-0524)"

**Comment by tobiasstern** [comment]
Aktuell werden noch Fehler geworfen, wenn eine AKR erzeugt wird, siehe Log:
![Image](https://github.com/user-attachments/assets/89eeb8d3-18e8-4a17-9e35-4ed496cb03ec)


@codez ist am untersuchen.

**Comment by tobiasstern** [comment]
Diverse Issues wurden behoben. Aktuell wird noch der Fehler "UserField22' can not be mapped as a property or an annotation." geworfen. Support von Abraxas wurde angefragt.

**Comment by tobiasstern** [comment]
AKRs werden nun auch erzeugt und in Abacus angelegt. Es gibt noch offene Punkte.

Ob eine AKR korrekt angelegt wird, wenn für den Kurs keine originale/normale Kursrechnung vorhanden ist, ist z.b. noch zu testen

**Comment by tobiasstern** [comment]
- In einem Test habe ich eine Kursanmeldung erstellt hier: https://sac-cas.puzzle.ch/de/groups/1/events/70/participations/300
- Dann habe ich die Person abgemeldet über den Button auf der Anmeldung
- Es wurde eine Rechnung erzeugt, aber **nicht die AKR sondern eine normale Kursrechnung**, vgl. https://sac-cas.puzzle.ch/de/groups/4255/people/100902/external_invoices

**Comment by codez** [comment]
@TheWalkingLeek In der Zwischenzeit wurde die ExternalInvoice::Course aufgeteilt in ExternalInvoice::CourseParticipation und ExternalInvoice::CourseAnnulation. In diesem Fall müsste im Controller Callback `cancel_invoices`  nicht `enqueue_invoice_job` aufgerufen werden, sondern `ExternalInvoice::CourseAnnulation.invoice!(entry)`

**Comment by tobiasstern** [comment]
Erfolgreich getestet
