### ISSUE TITLE
PEOPLE: `nav6-1_sac_sections` Sektionen inkl. Ortsgruppen importieren (aus NAV6)

### ISSUE THREAD

**Issue by openscript** [hitobito/hitobito_sac_cas#1019]
Es geht darum die Sektionen inkl. Ortgruppen aus Navision zu importieren und damit den früheren Excel-Import abzulösen. 

# Tech-Spec

## 1. Arbeitsvorbereitung

- Quelldaten `NAV6_Sektionen-20240814_with_headers.csv` von NextCloud herunterladen (**ACHTUNG: Sensitive Daten**)
- Fixture anpassen

## 2. CSV Datei lesen

- `app/domain/sac_imports/csv_source.rb` Mapping anpassen
- Vorschlag für Mapping:

| **Ruby Hash Attribut** | **NAV6 CSV Export Spaltenname** |
|---|---|
| navision_section_id | NAV Sektions-ID |
| is_active | Ist aktiv |
| name | Name |
| address | Adresse |
| postbox | Zusätzliche Adresszeile |
| town | Ort |
| zip_code | PLZ |
| phone | Telefonnummer |
| email | Haupt-E-Mail |
| youth_homepage | Homepage Jugend |
| has_youth | Hat JO |
| foundation_year | Gründungsjahr |
| review_flow | Mit Freigabeprozess |
| leave_through_section | Austritt nur durch Sektion |
| language                                    | Sprache                                                 |
| language | Sprache |
| section_fee_single | Sektionsbeitrag Mitgliedschaft Einzel|
| section_fee_family| Sektionsbeitrag Mitgliedschaft Familie |
| section_fee_youth | Sektionsbeitrag Mitgliedschaft Jugend |
| entry_fee_single| Eintrittsgebühr Mitgliedschaft Einzel |
| entry_fee_family| Eintrittsgebühr Mitgliedschaft Familie|
| entry_fee_youth | Eintrittsgebühr Mitgliedschaft Jugend |
| foreign_mail_section_bulletin | Porto Ausland Sektionsbulletin|
| central_association_fee_waiver_honorary | Zentralverbandsgebührenerlass für Ehrenmitglieder|
| section_fee_waiver_honorary | Sektionsgebührenerlass für Ehrenmitglieder |
| central_association_fee_waiver_beneficiaries| Zentralverbandsgebührenerlass für Begünstigte |
| section_fee_waiver_beneficiaries| Sektionsgebührenerlass für Begünstigte|
| discount_for_years_of_membership_or_age | Reduktionsbetrag Mitgliedsjahre/Alter |
| discount_starting_after_years_of_membership | Reduktion ab Mitgliedsjahren|
| discount_starting_after_age | Reduktion ab Altersjahren |

Für Faktura Params wie z.B. section_fee_single das Jahr 2024 als Gültigkeitsjahr verwenden. Siehe HIT-131

## 3. Report vorbereiten

- In `app/domain/sac_imports` neue `SacSectionsImporter` Klasse erstellen
- Zu jedem Import wird ein Report zu handen des Kunden erstellt.
- Folgende Header hat der Report in diesem Fall:
  ```ruby
  REPORT_HEADERS = [
    :navision_section_id,
    :errors
  ]
  ```

## 4. Import umsetzen

- In `app/domain/sac_imports` neue `SacSectionEntry` Klasse implementieren

# ToDo

- [x] Fixture anpassen
- [x] Importer schreiben
- [ ] ~Import lokal laufen lassen und erster Report an Kunden übergeben~ kein CSV report
- [x] Alter Excel-Import entfernen `sektionen_importer.rb`
- [x] test case error meldung falls sektion nicht updated/erstellt werden kann
- [x] code clean-up
- [x] update doc/import.md
