### ISSUE TITLE
PEOPLE: Mitgliederrollen vs. Beitragskategorie

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#102]
blocked_by #96 

Beim SAC gibt es verschiedene Beitragskategorien für eine Mitgliedschaft. Heute sind dies:

EINZEL, JUGEND, FAMILIE, FREI FAM, FREI KIND

Zurzeit sind diese Kategorien teilweise noch als einzelne Rollen in Hitobito abgebildet.

Neu gibt es aber nur noch die Rolle **Mitglied** bzw. **Neuanmeldung**:
- Auf dem Rollenmodel gibt es neu ein i18n enum :category
- Auf der Rolle Mitglied/Neuanmeldung (NeuanmeldungenNV, Neuanmeldungen, SektionsMitglieder) werden folgende Kategorien/Beitragskategorien definiert:
  - Einzel
  - Jugend
  - Familie
- Frei Fam, Frei Kind wird nicht mehr benötigt (Abbildung über Familienkonstrukt #98)
- Die Kategorie wird bei der Rolle im UI angezeigt (vor optionaler Bezeichnung), ist jedoch nicht manuell editierbar

![image](https://github.com/hitobito/hitobito_sac_cas/assets/655627/eadd6e0a-b185-4fea-b778-cf22c11f01a3)

Mechano um die richtige Beitragskategorie zu bestimmen: (siehe auch #98)
  - Falls keine PartnerIn/Kinder vorhanden, sowie 22 Jahre und älter -> Einzel
  - Falls keine PartnerIn/Kinder vorhanden, sowie jünger als 22 Jahre -> Jugend, min. 6 Jahre Alt
  - Falls PartnerIn und/oder Kinder vorhanden, sowie 22 Jahre und älter -> Familie

Die Beitragskategorie wird beim Erstellen der Rolle bestimmt und persistiert und kann vorerst später nicht mehr geändert werden (attr_readonly)

Die Logik um die Beitragskategorie einer Person zu bestimmen soll in eine eigene Domainklasse untergebracht werden. So kann diese Logik auch beim Selbstregistrierungsformular verwendet werden. (Umsetzung mit #95)

# Tech-Spec

- Umsetzung im SAC Wagon, weil die Kategorien und ihr Verhalten sehr SAC-spezifisch sind
- in folgenden STI Subclassen werden die Categories(Beitragskategorien) definiert: Group::NeuanmeldungenNV::Neuanmeldung,  Group::NeuanmeldungenSektion::Neuanmeldung, Group::SektionsMitglieder::Mitglied

- Im Navison Export File kategorien: Einzel, Frei Fam, Jugend, usw.)
- https://github.com/hitobito/hitobito_sac_cas/blob/master/lib/hitobito_sac_cas/import/people/bluemlisalp_importer.rb

# ToDo

- [x] Sicherstellen das es nur noch die Rolle Mitglied in den erwähnten Gruppen gibt (siehe auch #96)
- [x] Domain Logik um zu bestimmen welche Beitragskategorie ein Mitglied/Rolle hat
- [x] Import Mitglieder anpassen (angepasste Rollen/Kategorien verwenden)
  - Inkl. Specs
  - Beitragskategorie aus Import File übernehmen und nicht via Domain Logik bestimmen
- [x] Ticket #103 aktualisieren (Tech-Spec usw. mit Know-How aus diesem Ticket)
- [x] Manuell Testen
- [x] CHANGELOG entry

**Comment by daniel-illi** [comment]
@mtnstar was passiert, wenn ein Jugendmitglied seinen 22. Geburtstag feiert? Sollte die Kategorie dann nicht wechseln?
