### ISSUE TITLE
PEOPLE: Anpassung Altersspanne Erwachsene

### ISSUE THREAD

**Issue by daniel-illi** [hitobito/hitobito_sac_cas#1026]
Bei der Berechnung der Alterskategorie hat sich ein Fehler eingeschlichen. Laut Reglement gilt eine Person bis zum Alter von 22 als Jugendliche/r, folglich ab 23 als Erwachsene/r.

Die Definition der Altersspanne für Erwachsene muss entsprechend angepasst werden.

# Tech-Spec

- `SacCas::Beitragskategorie::Calculator::AGE_RANGE_MINOR_FAMILY_MEMBER#begin` muss `23` sein
- I18n text `activemodel.errors.messages.youth_not_allowed_in_family` anpassen, hartcodierte Zahlen ersetzen mit `%{from_age}` und `%{to_age}` ersetzen.
- `Wizards::Steps::Signup::Sektion::FamilyFields::Member#assert_family_age` anpassen, `from_age` und `to_age` übergeben mit Werten vom calculator:
  ```ruby
  from_age = SacCas::Beitragskategorie::Calculator::AGE_RANGE_MINOR_FAMILY_MEMBER.end + 1
  to_age = SacCas::Beitragskategorie::Calculator::AGE_RANGE_YOUTH.end 
  errors.add(:birthday, :youth_not_allowed_in_family, from_age:, to_age:) if calculator.youth?
  ```

# ToDo

- [x] Range im Calculator anpassen
- [x] Translation parametrisieren
- [x] Parameter dem validation error mitgeben
- [x] Specs schreiben/anpassen

**Comment by hunchr** [comment]
@daniel-illi sollte die to_age nicht `SacCas::Beitragskategorie::Calculator::AGE_RANGE_YOUTH.end - 1` sein? bis jetzt steht ja:
> Jugendliche im Alter von 18 bis 21 Jahre können nicht in einer Familienmitgliedschaft aufgenommen werden

und danach sollte es 18-22 sein, oder? dann braucht man das end - 1, sonst ist es 17

**Comment by Largo** [comment]
Review Checklist:

## Issue Description:
- [ ] Error in age category calculation
- [ ] According to regulations, a person is considered a youth up to age 22, and an adult from age 23

## Required Changes:
### 1. Age Range Adjustment
- [ ] Set `SacCas::Beitragskategorie::Calculator::AGE_RANGE_MINOR_FAMILY_MEMBER#begin` to 23

### 2. I18n Text Update
- [ ] Modify `activemodel.errors.messages.youth_not_allowed_in_family`
- [ ] Replace hardcoded numbers with `%{from_age}` and `%{to_age}`

### 3. Family Fields Member Assertion
- [ ] Update `Wizards::Steps::Signup::Sektion::FamilyFields::Member#assert_family_age`
- [ ] Pass `from_age` and `to_age` using calculator values:
  ```ruby
  from_age = SacCas::Beitragskategorie::Calculator::AGE_RANGE_MINOR_FAMILY_MEMBER.end + 1
  to_age = SacCas::Beitragskategorie::Calculator::AGE_RANGE_YOUTH.end
  ```
- [ ] Modify error addition:
  ```ruby
  errors.add(:birthday, :youth_not_allowed_in_family, from_age:, to_age:) if calculator.youth?
  ```
