### ISSUE TITLE
PEOPLE: Selbstregistrierungsformular und Beitragskategorie 

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#103]
~~blocked by #95, #102~~

### Transparenz über zu bezahlende Beträge
Bei der Neuanmeldung im SAC müssen die neuen Mitglieder einen Jahresbeitrag sowie eine einmalige Anmeldegebühr bezahlen. Damit für die User klar ist, wieviel sie bezahlen werden müssen, sollen die zu bezahlenden Beträge während der Anmeldung im Selbstregistrierungsformular jederzeit ersichtlich sein.

### Höhe der Beiträge
Die Höhe der zu bezahlenden Beiträge ist abhängig von:

- Der ausgewählten Sektion, zu welcher der User beitreten will
- Der Zeitpunkt im Jahr, ab dem die Mitgliedschaft gelten soll, vgl. "Beitritt per" in #97 
- Die Art der Mitgliedschaft (Jugend/Einzel/Familie), vgl. #95 
- Einem allfälligen Promocode

### Dynamische Anzeige der Beträge
-> dies wird im separaten Issue #191 behandelt
Die im Formular angezeigten Beträge sollen sich dynamisch verändern, je nachdem was der User für Informationen angibt. 
- z.B. Je nach eingegebenem Geburtsdatum in Schritt 1 ändert sich der Jahresbeitrag. Üblicherweise passiert dies, wenn der User das Input-Feld für das Datum "verlässt" (onFocusLeave oder ähnlich)
- Oder z.B. wenn der User in Schritt zwei eine Person hinzufügt, soll sich die Mitgliedschaft sofort ändern zu einer Familienmitgliedschaft und die angezeigten Beträge sollen ebenfalls sofort ändern.

# Mockup
![Screenshot 2023-12-12 at 16-42-35 SAC Hitobito Balsamiq-Mockups pdf](https://github.com/hitobito/hitobito_sac_cas/assets/7566995/12b8c151-e865-4b57-902d-80e1ded9ad50)
Quelle: https://raw.githubusercontent.com/hitobito/hitobito_sac_cas/master/doc/SAC%20Hitobito%20Balsamiq-Mockups.pdf#page=5

# Tech-Spec
- Umsetzung im SAC Wagon
- Die Höhe der Beiträge wird von einer Domainklasse berechnet. Das überarbeiten wir noch einmal wenn mit dem ERP die Beitragsberechnung pro Sektion umgesetzt wird. Bis dahin einfach mal Dummy-Daten anzeigen.
- Die genauen Texte werden noch vom SAC geliefert.
- Auf Mobile soll das Aside, ähnlich wie es [sonst schon](https://github.com/hitobito/hitobito/blob/master/app/views/people/_roles_aside.html.haml) in hitobito ist, einfach unter das Formular rutschen

# ToDo
- [ ] Aside anlegen (in jedem Formularschritt ab Schritt 2)
- [ ] Informationen gemäss Mockup anzeigen
  - [ ] Links können der heutigen SAC-Webseite entnommen werden: https://www.sac-cas.ch/de/mitgliedschaft/mitglied-werden/ (URLs müssen aber je nach Sprache unterschiedlich sein können)
- [ ] Wenn wir gerade dran sind, im Familienmitglieder-Schritt einen Back-Link neben dem Submit Button ergänzen, gleich wie es bei allen anderen Schritten der Fall ist
- [ ] Kunde wegen Übersetzungen informieren
