### ISSUE TITLE
PEOPLE: Wizards aside rendering erweitern

### ISSUE THREAD

**Issue by daniel-illi** [hitobito/hitobito_sac_cas#1031]
Im Sektion Signup Wizard wird im aside rechts ein Block mit Preisinformationen und ein Block mit Kontaktinformationen angezeigt. In den Signup Wizards für Magazin Abo und Tourenportal wird die Preisinformation im Footer angezeigt.

Neu soll auch im Magazin Abo und im Tourenportal Wizard der Preisinfo Block und derselbe Kontaktinfo Block wie im Sektion Wizard im aside rechts angezeigt werden.

# Mockup

![e464ee5c-e0fe-4285-9b8a-68642102a115](https://github.com/user-attachments/assets/f9d0a8dd-f3ab-4103-9469-c5972f907395)

# Tech-Spec

- [x] Im SAC Wagon sollen die Wizards um ein class attribute `asides` ergänzt werden über welches auf dem Wizard konfiguriert werden kann, welche view partials als asides angezeigt werden.   
  Dies kann im `lib/hitobito_sac_cas/wagon.rb` gemacht werden:
  ```ruby
  Wizards::Base.class_attribute :asides, default: []
  ```
- [x] `Wizards::Signup::AboMagazinWizard` sowie `Wizards::Signup::AboTourenPortalWizard` ergänzen:
  ```ruby
  self.asides = ["aside_abo"]
  ```
- [x] `Wizards::Signup::SektionWizard` ergänzen:
  ```ruby
  self.asides = ["aside_sektion"]
  ```
- [x] `app/views/groups/self_registration/_form.html.haml`:  
  - aside rendering block ersetzen:  
    über `wizard.asides` iterieren und jedes element rendern, z.B.:
    ```ruby
    - if wizard.asides.present?
      = c.with_aside do
        - Array.wrap(wizard.asides).each do |aside|
          = render aside, partial_name: aside, c:, wizard:
    ```
  - footer rendering block entfernen
- [x] `app/views/groups/self_registration/_aside.html.haml` umbenennen nach `_aside_sektion.html.haml`  
  - `turbo_frame_tag(:aside, class: '.col-md') do` ändern nach `turbo_frame_tag(partial_name, class: '.col-md') do`
- [x] `app/views/groups/self_registration/_aside_abo.html.haml` erstellen:
  ```ruby
  = turbo_frame_tag(partial_name, class: '.col-md') do
  = render "abo_infos", costs: wizard.costs
  = render(SelfRegistration::InfosComponent.new)
  ```
- [x] `app/views/groups/self_registration/_abo_infos.html.haml` anpassen um das design dem mockup anzugleichen:  
  die `table` wrappen in eine `card`:
  ```haml
  %aside.card{id: :fees}
    .card-body
      %table.table
        ...
  ```

# ToDo

- [x] `Wizard::Base` um class attribute ergänzen
- [x] `self.asides` auf Wizards setzen
- [x] View partials anpassen
- [x] Specs schreiben
- [x] Mit angemessener Rolle "durchklicken"

**Comment by Largo** [comment]
Nach langen Abklärungen bin ich zur Einsicht gekommen, dass hier Capybara mit Selenium am Anschlag ist mit den (Wizard) Feature Specs. Anders kann ich mir dies nicht erklären.  Ich habe Versuche angestellt mit Cuprite (Erstatz von Selenium) und konnte dort feststellen, dass ein Fehler beim automatischen Ausfüllen vom Geburtstdatum auftreten kann, der aber auch nicht mit diesem Issue zusammenhängt. Die Anpassungen im Commit funktionieren aber.

Ich kann hier direkt nichts mehr beitragen, aber vielleicht findet jemand anderes mehr heraus.
