### ISSUE TITLE
SIGNUP: Anpassungen Geburtstagsfeld in Wizards

### ISSUE THREAD

**Issue by daniel-illi** [hitobito/hitobito_sac_cas#1043]
Im Formular der Signup Wizards soll das Geburtsdatumfeld angepasst werden: 
- Placeholder Text `"TT.MM.YYYY"` mehrsprachig, kursiv und hellgrau (das styling soll für alle input field placeholders gelten)
- Im Dropdown zur Jahreswahl sollen die letztene 100 Jahre bis heute angeboten werden

# Mockup

![Screenshot from 2024-09-26 11-55-00](https://github.com/user-attachments/assets/1217e6f6-700d-4590-b204-4a61f634d0fa)

# Tech-Spec

- im `CORE`:
  - [x] datepicker config anpassen:  
    `app/javascript/javascripts/modules/datepicker.js.coffee`:  
    Datepicker mit `yearRange` option initialisieren
    ```coffeescript
    # yearRange defines what years are selectable in the dropdown.
    # either relative to today's year ("-nn:+nn"), relative to the currently selected
    # year ("c-nn:c+nn"), absolute ("nnnn:nnnn").
    yearRange = if input.attributes.yearRange? then input.attributes.yearRange.value else $.datepicker._defaults.yearRange

    options = $.extend({ onSelect: (d, i) -> self.track(this, d, i) },
      minDate: minDate,
      maxDate: maxDate,
      changeMonth: true,
      changeYear: true,
      yearRange: yearRange,
      $.datepicker.regional[$('html').attr('lang')])
    ```
- im `SAC` wagon:
  - [x] stylesheet ergänzen in `app/assets/stylesheets/hitobito/customizable/_wagon.scss` (passt styling des placeholders auf allen input fields an):
    ```css
    ::placeholder {
      font-style: italic;
      color: $border-color;
      /* Firefox adds a lower opacity to the placeholder, so we use opacity: 1 to fix this. */
      opacity: 1;
    }

    ```
  - [x] wizard date fields anpassen in 
    `app/views/wizards/steps/signup/_common_person_fields.html.haml`:  
    bei beiden `form.labeled_date_field` Parameter ergänzen: 
      - `placeholder: t("global.date_field_placeholder")`
      - `yearRange: "-100:+0"`
  - [x] i18n ergänzen in `config/locales/views.de.yml`:  
      `global.date_field_placeholder: "DD.MM.YYYY"`

# ToDo

- [x] datepicker config in `CORE` anpassen
- [x] css ergänzen
- [x] view partial anpassen
- [x] i18n key ergänzen
- [x] Specs schreiben
- [x] Mit angemessener Rolle "durchklicken"
