### ISSUE TITLE
SIGNUP: Anpassungen Basislogin Wizard Form

### ISSUE THREAD

**Issue by daniel-illi** [hitobito/hitobito_sac_cas#1050]
Im Signup Wizard für das Basiskonto soll angepasst werden
- Label des submit buttons auf der letzten Seite ändern auf `"SAC-KONTO ERSTELLEN"`
- Checkbox “Statuten gelesen” entfernen

# Mockup

![ef95ce37-85a2-4eb3-9f23-0df2473e85c1](https://github.com/user-attachments/assets/7ef68b49-1d2f-4d30-8c18-f1af217c1f60)

# Tech-Spec

- [x] Submit button label anpassen: 
  - in `Wizards::Steps::Signup::AboBasicLogin` das `self.partial = ...` entfernen   
    (es soll der default value verwendet werden welcher den partial name vom Klassennamen ableitet)
  - view erstellen: `app/views/wizards/steps/signup/abo_basic_login/_person_fields.html.haml`
    ```haml
    = render "wizards/steps/signup/person_fields", c: c
    ```
  - label in i18n file einpflegen:
    ```yaml
    wizards:
      steps:
        signup:
          abo_basic_login:
            person_fields:
              next_button: SAC-KONTO ERSTELLEN
    ```
- [x] Checkbox “Statuten gelesen” entfernen:  
    Die checkbox werden hier generiert sofern der wizard ein attribute `statutes` besitzt: `app/views/wizards/steps/signup/_agreement_fields.html.haml:11`.  
    Definiert wird das attribute hier: `Wizards::Steps::Signup::AgreementFields::AGREEMENTS`  
    Das `AgreementFields` wird im `Wizards::Steps::Signup::AboBasicLogin::PersonFields` included.  
      
    Damit die Checkbox nicht mehr angezeigt wird, muss das `statutes` aus dem `Wizards::Steps::Signup::AgreementFields::AGREEMENTS` entfernt werden, dieses ist aber ein frozen array.
    Eine Ansatz ist, die Konstante `Wizards::Steps::Signup::AgreementFields::AGREEMENTS` in ein `class_attribute :agreements, default: [:statutes, :data_protection]` zu ändern, und dieses dann im `Wizards::Steps::Signup::AboBasicLogin::PersonFields` zu customizen: 
    ```ruby
    self.agreements = [:data_protection]
    ```

# ToDo

- [x] Submit Button auf `"SAC-KONTO ERSTELLEN"` umbenannt
- [x] Checkbox “Statuten gelesen” entfernt
- [x] Specs anpassen
- [x] Mit angemessener Rolle "durchklicken"

**Comment by ThomasEllenberger** [comment]
![Image](https://github.com/user-attachments/assets/726e16e7-d02c-43e5-95a3-7866cdf91ea1)

**Comment by Largo** [comment]
Wir muessen die production/integration reseeden, damit dies funktioniert!
