### ISSUE TITLE
SIGNUP: Anpassung Abo Magazine Zusammenfassung

### ISSUE THREAD

**Issue by daniel-illi** [hitobito/hitobito_sac_cas#1056]
Die letzte Wizard Seite des Magazin Abo Signup soll überarbeitet werden.

* letzten Step umbenennen nach "Zusammenfassung"
* Label des submit buttons auf der letzten Seite ändern auf "ABO KOSTENFPLICHTIG BESTELLEN"
* Field zur Wahl des Datums entfernen
* Checkbox für Statuten entfernen, AGB hinzufügen
* Tabelle mit Info zum Abo (Name, Preis...)
* Tabelle mit angegebenen Personalien

siehe Mockup

# Mockup

> [!IMPORTANT]
> Rechnungsadresse kann weg. Dafür bitte Geburtsdatum unterhalb Mail und Adresszusatz unter Strasse und Nr. 

![205289e8-51c9-41a6-b066-95e2cab9c31b-2](https://github.com/user-attachments/assets/5aa8cb1d-6293-4259-b989-b8eed42d4a95)

# Tech-Spec

- [x] `Wizards::Steps::Signup::AboMagazin::IssuesFromField`:  
  - umbenennen in `Wizards::Steps::Signup::AboMagazin::Summary`
  - ```ruby
    def self.agreements = [:agb, :data_protection]
    ```

- [x] `Wizards::Signup::AboMagazinWizard#calculated_costs` implementieren:
    - Land aus `PersonFields` step auslesen
    - amount aus `Wizards::Signup::AboMagazinWizard#costs` zurückgeben, je nachdem ob Schweiz gewählt oder anderes Land
      ```ruby
      wizard.step("person_fields").country == "CH"
      ```

- [x] partial `app/views/wizards/steps/signup/_agreement_fields.html.haml` anpassen:  
  - `"agb"` zur Liste der keys hinzufügen (line 10)

- [x] partial `app/views/wizards/steps/signup/abo_magazin/_issues_from_field.html.haml`:  
  - umbenennen in `_summary.html.haml`
  - `issues_from` field entfernen
  - Tabellen wie im Mockup: 
    - `"Gewünschtes Magazin"`: Gruppenname
    - `"Preis"`: `wizard#calculated_costs`

- [x] I18n Anpassungen: 

  - key `wizards.steps.signup.abo_magazin.issues_from_field_title`:  
    - umbenennen in `wizards.steps.signup.abo_magazin.summary_title`
    - value: `Zusammenfassung`

  - key `wizards.steps.signup.abo_magazin.summary.next_button`:  
    value: `ABO KOSTENFPLICHTIG BESTELLEN`

  - key entfernen: `wizards.steps.signup.abo_magazin.issues_from_field`

  - key `self_registration.infos_component.link_agb_title`:  
    value: `AGB`

  - key `self_registration.infos_component.link_agb`:  
    value: `https://www.sac-cas.ch/de/meta/agb/die-alpen/`

  - key `groups.self_registration.agreement_link.agb_text`:  
    value: `Ich habe die %{link} gelesen und stimme diesen zu`

# ToDo

- [x] Domainklassen anpassen
- [ ] View partials anpassen
- [x] I18n anpassen/ergänzen
- [ ] Specs schreiben
- [ ] Mit angemessener Rolle "durchklicken"
