### ISSUE TITLE
PEOPLE: Pflichtfelder für Mitglieder/Abonnenten

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#1057]
Für Personen mit aktiven Rollen `Mitglied (Stammsektion)` oder `Abonnent` werden folgende Pflichtfelder definiert:

## Haupt-E-Mail

- Kann beim Bearbeiten durch eine Person mit `SAC Geschäftsstelle / Mitarbeiter*in (schreibend) ` beim Speichern leer gelassen werden
- Für die Person selber sowie alle anderen Personen die Schreibrechte auf dieser Person haben ist `Haupt-E-Mail` ein Pflichtfeld
- Ausnahme: War bisher keine Haupt-E-Mail gesetzt, kann die Person weiterhin ohne Haupt-E-Mail gespeichert werden 

## Namens- und Adress-Felder

Personen Felder: Vorname, Nachname, Adresse, Hausnummer, PLZ, Ort

- Sind alles Pflichtfelder für Personen mit den oben erwähnten Rollen, egal von wem diese bearbeitet/gespeichert werden

# Tech-Spec

- Neue Validator Klasse: `People::SacPersonAttrsValidator`, sac_wagon/app/models/people/sac_person_attrs_validator.rb
- in Module SacCas::Person: `validates_with People::SacPersonAttrsValidator`

# ToDo

- [x] ~Validator~ Validations mit Spec umsetzen
- [x] Mit angemessener Rolle "durchklicken"
- [x] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen
