### ISSUE TITLE
PEOPLE: Abbilden/Import Hauptsektion vs. Zusatzsektion

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#106]
Alle Mitglieder haben eine Hauptsektion. 

Teilweise sind Personen Mitglieder in mehreren Sektionen. Neben der Hauptsektion kennt man beim SAC die Zusatzsektion. Für die zusätzliche Sektion bezahlen Mitglieder nur den Anteil der Zusatzsektion, nicht jedoch den NV Beitrag nochmals.

- Mitglieder sollen selbstständig einer Zusatzsektion beitreten können. Umsetzung mit  #119
- Anpassen des Sektions Personen Imports sodass Zusatzsektionsmitglieder entsprechend angelegt werden
- Auf einer Rolle wird angezeigt ob es sich um die Hauptsektion (mit dem Stern) oder um eine Zusatzsektion (Text) handelt
- Zusatzsektion ist nur für Einzel oder Jugend Mitglieder möglich, nicht für ganze Familien

# Tech-Spec

## Neuer Import Personen Zusatzsektion

blocked by: #117 

- es gibt ein File pro Sektion mit allen Zusatzmitgliedschaften. Der Import dieser Zusatzmitgliedschaften soll nach dem Import aller Hauptmitgliedschaften aller Sektionen erfolgen
- Sektion ID im Dateinamen unterbringen. **zusatzmitglieder-1650.xlsx**, 1650 = navision_id
- [test files](https://files.puzzle.ch/apps/files/files?dir=/swe/projects/SAC_SchweizerAlpenClub/Hitobito/7_Verschiedenes/navision-exporte&fileid=5855028)
- Aktive Zusatzmitglieder werden nur importiert falls diese bereits eine aktive Hauptsektion haben, sonst werden diese als Fehlerhaft markiert

## Hauptsektion == Hitobito Hauptgruppe (primary_group)

![image](https://github.com/hitobito/hitobito_sac_cas/assets/655627/f2b25aa2-7d6f-42a9-bca1-5e7eee569998)

- Die Hauptsektion wird via primary_group festgelegt
- Falls eine Person eine Mitglied Rolle hat, muss zwingend eine dieser Rolle die primary_group sein
- Mitglieder können die Hauptsektion/primary_group nicht selber ändern (sac wagon permission Anpassung), Stern auch im UI read-only
- Via dem Stern wird die aktuelle Hauptsektion angezeigt (Hovertext für Mitglied Rolle  anpassen, Hauptsektion anstatt Hauptgruppe)
- Ist die Primärgruppe auf eine Nicht-Mitgliederrolle gesetzt (z.b. ExternerKontakt), wird Hauptgruppe als Begriff verwendet)
- Erhält eine Person eine Mitglied/Neuanmeldung Rolle und hatte vorher keine aktive dieser Rollen, wird die Gruppe der neuen Rolle gleich als primary group der Person gesetzt.
- Wird die Hauptsektion Rolle einer Person gelöscht oder terminiert, wird automatisch die nächste Zusatzsektion Rolle als Hauptsektion gesetzt falls eine solche vorhanden ist

![image](https://github.com/hitobito/hitobito_sac_cas/assets/655627/b59338c3-d337-4a64-b646-c11fc2590dd4)

## Zusatzsektion

- Info auf Rolle ausgeben falls nicht Hauptsektion (Primary Group), überschreiben Role#to_s
  - https://github.com/hitobito/hitobito_sac_cas/blob/master/app/models/sac_cas/role_beitragskategorie.rb beachten

## Beitragskategorie Calculator

- So anpassen das bei Zusatzsektionen Familie nicht möglich ist
- https://github.com/hitobito/hitobito_sac_cas/blob/master/app/domain/sac_cas/beitragskategorie/calculator.rb

# ToDo

- [ ] Primary Group / Hauptsektion Stern/Text anpassen
- [ ] Role-Model Validierungen implementieren
- [ ] Anpassen Beitragkategorie Calculator
- [ ] Erstellen Import Personen Zusatzsektion
- [ ] manuelles Testen
- [ ] CHANGELOG entry

**Comment by daniel-illi** [comment]
Es schlagen noch tests fehl in `./spec/features/person_show_spec.rb`
