### ISSUE TITLE
PEOPLE: Import `nav1-2_sac_families`  implementieren

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#1081]
Nachdem `nav1-1_people` sowie `nav2-1_membership_roles` durchgelaufen sind, müssen die Personen noch in SAC Familien(Hitobito Haushalte) zusammengeführt werden.

1. Suche alle Personen in Hitobito mit einer aktiven `Group::SektionsMitglieder::Mitglied` Rolle mit `beitragskategorie` `:family`
2. Iteriere über all diese Personen und suche via `NAV1` den `household_key` für die jeweilige Person
  - a. Falls die Person die erste Person in Hitobito mit dem `household_key` ist, einfach den `household_key` aus `NAV1` setzen (person#household_key setzen)
  - b. Falls es bereits eine Person mit dem gleichen `household_key` in Hitobito gibt, via `Household` Domain Klasse die Person zum Haushalt hinzufügen ( save!(context: :import), maintain_sac_family: false), so stellen wir sicher das alle PeopleManager entries korrekt angelegt werden

in `nav2-1_membership_roles` wird `sac_family_main_person` bereits gesetzt. 

# Tech-Spec
 * Das meiste scheint schon in https://github.com/hitobito/hitobito_sac_cas/blob/master/app/domain/sac_imports/sektion/membership.rb implementiert
 * https://github.com/hitobito/hitobito_sac_cas/blob/master/app/domain/sac_imports/sektion/memberships_importer.rb
 * etwas ähnliches wurde bereits gemacht: https://github.com/hitobito/hitobito_sac_cas/blob/master/app/domain/sac_imports/sektion/membership.rb#L81

## Cleanup

Als erstes soll bei allen Personen die im NAV1 existieren der `household_key` gelöscht werden.

## CsvReport

```
REPORT_HEADERS = [
  :navision_id,
  :hitobito_person,
  :household_key,
  :errors
]
```
## Konsistenz

Am Schluss sollen die Familien und Personen wieder konsistent sein. Darüber nachdenken wie das gemacht werden könnte (Run am Schluss, separater Task, ...) und follow up Ticket erstellen oder direkt umsetzen.

 * Ein einfacher check ist ob es Personen gibt die als einzige einen gewissen `household_key` haben.

# ToDo

 * [x] `MembershipsImporter` umbenennen in `FamilyImporter` und umschreiben: `CsvReport` verwenden, Personen nicht via csv/xlsx sondern via query finden.
 * [x] Rake Task erstellen
 * [x] `docs/import.md` anpassen
