### ISSUE TITLE
PEOPLE: Neuanmeldungen verwalten

### ISSUE THREAD

**Issue by tobiasstern** [hitobito/hitobito_sac_cas#109]
Manche SAC Sektionen entscheiden für jedes neue Mitglied selber, ob das Mitglied aufgenommen werden soll oder nicht. (Bei anderen SAC Sektionen ist der Prozess automatisiert). Damit die Sektions-Admins die neuen Mitglieder überprüfen und zulassen/ablehnen können, muss die eigens dafür vorgesehenen Gruppe "Neuanmeldungen (Zur Freigabe)" wie folgt angepasst werden.

### Allgemeine Anpassungen
- Titel der Seite bzw. Name der Gruppe ändern zu "Neuanmeldungen (Zur Freigabe)"
- Standard Filter: Ändern von "Mitglieder" zu Neuanmeldungen"

### Unnötige Dinge streichen
Für die Verwaltung der Neuanmeldung braucht es in der Gruppe nur die Tabs "Info, "Personen" und "Log".
Im Tab "Personen" braucht es einige der Buttons und Aktionen auch nicht: "Rechnung erstellen", "Liste importieren",  "Zu Veranstaltung hinzufügen", "Zu Abo hinzufügen".

-> Optional falls dies einfach möglich ist

### Neue Aktionen Übernehmen / Ablehnen bei Tabelle
Für die Einträge in der Tabelle werden zwei neue Aktionen benötigt.
![image](https://github.com/hitobito/hitobito_sac_cas/assets/11408951/bafebc19-6cb1-476c-84d5-6ed7dd2aff60)

Beschreibung der Buttons:
- icon ist "user-check" bzw "user-slash"
- Label des Buttons ist "Übernehmen" bzw. "Ablehnen"
- Auswahl einer der Aktionen öffnet das Confirmation modal

### Bestätigung im Confirmation Modal
Wenn eine der beiden Aktionen gewählt wird, dann muss der User die Aktion im Confirmation modal nochmals bestätigen, vgl. Bild:
![image](https://github.com/hitobito/hitobito_sac_cas/assets/11408951/29933813-fee8-43f6-9f25-9ea6b8407189)

Die Texte im Confirmation Modal sind je nach Anzahl gewählter Einträge und nach gewählter Aktion wie folgt:

Titel
Beschreibung
[Primary Button] Secondarybutton

**Anmeldung übernehmen**
Bitte bestätigen Sie die Übernahme der ausgewählten Anmeldung.
[1 übernehmen] Abbrechen

**Anmeldungen übernehmen**
Bitte bestätigen Sie die Übernahme der ausgewählten Anmeldungen.
[3 übernehmen] Abbrechen

**Anmeldung ablehnen*
Bitte bestätigen Sie die Ablehnung der ausgewählten Anmeldung.
[1 ablehnen] Abbrechen

**Anmeldungen ablehnen*
Bitte bestätigen Sie die Ablehnung der ausgewählten Anmeldungen.
[4 ablehnen] Abbrechen

Beim Ablehnen soll zudem ein Textfeld angezeigt werden, in dem eine optionale Bemerkung angegeben werden kann, vgl Bild:
![image](https://github.com/hitobito/hitobito_sac_cas/assets/11408951/b954068d-2faf-457f-8282-df052b586800)

### Success Message
Wenn der User die Aktion bestätigt hat, wird diese durchgeführt, die Liste wird aktualisiert und eine Erfolgsmeldung/Success Message wird angezeigt.

![image](https://github.com/hitobito/hitobito_sac_cas/assets/11408951/41ae0e25-f432-4eed-9102-a3ab3a2abb60)

Texte für die Meldung:

- Die ausgewählte Anmeldung wurde übernommen
- Die ausgewählte Anmeldung wurde abgelehnt
- Die ausgewählten Anmeldungen wurden übernommen
- Die ausgewählten Anmeldungen wurden abgelehnt

# Tech-Spec

- Umsetzung rein im SAC wagon
- Bei akzeptieren wird die Neuanmeldung Rolle der Person in NeuanmeldungenSektion durch eine in NeuanmeldungenNv in gleichen Layer ersetzt. 
- Beim Ablehnen:
  -  wird die Neuanmeldung Rolle per sofort terminiert
  -  Login der Person wird gesperrt
  - Die Bemerkung die beim Ablehnen erfasst werden kann wird als Notiz auf der Person hinterlegt
- soll später auch mit Rollen mit Startdatum in der Zukunft funktionieren, siehe #97 , wird mit #114 umgesetzt
- Neuer Controller im SAC wagon, sowas wie Roles::NeuanmeldungenSektion::ConfirmationController
  - #show: modal fenster Rendern
  - #create: Akzeptieren und Rolle verschieben in NeuanmeldungenNv
  - #delete: Ablehnen

# ToDo

- [x] Controller erstellen und create, delete actions implementieren (mits species)
- [x] index action buttons ergänzen
- [x] Controller show, für modalfenster implementieren
- [x] Action Buttons auf Person#show ergänzen
- [x] Ausblenden unnötige Elemente/Tabs auf Neuanmeldungsgruppen (ggf. follow up ticket erstellen)
- [x] Ticket #114 noch ergänzen falls es da noch Anpassungen braucht, oder dieses Ticket löschen/schliessen
- [x] Feature spec im sac wagon
- [ ] manuell testen
- [x] CHANGELOG entry

**Comment by daniel-illi** [comment]
Follow-up ticket #122
