### ISSUE TITLE
PEOPLE: Import People / Families Konsistenz

### ISSUE THREAD

**Issue by rnestler** [hitobito/hitobito_sac_cas#1121]
In https://github.com/hitobito/hitobito_sac_cas/issues/770 und https://github.com/hitobito/hitobito_sac_cas/issues/1081 wurde der Import von Personen und Familien implementiert.

Da während dem Import Inkonsistenzen auftreten können bis alles importiert ist, werden validations ausgeschaltet. Am Schluss müssen wir sicherstellen, dass alle Personen und Familien gültig erstellt wurden.

Dies wird in einem separaten Task gemacht, welcher einen CsvReport generiert

- Prüfen ob People Manager sauber erstellt werden (in spec)
- Familien CSV Report ?

# Tech-Spec

TBD

# ToDo

- [ ] CsvReport defninieren
- [ ] Alle Personen Validieren
- [ ] Alle SAC Familien validieren
- [ ] Job lokal durchlaufen lassen
- [ ] Job in Production durchlaufen lassen
- [ ] Report am SAC zur Verfügung stellen

**Comment by daniel-illi** [comment]
obsolet
