### ISSUE TITLE
PEOPLE: `nav2-1_membership_roles` mit begünstigt/ehrenmitglieder ergänzen

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#1130]
Nachdem die Mitgliederrollen via #770 importiert werden, müssen zusätzlich noch die Begünstigt/Ehrenmitglieder Rollen als nächster Schritt importiert werden.

- Beide Rollen können nur vergeben werden falls eine aktive Mitgliederrolle vorhanden ist (Stamm oder Zusatz)
  - Dies sollte bereits via Rollen Validierung so geprüft werden
- Falls Rolle nicht erstellt werden kann, soll dies im CSV Log ersichtlich sein
- Integration in membership roles import, anlegen nach Mitgliederrollen
- Rollen werden beim Start für alle Personen im Source CSV resettet

## Fix Ortsgruppen

die Mitglieder von Ortsgruppen werden mit dem aktuellen Import `nav2-1_membership_roles` noch nicht importiert.
im Export-File sind die Ortsgruppen nested unter der Sektion. 

Beispiel: Gruppe_Lvl_1: CAS Diablerets, Gruppe_Lvl_2: CAS Diabl. Château d'Oex, Gruppe_Lvl_3: Mitglieder

Sobald also Gruppe_Lvl_3 mit Mitglieder befüllt ist, handelt es sich um eine Ortsgruppe.

Dies wird auch für den Import der Begünstigt/Ehrenmitglieder benötigt und soll gleich auch für die Mitgliederrolle mit diesem Ticket gefixt werden.

# Tech-Spec

- https://github.com/hitobito/hitobito_sac_cas/blob/master/app/domain/sac_imports/roles_importer.rb
- Neuen Importer wie z.B. `SacImports::Roles::BenefitedHonaryMemberImporter` oder zwei separate Klassen

# ToDo

- [x] CSV Fixture mit Ortsgruppe ergänzen
- [x] Ortsgruppe handling Membership/AdditionalMembership Import fixen
- [x] Benefited/Honary Importe implementieren
- [x] doc/import.md updaten
- [x] Import auf neuer Prod laufen lassen
