### ISSUE TITLE
EVENTS: Kurskaderabrechnung

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#1180]
Als Kursleiter oder Klassenleiter will ich ein PDF mit einer QR-Code Rechnung meiner Kursauslagen erzeugen können.

## Button

- [x] Neu soll auf der Show Seite eines Kursleiters oder eines Klassenleiters in der Button Toolbar zuhinterst ein Button "Kurskaderabrechnung erstellen" erscheinen. Dieser wird nur angezeigt, wenn für diese Teilnahme eine Rolle mit dem Flag "Selbständig erwerbend" (Event::Role#self_employed)  existiert. 
- [x] Berechtigt sind Personen, welche den Kurs selbst bearbeiten können (für alle entsprechenden Teilnahmen) und die Kurs-/Klassenleiter (nur für sich selbst). Dazu auf der EventParticipationAbility eine neue Action :leader_settlement definieren.
- [x] Der Button öffnet ein Popover (analog z.B. Teilnahme Abmelden) mit folgenden Eingabefeldern:
  * Effektive Tage (von Participation#actual_days), vorausgefüllt
  * IBAN (string)
  * Button "Abrechnung erstellen", Link "Abbrechen"
- [x] Im Popover steht zuoberst in einem blauen Alert die folgenden Hinweise:
  > Falls die Person in der Rolle der Kurs- oder Klassenleitung nicht Inhabende der angegebenen IBAN ist, muss die Rechnung eigenständig erstellt werden und der hier bereitgestellte QR-Rechnungsgenerator darf nicht verwendet werden.
  > Falls die kontoführende Person bzw. Institution MWST-pflichtig ist, muss die Rechnung eigenständig erstellt werden und der hier bereitgestellte QR-Rechnungsgenerator darf nicht verwendet werden.

## Controller

- [x] Es gibt einen neuen Controller `Event::Courses::LeaderSettlementPdfsController` mit einer `create` Action
- [x] Prüft die obige Berechtigung :leader_settlement
- [x] Prüft die IBAN auf das Format von `InvoiceConfig::IBAN_REGEX`, sowie auf die korrekte Prüfziffer (Anleitung zb [hier](https://gocardless.com/de/handbuch/artikel/iban-pruefziffer-berechnen-so-gehts/))
- [x] Prüft die Effektiven Tage, dass diese >= 0 und maximal so gross wie die Total Tage des Kurses sind
  - [x] Die Total Tage des Kurses können als Methode auf dem Kurs berechnet werden. Die Methode `Export::Pdf::Participations::KeyDataSheet::Sections::Table#total_event_days` kann dafür verschoben werden und ebenfalls die Methode auf dem Kurs verwenden. Allenfalls stimmt dort die Berechnung nicht, wenn Start und Endzeiten verwendet werden. Relevant sind ausschliesslich die ganzen Tage, egal wann sie starten oder enden. Beispiel: 1.1. 23:00 - 2.1. 01:00 => Dauer 2 Tage, falls `start_point_of_time == :evening` würde noch 0.5 abgezogen. Tests ergänzen.
- [x] Falls eine Prüfung fehlschlägt, wird die passende Fehlermeldung wie üblich im Formular angezeigt.
- [x] Sonst werden die "Effektive Tage" zurück auf die Participation gespeichert und
- [x] ein PDF generiert (siehe unten), welches dem User zum Download zurück gegeben wird.

## PDF

Das zu generierende PDF enthält zuunterst auf der Seite ausschliesslich den Zahlteil mit einer QR Rechnung.

Es wird dabei kein Rechnungsmodel (weder Invoice noch ExternalInvoice) gespeichert. Idealerweise kann jedoch in Memory eine Invoice Instanz erstellt werden, welche alle für das PDF notwendigen Angaben enthält. Falls das nicht direkt klappt, könnte eine Subklasse von Invoice erstellt werden, welche die Daten bereitstellt, so dass `Export::Pdf::Invoice::PaymentSlipQr`unverändert verwendet werden kann.

- [x] Es wird eine neue Hülle `Export::Pdf::Participations::LeaderSettlement` erstellt, welche die `Event::Participation` und die IBAN als Argument erhält, das Invoice Object abfüllt und damit die `Export::Pdf::Invoice::PaymentSlipQr` Section rendert.
- [x] Die Methode `Invoice::Qrcode#payment_reference` wird im Core angepasst. Falls die `invoice.reference.blank?` ist, wird als type `NON` verwendet. Test und Kommentar hinzufügen, dass dies im SAC Wagon so vorkommt.
- [x] Die Methode `Export::Pdf::Invoice::PaymentSlipQr#payment_extra_infos` wird im Core angepasst: `render_esr_number` ist nur true, wenn die `invoice.esr_number.present?` ist. Test und Kommentar hinzufügen, dass dies im SAC Wagon so vorkommt.
- [x] Der Rechnungsbetrag berechnet sich wie folgt:
  - Via Event Kind und deren CourseCompensationCategories werden die CourseCompensationRate geladen, welche am ersten Startdatum des Events gültig sind. Falls an diesem Datum keine Rate gültig ist, gibt es die Kategorie nicht für den vorliegenden Kurs.
  - Je nach Rolle der Participation wird entweder der Wert aus `rate_leader` oder `rate_assistant_leader` verwendet.
  - Die Tagesraten werden mit den Anzahl Tagen multipliziert; dazu kommen die Summen der Pauschalen und Budgets:
  - `total_amount = participation.actual_days * rates.select { it.category.kind == 'day' }.map(&:rate_(assistant_)leader) + rates.select { it.category.kind != 'day' }.map(&:rate_(assistant_)leader)`
- [x] Folgende Felder werden abgefüllt:
  - Zahlungsempfänger (payee): `Person::Address.new(participation.person).for_invoice`
  - Zahlungsempfänger IBAN: Eingegbene IBAN
  - Betrag (amount_open, total): Siehe oben
  - Währung (currency): CHF 
  - Mitteilung (payment_purpose): "Kurs {Kursnummer}"
  - Referenznummer (reference): leer
  - Zahlungspflichtiger (recipient_address): Hardcoded
    > Schweizer Alpen-Club SAC
    > Zentralverband, Monbijoustrasse 61
    > 3000 Bern 14 

# ToDo

- [x] Domainklasse erstellen 
- [x] Model/View/Controller anpassen
- [x] Specs schreiben
- [x] Mit angemessener Rolle "durchklicken"
