### ISSUE TITLE
PEOPLE: Beitritt Zusatzsektion / Wiedereintritt 1 von 2

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#119]
blocked by: #106
follow up: #126 

# Beitritt Zusatzsektion

Mitglieder mit bereits einer Hauptsektion sollen selbstständig einer Zusatzsektion beitreten können.
Der Beitritt soll ebenfalls via Selbstregistrierungsformular/Link der gewünschten Sektion erfolgen:

- Ein Mitglied muss bereits eine aktive Mitgliedschaft in einer Hauptsektion besitzen
- Anmeldungen für eine Zusatzsektion erfolgt über den gleichen Workflow wie für die Hauptsektion (Neuanmeldungen NV oder Neuanmeldungen Sektion)

Besitzt man heute bereits ein Login, wird beim Aufruf der Selbstregistrierungs-Url einer Gruppe anstatt dem Formular folgende Seite angezeigt:

![image](https://github.com/hitobito/hitobito_sac_cas/assets/655627/e4f4d993-e59a-4f81-ae50-c0d91a2993cb)

Neu soll der Text oberhalb sowie der Button-Text selber customized werden:

- Willst du dieser Sektion als Einzel-Mitglied beitreten? [Beitreten]
- Willst du dieser Sektion als Jugend-Mitglied beitreten? [Beitreten als Zusatzsektion]

Ein Beitritt ist nur möglich falls nicht bereits eine aktive Rolle unter Mitglieder der Sektion vorhanden ist

# Wiedereintritt

Bei einem Wiedereintritt ist die Person bereits in der DB vorhanden und hat bereits ein Login oder erstellt eines über die Passwort-Zurücksetzen-Funktion.

- Willst du dieser Sektion als Einzel-Mitglied beitreten? [Beitreten]

# Login mit Mitglied-Nr

![image](https://github.com/hitobito/hitobito_sac_cas/assets/655627/128287ff-e49e-4543-a6ce-ce21d82fddcf)

Es soll möglich sein sich via Mitglied-Nr einzuloggen

# Tech-Spec

- ~Validierung auf Rolle Neuanmeldung das diese nur erstellt werden kann falls die Person noch keine aktive Rolle in der gleichen Sektion unter Mitglieder hat~ Vorläufig validieren wir nur, dass die Person noch keine Neuanmeldung Rolle in dieser Neuanmeldungsgruppe hat
- https://github.com/hitobito/hitobito_sac_cas/blob/master/app/domain/sac_cas/beitragskategorie/calculator.rb

## Login via Mitglied-Nr

- Ggf. könnte man das im Core realisieren sodass man eine Liste der Login-Felder auf der Person definieren kann (class_attribute, :login_id_columns), Standardmässig ist dort einfach :email der Person drin. Im Wagon dann erweitern
- oder alternativ dieses ganze Verhalten einfach im SAC Wagon customizen

# ToDo

- [x] Login mit Mitglied-Nr ermöglichen, Label entsprechend anpassen, Styling Login Form
- [x] Anpassen Text/Button Selbstregistrierungsformular für bereits registrierte/vorhandene Personen
- [x] Validierungen Rolle Neuanmeldung
- [x] Manuelles Testen
- [x] CHANGELOG entry

**Comment by daniel-illi** [comment]
@mtnstar wie soll entschieden werden, welcher Text im Dialog angezeigt werden soll? Richtet sich das nach der Beitragskategorie der Hauptsektion?

Ich frage mich, ob diese zusätzliche Komplexität wirklich sinnvoll ist. Jemand der Einzelmitglied resp. Jugend-Mitglied ist, weiss das ja in der Regel und will auch kaum mit einer anderen Beitragskategorie zur Zusatzsektion beitreten.
Wieso halten wir den Text nicht einfach generisch? Einen i18n String können wir easy im Wagon überschreiben, wenns da aber logik dahinter braucht, halsen wir uns nur zusätzlichen maintenance- und Testaufwand auf.

**Comment by mtnstar** [comment]
> @mtnstar ~wie soll entschieden werden, welcher Text im Dialog angezeigt werden soll? Richtet sich das nach der Beitragskategorie der Hauptsektion?~ Nach genauerem Durchlesen des Tickets kann ich die Frage selber beantworten.
> 
> Ich frage mich, ob diese zusätzliche Komplexität wirklich sinnvoll ist. Jemand der Einzelmitglied resp. Jugend-Mitglied ist, weiss das ja in der Regel und will auch kaum mit einer anderen Beitragskategorie zur Zusatzsektion beitreten. Wieso halten wir den Text nicht einfach generisch? Einen i18n String können wir easy im Wagon überschreiben, wenns da aber logik dahinter braucht, halsen wir uns nur zusätzlichen maintenance- und Testaufwand auf.

Grundsätzlich habe ich das so vorgesehen da es bei den Mitgliedern oft zu Verwirrung gekommen ist in der Vergangenheit zu welcher Beitragskategorie man sich entscheiden soll. Die Idee dahinter war einfach mehr transparent zu sein und es offensichtlich darzustellen. Du kannst das aber gerne in ein Ticket extrahieren und ich kläre mit dem SAC ob es das braucht oder nicht. 
wir werden später dies sicher auch gleich noch mit Preisinformationen ergänzen. Also den Benutzer darüber informieren mit welchen Kosten er zu rechnen hat.
