### ISSUE TITLE
EVENTS: Selbständig erwerbend nur für Leitungsrollen

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#1196]
- [x] Neu soll im Formular einer Event Rolle die Checkbox "Selbständig erwerbend" nur für Leitungsrollen (kind = :leader) von Kursen angezeigt werden (also nicht mehr für TN und auch nicht für andere Anlasstypen). 
- [x] Auch in der Tabelle im Aside der Rollen eines TN soll die entsprechende Information nur bei Leitungsrollen von Kursen angezeigt werden.

# ToDo

- [x] View/Controller anpassen
- [x] Specs schreiben
- [x] Mit angemessener Rolle "durchklicken"

**Comment by rnestler** [comment]
> Neu soll im Formular einer Event Rolle die Checkbox "Selbständig erwerbend" nur für Leitungsrollen (kind = :leader) von Kursen angezeigt werden (also nicht mehr für TN und auch nicht für andere Anlasstypen).

Das braucht dann einen Stimulus Controller.
