### ISSUE TITLE
EVENTS: Export Kursdaten

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#1198]
Als Kursadmin will ich für einen Kurs eine Liste aller TN inkl Kursdaten exportieren können, um daraus Serienbriefe zu erstellen.

- [x] Neu soll auf der TN Liste eines Kurses ein zusätzlicher Exporttyp "Adressliste und Kursdaten" auswählbar sein (für CSV und Excel)
- [x] Berechtigungen sind gleich wie alle anderen Exporte
- [x] Der Export berücksichtigt den aktuell gewählten Filter/Tabs auf der Ansicht.
- [x] Der Export ist in der gewählten Sprache des Kurses. Falls ein Kurs zweisprachig ist (“Deutsch/Französisch”), wird Deutsch verwendet. Betrifft nur die I18n Spalten (Kurs Name, Geschlecht, Hauptebene Name).
- [x] Der Export enthält folgende Spalten (Titel werden **nicht** übersetzt und 1:1 übernommen)

|Spaltentitel | Wert |
|---|---|
|Veranstaltungsnummer  | Kurs→ Kursnummer|
|Kursortname | Kurs → Daten → Ort (Distinct, Komma separiert, falls mehrere Daten und Orte)|
|Kursbezeichnung | Kurs → Name|
|Anfangsdatum | Kurs → Daten → Von (Erstes Von) |
|Enddatum | Kurs → Daten → Bis (Letztes Bis)|
|Teilnehmernummer | Person → ID|
|Geschlecht | Person → Geschlecht (männlich, weiblich, divers)|
|Familienname | Person → Nachname |  
|Vorname | Person → Vorname |  
|Sprachcode  | Person → Sprache mit Suffix "S" (z.B. DES, FRS, ITS)|
|Adresse | Person → Strasse + HausNr|
|PLZ | Person →PLZ |  
|Ort | Person → Ort |  
|Sektionsname | Person →Hauptebene ID + Name (z.B "42 Sektion Blüemlisalp") |
|Geburtsdatum | Person → Geburtsdatum|
|Mailadresse |Person → Haupt-E-Mail |  

# ToDo

- [x] Domainklasse erstellen oder anpassen
- [x] View/Controller anpassen
- [x] Specs schreiben
- [x] Mit angemessener Rolle "durchklicken"
