### ISSUE TITLE
Grundpaket: Integration Youth wagon

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#13]
soll der youth wagon integriert werden? macht vermutlich aus verschiedenen Gründen Sinn.

https://github.com/hitobito/hitobito_youth -> Sieht feature liste in Readme

# ToDo

- [x] Entscheid youth wagon ja/nein --> JA
- [x] sac/cas setup mit youth wagon lokal testen
- [x] youth wagon einbauen in composition repo falls erwünscht
