### ISSUE TITLE
MAILING_LIST: Opt_in und Opt_out für subscribable beachten

### ISSUE THREAD

**Issue by njaeggi** [hitobito/hitobito_sac_cas#1307]
Die Mailing Listen haben aktuell mehrere Möglichkeiten um zu überprüfen ob eine Person subscribed ist oder nicht.

`subscriber.rb`
`subscription.rb`

Es scheint das nicht beide das gleiche machen und auch das `MailingList.first.subscribed?(person)` das OptIn und OptOut nicht korrekt beachtet. Je nachdem welche Einstellungen die Mailing Liste hat, soll eine Person auch wenn keine aktive Subscription existiert als subscribed gezählt werden. 

Der PersonController sollte im `destroy` ausserdem beachten ob die Person zum Beispiel durch eine aktive Subscription Teil der Mailing Liste ist, da in diesem Fall die Subscription gelöscht wird (ist aktuell für jede Anfrage so) aber wenn die Person "subscribed" ist weil die Liste OptIn ist und somit keine Subscription existiert, muss eine Exclusion erstellt werden.

# ToDo
- [ ] Überprüfen welche Teile der Mailing Listen aktuell noch nicht korrekt auf OptIn/OptOut reagieren
- [ ] subscriber.rb#subscribed und subscription.rb#subscribed vereinheitlichen
- [ ] Überprüfen das auf MailingList#show Info immer die richtigen Buttons angezeigt werden, mit dem korrekten Verhalten (Subscription löschen oder Exclude bei Abmeldungen)
- [ ] Mit angemessener Rolle "durchklicken"
