### ISSUE TITLE
PEOPLE: Einschreiben auf Neuanmeldungen Sektion

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#132]
Jede Sektion hat auf der Untergruppe **Neuanmeldungen** den Selbstregistrierungslink aktiviert. Ist man bereits in Hitobito eingeloggt und besucht diesen Link, erfolgt eine Weiterleitung auf die Einschreibe-Seite anstatt des Selbstregistrierungsformulars für neue Mitglieder.

**self_inscription** (Einschreiben) wurde für den SAC bereits mit #119 customized:

![image](https://github.com/hitobito/hitobito_sac_cas/assets/11408951/ea48f01b-f5c2-41e8-9129-4e56e54cac37)

Text:
`Du kannst dem SAC Blüemlisalp entweder als Zusatzsektion beitreten oder du kannst sie als deine neue Stammsektion auswählen und damit aus deiner bisherigen Stammsektion austreten.
Hinweis für Familien: Der Wechsel der Stammsektion gilt automatisch auch für alle Familienmitglieder. Der Beitritt zu einer Zusatzsektion gilt hingegen immer nur für dich persönlich.`

Aufbauend auf dieser **Customization** sollen folgende Features ergänzt werden:

## 1. Wechsel der Stammsektion

1. Im Normalfall hat eine Person bereits eine aktive Mitgliedschaft in einer Stammsektion
2. Über den self inscription link gelangt sie auf die Beitritts-Seite. Dort wählt sie den Wechsel und damit den Austritt aus der bisherigen Stammsektion.
3. Es wird ein Bestätigungsdialog angezeigt mit dem Hinweis das dieser Vorgang nicht rückgängig gemacht werden kann
4. Beim Bestätigen wird die aktuell aktive Rolle in der Stammsektion auf Heute oder das gewählte Datum - 1 Tag terminiert. Gleichzeitig wird eine neue Rolle in Neuanmeldungen mit Von-Datum Morgen oder dem gewählten Datum der aktuellen Gruppe erstellt

## 2. Antrag Zusatzsektion

1. Über den self inscription link gelangt sie auf die Beitritts-Seite. Dort wählt sie den Beitritt in die Zusatzsektion aus
2. Es wird ein Bestätigungsdialog angezeigt mit dem Hinweis das dieser Vorgang nicht rückgängig gemacht werden kann
3. Beim Bestätigen wird eine neue Rolle in Neuanmeldungen mit dem gewählten Von-Datum erstellt

## 3. Wiedereintritt

- Besitzt eine Person ein Login, hat aber keine Aktive Mitglied Rolle in irgend einer Sektion, so wird nur der Beitritt zur Stammsektion angeboten
- In diesem Fall die Radio Buttons für Zusatz/Stamm sowie den Hinweis-Text ausblenden

## 4. Anmeldung ab

- Der Zeitpunkt für den Beitritt in eine Zusatzsektion bzw. Wechsel der Sektion kann von dem User gewählt werden. Vgl. mit Auswahl bei Selbst-Registrierung
- Auswahlmöglichkeiten: sofort, 1. Juli, 1. Oktober
- Diese beziehen sich immer aufs aktuelle Jahr, z.B. am 22. Juli steht nur noch sofort oder 1. Oktober zur Auswahl
- Es wird immer das Datum des laufenden Jahres verwendet
- Das gewählte Datum wird der Neuanmeldung Rolle assigned beim Erstellen

## 5. Link auf Person-Mitgliedschaften (history)

Damit die User einer beliebigen Sektion beitreten können, wird bei allen User im Tab "Mitgliedschaften" ein Hinweis eingeblendet mit Link auf die Sektionen-übersicht auf der SAC-Website, vgl. Mockup:

![image](https://github.com/hitobito/hitobito_sac_cas/assets/11408951/e8c8644f-f45f-4d33-9bfb-886d3642da0a)

Text übersetzt und auch Link konfigurierbar pro Sprache.
deutscher Link: https://www.sac-cas.ch/de/der-sac/sektionen/

## 6. Bereits Mitglied in dieser Sektion

Hat die Person bereits eine Mitgliedschaft in der Sektion, wird sie weitergeleitet auf Person#show mit einem Hinweis das sie bereits Mitglied in dieser Sektion ist.
Das selbe gilt auch für eine Pending Neuanmeldung Rolle. Dies sollte aber bereits standardmässig durch Hitobito abgedeckt sein.

# Tech-Spec
- https://github.com/hitobito/hitobito_sac_cas/blob/master/app/controllers/sac_cas/groups/self_inscription_controller.rb
- Logik für Wechsel/Antrag Sektion in eine eigene Domainklasse auslagern und nicht alles in den Controller wursteln ;)

# Related
#153 

# ToDo

- [ ] Bestätigungsdialog Modal mit Hinweis implementieren
- [ ] Option Stamm/Zusatzsektion (Radiobtns) mit Hinweis in View anzeigen
- [ ] Optionen für Datumswahl mit Hinweisen
- [ ] Wechsel Stammsektion umsetzen inkl. Wiedereintritt
- [ ] Wechsel Stammsektion für alle Familienmitglieder -> siehe #98 
- [ ] Antrag Zusatzsektion umsetzen
- [ ] Redirect wenn bereits Mitglied Sektion, Neuanmeldung vorhanden
- [ ] Manuelles Testen
- [ ] CHANGELOG entry Wagon

**Comment by sykesonrocks** [comment]
**3. Wiedereintritt**
Grundsätzlich ist der Onboarding Prozess von wiedereintretenden Mitgliedern identisch zum Onboarding Prozess von neueintretenden Mitgliedern. Da der Antragsteller früh im Onboarding Prozess eine E-Mail Adresse angeben muss, erkennt Hitobito, dass die E-Mail bereits im Einsatz ist. Der Antragsteller wird zum Login-Fenster weitergeleitet und loggt sich ein. Der User befindet sich nun auf sac-cas.ch. Wie muss der User jetzt vorgehen, um einen Wiedereintritt zu beantragen?

**Wechsel Beitragskategorie**
Aktuelle Hypothese ist, dass 
- die Beitragskategorien resp. die Rollen immer gültig von 01.01 bis 31.12 sind. Das von- und bis-Datum bleiben bis zum nächsten Jahresinkassolauf unverändert, auch wenn der Eintritt unterjährig geschieht, die Familie aufgelöst wird oder ein Austritt vorgenommen wird (die Person hat die Mitgliedschaft für ein Kalenderjahr bezahlt).
- der Beitragskategoriewechsel nie manuell ausgelöst werden muss. Im Zuge des Jahresinkassos prüft das System bei der Rollenverlängerung, ob die aktuell zugewiesene Beitragskategorie noch gültig ist (konkret Familien- und Jugend-Mitglieder). Wenn nicht, nimmt das System den entsprechenden Beitragskategoriewechsel automatisch vor.
Wenn eine Familie bestehend aus 2 Personen am 01.01 eintritt und 1 Fam-Mitglied am 01.02 den Austritt beantragt, dann wird die Rolle am 01.02 noch nicht terminiert, sondern im Zuge des Jahresinkassos wird die Rolle des ausgetretenen Fam-Mitglieds nicht verlängert - die Mitgliedschaft läuft dann am 31.12 einfach aus. Wenn aber das andere Fam-Mitglied am 02.02 ein Sektionswechsel beantragt, dann würde man der Person eine neue Rolle, “Einzel”, zuweisen mit gültig von 02.02-31.12, und die bestehende Rolle, “Fam”, terminieren auf 01.02. Ist dieses Verständnis korrekt? Das würde bedeuten, dass ein Wechsel der Beitragskategorie nicht nur im Zuge des Jahresinkassos vorkommen kann, sondern auch bei einem Sektionswechsel. Gibt es weitere solche Fälle, in der die Beitragskategorie angepasst werden muss?

**Comment by sykesonrocks** [comment]
2 Fragen:
- Was ist beim Wechsel Stammsektion der Prozess, wenn eine Rechnung noch offen ist? Aus unserer Sicht sollte ein Sektionswechsel nur dann möglich sein, wenn keine offene Rechnung existiert. Sollte eine Rechnung offen sein, muss der Antragsteller im UI informiert werden und der Button "Beitritt beantragen" muss deaktiviert sein.
- Gemäss Arbeitshypothese wird eine Mitgliedschaft am festgelegten Eintrittsdatum aktiviert, nach a) Erhalt der Zahlung, b) erfolgreicher E-Mail-Verifikation und c) Zustimmung der Sektion, falls die Sektion die Mitgliederaufnahme selbständig vornimmt. Wie sieht der Prozess aus, wenn eine Nullerrechnung erzeugt wird?
