### ISSUE TITLE
EXPORT: Abo (Die Alpen Papier, ID 4) - Download mit Export-Option "Spaltenauswahl" funktioniert nicht

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito_sac_cas#1325]
## Problemstellung / Aktuelles Verhalten
Wenn ich unter [SAC/CAS-Portal - Die Alpen Papier](https://portal.sac-cas.ch/de/groups/1/mailing_lists/4/subscriptions?returning=true) die Empfängerliste wie folgt versuche zu erstelle, ist der Download nach 12 Stunden nicht beendet:

1. Unter “Export”
2. Wähle “CSV”
3. Wähle “Spaltenauswahl”
![grafik](https://github.com/user-attachments/assets/30d439cc-4cb6-4630-9839-4b24ee5af174)

## Erwartetes Verhalten
Der Download sollte funktionieren. Performance-technisch sollte es etwa gleich lang dauern, wie wenn die Export-Option “Haushaltsliste” bedient wird.

## Bemerkung
Da der Sprachcode in allen anderen Export-Optionen (Haushaltliste, Adressliste, Empfänger Einzelperson, Empfänger Familien) fehlt, möchte man die die Option “Spaltenauswahl” bedienen.

Wahrscheinlich liegt es am fehlenden `household_key`. GH Ticket zum entsprechenden Sentry Issue: https://github.com/hitobito/hitobito_sac_cas/issues/1327

## ToDo
- [ ] Migration erstellen
- [ ] Domainklasse erstellen oder anpassen
- [ ] Model/View/Controller anpassen
- [ ] Specs schreiben
- [ ] Mit angemessener Rolle "durchklicken"

**Comment by amaierhofer** [comment]
@ThomasEllenberger grundsätzlich funktioniert der Export und auch die Sprache ist dann wie gewünscht in der Liste drinnen. Ich denke es hat mit der grösse des Exports zu tun, gibt es dafür nicht schon ein separates Ticket, diese Exporte zu beschleunigen?  Wie gehen wir weiter vor?

**Comment by ThomasEllenberger** [comment]
Betreffend Grosse Exporte haben wir hier bereits ein Github Issue: https://github.com/hitobito/hitobito/issues/1712
