### ISSUE TITLE
PEOPLE: Aus Einzel-Mitglied wird Familie, Kinder erfassen

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#136]
## 1. Aus Einzel-Mitglied wird Familie

Dies erfolgt manuell über die Mitglieder-Verwaltung des NV oder der Sektion. Es werden einfach zwei Einzel-Mitglieder mit Wohnt im gleichen Haushalt mit zusammengeführt und bei der nächsten Fakturierung wird dann eine Familien-Mitgliedschaft daraus.
Falls die zweite Person noch nicht registriert ist, kann sie sich via Selbstregistrierungsformular als Mitglied in der gleichen Sektion registrieren. Danach kann die Mitglieder-Verwaltung diese Person mit der anderen zusammenführen.

Es braucht für diesen Punkt zurzeit keinen Entwicklungsaufwand.

## 2. Haushalt/Kinder und Person suchen (Core)

Im Person#edit form:

![image](https://github.com/hitobito/hitobito_sac_cas/assets/655627/44288e0b-ccea-4708-ba7c-a87c93fdc91e)

Neu Core: Falls man keine Schreibrechte auf irgend eine andere Person hat, das Feld **Person suchen** deaktivieren mit dem Hinweis/Hover info: 'Du benötigst Schreibrechte auf mehrere Personen und diese in einem Haushalt zusammenzuführen'

Im SAC Wagon: Diesen Text dann customizen: 'Bitte wende dich an den Mitglieder-Dienst deiner Sektion um weitere erwachsene Personen in deinen Haushalt zusammenzuführen'

Das selbe gilt für Kinder und **Eintrag hinzufügen** vs. **Person suchen** Feld:

![image](https://github.com/hitobito/hitobito_sac_cas/assets/655627/18de6008-8274-413a-b73d-6615ed6c274e)

Neu:  Falls man keine Schreibrechte auf irgend eine andere Person hat, die Funktion **Eintrag hinzufügen** und damit implizit das Feld **Person suchen** ausblenden/nicht verfügbar machen

## 3. Kinder erfassen

Im Person#edit form:

Es soll neu möglich sein unter Kinder neue Kinder zu erfassen. 

### Youth Wagon

- Inline-Form mit: **Vorname**, **Name,** **Geschlecht**, **Geburtsdatum** (alle als Pflichtfelder)
- Feature-Toggle für dieses Feature

### SAC Wagon

- Feature-Toggle Kind erfassen aktivieren
- Personen unter 22 Jahren können keine Kinder hinzufügen
- Kinder müssen zwischen 6 und 17 Jahre alt sein

#### Rolle vs. Beitragskategorie Kind

1. Fügt eine Person mit Mitglied (Stammsektion) und Beitragskategorie `Familie` ein Kind hinzu, erhält das Kind automatisch eine Mitglied (Stammsektion) Rolle in der selben Sektion mit Beitragskategorie `Familie`
2. Fügt eine Person mit Mitglied (Zusatzsektion) und Beitragskategorie `Familie` ein Kind hinzu, erhält das Kind automatisch eine Mitglied (Zusatzsektion) Rolle in der selben Zusatzsektion mit Beitragskategorie `Familie`
3. In allen anderen Fällen erhält das Kind nicht automatisch eine Mitglied-Rolle, dies muss von Mitgliederdienst manuell gemacht werden (z.B. hinzufügen in Neuanmeldung Gruppe für Jugend-Mitgliedschaft oder ändern in Familie)

#### Haushalt Kind

- Das Kind erhält beim SAC direkt denselben Haushalt wie das erfasste Elternteil

## 4. Kinder auflisten

Hier im Youth Wagon die Darstellung verbessern:

![image](https://github.com/hitobito/hitobito_sac_cas/assets/655627/3dcbdfcb-45cf-49fa-bbbd-82461f891613)

Badges wie beim Haushalt sowie `x` Icon/Link um den Eintrag zu entfernen

# Tech-Spec

Kinder sind ein Youth Wagon Feature (Elternzugang)

https://github.com/hitobito/hitobito_youth/blob/master/app/views/people/_fields_youth.html.haml

# ToDo

- [x] Anpassung Person#edit Personen suche (2.)
- [x] 3. Erweiterung Kinder erfassen Core
- [x] 3. Erweiterung Kinder erfassen SAC Wagon
- [x] 4. Darstellung Kinder auflisten fixen
- [x] mit angemessener Rolle durchclicken
- [ ] CHANGELOG entry

**Comment by mtnstar** [comment]
> Sehe ich hier korrekt, dass es sich hier um ein Feature mit Auswirkungen auf den Core, den Youth-Wagon UND den Elternzugang hat? Wird hier ein Youth-Community Feature vom SAC weiterentwickelt?

Hoi Richi
dieses Feature wird nur im SAC wagon umgesetzt

**Comment by mtnstar** [comment]
wird mit #255 feriggestellt
