### ISSUE TITLE
PEOPLE: Import Sektions Mitglieder prüfen

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#137]
wir haben alle aktuellen Mitglieder der Sektion Blüemlisalp auf der Integration importiert.

es werden 3’770 Personen ausgewiesen

im verwendeten Import File sind  4’650 Personen-Einträge (davon sind 2'621 aktiv, 19 Abonnenten, 2'010 ausgetreten/inaktiv)

# Tech-Spec

- Export File in nextcloud/sac share unter Hitobito/7_Verschiedenes/navision-exporte, sektions_mitglieder.xlsx
- https://github.com/hitobito/hitobito_sac_cas/blob/master/lib/hitobito_sac_cas/import/sektion/mitglieder_importer.rb
- Vermutung: Aktive/Inaktive Rollen werden nicht richtig angelegt
- Reine Abonnenten nicht importieren

# ToDo

- [ ] Herausfinden wie die 3770 zu Stande kommen
- [ ] Import fixen und sicherstellen das die 2'621 aktiven bzw. 2'010 ausgetreten/inaktiv korregt angelegt werden
  - Die Abonnenten können vorerst ignoriert werden
- [ ] Ein Report beim Abschluss des Scripts einbauen. Wieviele Personen im Import-File und wieviele Personen Import werden konnten. Anzahl Fehlerhafte. Idealerweise sogar nr. aktive/inaktive
- [ ] Import nochmals auf Integration mit gefixter Version laufen lassen
- [ ] Stefan informieren

**Comment by amaierhofer** [comment]
Mit den letzten Anpassungen siehts so aus:
2621 (aktive), 2003 (inaktive), 26 (fehlerhafte + Abos) sind insgesamt 4650

- Folgende Personen (106455,106572,106832,155704,214104) habe ein ungültiges Geburtsdatum (00.01.1900)
- Person (325797) hat keinen Namen und auch Sprache fehlt
- der Rest sind Abonnenten, die aktuell noch nicht importiert werden

Und 20 Emails sind ungültig, diese personen werden ohne email importiert
