### ISSUE TITLE
PEOPLE: Import Mitgliedschaft Zusatzsektion

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#138]
Nachdem die Mitglied (Stammsektion) Rollen sowie deren Personen importiert wurden, sollen ebenfalls alle Mitglied (Zusatzsektion) Rollen erstellt werden. Dazu gibt es ein Export-XLSX `zusatzmitgliedschaften.xlsx`.

- Die Person muss schon existieren und eine aktive Mitglied (Stammsektion) Rolle in einer anderen Sektion haben. Dies sollte bereits über die Validierungen der Rollen sichergestellt sein. 
- Rollen die nicht erstellt werden können werden zusammen mit der Personen-ID im Error-Output aufgelistet (z.B. wenn Person nicht existiert oder diese keine aktive Stammsektionsrolle hat)
- Die Rollen haben das gleiche Bis-Datum wie das der Stammsektion Mitglied Rolle

## Beitragskategorie

-  Es ist möglich das alle Personen einer Familie in einer Zusatzsektion sind oder auch nur eine einzelne Person der Familie
- Grundsätzlich übernehmen wir die Beitragskategorie für Mitglied (Zusatzsektion)  aus dem Export und wir vertrauen beim Import das diese richtig gesetzt ist. Die Beitragskategorie ist hauptsächlich faktura-relevant und wird beim nächsten Fakturalauf im Herbst 2024 validiert und wo nötig automatisiert angepasst.

# Tech-Spec

- Für die Umsetzung sich am Mitglieder-Import https://github.com/hitobito/hitobito_sac_cas/tree/master/app/domain/import/sektion orientieren

relevante Spalten Export-File:
- Adressnummer: Mitglied-Nr / PK Person
- Sektion: Nr der Sektion, group#navision_id
- Zusatzelement: Beitragskategorie, Mitglied (Zusatzsektion) role#beitragskategorie
- Eintrittsdatum: Mitglied (Zusatzsektion) role#created_at, ist teilweise 1.1.1900 was vorerst ok ist und ggf. später noch korrigiert wird (dies sind aus dem Vor-vor System importierte Records bei denen das effektive Einrittsdatum nicht bekannt war)
- delete_on der Rolle analog aktiver Stammsektions-Rolle der Person (oder einfach statisch auf 31.12.2024 was eigentlich auf das gleiche Resultat führen sollte)

# ToDo

- [ ] Download/Analyse zusatzmitgliedschaften.xlsx (nextcloud)
- [ ] Importer Klassen definieren, test-xlsx mit fake-daten für die specs, spec files anlegen
- [ ] Specs ergänzen und Import implementieren
- [ ] Lokal den Import mit dem zur Verfügung stehenden Export-File testen
- [ ] Nach dem Merge des PRs den Import auf der Integrations-Umgebung laufen lassen

**Comment by sykesonrocks** [comment]
@mtnstar Das Bis-Datum der Zusatzmitgliedschaft ist nicht zwingend identisch mit dem Bis-Datum der Stammmitgliedschaft. Ein Mitglied kann für eine Zusatzsektion heute bereits ein Austritt auf den 31.12.2024 geplant haben, während bei der Stammsektion kein Austritt geplant ist (aktuell sind 15 solche Mutationen vor erfasst in Navision).

**Comment by mtnstar** [comment]
@daniel-illi ich assigne dieses Ticket mal noch dir da du ja die Import-Mechanos anschaust.
