### ISSUE TITLE
ROLES: Validierungen Stammsektion

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#139]
blocked by #106 

Mit #106 wurde das Thema Stammsektion/Zusatzsektion eingeführt.

Mit diesem Ticket sollen weitere Validierungen und Verbesserungen an diesem Feature vorgenommen werden.

## 1. Rename zu Stammsektion

Offiziell wird eine Hauptsektion **Stammsektion** genannt weshalb wir dies entsprechend renamen

## ~2. Validierung Mitglied-Rolle unique~

~Innerhalb der gleichen Mitglieder-Gruppe kann eine Person nur eine einzelne, aktive Mitglied-Rolle haben. Eine Validierung auf STI Rolle soll entsprechend verhindern das Rollen doppelt assigned werden können.~

~Betrifft ebenfalls Neuanmeldungen[NV, Sektion]::Neuanmeldung Rolle~

~Für diesen Workflow einen entsprechenden Unit Test auf Ebene Rolle schreiben~

wird mit #145 umgesetzt

## 3. Validierungen Stammsektion

Es soll nicht/niemanden möglich sein die Stammsektion zu ändern solange eine Mitglied-Rolle die Primary Group definiert.

![image](https://github.com/hitobito/hitobito_sac_cas/assets/655627/fda7aa78-64f6-4dec-be17-17bcc152ef96)

In diesem Beispiel soll der Stern also Read-Only sein und kann nicht einfach auf die Zusatzsektion Gruppe gesetzt werden. 

Betrifft ebenfalls Neuanmeldungen[NV, Sektion]::Neuanmeldung Rollen

### Workflow Wechsel Stammsektion

1. Aktuelle Mitglied-Rolle mit Stammsektion wird terminiert auf ein Datum
2. Neue Rolle in neuer Stammsektion wird ab dem terminierten Datum erstellt und setzt ab dann die neue Primary Group

## Sonstiges

Darstellung Stammsektion ⭐ wenn read-only aus Sicht Mitglied (imitieren)

![Image](https://github.com/hitobito/hitobito_sac_cas/assets/655627/57f08edf-4d35-4df8-901c-b9528c2bddca)

Etwas viel Space zwischen Stern und Gruppenname

# Tech-Spec

- https://github.com/hitobito/hitobito_sac_cas/blob/master/app/models/sac_cas/role/mitglied.rb
- Groups::Primary

# ToDo

- [x] Den Begriff 'Hauptsektion' überall durch den offiziellen Begriff **Stammsektion** ersetzen
- [x] Mitglied Rolle unique Validierungen einbauen
- [x] Stammsektion Validierungen
- [x] manuelles Testen inkl. Mitglieder Import Sektion
- [x] kurz und knackig dokumentieren in: https://github.com/hitobito/hitobito_sac_cas/blob/master/doc/README.md bzw. bei Bedarf eigenes md erstellen. z.B. roles.md und verlinken
