### ISSUE TITLE
Berechtigungsanpassung: Rolle "Schreibend" soll Abos im ganzen Layer bearbeiten können

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito_sac_cas#1396]
## Ausgangslage
 Eine Person mit der Rolle "Schreibend" in einer "Mitglieder" Gruppe kann aktuell nur die Abos in der eigenen Gruppe bearbeiten. 

## Anforderungen
 Sie sollte auch Abos im eigenen Layer bearbeiten können.
 
 Beispiel:
 Hat eine Person in der Gruppe "Mitglieder" des SAC Aarau eine Rolle "Schreibrecht" so muss sie auch die Abos der Hautpgruppe SAC Aarau bearbeiten können

## Mockup

![grafik](https://github.com/user-attachments/assets/b96943fd-b7e4-4dcb-a5ce-e8f0d46af9ee)

## ToDo

- [ ] Migration erstellen
- [ ] Domainklasse erstellen oder anpassen
- [ ] Model/View/Controller anpassen
- [ ] Neues Feature mit FeatureGate deaktivierbar machen
- [x] Specs schreiben
- [x] Mit angemessener Rolle "durchklicken"
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen
