### ISSUE TITLE
ROLE: Eigene Rolle für Zusatzsektion

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#150]
blocked by: #139, #133 

Bisher kennen wir nur eine Mitglied Rolle für Stamm- wie auch Zusatzsektionsmitgliedschaft. Stammsektion wird einfach über die Primary Group definiert. Mit diesem Ticket wollen wir eine eigene, neue Rolle für Mitgliedschaft Zusatzsektion einführen:

- So ist auch in der History der Person klar ersichtlich wann welche Zusatzmitgliedschaft aktiv war
- Es lassen sich spezifische Validierungen auf der Rolle definieren. z.B. eine Zusatzmitgliedschaft ist nur möglich falls eine aktive Mitgliedschaft in einer Stammsektion vorhanden ist
- Es kann eine Liste von Zusatzmitgliedern erstellt werden
- Der kommende Importer für die Zusatzmitgliedschaften kann so mit einer spezifischen Rolle arbeiten welche auch gleich die Validierungen vornimmt, wird mit #138 umgesetzt
- Berechnung der Anzahl Mitgliederjahre wird so klarer da nur die Mitgliedschaft Stammsektion entscheidend ist

## Beitragskategorie

Wir sind zu beginn davon ausgegangen das es keine Beitragskategorie **Familie** für **MitgliedZusatzsektion** gibt. Dem ist aber nicht so. die Beitragskategorien sind also identisch für Stammsektion-Mitglied als auch Zusatzsektion Mitglied. Mit diesem Ticket soll die Beitragskategorie vorerst identisch behandelt werden. Es gibt noch spezielle Cases die wir später noch handhaben müssen.

## Anpassungen

Folgende bestehende Bereiche müssen angepasst werden:

- Mitglied Rollen -> Stammsektion
- group self inscription: Beitritt Zusatzsektion
- Neuanmeldungen Gruppen
- Austritt
- Entfernen des Features Stammsektion gleich Hauptgruppe
  - Stammsektion wird neu über den spezifischen Rollentyp Mitglied (Stammsektion) gesteuert
  - :star: inkl. read-only logik usw. kann komplett entfernt werden
  - Standard-Core-Verhalten für :star:  / Hauptgruppe

### Rollen Label

- bestehend: Neuanmeldung (Einzel) (Zusatzsektion) -> neu: Neuanmeldung Zusatzsektion (Einzel)
- bestehend: Mitglied (Einzel) (Zusatzsektion) -> neu: Mitglied Zusatzsektion (Einzel)

# Tech-Spec

- Neue Rollen SektionsMitglieder::MitgliedZusatzsektion, SektionsNeuanmeldungen::NeuanmeldungZusatzsektion
  - Validierung das eine aktive **Mitglied Stammsektion** Rolle vorhanden sein muss, eine pendente Neuanmeldung Rolle gilt nicht als aktive **Mitglied** Rolle
  - Eine Person kann beliebig viele MitgliedZusatzsektion Rollen haben, jedoch nur eine aktive Mitglied Rolle (Stammsektion) 
  - NeuanmeldungZusatzsektion/MitgliedZusatzsektion kann nur erstellt werden falls eine aktive  **Mitglied Stammsektion** Rolle vorhanden ist
- Validierung auf Mitglied und Zusatzmitglied-Rollen das von/bis Datum immer gesetzt sein muss
- Sicherstellen das Beitragskategorie richtig assigned wird (Für alle Mitglied/Neuanmeldung Rollen)
- Anpassung group self inscription -> assignen richtige Neuanmeldung Rolle, blocked by: #126 
- Mitglied Role #to_s anpassen, Logik für Detektion Stammsektion anpassen
- Development Seeder anpassen sodass auch Zusatzsektion Mitgliedschaften geseedet werden (Beitragskategorie ggf. noch anpassen, wird anhand Geburtsdatum eigentlich automatisch bestimmt, Personen-Geburtsdatum sicherstellen das Person älter als 6 Jahre)

# ToDo

- [x] Neue Rollen Zusatzsektion Mitglied/Neuanmeldung inkl. Validierungen erstellen
- [x] Anpassen Rollen Bezeichnung Stammsektion, Zusatzsektion, usw., inkl :star: Stammsektion
- [x] Entfernen des Features Stammsektion gleich Hauptgruppe
- [x] group self inscription anpassen
- [x] Validierungen Mitglied Stammsektion
- [x] Anpassungen group self inscription
- [ ] https://github.com/hitobito/hitobito_sac_cas/issues/145 ticket updaten mit den Inhalten die noch nicht angepasst wurden
- [ ] mit angemessener Rolle durchclicken
- [ ] dokumentation in doc/README.md im sac wagon anpassen

**Comment by sykesonrocks** [comment]
@mtnstar Ich verstehe folgende Anpassung in der Spezifikation nicht:

 _Entfernen des Features Stammsektion gleich Hauptgruppe_
- _Stammsektion wird neu über den spezifischen Rollentyp Mitglied (Stammsektion) gesteuert_
- _⭐ inkl. read-only logik usw. kann komplett entfernt werden_
- _Standard-Core-Verhalten für ⭐ / Hauptgruppe_

Wenn ich ein Mitglied imitiere, kann ich den Stern beliebig setzen. Auf read-only setzen resp. nur editierbar für gewisse Rollen machen (z.B. Mitgliederverwaltung, Administrator)?

**Comment by sykesonrocks** [comment]
@mtnstar Wenn ich für ein Mitglied mit Beitragskategorie "Familie" eine Mitgliedschaft in einer Zusatzsektion beantrage, betrifft dieser Antrag nur diese Person nicht aber die gesamte Familie. Dito bei einem Sektionswechsel. Mit diesem Systemverhalten lassen wir aktuell zu, dass alleinstehende Personen eine Familienmitgliedschaft erlangen können. Folgende Richtlinie muss immer eingehalten sein: _Die Familienmitgliedschaft schliesst max. zwei Erwachsene ab 23 Jahren und gegebenenfalls x Kindern von 6 bis 17 Jahren im gleichen Haushalt ein._

Korrektes Verhalten: wenn ein Mitglied mit Beitragskategorie "Familie" eine Mitgliedschaft in einer Zusatzsektion oder ein Sektionswechsel beantragt, muss gefragt werden, ob dieser Antrag die gesamte Familie betrifft oder nur die beantragende Person. Betrifft der Antrag die gesamte Familie, müssen alle Familienmitglieder in der Gruppe "Neuanmeldungen" erscheinen. Betrifft der Antrag nur die beantragende Person, darf die Person in der Gruppe "Neuanmeldung" nicht in der Beitragskategorie "Familie" erscheinen - in diesem Fall sind nur die Beitragskategorien "Einzel" und "Jugend" möglich.

**Comment by mtnstar** [comment]
> @mtnstar Wenn ich für ein Mitglied mit Beitragskategorie "Familie" eine Mitgliedschaft in einer Zusatzsektion beantrage, betrifft dieser Antrag nur diese Person nicht aber die gesamte Familie. Dito bei einem Sektionswechsel. Mit diesem Systemverhalten lassen wir aktuell zu, dass alleinstehende Personen eine Familienmitgliedschaft erlangen können. Folgende Richtlinie muss immer eingehalten sein: _Die Familienmitgliedschaft schliesst max. zwei Erwachsene ab 23 Jahren und gegebenenfalls x Kindern von 6 bis 17 Jahren im gleichen Haushalt ein._
> 
> Korrektes Verhalten: wenn ein Mitglied mit Beitragskategorie "Familie" eine Mitgliedschaft in einer Zusatzsektion oder ein Sektionswechsel beantragt, muss gefragt werden, ob dieser Antrag die gesamte Familie betrifft oder nur die beantragende Person. Betrifft der Antrag die gesamte Familie, müssen alle Familienmitglieder in der Gruppe "Neuanmeldungen" erscheinen. Betrifft der Antrag nur die beantragende Person, darf die Person in der Gruppe "Neuanmeldung" nicht in der Beitragskategorie "Familie" erscheinen - in diesem Fall sind nur die Beitragskategorien "Einzel" und "Jugend" möglich.

ja, das haben wir auf dem Radar. Habe das hier noch ergänzt: https://github.com/hitobito/hitobito_sac_cas/issues/368
