### ISSUE TITLE
IMPORT: Anpassungen Hütten-Importer

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito_sac_cas#154]
partially blocked by: #244 (Sprache Sektion fehlt für Übersetzungen)

mit #213 hat die Gruppenstruktur der Sektionen leicht geändert.
Anstatt einem Sektions-Sub-Layer werden Hütten nun als Untergruppen in der Untergruppe Hüttenkommission geführt. Dazu muss der Hütten-Importer entsprechend angepasst werden. Bisher gab es auch noch keine Specs für diesen Importer was wir mit diesem Ticket nacholen.

Neu gibt es folgende Rollen in der Untergruppe Hütte:

- Hüttenwart*in
- Hüttenchef*in
- Andere

Import folgender Rollen:

- Hüttenwartspartner -> Andere, Bezeichnung auf Rolle: Hüttenwartspartner (Übersetzen falls Sektion FR, IT)
- Hüttenwart -> Hüttenwart*in
- Hüttenchef -> Hüttenchef*in
- Schlüsseldepot -> Andere,  Bezeichnung auf Rolle: Schlüsseldepot (Übersetzen falls Sektion FR, IT)
- Sektion > Hüttenkommission, Hüttenobmann*frau

# Tech-Spec

https://github.com/hitobito/hitobito_sac_cas/blob/master/app/domain/import/huts_importer.rb

Auch testen, dass Hüttenwart*innen etc. importiert werden können:
https://github.com/hitobito/hitobito_sac_cas/tree/master/app/domain/import/huts

Tests nicht mit Excel-File schreiben, sondern mit Mocking, ähnlich wie https://github.com/hitobito/hitobito_sac_cas/blob/master/spec/domain/import/sektionen_importer_spec.rb

Untergruppe Hüttenkommission anlegen falls diese nicht bereits existiert unter der Sektion.

# ToDo

- [x] Importer so anpassen das die Hütten in der Untergruppe 'Hüttenkommission' angelegt werden und nicht mehr als eigener Sub-Layer der Sektion (Gruppenstruktur wurde bereits angepasst, ebenso der devel seeder), specs schreiben
- [x] Anpassen der Rollen-Importe, spec spec spec
  - [x] Personen sollen nur noch gesucht werden (`Person.find_by`). Falls die Person noch eine Rolle in der "Navision Import" Gruppe hat, soll diese Rolle anschliessend entfernt werden https://github.com/hitobito/hitobito_sac_cas/blob/b38791e63ef7ded8a510b9a49c0188f5ecbd928c/app/domain/import/sektion/membership.rb#L80
- [x] manuell Testen mit Import-File auf Nextcloud
- [ ] Nach mörtsch Import auf der Integrationsumgebung laufen lassen
