### ISSUE TITLE
PEOPLE: Selbstregistrierung für Fan-Accounts

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito_sac_cas#162]
Externe Personen sollen sich, neben der Registrierung als Mitglied, auch als Fan registrieren können.
Fan-Accounts werden Stand heute als Kontakte in einer Externe-Kontakte-Gruppe auf dem Dachverband geführt. Dort wird die Selbstregistrierung aktiviert.
Die Selbstregistrierung braucht aber in diesem Gruppentyp (eigentlich überall ausser bei den Neuanmeldungs-Gruppen) ein anderes abgespecktes Formular, bei dem z.B. die Familienmitglieder nicht gleich mit registriert werden können. Das Formular soll nur Name, Mailadresse, sowie Checkboxen für Privacy Policy und Newsletter enthalten, also sehr ähnlich wie es im Core ist.

# TODO
- [ ] [SelfRegistrationController](https://github.com/hitobito/hitobito/blob/master/app/controllers/groups/self_registration_controller.rb) oder [SelfRegistration Model](https://github.com/hitobito/hitobito/blob/master/app/models/self_registration.rb) im Core so erweitern, dass die [`partials`](https://github.com/hitobito/hitobito/blob/master/app/models/self_registration.rb#L14) oder gleich das ganze SelfRegistration Model abhängig von externen Faktoren (in diesem Fall abhängig vom Gruppentyp) unterschiedlich gewählt werden können
- [ ] Im SAC Wagon die Partials `[:main_person, :household, :summary]` nur noch verwenden, wenn die Gruppe vom Typ `Group::SektionsNeuanmeldungenNv` oder `Group::SektionsNeuanmeldungenSektion` ist
- [ ] Für alle anderen Gruppentypen ein simpleres Selbstregistrierungsformular anbieten, ähnlich dem wie es im Core ist
  - [ ] Inputs für Firmenname und Firma entfernen, Inputs für Name und Mailadresse belassen
  - [ ] Privacy Policy soll akzeptierbar sein (müsste in der Implementation vom Core automatisch mitkommen)
  - [ ] Newsletter-Checkbox gleich wie bei der Neuanmeldungs-Selbstregistrierung, setzt für den Moment ein Tag auf der erstellten Person
  - [ ] Bei existierender Mailadresse auf Login-Maske bzw. Selbsteinschreibung für die Gruppe verweisen
- [ ] Feature Specs schreiben
- [ ] Mit angemessener Rolle durchklicken
- [ ] Changelog-Eintrag erfassen
