### ISSUE TITLE
PEOPLE: Selbstregistrierung Rollen-Validierungen für Familienmitglieder

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito_sac_cas#164]
Aktuelles Verhalten: Wird bei der Selbstregistrierung eine Person oder ein Familienmitglied jünger als 6 Jahre angegeben, dann schlägt die Validierung erst beim finalen Absenden des Mehrschritt-Formulars an, und gibt dem User einen 500er Fehler.

Gewünschtes Verhalten: Validierungen auf allen registrierten Personen (und insbesondere auch deren zukünftigen Rollen) werden bereits früher im Prozess vollständig evaluiert und etwaige Probleme direkt im entsprechenden Formular-Schritt dem User angezeigt. Allermindestens sollte kein 500er-Fehler auftreten, sondern dem User die Möglichkeit geboten werden, den Fehler zu korrigieren.

Grund ist vermutlich, dass diese Alters-Validierung auf der Rolle ist, aber im Formular nur die MainPerson bzw. Housemate validiert wird.
Andere Validierungen, z.B. fehlender Name und fehlende Mailadresse werden nämlich korrekt bereits während dem Prozess angezeigt.

## Tech-Spec

- Im Core generischer Ansatz der die künftig erstellen Rollen validiert und Fehler auf Rollen bereits im Formular anzeigt

## ToDo

- [x] Z.B. in [`SelfRegistration::Housemate`](https://github.com/hitobito/hitobito/blob/master/app/models/self_registration/housemate.rb) im Core oder im Wagon before_validation auch noch die Rollen konstruieren die bei der Selbstregistrierung entstehen wird, damit diese bei den Validierungen miteinbezogen werden
- [x] Feature Spec für den Fehlerfall schreiben
- [x] mit angemessener Rolle durchklicken
- [ ] CHANGELOG entry
