### ISSUE TITLE
PEOPLE: Formatierung der inline Validierungsmeldungen im Selbstregistrierungsformular

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito_sac_cas#165]
Um zu reproduzieren, hitobito mit einem anderen Wagon als SAC oder SWW starten (in den Screenshots ists der SKV).

Aktuelles Verhalten:
![Screenshot 2023-11-30 at 09-53-20 hitobito - Test Titel](https://github.com/hitobito/hitobito_sac_cas/assets/7566995/a7634327-8cf2-4a56-981e-23329cb3d6eb)

Gewünschtes Verhalten:
![Screenshot 2023-11-30 at 15-01-39 hitobito - Test Titel](https://github.com/hitobito/hitobito_sac_cas/assets/7566995/84802226-ba3c-4dea-a621-0a6d54936468)

# TODO
- [ ] Formatierung der Validierungs-Message fixen
- [ ] Sicherstellen, dass die Änderung an der Validierung im SAC-Wagon nichts kaputt macht
- [ ] Da im Core keine weitere Mailadressen angegeben werden können, den zweiten Teil der Übersetzung mit den weiteren Mailadressen löschen

**Comment by amaierhofer** [comment]
Die formatierung der Error Messages wurde schon in vorigen commits korrigiert. Hier kommt noch die Anpassung, dass die plain `taken` und nicht die custom `person.email.taken` Fehlermeldung angezeigt wird. 

![image](https://github.com/hitobito/hitobito_sac_cas/assets/180780/6cf852fa-fc8f-422d-8a4b-4fc8d7ea06b5)

**Comment by amaierhofer** [comment]
Habe wieder zurückgestellt auf die ausführlichere Fehlermeldung
