### ISSUE TITLE
PEOPLE: Selbstregistrierung Familienmitglieder required Markierungen

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito_sac_cas#166]
Im zweiten Schritt des Selbstregistrierungsformulars im SAC-Wagon sind einige der Felder Pflichtfelder, haben aber keinen roten Stern wie wir das sonst überall in hitobito (und auch bei den anderen Schritten des Formulars) haben. Diese visuelle Markierung soll ergänzt werden.

Vormals als diese Felder mal mit HTML5 required markiert wurden, gab es Probleme, wenn man ein Familienmitglied im Formular hinzufügt, nichts ausfüllt und wieder löscht. Die nested form Felder bleiben dann im HTML, einfach mit `display: none`, und dann kann man im Formular nicht mehr fortschreiten, weil für immer unausfüllbare required Inputs vorhanden sind. Die [empfohlene Lösung](https://github.com/ryanb/nested_form/wiki/How-To:-HTML5-validation-in-hidden-fields) von nested_form ist, folgendes JS auf der Seite laufen zu lassen:

```coffeescript
$(document).on 'nested:fieldRemoved', (event) ->
  $('[required]', event.field).removeAttr('required')
```

# TODO
- [x] Felder mit required Attribut versehen, dann müsste hitobito's CSS den Stern automatisch machen
- [ ] Sicherstellen, dass die Required-Markierung von wieder gelöschten Familienmitgliedern keine Probleme macht
  - [x] Falls doch, den obigen coffeescript-Fix im Core einfügen (einfach als coffeescript-Datei unter app/javascript/javascripts/modules/)
