### ISSUE TITLE
PEOPLE: Im Selbstregistrierungsformular zurück navigieren nach Validierungsfehler

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito_sac_cas#167]
Schritte zum Reproduzieren:
1. Selbstregistrierungsformular einer Neuanmeldungen-Gruppe aufrufen
2. Erste Seite mit Personendaten ausfüllen
3. Auf zweiter Seite ein Familienmitglied erfassen, aber Validierungsfehler provozieren (z.B. solange #166 nicht umgesetzt ist einfach alle Felder leer lassen, oder dieselbe Mailadresse wie bei der Haupt-Person verwenden)
4. Auf "Weiter als Familienmitgliedschaft" klicken, um Validierungsfehler auf dem Screen zu sehen
5. "Zurück" Link klicken (z.B. weil man bei der Hauptperson eine andere Mailadresse eintragen möchte)

Aktuelles Verhalten:
Der Weiter-Button funktioniert nicht mehr, man kommt nie mehr auf den zweiten Formular-Schritt. Je nach Validierungsproblem (z.B. wenn man dieselbe Mailadresse für Haupt-Person und Haushaltsperson verwendet hat) kann es möglich sein, das Problem im ersten Formular-Schritt zu beheben und fortzufahren. Falls nicht (z.B. weil das Kind weniger als 6 Jahre alt ist), ist die einzige Lösung, die Seite neu zu laden und die bereits gemachten Eingaben zu verlieren.

Erwartetes Verhalten:
Alle Schritte des Formulars können von hier aus weiterhin normal ausgefüllt werden.

# Screencast
https://github.com/hitobito/hitobito_sac_cas/assets/7566995/6d6ba153-2db3-4071-9e8f-f67f80813359

# TODO (wähle eine Option)
- [ ] Option 1: Den Zurück-Link deaktivieren wenn Validierungsfehler im aktuellen Schritt vorhanden sind. Ist aber eher unschön und potenziell unverständlich für die User, wenn sie eigentlich nur im Formular zurück wollen.
- [ ] Option 2: Beim Zurück-Link auch eine serverseitige Abfrage machen und die Navigation bei Validierungsfehlern abbrechen. Könnte aber zu Problemen führen, wenn es Validierungen gibt die Daten von mehreren Schritten miteinbeziehen, und man eigentlich zum vorherigen Schritt zurück müsste um etwas zu beheben.
- [ ] Option 3: Doch noch eine Lösung bauen, bei der nur jeweils die Daten des aktuellen Schritts validiert werden, nicht die Daten der restlichen Schritte. Ist sehr aufwändig und herausfordernd eine saubere Architektur zu finden, wie sich in https://github.com/hitobito/hitobito/pull/2264 gezeigt hat.
- [ ] Option 4: Custom Lösung für die Schritte des SAC bauen, und auch bei allen anderen Kunden die je eigene Schritte definieren wollen. Ist keine generische Lösung, sondern Symptombekämpfung, und wir laufen das Risiko, einige dieser Probleme zu übersehen und den Usern eine schlechte UX beim Registrierungsformular zu bieten.

**Comment by sykesonrocks** [comment]
Siehe Arbeitshypothese #10a: https://saccas.atlassian.net/wiki/spaces/DIGISAC/pages/3959193601/Arbeitshypothesen

_Eine E-Mail Adresse eines aktiven und inaktiven Mitglieds muss jederzeit eindeutig sein. 
Ausnahme bei “Frei Kind”- und “Frei Fam”-Mitglieder: sie können optional eine E-Mail Adresse erfassen und bestätigen. Wenn eine E-Mail Adresse erfasst wird, muss diese innerhalb derselben Familie nicht eindeutig sein (d.h. “Fam”, “Frei Fam” und “Frei Kind” derselben Familie können dieselbe E-Mail Adresse erfassen)._

Falls die Hypothese falsch ist, bitte mitteilen. Aktuell gehen wir davon aus, dass 
a) die Erfassung einer E-Mail Adresse bei "Frei Kind" und "Frei Fam" optional ist und
b) die E-Mail Adresse eines "Frei Kind" und "Frei Fam" Mitglieds innerhalb derselben Familie nicht eindeutig sein muss.

**Comment by sykesonrocks** [comment]
Wichtig:
- Das Familienoberhaupt (Fam) muss eine Telefonnummer sowie eine eindeutige E-Mail Adresse erfassen und diese bestätigen. 
- Familienmitglieder (Frei Fam und Frei Kind) dürfen, müssen aber nicht, folgende Angaben beim Onboarding erfassen: E-Mail, Telefon und Mobil (Vorname, Nachname, Geschlecht und Geburtsdatum sind Pflichtfelder).
- Die E-Mail Adresse eines Familienmitglieds muss innerhalb der Familie nicht eindeutig sein, sprich ein Frei Kind oder Frei Fam kann die E-Mail Adresse des Fam-Oberhaupts wiederverwenden.

Wenn nun ein Wechsel bevorsteht (z.B. aufgrund des Alters), muss Hitobito vor dem Wechsel prüfen, ob eine E-Mail Adresse erfasst ist und ob diese eindeutig ist. Nur wenn diese Bedingungen erfüllt sind, darf die Person zur Gruppe "Neuanmeldungen" gezügelt werden. Mein Verständnis ist, dass sobald die Person zur Gruppe "Neuanmeldungen" gezügelt wird, wird die Person eine von Hitobito automatisch erzeugte E-Mail erhalten, mit der Bitte um E-Mail Adressbestätigung. Wenn eine der beiden Kriterien nicht erfüllt sind, kann Hitobito den Wechsel nicht vornehmen, ergo die Person kann nicht zur Gruppe "Neuanmeldungen" gezügelt werden. Hier müsste der SAC Rücksprache mit der Person nehmen. Die Idee ist auch, dass man Personen mit einem bevorstehenden Wechsel frühzeitig identifiziert (Thema "Liste") und über dessen Wechsel informiert (z.B. E-Mail an Fam-Oberhaupt oder Briefpost), mit der Bitte, sicherzustellen, dass eine eindeutige E-Mail Adresse hinterlegt ist (in diesem Fall müsste das Fam-Oberhaupt die Mutation in Hitobito direkt vornehmen, da z.B. das Frei Kind noch kein Login hat). Es gibt sicherlich andere Wege, die wir besprechen könnten: z.B. Personen mit einem bevorstehenden Wechsel, aber mit fehlender E-Mail Adresse, könnten wir trotzdem in die Gruppe "Neuanmeldungen" zügeln, aber dann halt mit folgenden Flags (siehe Arbeitshypothese 4):
- Elektronische Rechnungsstellung/Verzicht auf physische Rechnungsstellung=Nein
- Digitaler Mitgliederausweis/Verzicht auf physischen Mitgliederausweis=Nein
- Erfolgreiche E-Mail Adressverifikation=Nein
Ich bin grundsätzlich offen, welche der beiden Varianten wir verfolgen möchten.

Um Missverständnisse zu vermeiden:
- Dass Hitobito nur dann ein Konto anlegt, wenn eine E-Mail Adresse erfasst und bestätigt ist, ist völlig i. O. Die Konsequenz einer fehlenden E-Mail Adresse resp. Bestätigung, dass man sich nicht in andere Systeme wie z.B. SAC App einloggen kann, passt.
- Dass man sich nur dann mit der Mitgliedernummer einloggen kann, wenn eine E-Mail Adresse hinterlegt und bestätigt ist, ist völlig i. O. 
- Dass nur der Fam-Oberhaupt die Stammdaten der Frei Kind und Frei Fam Mitglieder anpassen kann, ist i. O.
- Dass das Frei Fam Mitglied die Stammdaten des Fam und Frei Kind Mitglieds nicht anpassen kann, ist i. O.
- Dass jedes Mitglied eine E-Mail Adresse besitzen muss, ist falsch. Frei Fam und Frei Kind Mitglieder können, müssen aber nicht, eine E-Mail Adresse erfassen und bestätigen. Einzel, Jugend und Fam Mitglieder müssen eine eindeutige E-Mail Adresse erfassen und bestätigen. Aber Achtung: heute bestehende Mitglieder der Kategorie Einzel, Jugend und Fam ohne E-Mail Adresse sind weiterhin gültige Mitglieder! Diese Mitglieder können dann die digitalen SAC Dienstleistungen nicht wahrnehmen (aufgrund fehlendem Login).
