### ISSUE TITLE
PEOPLE: Mehrschritt-Selbstregistrierungsformular mit ENTER absenden

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito_sac_cas#170]
Aktuelles Verhalten: Wenn man auf dem letzten Schritt des Selbstregistrierungsformulars ist, den Fokus z.B. im Promocode-Feld hat und dann ENTER drückt, dann wird nicht das Formular abgeschickt sondern man kommt auf den zweiten Schritt des Formulars.

Gewünschtes Verhalten: Mit ENTER wird der primäre Submit Button des Formulars betätigt, und somit das ganze Formular abgesendet.

Vormals wurde deswegen ENTER auf diesem Formular komplett unterdrückt, was aber schlecht für die Accessibility ist. Daher wurde das in ff292409908dcb13487c38670fee515bc356d04e rückgängig gemacht.

# ToDo
- [x] Grund finden, warum man mit ENTER im letzten Step auf den zweiten Step zurück kommt
- [x] Fix umsetzen, der nur dieses eine Problem fixt und nicht die ganze Accessibility des Forms opfert
- [x] mit angemessener Rolle durchklicken
