### ISSUE TITLE
PEOPLE: Selbstregistrierung Felder für Familienmitglieder

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito_sac_cas#187]
Die Felder der Familienmitglieder im Selbstregistrierungsformular sollen wie folgt angezeigt werden:

## Mockup
![Screenshot 2023-12-13 at 13-16-42 SAC Hitobito Balsamiq-Mockups pdf](https://github.com/hitobito/hitobito_sac_cas/assets/7566995/5946efce-8d08-4481-8bab-0a92bcda30af)
Quelle: https://raw.githubusercontent.com/hitobito/hitobito_sac_cas/master/doc/SAC%20Hitobito%20Balsamiq-Mockups.pdf#page=7

Was nicht stimmt auf dem Mockup:
- Vorname, Nachname, Geschlecht und Geburtsdatum sind Pflichtfelder und sollen auch entsprechend mit Stern markiert werden
- Anrede sollte Geschlecht heissen

Das Aside mit "Beiträge in der Sektion..." etc. wird in einem separaten Ticket erweitert.

UPDATE: Familienmitglieder müssen nicht unbedingt eine Mailadresse haben. Eine Familienmitgliedschaft muss einfach mindestens eine Person mit validierter Mailadresse enthalten. Daher kann das E-Mail-Feld bei den Familienmitgliedern optional sein und wir müssen den Wert nicht als zusätzliche E-Mail abspeichern, sondern als Haupt-E-Mail. Dafür müssen wir (weiterhin?) validieren dass dieselbe Mailadresse nicht bei mehreren Personen eingesetzt wird (auch nicht bei mehreren Personen die gerade zusammen als Familie registriert werden).

## TODO
- [x] Form Submit / Zurück Buttons bei diesem Schritt oben und unten einfügen
- [x] Reihenfolge der Felder ändern
- [x] Labels der Felder ändern
- [x] Vorname, Nachname, Geschlecht und Geburtsdatum als required validieren und markieren, andere Felder nicht
- [x] In den Wagon-settings.yml die `phone_number.predefined_labels` erweitern um ein Label 'Haupt-Telefon'
- [ ] ~~Das Feld E-Mail wird automatisch als weitere E-Mail mit Bezeichnung "Privat" auf das Familienmitglied geschrieben~~
- [x] Das Feld Telefon wird automatisch als weitere E-Mail mit Bezeichnung "Haupt-Telefon" auf das Familienmitglied geschrieben
