### ISSUE TITLE
PEOPLE: Weitere Spalten in Personenlisten für SAC-spezifische Informationen

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito_sac_cas#188]
Partially blocked by #101

Der SAC braucht für diverse Use Cases, insbesondere für den Onboarding-Prozess, weitere Informationen als auswählbare Spalten auf Personenlisten.

# Tech Spec
- Umsetzung im SAC Wagon
- Auswählbare Spalten heissen in hitobito TableDisplay Columns. Eine kleine Doku gibts hier: https://github.com/hitobito/hitobito/blob/master/doc/features/table-display-additional-columns.md
- Im Wagon können solche Spalten im wagon.rb definiert werden, mit `TableDisplay.register_column(Person, MyCustomTableDisplayClass, :field_or_array_of_fields_to_display)`
- Ein Beispiel für eine solche Custom TableDisplay Column Klasse ist hier: https://github.com/hitobito/hitobito_sac_cas/blob/master/app/domain/table_displays/people/membership_years_column.rb oder hier: https://github.com/hitobito/hitobito/blob/master/app/domain/table_displays/people/login_status_column.rb
- Statt `template.format_attr(target, target_attr)` kann man auch direkt z.B. eine Domain-Klasse verwenden, um den angezeigten Wert zu berechnen. Achtung: Derselbe Wert muss im UI wie auch im Excel-Export anzeigbar sein, also nicht unbedacht HTML-Tags ausgeben

# TODO
- [ ] Neue TableDisplay Column Beitragskategorie
  - [ ] Required permission `:show_full`
  - [ ] Verwendet [SacCas::Beitragskategorie::Calculator](https://github.com/hitobito/hitobito_sac_cas/blob/master/app/domain/sac_cas/beitragskategorie/calculator.rb) um die Beitragskategorie der Person zu berechnen
- [ ] Neue TableDisplay Column "Antrag für" (macht nur Sinn in Neuanmeldungs-Gruppen)
  - [ ] Required permission `:show`
  - [ ] Falls die Person eine aktive Hauptsektions-Mitgliedschaft hat, zeigt diese Spalte "Zusatzsektion" an. Sonst zeigt diese Spalte "Hauptsektion" an (übersetzbare Texte)
- [ ] Neue TableDisplay Column Antragsdatum (macht nur Sinn in Neuanmeldungs-Gruppen)
  - [ ] Required permission `:show`
  - [ ] Zeigt das created_at Datum der Neuanmeldungen-Rolle an (oder generell das created_at einer der Rollen, wegen der die Person in dieser Liste angezeigt wird)
- [ ] Neue TableDisplay Column "Beitritt per" (macht nur Sinn in Neuanmeldungs-Gruppen, blocked by #101)
  - [ ] Required permission `:show`
  - [ ] Zeigt die Rollen-Eigenschaft "Eintrittsdatum per" der Neuanmeldungen-Rolle an (oder generell von einer der Rollen, wegen der die Person in dieser Liste angezeigt wird, wobei das Feld dann aber immer leer ist)
- [ ] Neue TableDisplay Column "E-Mail bestätigt am"
  - [ ] Required permission `:show_full`
  - [ ] Zeigt Person#confirmed_at an
- [ ] Neue TableDisplay Column "Dublette"
  - [ ] Required permission `:show`
  - [ ] Zeigt an (ja/nein), ob ein nicht ignoriertes PersonDuplicate existiert wo diese Person involviert ist
- [ ] Neue TableDisplay Column "Wiedereintritt" (macht nur Sinn in Neuanmeldungs-Gruppen)
  - [ ] Required permission `:show`
  - [ ] Falls die Person keine aktive Mitgliedschaftsrolle hat, aber mindestens eine beendete Mitgliedschaftsrolle hat, zeigt diese Spalte "ja" an. Sonst zeigt diese Spalte "nein" an (übersetzbare Texte global.yes / global.no oder so ähnlich)
- [ ] Neue TableDisplay Column "Adresse gültig"
  - [ ] Required permission `:show`
  - [ ] Falls die Person das Tag `PersonTags::Validation.ADDRESS_INVALID` hat, zeigt diese Spalte "nein" an. Sonst zeigt diese Spalte "ja" an (übersetzbare Texte global.yes / global.no oder so ähnlich)
- [ ] Neue TableDisplay Column "Eintrittsgrund" (blocked by #101)
  - [ ] Required permission `:show_full`
  - [ ] Zeigt den übersetzten Text von `Person.self_registration_reason` an
- [ ] Neue TableDisplay Column "Newsletter"
  - [ ] Required permission `:show`
  - [ ] Falls die Person das Tag `'newsletter'` hat, zeigt diese Spalte "ja" an. Sonst zeigt diese Spalte "nein" an (übersetzbare Texte global.yes / global.no oder so ähnlich)
- [ ] Optional, falls in nützlicher Frist möglich: Die Spalten die mit "macht nur Sinn in Neuanmeldungs-Gruppen" markiert sind nur in Gruppen vom Typ NeuanmeldungenZv und NeuanmeldungenSektion anzeigen.
- [ ] Tests für Listen und Exports schreiben
- [ ] Mit angemessener Rolle durchklicken
- [ ] Kunde wegen Übersetzungen informieren
- [ ] Changelog-Eintrag erfassen

**Comment by daniel-illi** [comment]
@carlobeltrame ich habe noch ein paar Bedenken zu der Spezifikation.

* Auf einer Personenliste werden alle Personen angezeigt mit einer Rolle in diesem Scope. Welche von den Rollen soll dann verwendet werden zur Anzeige der Attributen? 
    - aktuelle Rolle
    - zukünftige Rolle
    - was ist bei mehreren gleichzeitig gültigen Rollen oder FutureRoles in verschiedenen Subgruppen

* gewisse Spalten werden ja nur in der Neuanmeldungsgruppe angezeigt. Wenn ich in einer parent group die Personen anzeigen, sehe ich dort die Personen auch mit der Neuanmeldungsrolle, sehe aber die Details dazu nicht. Ist das gewollt so?
