### ISSUE TITLE
PEOPLE: Selbstregistrierung Aside Inhalte dynamisch an Eingaben anpassen

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito_sac_cas#191]
Blocked by #103, #187

Im Aside neben dem Selbstregistrierungsformular werden seit #103 Informationen über die Mitgliedschaft (und später auch über die Preise) angezeigt, basierend auf der Sektion zu der das Selbstregistrierungsformular gehört.

Je nach dem wie viele und wie alte Familienmitglieder erfasst werden, soll sich diese Anzeige auch ändern.

## Mockup
![Screenshot 2023-12-13 at 13-29-13 SAC Hitobito Balsamiq-Mockups pdf](https://github.com/hitobito/hitobito_sac_cas/assets/7566995/31fc98ef-f3e3-4cf8-b95b-af77053f0aee)
Quelle: https://raw.githubusercontent.com/hitobito/hitobito_sac_cas/master/doc/SAC%20Hitobito%20Balsamiq-Mockups.pdf#page=7

Im Mockup fehlt noch die statische Infobox:
![Screenshot 2023-12-13 at 13-33-36 SAC Hitobito Balsamiq-Mockups pdf](https://github.com/hitobito/hitobito_sac_cas/assets/7566995/9f8193ac-1d05-44d6-9c7a-852594b7487d)

## Tech Spec
Damit wir später die komplizierte Preisberechnung sowie bereits jetzt die Familien-Regeln nicht in JS noch einmal nachprogrammieren müssen, soll die Berechnung der angezeigten Informationen serverseitig geschehen. Also entweder mit einem XHR JS Partial (so wie wir es bisher in hitobito überall machen), oder via API die von JS aus abgefragt werden kann, oder falls mit vertretbarem Aufwand im Core einrichtbar mit Turbo Streams.
Begründung: Eine Technologie wie Turbo Streams nur im Wagon einzuführen würde den Gap zwischen den verschiedenen Kunden-Instanzen unnötig vergrössern, hier besonders auch in Bezug auf die Infrastruktur, wegen den benötigten WebSockets. Solche Dinge erst später vom Wagon in den Core zu zügeln ist erfahrungsgemäss niemand zu zahlen bereit.

Die Sektionsbeiträge werden erst berechnet wenn wir zur ERP-Anbindung kommen, diese können vorerst weggelassen werden.

Falls ungültige Eingaben gemacht werden, wird dies weiterhin durch Validierungen abgefangen. Das Aside ist mehr als Zusatz-Information zu verstehen, denn auf Mobile ist es weit unter dem Fold, und ist daher keine verlässliche, einfach zugängliche Informationsquelle.

## TODO
- [ ] Inhalt des Asides dynamisch anpassbar machen (Grundlagen dafür schaffen)
- [ ] Anzeige der eingetragenen Familienmitglieder gemäss Mockup umsetzen
- [ ] Der Fehlerfall (dass man eine ungültige Familienkombination oder Personen mit ungültigem Alter erfasst) kann weiterhin durch Validierungen abgefangen werden. Das Aside sollte dann einfach nichts unsinniges anzeigen.
- [ ] Für die Anzeige der Beitragskategorie die neu erstellte Rolle mit `new` erstellen (aber nicht in die DB persistieren) und diese Rolle nach der Beitragskategorie befragen

**Comment by amaierhofer** [comment]
Ersetzt durch https://github.com/hitobito/hitobito_sac_cas/issues/933
