### ISSUE TITLE
IMPORT: Alle Personen von Navision importieren

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito_sac_cas#192]
Im Zuge des Datenimports haben wir eine Datei mit sämtlichen Personen des SAC bekommen, vorerst noch ohne Rollen, da die Zuordnung der Navision-Verteilercodes zu hitobito-Rollen noch in Arbeit ist.
Diese Personenliste soll in hitobito importiert werden. Zur Kontrolle und zur einfacheren Sichtbarkeit für Stefan sollen alle importierten Personen, die nicht schon eine Rolle in hitobito haben, in der Gruppe "Kontakte" auf dem Dachverband eine Rolle "Kontakt" bekommen.

Die Import-Datei ist für die Dauer dieses Tickets unter https://files.puzzle.ch/apps/files/?dir=/swe/projects/SAC_SchweizerAlpenClub/Hitobito/7_Verschiedenes/navision-exporte&fileid=5855028 unter dem Namen "Kontakte_20231129.xlsx" abgelegt.

## Security
Mit dem SAC wurde abgesprochen, dass Puzzle keinerlei Verantwortung trägt, wenn wegen diesem Import von produktiven Daten auf der SAC-Integrationsumgebung Unberechtigte Personen an Daten kommen. Der SAC muss vorerst grösste Vorsicht walten lassen, wem der Zugang zur Integrationsumgebung gewährt wird, solange die Rollen und Berechtigungen nicht ausreichend eingeschränkt sind.

## TODO
- [x] Importer für rollenlose Kontakte schreiben, ähnlich wie der existierende [Sektions-Importer](https://github.com/hitobito/hitobito_sac_cas/blob/master/lib/hitobito_sac_cas/import/sektion/mitglieder_importer.rb)
  - [x] Importer soll wieder idempotent sein, d.h. mehrmals ausgeführt werden können und die Daten dabei aktualisieren. Sämtliche "Kontakt" Rollen in der Dachverbands-Kontakt-Gruppe (aber nicht in Untergruppen davon) dürfen dabei beim Import jeweils zuerst herausgespült werden. (Achtung, möglicherweise müssen wir auch die Logeinträge der entsprechenden Personen löschen, sonst könnte es Fehler geben, wenn die Logs auf herausgespülte Kontakt-Rollen verweisen. Möglicherweise passiert das aber auch automatisch via cascade delete der Rolle..?)
  - [x] Möglichst alle Spalten der Datei importieren. Wie immer können wir Adresse, Adresszusatz und Postfach in ein Feld kombinieren. Personentyp, Erfasst von, Aktualisiert von können wir vorerst ignorieren.
  - [x] Jeder importierten Person, falls sie nicht bereits eine andere Rolle in der Datenbank hat (würde man via Mitgliedernummer == ID erkennen), eine Rolle "Kontakt" in der Gruppe "Kontakte" direkt im Dachverband geben
- [x] Tests für Importer schreiben
- [ ] Nach Merge: Import auf Integrationsumgebung ausführen und Stefan benachrichtigen
- [ ] Nach OK von Stefan: Datei von Nextcloud und Entwickler-Computern löschen

**Comment by daniel-illi** [comment]
Der Import auf Integration ist abgeschlossen.
Das Fehlerprotokoll liegt hier: https://files.puzzle.ch/f/6025554
