### ISSUE TITLE
IMPORT: Alle aktiven Mitgliederrollen importieren

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito_sac_cas#193]
Blocked by #192

Im Zuge des Datenimports haben wir eine Datei mit sämtlichen aktiven Sektionsmitgliedern des SAC bekommen.
Diese Liste von Mitgliedsrollen soll in hitobito importiert werden.

Die dazugehörigen Personen müssten seit #192 bereits alle in der Datenbank vorhanden sein. Sie sollten alle mindestens eine Rolle haben, im Zweifelsfall nur eine einfach eine "Kontakt" Rolle in der Gruppe Kontakte im Dachverband. Diese Platzhalter-Kontakt-Rollen sollen beim Import bei allen aktiven Mitgliedern hart gelöscht werden. So kann der SAC in dieser Kontakte-Gruppe nachvollziehen, welche Navision-Personen noch keine korrekten Rollen importiert bekommen haben, und folglich welche Rollen wir später noch importieren müssen.

Die Import-Datei ist für die Dauer dieses Tickets unter https://files.puzzle.ch/apps/files/?dir=/swe/projects/SAC_SchweizerAlpenClub/Hitobito/7_Verschiedenes/navision-exporte&fileid=5855028 unter dem Namen "Mitglieder_aktive_20231129.xlsx" abgelegt.

## Security
Mit dem SAC wurde abgesprochen, dass Puzzle keinerlei Verantwortung trägt, wenn wegen diesem Import von produktiven Daten auf der SAC-Integrationsumgebung Unberechtigte Personen an Daten kommen. Der SAC muss vorerst grösste Vorsicht walten lassen, wem der Zugang zur Integrationsumgebung gewährt wird, solange die Rollen und Berechtigungen nicht ausreichend eingeschränkt sind.

## TODO
- [ ] [Sektions-Importer](https://github.com/hitobito/hitobito_sac_cas/blob/master/lib/hitobito_sac_cas/import/sektion/mitglieder_importer.rb) umschreiben oder neuen Importer anlegen
  - [ ] Importer soll wieder idempotent sein, d.h. mehrmals ausgeführt werden können und die Daten dabei aktualisieren
  - [ ] Im Importer keine ganz neuen Personen mehr anlegen, sondern nur noch Mitgliederrollen in der korrekten Sektion (müssten alle schon vorhanden sein und via Sektionsnummer identifizierbar sein)
  - [ ] Bei jeder importierten Person allfällige Kontakt-Rolle aus der Kontakte-Gruppe im Dachverband (aber nicht deren Untergruppen) hart löschen
- [ ] Tests für Importer schreiben
- [ ] Nach Merge: Import auf Integrationsumgebung ausführen und Stefan benachrichtigen

**Comment by daniel-illi** [comment]
Der Import auf Integration ist abgeschlossen.
Das Fehlerprotokoll liegt hier: https://files.puzzle.ch/f/6025555
