### ISSUE TITLE
ROLES: Austritt Mitgliedschaft fix per Bis-Datum

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#200]
Aktuell kann die Mitgliedschaft auf dem 'Mitgliedschaften' Tab per einem beliebigen Datum gekündigt werden:

![image](https://github.com/hitobito/hitobito_sac_cas/assets/655627/d9ae789e-9c8e-41bc-b774-455605913f9e)

Neu ist ein Austritt beim SAC nur immer per dem Bis-Datum der Mitglied-Rolle möglich. Sprich es braucht kein Datums-Feld im Austritt-Dialog. 

Das Bis-Datum ist ein Pflichtfeld für Mitglied Rolle und darum können wir dieses für diesen Use Case auch verwenden.

Anstatt einem Input Feld wird das Kündigungsdatum fix angezeigt:

**Austritt per 31.12.2024**

# Tech-Spec

- https://github.com/hitobito/hitobito/blob/master/app/models/role.rb#L54
- https://github.com/hitobito/hitobito/blob/master/app/controllers/roles/terminations_controller.rb

Alle Anpassungen im Core

Generischer Ansatz: falls kein Bis-Datum auf der Rolle gesetzt ist, wird ein Input-Feld angezeigt. Sonst wird das Bis-Datum read-only verwendet

# ToDo

- [ ] Anpassungen Austrittsdatum per Bis-Datum der Rolle falls Bis-Datum gesetzt
- [ ] Dialog sauber formatieren (fixing Auflisten Gruppen, label/input field)
- [ ] mit angemessener Rolle durchklicken

**Comment by sykesonrocks** [comment]
@mtnstar Nachfolgend meine Testergebnisse.

----------------------------------------------------------------------------

Ich kann bestätigen, dass kein Austrittsdatum mehr eingegeben werden muss.

----------------------------------------------------------------------------

Der Austrittsmechanismus bei Familien muss angepasst werden:
- Ein SAC Austritt der gesamten Familie kann nur das Familienoberhaupt auslösen. Dies funktioniert grundsätzlich, jedoch kann ein nicht-Familienoberhaupt (Frei Kind, Frei Fam) ein Austritt der gesamten Familie vornehmen.
- Ein nicht-Familienoberhaupt kann ein Austritt beantragen, der Austritt erfolgt aber nur für diese Person. Wenn die Familienkonstellation nach dem Austritt dieser Person nicht mehr gültig sein sollte, dann muss gefragt werden, ob für die übrigen Familienmitglieder der entsprechende Wechsel der Beitragskategorie vorgenommen werden darf. Wenn z.B. die Familie nach dem Austritt nur noch aus einer Person besteht, dann muss gefragt werden, ob diese übrige Person zu Einzel resp. zu Jugend gewechselt werden darf. Wenn man dem nicht zustimmt, bricht der Prozess ab und ein Austritt ist nicht möglich.

----------------------------------------------------------------------------

Ist es möglich den Titel umzubenennen?
--> Für Austritt aus Stammsektion: "SAC Austritt" 
--> Für Austritt aus Zusatzsektion: "Austritt aus Zusatzsektion" oder "Austritt aus <sektionsname>"

----------------------------------------------------------------------------

Ist es möglich diesen Text anzupassen: _Bist du sicher, dass du aus dieser Gruppe austreten möchtest?_
--> Für Austritt aus Stammsektion: "Bist du sicher, dass Du aus dem SAC austreten möchtest?"
--> Für Austritt aus Zusatzsektion: "Bist du sicher, dass Du aus der Zusatzsektion austreten möchtest?"
Diese Texte habe ich verfasst und müsste diese mit Marketing kurz abstimmen. Zudem bin ich mir nicht sicher, ob man die Rollen auflisten soll. Wenn ich dem SAC austreten möchte, interessiert mich nicht, in welchen Sektionen ich derzeit registriert bin resp. es kann aus meiner Sicht zu Verwirrungen führen, da das Popup-Fenster nicht klar ausweist, dass es sich um ein SAC Austritt handelt:
![image](https://github.com/hitobito/hitobito_sac_cas/assets/132900428/bdcbf3c0-abf4-4707-8721-8d759a5a8b99)

----------------------------------------------------------------------------

Folgende Elemente fehlen:
- Frage betreffend Datenlöschung/Datenaufbewahrung (Datenschutz).
- Frage betreffend Austrittsgrund.

----------------------------------------------------------------------------

Mir ist nicht klar, wie ich eine Personenliste ziehen kann von Mitgliedern, die einen geplanten Austritt ausweisen. Dieser Filter gibt keine Resultate zurück:
![image](https://github.com/hitobito/hitobito_sac_cas/assets/132900428/9582c09e-ed43-4362-9ee8-4c678dcdf109)

----------------------------------------------------------------------------

Ist mein Verständnis korrekt, dass unsere Mitgliederverwalter Sofortaustritte vornehmen können? Dies geschieht nicht über den Austritts-Wizard, sondern direkt auf dem Userprofil, indem man die entsprechende(n) Rolle(n) löscht oder das bis-Datum setzt - korrekt? Wenn ich das bis-Datum setze, wird es jedoch nicht als Austritt ausgewiesen:
![image](https://github.com/hitobito/hitobito_sac_cas/assets/132900428/2c3df7e6-9e2f-4ecf-afd8-a3d4cf5b3643)
vs. Austritt via Wizard:
![image](https://github.com/hitobito/hitobito_sac_cas/assets/132900428/4a65900e-5710-42eb-b927-da66dcd99f12)
Mir ist aufgefallen, dass man das bis-Datum setzen kann und danach den Austritt vornehmen kann, dann wird der Austritt korrekt ausgegeben:
![image](https://github.com/hitobito/hitobito_sac_cas/assets/132900428/ed31f43f-a2fe-4cdc-86ce-de9f500b0530)
Müssen unsere Mitgliederverwalter demnach in zwei Schritten vorgehen um ein Sofortaustritt vorzunehmen?
