### ISSUE TITLE
GROUPS: Sektion ID auf Sektion, ID Ortsgruppe

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#211]
**Label vom `groups#id` Feld auf der Gruppen Seite wird nach Absprache mit @sykesonrocks von Sektions ID auf `Gruppen-ID` umbenannt.**

Fremdsysteme benötigen pro Sektion eine eindeutige ID. In Navision gab es bereits so eine ID. Legacy-Umsysteme sollen weiterhin diese ID zur Verfügung haben. Parallel dazu soll aber eine neue Sektions-ID eingeführt werden.

- Begriff Sektions-ID kann auch bei Ortsgruppen verwendet werden
- Sicherstellen das beide IDs auch im JSON:API ausgegeben werden (read-only)

## Legacy ID

- Attribute Navision ID ist bereits auf Group vorhanden und wird vom Importer gesetzt/verwendet
- Dieses Feld auf group#show als Attribut anzeigen falls Sektion oder Ortsgruppe
- Label: NAV Sektions-ID
- Wird nur angezeigt falls ein Wert vorhanden
- Attribut kann weder über group#edit/new noch über das JSON:API geändert/gesetzt werden (read-only)

NAV Sektions-ID: 4242

Label vom `groups#id` Feld auf der Gruppen Seite wird nach Absprache mit @sykesonrocks von Sektions ID auf `Gruppen ID` umbenannt.

## Neue ID

- Ist einfach ein Alias auf group#id
- Label: Sektions-ID
- Wird vor Alte Sektions-ID auf group#show angezeigt

# Tech-Spec

- https://github.com/hitobito/hitobito_sac_cas/blob/master/db/migrate/20230821120000_add_legacy_fields.rb#L11
- https://github.com/hitobito/hitobito_sac_cas/tree/master/app/views/sac_cas/groups

# ToDo

- [ ] IDs auf group#show anzeigen
- [ ] IDs als attribute (read-only) in /api/groups/42
- [ ] Mit angemessener Rolle durchklicken

**Comment by sykesonrocks** [comment]
Für die Steckbriefe unserer Sektionen unter https://www.sac-cas.ch/de/der-sac/sektionen/ dient zukünftig Hitobito als Datenquelle. Im Steckbrief werden folgende Informationen ausgegeben:
- **Kurzbeschrieb (in Fettschrift)**
- **Beschreibung**
- Foto(s)
- **Angebot (hat JO, hat Kinderbergsteigen, hat Seniorengruppe, hat Rettungskolonne usw.)**
- Grösse der Sektion (Anzahl Mitglieder)
- Webseite
- Webseite JO
- **Preise (für Einzel-, Familien- oder Jugendmitgliedschaft inkl. einmalige Eintrittsgebühr)**
- **RSS Feed Link für DropTours Anbindung**

Die Punkte in Fettschrift können in Hitobito noch nicht erfasst werden.

Wir werden die Punkte im morgigen Weekly mit Marek im Detail besprechen und den MVP Scope gemeinsam festlegen.

**Comment by amaierhofer** [comment]
Label vom `groups#id` Feld auf der Gruppen Seite wird nach Absprache mit @sykesonrocks von Sektions ID auf `Gruppen ID` umbenannt.
