### ISSUE TITLE
PEOPLE: Mitglieder-Jahre und Mitglieder-Nr nur für Mitglieder anzeigen

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#224]
Aktuell werden auf Person#show die Mitglied-Nr als auch die Mitglieder-Jahr angezeigt, egal ob eine Person ein Mitglied ist oder war.

Neu sollen diese Informationen nur angezeigt werden falls die Person min. eine aktive, inaktive oder künftige Mitglied-Rolle besitzt

![image](https://github.com/hitobito/hitobito_sac_cas/assets/655627/623f2582-fb2b-43e0-962d-d1b55ed7969b)

Attribut Mitglieder-Jahre auch im JSON:API /api/people/42 entsprechend excluded werden falls dies einfach möglich ist. oder halt eben einfach nil zurück geben.

# Tech-Spec
- Mitglieder Rollen https://github.com/hitobito/hitobito_sac_cas/tree/master/doc#rollen-1
- https://github.com/hitobito/hitobito_sac_cas/blob/master/app/views/people/_details_sac_cas.html.haml#L7

# ToDo

- [ ] Ausblenden Mitglieder-Attrs für nicht Mitglieder (inkl. Spec)
- [ ] Reihenfolge auf person#show ändern: Erst Mitglied-Nr, dann Mitglieder-Jahre
- [ ] Excluden Attribute JSON:API person
- [ ] clicky click manuell
