### ISSUE TITLE
PEOPLE: Job für automatische Zuteilung neuer Mitglieder

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito_sac_cas#232]
Personen welche in einer Neuanmeldungen-Gruppe landen (Achtung: nicht zu verwechseln mit "Neuanmeldungen zur Freigabe") sollen, wenn gewisse Bedingungen erfüllt sind, automatisch eine Mitgliedschafts-Rolle erhalten. Dabei kann es sich um Hauptsektions- oder Zusatzsektions-Mitgliedschaft handeln.

## Tech spec
- Umsetzung im SAC Wagon
- Fehler-Handling probieren wir mal mit dem [Hitobito Log](https://github.com/hitobito/hitobito/blob/master/app/utils/hitobito_logger.rb), mit Option dass man später auf der Person mal noch die Hitobito-Log-Einträge dieser Person anzeigen oder verlinken kann. Das Hitobito Log wurde mal programmiert als globales Log wo Admin-User selber reinschauen können, z.B. bei EBICS-Problemen etc., aber wir haben es schlussendlich noch nie verwendet. Die Idee ist, dass wir nicht unser Sentry mit Fehlern zuspammen, sondern die Fehler und deren Behebung wo möglich den Usern überlassen.

## TODO
- [x] Neuer Delayed Job, läuft alle 15 Minuten
- [x] Job iteriert über alle `Group::SektionsNeuanmeldungenNv::Neuanmeldung` und `Group::SektionsNeuanmeldungenNv::NeuanmeldungZusatzsektion` 
- [x] Für jede Rolle werden folgende Bedingungen überprüft:
  - [x] Die Person muss eine verifizierte Haupt-Mailadresse haben (Noch in Abklärung, allenfalls zukünftiges Ticket: was ist mit Familienmitgliedern die keine oder nur zusätzliche Mailadressen haben?)
  - [x] Es darf kein Duplikat für die Person existieren
  - [x] Die Person existiert seit mindestens 30 Minuten (damit die initiale Duplikatserkennung Zeit hatte zu laufen)
  - [x] [In Zukunft, in separatem Ticket] die Person hat eine bezahlte Rechnung im ERP
- [x] Falls eine der Bedingungen nicht erfüllt ist, wird die Rolle geskippt (und beim nächsten Lauf wieder neu versucht)
- [x] Falls alle Bedingungen erfüllt sind, versucht der Job (in einer Transaktion) die Rolle zu löschen und dafür in der Mitglieder-Gruppe der Sektion oder Ortsgruppe eine Mitgliedschaftsrolle zu erstellen
  - [x] Neue Mitgliedschaftsrolle soll natürlich Hauptsektion oder Zusatzsektion entsprechend der Neuanmeldung sein
  - [x] Created_at auf sofort setzen, delete_on auf Ende des aktuellen Jahrs
- [x] Falls beim Erstellen der neuen Rolle ein Fehler auftritt (z.B. weil die neue Rolle einen Validierungsfehler aufweist, oder weil keine Mitglieder-Gruppe in der Sektion gefunden werden kann), dann wird das ins [Hitobito Log](https://github.com/hitobito/hitobito/blob/master/app/utils/hitobito_logger.rb) geschrieben, mit polymorphischer Relation zur betroffenen Person

**Comment by daniel-illi** [comment]
@carlobeltrame sollten wir da Familienmitglieder zusammen behandeln? 
Und sollte das `created_at` nicht auf das Datum gesetzt werden, das der user als Startdatum der Mitgliedschaft gesetzt hat? Sonst wird doch bei seinen Mitgliederjahren unter Umständen weniger berechnet als er bezahlt hat.

**Comment by mtnstar** [comment]
@sykesonrocks 
unter Einstellungen > Hitobito Log gibt es neu eine Kategorie Neuanmeldung in der Fehler reported werden rund um die Neuanmeldung. z.B. Aktivieren Mitgliedschaft

![image](https://github.com/hitobito/hitobito_sac_cas/assets/655627/31d313b7-0a23-421d-9b12-56a6b7841cfd)
