### ISSUE TITLE
PEOPLE: Import Sektion Ehrenmitglieder, Begünstigte

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#243]
In den Gruppen Sektion > Mitglieder gibt es bereits die Rollen **Ehrenmitglieder** und **Begünstigte**. Der Sektion Mitglieder-Import soll angepasst werden das diese ebenfalls angelegt werden. Die beiden Rollen können nur assigned werden falls eine aktive Mitgliedschaft vorhanden ist. 

Im Mitglieder_aktive*.xlsx Export File sind die Spalten **Ehrenmitglied Sektion** sowie **Begünstigter Sektion** mit den Werten **Ja/Nein** vorhanden.

![image](https://github.com/hitobito/hitobito_sac_cas/assets/655627/d3aec8f4-e5fb-4838-aa3a-1ffb4db6e8c8)

### Rollen Ehrenmitglied, Begünstigte

- Beide Rollen können nur assigned werden falls die Person eine **aktive** Mitgliedschaft (Stammsektion oder Zusatzsektion) in der gleichen Sektion hat (Validation)
- Wird eine Mitglieder-Rolle (Stamm/Zusatz) gelöscht (soft-delete oder hard-delete), werden die Ehrenmitglied, Begünstigte Rollen ebenfalls gelöscht (auch soft oder hard), bei soft-delete gleiches deleted_at Datum wie Mitglieder-Rolle
- Bei Ehrenmitglied/Begünstigte muss kein Bis-Datum gesetzt sein
- Das Von-Datum der Rolle kann einfach auf heute gesetzt werden

# Tech-Spec

https://github.com/hitobito/hitobito_sac_cas/blob/master/app/domain/import/sektion/memberships_importer.rb

Tests nicht mit Excel-File schreiben, sondern mit Mocking, ähnlich wie https://github.com/hitobito/hitobito_sac_cas/blob/master/spec/domain/import/sektionen_importer_spec.rb

# ToDo

- [x] Validierungen Ehrenmitglied, Begünstigte implementieren
- [x] after_destroy hooks mitglieder vs. Ehrenmitglied, Begünstigte Rollen
- [x] Importer anpassen
- [ ] Import manuell laufen lassen (am besten DB dump aus Integration lokal einspielen da der Personen Import eine Weile dauert ...)
- [ ] Reviewer: Den Import dann auf der Integration laufen lassen nach Merge/Deployment

**Comment by mtnstar** [comment]
@sykesonrocks ich habe den Import für Begünstigt/Ehrenmitglieder auf der Integration laufen lassen. Es hat etwa die hälfte der erwarteten Mitglieder mit den entsprechenden zusätzlichen Rollen versehen. 
wir werden das mit #291 weiter debuggen und den Import verbessern
