### ISSUE TITLE
PEOPLE: Kinder erfassen

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#255]
Mit hitobito/hitobito#136 haben wir eine erste neue Version für das Erfassen von Kindern erstellt.

Leider gibt es bei den Validierungen für den SAC so zu viele Möglichkeiten das etwas schief läuft. Ausserdem ist das Erfassen von Kindern im Personen-Form etwas umständlich. Technisch gesehen eigentlich auch nicht so sauber mit den Nested Attributes. 

## Youth Wagon

**Kinder / Verwalter*innen neu auf person#show**

![image](https://github.com/hitobito/hitobito_sac_cas/assets/655627/71a97e32-7c92-410a-9844-9dae9d6e1852)

- Kinder werden nicht mehr via Person#edit form hinzugefügt oder gelöscht, dies wird komplett aus dem PeopleController sowie form entfernt
- Seperate Buttons für das hinzufügen von Kindern/Verwalter*innen

**Kinder / Verwalter*innen Auflisten auf person#show**

![image](https://github.com/hitobito/hitobito_sac_cas/assets/655627/752130ea-50d0-4804-a9f5-b0c52e5a9cdf)

- Kinder ODER Verwalter*innen werden aufgelistet als Links falls man mind. Lese-Rechte auf die Personen hat
- Da man nur entweder Kinder ODER Verwalter*innen haben kann, den <section> Titel entsprechend anpassen falls Einträge vorhanden sind (Kinder oder Verwalter*innen)
- nur noch EIN Hinzufügen Button anzeigen falls Einträge vorhanden
- Hinzufügen Buttons werden nur angezeigt falls man aufgrund der Berechtigung oder dem Feature `self_service_managed_creation` überhaupt Personen hinzufügen kann

**Kinder hinzufügen**

- Beim Click auf den Button Kinder hinzufügen landet man auf einer neuen Seite mit einem Suchfeld in dem man eine Person suchen kann
- Ist das Feature `people.people_managers.self_service_managed_creation` aktiv, können neben dem Suchfeld auch Personen erfasst werden
- Form für Kinder mit: Vorname, Name, Geschlecht, Geburtsdatum (alle als Pflichtfelder)

**Verwalter*in hinzufügen**

- Beim Click auf den Button Verwalter*in hinzufügen landet man auf einer neuen Seite mit einem Suchfeld in dem man eine Person suchen kann

:bulb: Eleganter wäre natürlich wenn man das Hinzufügen einfach als Inline-Form auf person#show realisieren könnte. Falls es nicht wirklich aufwändiger ist, dann wäre das sicher wünschenswert.

## SAC/CAS Wagon

- Feature-Toggle Kind erfassen aktivieren `people.people_managers.self_service_managed_creation` 

#### person#form

![image](https://github.com/hitobito/hitobito_sac_cas/assets/655627/5141f919-680f-47b0-992c-d7f7d731890e)

- Core Feature Familienmitglieder wie beim PBS wagon entfernen/ausblenden 

#### SAC spezifische Validierungen:

- Personen unter 22 Jahren können keine Kinder hinzufügen
- Kinder müssen zwischen 6 und 17 Jahre alt sein

#### SAC Familie

- Kinder automatisch in Haushalt der Eltern (managers) hinzufügen
- Kinder werden allen weiteren Erwachsenen im Haushalt welche eine Rolle mit Beitragskategorie 'Familie'  haben assigned
- Kinder erhalten die gleichen aktiven Rollen mit Beitragskategorie 'Familie' wie die Erwachsenen im gleichen Haushalt
- Wird ein Kind entfernt, dieses aus dem Haushalt entfernen und alle Rollen mit Beitragskategorie 'Familie' soft-deleten, sämtliche Managers des Kinds entfernen

#### Manageds (Kinder)

- Neuer Controller People::ManagedsController
- GET /groups/1/people/42/manageds/new
- PUT /groups/1/people/42/manageds
- DELETE /groups/1/people/42/manageds/444
- Virtual Model: People::Managed

#### Managers (Verwalter*innen)

- Neuer Controller People::ManagersController
- GET /groups/1/people/42/managers/new
- PUT /groups/1/people/42/managers
- DELETE /groups/1/people/42/managers/444
- Virtual Model: People::Manager

#### SacCasFamily Domain class

Neue Klasse die sich um all die SAC spezifischen Anforderungen rund um Familien kümmert:
- Assignen von Rollen mit Beitragskategorie (Familie)
- Hinzufügen von Kindern in den gleichen Haushalt
- Denkbar ist auch das SacCasFamily einfach der Modul-Name ist und man dann spezifische Klassen darunter hat

## ToDo

- [ ] Ticket für die Umsetzung ggf. auftrennen (youth wagon ticket, sac ticket)
- [ ] Reverten von: https://github.com/hitobito/hitobito_youth/pull/42
- [ ] Studieren alter PR SAC Wagon: https://github.com/hitobito/hitobito_sac_cas/pull/219/files
- [ ] Im SAC Wagon Core-Feature Familienmitglieder ausblenden
- [ ] Anpassungen Youth Wagon: Bisherige Views anpassen, People::ManagedsController, People::ManagersController
- [ ] CHANGELOG entry youth wagon
- [ ] manuelles Testen mit änderungen youth wagon
- [ ] Anpassungen SAC Wagon: Core Feature Familienmitglieder
- [ ] Anpassungen SAC Wagon: SacCasFamily Validierungen/Features
- [ ] manuelles Testen
- [ ] CHANGELOG entry sac wagon

**Comment by mtnstar** [comment]
@amaierhofer könnte man das noch etwas stylen?

![image](https://github.com/hitobito/hitobito_sac_cas/assets/655627/7d3ba451-973b-4801-86c2-0cfd68a4717b)

und den Speichern button unter das Input Feld mit Hinweis?

![image](https://github.com/hitobito/hitobito_sac_cas/assets/655627/a0cfe544-2ec2-4dd0-8be2-6f1c0c6d5661)

**Comment by mtnstar** [comment]
@amaierhofer ggf. kannst du diese Dinge auch gleich fixen wenn du #287 und #285 reviewst und mergst

**Comment by daniel-illi** [comment]
Es gibt noch einen Bug beim Entfernen von Kindern: hitobito/hitobito#2501
Abgesehen davon sollte das feature komplett sein.

**Comment by sykesonrocks** [comment]
Ich verstehe dieses Umsetzungsticket nicht.

Einzel-Mitglied https://sac-cas.puzzle.ch/de/groups/946/people/365870 kann Kinder hinzufügen:
![image](https://github.com/hitobito/hitobito_sac_cas/assets/132900428/74a9b83a-abb5-4e21-9617-6a783b81131e)

Jugend-Mitglied https://sac-cas.puzzle.ch/de/groups/946/people/468881 kann keine Kinder hinzufügen:
![image](https://github.com/hitobito/hitobito_sac_cas/assets/132900428/27c5f440-764e-4bf2-8b0c-592353e303dc)

Familienmitglied https://sac-cas.puzzle.ch/de/groups/946/people/143170 kann Kinder hinzufügen:
![image](https://github.com/hitobito/hitobito_sac_cas/assets/132900428/79e6c757-ef7f-4aa0-a5bb-01d86d8194e0)

Ich winke dieses Ticket durch, wir brauchen aber wie in https://saccas.atlassian.net/browse/HIT-279 beschrieben ein Gesamtkonzept. Bitte ein Lead definieren, sodass wir die Anforderungserhebung, Refinement etc. vornehmen können.

**Comment by ThomasEllenberger** [comment]
Merci fürs Testen und Festhalten der Fragen. Sehe auch dass wir das in einem Folgeticket umsetzen.
Den Lead hier würde wohl ich übernehmen. Refinement können wir gerne einmal an einem CO-Working day angehen.
