### ISSUE TITLE
EXPORT: Spezifischer Mitglieder-Adressen-Export für Sektionen

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito_sac_cas#271]
Für diverse sektionsspezifische Tools, Anbindungen und Zwecke soll der Adressen-CSV-Export von Navision in hitobito 1:1 nachgebaut werden.
Die Daten müssen später (in #272) für maximale Kompatibilität regelmässig (täglich oder 2stündlich) automatisch exportiert und auf einen SFTP-Server hochgeladen werden. In diesem Ticket geht es aber erst mal nur um den eigentlichen CSV-Export.

## Tech Spec
- Umsetzung im SAC Wagon
- Der Export betrifft alle Mitglieder einer Sektion, darum soll er auf der Ebene Sektion / Ortsgruppe verfügbar sein (anders als auf Confluence behauptet).
- Es sollen immer alle Mitglieder (MitgliedHauptsektion und MitgliedZusatzsektion) der aktuellen Ebene und ihrer Untergruppen (aber nicht Unter-Ebenen) exportiert werden, unabhängig davon welche Filter im UI gesetzt sind.
- Export wird Async / im Hintergrund erstellt, aufgrund der potenziell grossen Datenmengen
- Encoding für das CSV ist ISO-8859-1 (Western Europe)
- Spalten haben keine Headers, erste Zeile enthält bereits Daten
- Spaltenseparator ist ein Dollar-Zeichen
- Als Anführungszeichen nur wenn unbedingt nötig (bei mehrzeiligen Feldwerten) ein `"` verwenden
- Nach der letzten Zeile kommt eine letzte Zeile mit folgendem Inhalt: `* * * Dateiende * * *  / 00005300 / Anzahl Datensätze: 12011 / 30.11.2023 / 03:20`
  - `00005300` ist die navision_id der exportierten Sektion / Ortsgruppe, mit Nullen auf 8 Stellen gepaddet
  - `30.11.2023 / 03:20` ist aktuelles Datum und Zeit beim Exportieren
- Dateiname: Adressen_00005300.csv wobei 00005300 wieder die zero-paddete Navision ID der exportierten Sektion oder Ortsgruppe ist

Spalten:
- **Personen-ID** als Zahl
- **Navision ID des exportierten Layers** als Zahl, ohne Zero-Padding
- **Vorname**
- **Nachname**
- **Adresszusatz** wird allenfalls in hitobito/hitobito#2226 hinzugefügt, bis dahin eine leere Spalte in den Export schreiben
- **Adresse**
- **Postfach** wird allenfalls in hitobito/hitobito#2226 hinzugefügt, bis dahin eine leere Spalte in den Export schreiben
- **Postleitzahl**
- **Ort**
- **Land** als zwei-Buchstaben-Kürzel, z.B. `DE`, `FR` etc.; wenn Schweiz dann leer
- **Geburtsdatum** im Format dd.mm.yyyy
- **Beliebige Telefonnummer mit Label "Direkt"**
- **Beliebige Telefonnummer mit Label "Privat"**
- **1 leere Spalte**
- **Beliebige Telefonnummer mit Label "Mobil"**
- **Beliebige Telefonnummer mit Label "Fax"**
- **Haupt-E-Mail**
- **Geschlecht** mögliche Werte: `Weiblich` / `Männlich` / `Andere`
- **1 leere Spalte**
- **Sprache** Korrespondenzsprache der Person. Mögliche Werte: `D` / `F` / `ITS` (Englisch als Korrespondenzsprache wird für den SAC noch in separatem Ticket deaktiviert)
- **Eintrittsjahr** (der allerersten Mitgliederrolle dieser Person, egal welche Sektion gerade exportiert wird)
- **Begünstigt** anhand Präsenz einer aktiven Rolle vom Typ Beguenstigt im exportierten Layer. Mögliche Werte: `Yes` / `No`
- **Ehrenmitglied** anhand Präsenz einer aktiven Rolle vom Typ Ehrenmitglied im exportierten Layer. Mögliche Werte: `Yes` / `No`
- **Beitragskategorie der Person in der exportierten Sektion / Ortsgruppe** Mögliche Werte: `EINZEL` / `FAMILIE` / ~`FREI FAM`~ / ~`FREI KIND`~ / `JUGEND`. ~Möglicherweise muss dafür der Beitragskategorie-Calculator noch erweitert werden, damit er für diese Spalte FREI KIND etc. berechnen kann (bisher berechnen wir nur EINZEL / JUGEND / FAMILIE)~, vorerst einfach die Kategorien die wir auf der Rolle verwenden
- **3 Spalten S-INFO 1-3** momentan noch leer lassen
- **Bemerkungen** (Zusätzliche Daten, Person#additional_information)
- **Saldo** aktuell noch leer lassen
- **1 leere Spalte**
- **Anzahl die Alpen** Immer den Wert 0 ausgeben. Der Versand von Die Alpen wird seit längerem nicht mehr über diesen Adress-Export abgehandelt, sondern via Empfängerliste, was in #427 implementiert wird.
- **Anzahl Sektionsbulletin** Immer den Wert 0 ausgeben. Der Versand von Sektionsbulletins sollte seit längerem nicht mehr über diesen Adress-Export abgehandelt werden, sondern via Empfängerliste, was in #427 implementiert wird.

Referenz:
- [Mitglieder: Export für Sektionen](https://saccas.atlassian.net/wiki/spaces/RDIE/pages/3987669044/Datenbed+rfnisse+Filter+Berichte+Exporte+und+API+Zugriffe)
- [Beispiel-Exports](https://saccas.atlassian.net/wiki/spaces/RDIE/pages/3883040775/Datenmigrationskonzept#Export%2FImport-Dateien)
- [Informationen zu den einzelnen Spalten](https://saccas.atlassian.net/wiki/spaces/RDIEK/pages/4028727365/N+chtlicher+Export+der+Mitgliederdaten)

## TODO
- [x] Domain-Klassen für neuen Tabular People Export anlegen
  - [x] Spalten gemäss Tech Spec
  - [ ] In Folge-Ticket festhalten, welche der Spalten noch nicht abschliessend exakt so umgesetzt werden konnten, zum weiter Challengen mit Stefan
  - [x] ~`entries` überschreiben um bei diesem Export jegliche Filter zu ignorieren (siehe [Beispiel](https://github.com/hitobito/hitobito_pbs/blob/master/app/jobs/pbs/export/event_participations_export_job.rb#L17..L28))~ anders implementiert: entries werden erst in der Tabular Klasse berechnet
  - [x] Encoding fürs CSV nur in diesem Export von UTF-8 auf ISO-8859-1 ändern (Konvertierung passiert aktuell im [CSV-Generator](https://github.com/hitobito/hitobito/blob/master/app/domain/export/csv/generator.rb#L46))
  - [x] Dateiname gemäss Tech Spec
- [x] Exporter-Klasse im Wagon ~in [PeopleExportJob](https://github.com/hitobito/hitobito/blob/master/app/jobs/export/people_export_job.rb#L44) für die Async Berechnung einfügen~ Separater Export Job implementiert
- [x] ~Exporter im Dropdown::PeopleExport einfügen, aber nur auf Sektionen und Ortsgruppen (siehe [Beispiel](https://github.com/hitobito/hitobito_youth/blob/master/app/helpers/youth/dropdown/people_export.rb#L19..L23) im Youth Wagon)~ stattdessen wurde auf dem Infotab der Sektion/Ortsgruppe ein Button "CSV Mitglieder" hinzugefügt
- [x] Tests für Exporter schreiben
- [ ] Changelog-Eintrag

**Comment by carlobeltrame** [comment]
Eine Alternative zu diesem Ticket wäre es, ein vom SAC programmiertes Tool im Cluster zu betreiben. Dies ist eine Option, weil dieser Export nur ad interim Legacy-Kompatibilität bietet, und langfristig nicht mehr benutzt werden sollte. Der SAC ist aktuell an Abklärungen, wie viele solche Kompatibilitäts-Exports nötig sind. Wenn das erst mal klar ist können wir Aufwandschätzungen für dieses Ticket und für das Betreiben von n Tools im Cluster machen.

**Comment by sykesonrocks** [comment]
Siehe erste Testergebnisse unter https://saccas.atlassian.net/browse/HIT-115.
