### ISSUE TITLE
GROUPS: Sektionsdaten für Typo3

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito_sac_cas#275]
Für die Typo3-Webseite des SAC müssen einige Felder in der Gruppen-API ergänzt werden.

## Tech Spec
- Umsetzung im SAC Wagon
- Die neuen Daten werden nur auf Sektionen und Ortsgruppen ausgegeben

Zu ergänzende Felder:
- **Anzahl Mitglieder** berechnen anhand der Anzahl aktiver MitgliedHauptsektion und MitgliedZusatzsektion Rollen in der Untergruppe Mitglieder
- **Direktaufnahme durch Geschäftsstelle** hat Wert `false` wenn in der Sektion oder Ortsgruppe eine Untergruppe vom Typ SektionsNeuanmeldungenSektion existiert, ansonsten `true`
- ~~**Austritte GS** neues boolean mounted_attribute~~
- **Hat Jugendorganisation** hat Wert `true` falls in der Sektion oder Ortsgruppe ein social_media Account mit Label "Homepage JO" existiert, ansonsten `false`
- **Selbstregistrierungslink** der NeuanmeldungenNv oder NeuanmeldungenSektion Gruppe innerhalb der Sektion oder Ortsgruppe, :sac_cas_self_registration_url. Berechnung siehe `Groups::SektionSelbregistrierungsLink` domain class

## TODO
- [ ] ~~Neues boolean mounted_attribute "Austritte GS" auf Sektion und Ortsgruppe erfassen, default `true`~~
- [x] Groups-Endpoint um die Felder gemäss Tech Spec erweitern
- [x] In Folge-Ticket festhalten, welche der Felder noch nicht abschliessend exakt so umgesetzt werden konnten, zum weiter Challengen mit Stefan
- [x] Tests schreiben
- [x] Kontrollieren dass die Felder in OpenAPI Doku vernünftig dokumentiert werden (z.B. als optionale Felder auf der Group Entität)
- [ ] Changelog-Eintrag

**Comment by carlobeltrame** [comment]
> Austritte GS ... für was braucht es das genau? hat das irgendwelche Auswirkungen auf das Austritt-Feature?

Diese Frage gebe ich gerne weiter an @sykesonrocks

**Comment by sykesonrocks** [comment]
Der Boolean "Austritt durch GS" steuert, ob die Geschäftsstelle ein Mitgliederaustritt im Namen der Sektion ausüben darf. Dieser Boolean dient rein informativ, sprich damit wird applikationstechnisch nichts gesteuert. Nehmen wir bitte aus dem Scope. Dito für den Boolean "Versand Rechnungen und Ausweise". 

Der Boolean "Mitgliederaufnahme durch GS" wird allerdings benötigt, habe aber verstanden, dass dies in HIT anders abgebildet wird - kann von den angezeigten Gruppen abgeleitet werden (wenn Gruppe "Neuanmeldungen (zur Freigabe)" vorhanden ist, dann gilt "Mitgliederaufnahme durch GS"=true).

**Comment by daniel-illi** [comment]
@sykesonrocks bei *Anzahl Mitglieder*, sollen auf der Sektion die Mitglieder der Ortsgruppen auch miteingerechnet werden?

**Comment by daniel-illi** [comment]
@sykesonrocks noch eine Frage zu der Mitgliederzahl, sollen da die Zusatzsetktion Mitgliedschaften auch gezählt werden?

**Comment by sykesonrocks** [comment]
Ich kann bestätigen, dass folgende Attribute in der Swagger UI (https://sac-cas.puzzle.ch/api-docs/index.html) im "groups" Endpoint integriert sind:
- Anzahl Mitglieder: _members_count_
- Direktaufnahme durch Geschäftsstelle: _membership_admission_through_gs_
- Austritte GS: _mitglied_termination_by_section_only_
- Hat Jugendorganisation: _has_youth_organization_
- Selbstregistrierungslink der Neuanmeldungen: _membership_self_registration_url_
