### ISSUE TITLE
PEOPLE: SAC/CAS Familien (Prio 02.24)

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#276]
SAC Familien sind in der Wagon Doc beschrieben: https://github.com/hitobito/hitobito_sac_cas/tree/master/doc#beitragskategorie

Die bereits implementierte Logik ist relativ stark verteilt und wir wünschen uns EINE Domain-Klasse die über dieses Familien-Konzept Bescheid weiss und entsprechend Rollen, Haushalte sowie Verwalter*innen/Kinder verwaltet.

see [`People::SacFamily`](https://github.com/hitobito/hitobito_sac_cas/blob/master/app/domain/people/sac_family.rb)

Definition Familien-Mitgliedschaft SAC Webseite
```
max. 2 Erwachsene und beliebig viele Kinder im Alter zwischen 6 und 17 Jahren.

Die Familienmitgliedschaft ist auch für Paare ohne Kinder möglich. Eine Person wird als Hauptkontakt definiert.
```

### Household / Elternzugang
- [x] Kinder hinzufügen #287, #255
- [x] Erwachsene hinzufügen #287
- [x] Personen entfernen #285
- [x] Aus Einzelmitglieder wird Familie #287
- [x] #393
- [x] #394
- [x] #412
- [x] #424 

### Selfregistration
- [x] Neuanmeldung komplette Familie siehe Epic #95 
- [x] #340

### Selfinscription

- [x] Sektions-Wechsel komplette Familie
- [x] Zusatzsektion beantragen für die ganze Familie
- [x] Zusatzsektion beantragen für ein einzelnes Mitglied der Familie (für sich selber)

### Role termination

- [x] Austritt Zusatzsektion für alle Familien-Mitglieder
- [x] Austritt Stammsektion für alle Familien-Mitglieder 
- [x] #330

### Neuanmeldungen Approven

- [ ] Komplette Familie approven
