### ISSUE TITLE
OIDC: navision_id der Gruppe in with_roles Claim einbauen

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito_sac_cas#280]
**ON HOLD** Zitat Stefan im Meeting mit Umsystemen am 14.3. "Ein neues Element einführen kommt nicht in Frage", als Antwort auf den Vorschlag von Marek, welcher ungefähr diesem Issue entspricht.

Das Hüttenportal des SAC wird via OIDC an hitobito angebunden. Um den eingeloggten Nutzenden die korrekten Berechtigungen zu vergeben, müssen sie anhand der ihnen bekannten alten Hütten-ID herausfinden können, in welchen Hütten die eingeloggte Person Rollen hat.

Neu soll die navision_id der Gruppe jeder Rolle in den with_roles Claim der OIDC Schnittstelle eingebaut werden.

## Tech Spec
- Umsetzung im SAC Wagon
- Der with_roles Claim im Userinfo Endpoint wird im Core im [`Oauth::ProfilesController`](https://github.com/hitobito/hitobito/blob/master/app/controllers/oauth/profiles_controller.rb#L46..L57) zusammengestellt. Es gibt vermutlich noch keinen Wagon, der das schon mal erweitert hat.
- Die neuen Daten sollen nur hinzugefügt werden, wenn ein neuer SAC-spezifischer Scope (z.B. `with_roles_with_navision_id`) im OIDC-Flow aktiv ist

## TODO
- [ ] Neuen OIDC Scope im SAC Wagon definieren. Im Core sind die Scopes hier definiert: https://github.com/hitobito/hitobito/blob/master/config/initializers/doorkeeper.rb#L96..L97
- [ ] Wenn der Scope aktiv ist, im Wagon navision_id zu jeder Rolle in public_attrs_with_roles hinzufügen
- [ ] Tests für Profil-Endpoint schreiben ([Beispiel im Core](https://github.com/hitobito/hitobito/blob/master/spec/requests/oauth_profile_spec.rb))
- [ ] Sicherstellen dass jede Hütte eine navision_id hat, auch Hütten die erst noch in Zukunft erfasst werden. Dazu entweder das Feld im Formular bearbeitbar machen und eine Validierung einfügen, oder einen dynamischen Wert aus der `id` der Gruppe berechnen, falls keine legacy Navision ID importiert ist.
- [ ] Stefan informieren, dass das Hüttenportal-Team loslegen kann

**Comment by amaierhofer** [comment]
Obsolete, da die `navision_id` als `id` auf der Gruppe geführt wird und somit bereits im `with_roles` scope enthalten ist.
