### ISSUE TITLE
PEOPLE: Selbstregistrierung unterjähriger Personen

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito_sac_cas#281]
Abhängig vom Alter der Person die sich registriert gibt es verschiedene Spezialfälle:
Personen unter 6 Jahren dürfen gar keinen Account haben. Dies ist bereits implementiert.
Personen unter 23 Jahren dürfen keine Familienmitglieder erfassen.

## Tech Spec
- Umsetzung im SAC Wagon
- Der Formular-Schritt zur Erfassung der Familienmitglieder soll im besten Fall komplett übersprungen werden, oder allenfalls auch nur die Option zum Hinzufügen von weiteren Personen verhindert werden.
- Edge Case: Eingabe von Alter über 23, Erfassung von Familienmitgliedern, Navigation zurück zur Hauptperson und Korrektur des Geburtsdatums, so dass die Haupt-Person unter 23 Jahren ist. Auch dies muss verhindert werden, z.B. indem die bereits erfassten Familienmitglieder herausgelöscht werden wenn das Alter auf unter 23 geändert wird. Auch in der Sidebar soll der aktuelle Stand jederzeit korrekt abgebildet werden.

## TODO
- [ ] Im Mehrschritt-Formular Logik einfügen, welche bei Hauptperson-Alter unter 23 Jahren (also zwischen 6 und 22 Jahren) das Erfassen von Familienmitgliedern verunmöglicht
- [ ] Bei Änderung des Geburtsdatums der Haupt-Person auf ein Alter unter 23 Jahre sollen bereits erfasste Familienmitglieder herausgelöscht werden
- [ ] Sicherstellen dass die Sidebar jederzeit aktuelle und korrekte Informationen darstellt
- [ ] Feature Specs schreiben

**Comment by sykesonrocks** [comment]
@mtnstar OK
