### ISSUE TITLE
PEOPLE: Selbstregistrierung zu viele Erwachsene in der Familie führt zu weissem Screen

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito_sac_cas#283]
## Aktuelles Verhalten
Wenn man als Haupt-Person eine Person über 23 Jahren einträgt, und dann zwei Familienmitglieder hinzufügt welche ebenfalls über 23 Jahre alt sind, dann kommt nach dem Abschicken des letzten Formularschritts ein weisser Screen.

## Erwartetes Verhalten
Es ist beim SAC nicht erlaubt, mehr als 2 Personen über 23 in der gleichen Familie zu haben. Das Erstellen einer solchen Konstellation soll benutzerfreundlich abgefangen werden, so dass es noch korrigiert werden kann.

## Tech Spec
Vermutlich gibt es bereits die Validierung über die ganze Familie, sie wird aber erst beim eigentlichen Speichern der ganzen Daten angekickt.
In #277 wurde eine Domain-Klasse eingeführt, welche in Zukunft alle Business-Logik mit Familien verkapseln soll. Falls möglich sollten wir diese verwenden, um die Gültigkeit des Haushalts vorzu zu überprüfen.

## TODO
- [ ] [`SelfRegistrationNeuanmeldung#household_valid?`](https://github.com/hitobito/hitobito_sac_cas/blob/master/app/models/self_registration_neuanmeldung.rb#L52) so erweitern dass nicht nur die individuellen Housemates sondern auch der Haushalt als ganzes validiert wird, z.B. mit der neuen Familien-Domain-Klasse von #277
- [ ] Sicherstellen, dass beim Abschicken des kompletten Formulars allfällige noch übersehene Validierungsfehler nie zu einem weissen Screen führen, sondern dem User auf irgendeine Art sauber angezeigt werden, inkl. Möglichkeit, diese zu beheben
- [ ] Feature Specs schreiben
