### ISSUE TITLE
PEOPLE: Feature Specs für Selbstregistrierung

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito_sac_cas#284]
Durch die vielen Anforderungen ging bisher immer wieder mal etwas an der Selbstregistrierung kaputt. Dies soll durch bessere Feature Specs in Zukunft verhindert werden.

## Tech Spec
- Umsetzung im SAC Wagon
- https://sentry.puzzle.ch/pitc/hitobito-backend/issues/66260/?environment=integration

## TODO
- [ ] Bestehende [feature specs](https://github.com/hitobito/hitobito_sac_cas/blob/master/spec/features/self_registration_spec.rb) erweitern durch mindestens folgende Cases:
  - [x] Familienmitglieder erfassen funktioniert
  - [x] Validierungen auf Haupt-Person (v.a. required Felder, Geburtsdatum Validierungen und doppelte E-Mail) funktionieren
  - [x] Validierungen auf Familie (v.a. Familienkonstellation, required Felder, Geburtsdatum Validierungen und doppelte E-Mail) funktionieren
  - [x] Checkboxen im letzten Schritt verhindern das Absenden des Formulars
  - [x] Mehrmals und mehrere Schritte nacheinander vorwärts und rückwärts navigieren im Formular
  - [x] ~Mit den nummerierten Schritt-Links oben navigieren im Formular~ Die Links wurden zu einfachen Labels geändert, navigiert wird nur noch mit den Buttons
  - [x] Sidebar Inhalte stimmen auf allen Schritten, mit und ohne Familienmitglieder, und auch beim Zurück- und Vorwärtsnavigieren

**Comment by mtnstar** [comment]
Beim Erfassen einer Familie im Selbstregistrierungsformular wird ein Kind zwar im Haushalt mit erfasst, jedoch nicht als Kind (people managers)

1. Selbstregistrierungsformular einer Sektion aufrufen
2. Haupt-E-Mail definieren
3. Erwachsene Person erfassen
4. Ein Kind erfassen auf Schritt 3
5. Registrierung abschliessen auf Schritt 4

Kind ist war im Haushalt, jedoch nicht als Kind bei der Erwachsenen Person erfasst.

Die Specs failen irgendwie auch noch, aber das hat vermutlich gar nichts mit diesem Change zu tun? ich habe leider gerade die Übersicht nicht. 

Core PR habe ich bereits gemerged (master und sac-master) da keine Changes die andere Kunden als der SAC betreffen.
