### ISSUE TITLE
PEOPLE: Person aus Familie entfernen

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#285]
Teil des Epics #276 

## Erwachsene Person

- Eine Erwachsene Person als aktives Sac-Family Mitglied soll aus einem Haushalt entfernt werden können (dies funktioniert zurzeit nicht, Haushalt wird nicht entfernt beim person#update)
- Die aktiven Rollen werden bei diesem Vorgang nicht verändert oder gelöscht. Auch wenn die Person in einem Nicht-Haushalt lebt, hat sie bis zur nächsten Faktura einfach die Rollen mit Beitragskategorie Familie
- Allfällige Kinder werden von der erwachsenen Person entfernt

Bei der entfernten Person:

- wird keine Familien-Nr mehr angezeigt
- Person#sac_family.member? gibt false zurück
- Person#sac_family.family_members ist leer []

## Kind entfernen

Siehe auch #255

- Kinder können via people_manager (Elternzugang Youth Wagon) oder via Haushalts-Feature (Core) entfernt werden
- Wird das Kind aus dem Haushalt entfernt, wir das Kind (managed) bei allen Verwaltern entfernt
- Wird das Kind bei einem Elternteil (Verwalter) entfernt, wird es bei allen Verwaltern im selben Haushalt sowie aus dem Haushalt selbst entfernt
- Die aktiven Rollen werden bei diesem Vorgang nicht verändert oder gelöscht. Auch wenn das Kind in einem Nicht-Haushalt lebt, hat es bis zur nächsten Faktura einfach die Rollen mit Beitragskategorie Familie

Bei der entfernten Person:

- Es wird keine Familien-Nr mehr angezeigt
- Person#sac_family.member? gibt false zurück
- Person#sac_family.family_members ist leer []

# Tech-Spec

- https://github.com/hitobito/hitobito_sac_cas/blob/master/app/domain/sac_cas/people/sac_family.rb
- https://github.com/hitobito/hitobito_sac_cas/blob/master/spec/domain/sac_cas/people/sac_family_spec.rb

# ToDo

- [x] Fix sodass Familien Personen wieder aus dem Haushalt entfernt werden können
- [x] Erwachsene entfernen implementieren (TDD)
- [x] Kinder entfernen implementieren (TDD)
- [x] Mit angemessener Rolle "durchklicken"
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by mtnstar** [comment]
@daniel-illi kannst du dieses Feature dann auch nochmals testen und wenn i.o. auf der Integrationsumgebung an Stefan assignen?
