### ISSUE TITLE
PEOPLE: Person in Familie hinzufügen

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#287]
Teil des Epics #276

Erwachsene oder Kinder können einer SAC Familie hinzugefügt werden.

Um eine Person hinzuzufügen wird diese entweder als **Wohnt im Haushalt mit** (household feature core) oder für Kinder über **Kind hinzufügen** bei einer erwachsenen Person erfasst. (people manager feature youth wagon)

## Erwachsene Person hinzufügen

- [x] Eine erwachsene Person (mind. 22 Jahre oder älter), kann einer Familie hinzugefügt werden falls bereits 1 und nur 1 erwachsene Person mit einer aktiven Mitglieder Rolle Stammsektion (Familie) vorhanden ist
- [x] Kann die erwachsene Person hinzugefügt werden, erhält sie die aktiven Stammsektion Rollen (Familie) der vorhandenen Person sowie alle Zusatzmitgliedschaften mit Beitragskategorie Familie (start datum der Rollen = Heute, Enddatum gleich wie bei den anderen Rollen der Familienmitglieder, role#terminated attribut auch berücksichtigen)
- [x] Sind bereits zwei Erwachsene in der Familie vorhanden, wird die Person einfach dem Haushalt hinzugefügt, erhält aber keine Rollen und ist damit nicht Familienmitglied
- [x] Sind Personen aber keine Sac Familie bereits im Haushalt vorhanden, wird die Person einfach dem Haushalt hinzugefügt sowie für alle Erwachsenen-Kind Paare die PeopleManager erstellt. Es werden keine Mitgliedschaftsrollen erstellt.
- [x] Hat die hinzuzufügende Person bereits eine aktive Stammsektionsrolle bzw. noch weitere Zusatzsektionsrollen, wird die Person einfach dem Haushalt hinzugefügt und es passiert nichts weiter. Die aktiven Rollen müssen erst manuell beendet werden damit die Person dann der Familie beitreten kann.
- [x] Hat die hinzuzufügende Person bereits eine aktive Familienmitgliedschaft, kann sie weder der Familie noch dem Haushalt hinzugefügt werden
- [x] Hat die Person kein Geburtsdatum, wird die Person nur dem Haushalt hinzugefügt und es passiert nichts weiter
- [x] Vorhandene Kinder werden der Person ebenfalls als Kinder assigned
- [x] Personen von 0-5 werden dem Haushalt hinzugefügt und PeopleManager erstellt. Es werden keine Mitgliedschaftsrollen erstellt.
- [x] Personen von 18-21 werden einfach dem Haushalt hinzugefügt und es passiert nichts weiter

## Kind hinzufügen

- [x] Ein Kind wird immer als Kinder der erwachsenen Personen der Familie sowie als Wohnt im Haushalt mit erfasst
- [x] Ein Kind kann über 'Kind hinzufügen' (siehe #255) oder via 'Wohnt im Haushalt mit' analog wie das bei der erwachsenen Person gemacht wird hinzugefügt werden
- [x] Ein Kind muss zwischen 6-17 Jahre alt sein
- [x] Ein Kind kann nur einer Person die 22 Jahre oder älter ist assigned werden
- [x] Hat ein Kind bereits eine aktive Mitgliedrolle (Stamm oder Zusatz), wird das Kind einfach dem Haushalt hinzugefügt sowie für alle Erwachsenen-Kind Paare die PeopleManager erstellt. Es werden keine Mitgliedschaftsrollen erstellt.

# Tech-Spec

- https://github.com/hitobito/hitobito_sac_cas/blob/master/app/domain/sac_cas/people/sac_family.rb
- https://github.com/hitobito/hitobito_sac_cas/blob/master/spec/domain/sac_cas/people/sac_family_spec.rb
- Bei Änderungen der Haushalt-ID auf der Person oder PeopleManager Entry, person.sac_family.update! triggern welches dann #update_children und #update_adults triggert. Mit dieser Methode soll die Integrität der Sac Familie sichergestellt werden. Denkbar ist das #update! dann auch via einen CronJob getriggert wird
- family seeding fixen: https://github.com/hitobito/hitobito_sac_cas/pull/266 (PR als inspiration, dann schliessen und branch löschen)

# ToDo

- [x] sac_family#update! erweitern damit Personen richtig hinzugefügt werden (TDD)
- [x] Household change callback implementieren
- [x] ~people manager change callback implementieren~ in `PeopleManagersController` aufrufen (depends on hitobito/hitobito_youth#44)
- [x] family seeding fixen (sicherstellen das familien richtig geseedet werden ala sac familie)
- [x] Mit angemessener Rolle "durchklicken"
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by mtnstar** [comment]
> Dinge die falsch sind:
> 
>     * Wenn man versucht, eine Person, die bereits eine Familie hat, zu einem anderen Haushalt hinzuzufügen, dann kommt korrekt die folgende Validierungsmeldung:
cut ...
> 
> 
> Dinge die mir unklar sind:
> 
>     * Wenn ich ein Kind einer Familie hinzufüge, welches keine Mitgliederrollen hat, dann bekommt es aktuell auch keine Mitgliederrolle. Ist das wirklich korrekt? Wenn ja, warum war dann folgender Punkt in den Anforderungen nötig?
>       > Hat ein Kind bereits eine aktive Mitgliedrolle [...] werden keine Mitgliedschaftsrollen erstellt.
-> wird ein Kind hinzugefügt, und hat mind. 1 Erwachsene Person bereits die Beitragskategorie Familie, so erhält das Kind ebenfalls die gleichen Stammsektion/Zusatzsektion Rollen mit Beitragskategorie Familie. Kinder müssen zwischen 6-17 Jahre alt sein. 
> 
>     * Warum wurde eine neue Methode `Person::Household#leave` im Core eingeführt, statt die bisherige Methode `Person::Household#remove` zu verwenden? Warum sind die private/public Changes im Core nötig oder sinnvoll?
> 
>     * Hat eine erwachsene Person keine Rolle, dann finde ich sie gar nicht im Haushalts-Suchfeld, weil man Schreibrechte auf beide Personen braucht, um sie zu verknüpfen. Was ist genau der Workflow, in welchem Fall fügt man eine Person die nur Nicht-Mitglieder-Rollen hat zu einer Familie hinzu?
> 
>     * Wenn man eine Familie hat, und ein Kind unter 18 Jahren welches noch keine Mitgliedschaftsrolle hat in diese Familie einfügt, dann bekommt das Kind eine Mitgliedschaftsrolle mit Beitragskategorie "Familie". Ich dachte eigentlich, Personen unter 18 Jahren können gar nie die Beitragskategorie "Familie" haben, sondern nur "Jugend". Liege ich falsch?
-> Doch, das ist korrekt so. Definition Familie SAC: Für Familien mit max. 2 Erwachsenen ab 22 Jahren sowie beliebig viele Kinder von 6 bis 17 Jahren die im selben Haushalt wohnen.
> 
> 
> Kleinere visuelle Bugs:
> 
>     * Fehlermeldung beim Hinzufügen eines Kindes welches bereits in einem Haushalt ist müsste besser anders herum formuliert sein. Aktuell:
>       ![image](https://private-user-images.githubusercontent.com/7566995/314474935-d7eab7b0-b0b6-48f8-8c74-50e7ea2f0c05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5NTE5NzQsIm5iZiI6MTcxMDk1MTY3NCwicGF0aCI6Ii83NTY2OTk1LzMxNDQ3NDkzNS1kN2VhYjdiMC1iMGI2LTQ4ZjgtOGM3NC01MGU3ZWEyZjBjMDUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjBUMTYyMTE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Zjc2MjQ2ZWM4YWVkMDJkN2ZhYTI1MzM1MGQ4MmFiZDI4NzFjNjEwYWIwNGEzMjE5ZDY2MDkwYWFmMTQyODQ2OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.m-1Ts8Es2Pq8GbZQZ9YXozyTtIUyKR7-Pg-z4g_M8Ng)
>       Besser wäre: "Sohn AAA gehört bereits zu einem anderen Haushalt und kann daher nicht als Kind hinzugefügt werden."
> 
>     * Wird eine Kinder-Beziehung auf der Personen-Seite gelöscht, dann wird das via Turbo aktualisiert, inkl. Animation. Aber beim SAC wird jetzt im Hintergrund auch die Haushaltsbeziehung aufgelöst, und dies wird erst nach einem Refresh sichtbar.
> 
>     * Gleiches gilt auch beim Hinzufügen eines Kindes, wo der neu erstellte oder aktualisierte Haushalt erst nach einem Refresh sichtbar wird

**Comment by daniel-illi** [comment]
Das Feature ist gemergt, zum offenen Punkt habe ich ein Ticket erstellt: #424
