### ISSUE TITLE
PEOPLE: Selbstregistrierungsformular Promocode + Newsletter

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito_sac_cas#288]
Der Promocode wurde inzwischen aus dem MVP-Scope genommen.
Beim Newsletter wissen wir inzwischen genauer, wie dieser umgesetzt werden soll.
Diese beiden Optionen sollen daher im Selbstregistrierungsformular angepasst werden.

# Tech-Spec

- Umsetzung im SAC Wagon
- Promocode-Input wird im Moment ganz entfernt
- Newsletter-Checkbox soll kein Tag mehr schreiben. Stattdessen gibt es auf dem Nationalverband ein Abo (welches genau soll auf dem Nationalverband einstellbar sein). Das Abo hat den Modus Opt-Out (damit alle bisher abonnierten Personen den Newsletter weiterhin bekommen). Wird die Newsletter Checkbox aktiviert passiert nichts besonderes. Wird sie nicht aktiviert, dann wird für die registrierte Person ein Opt-Out erfasst (PersonSubscription mit `exclude: true`)

# ToDo

- [ ] Auf Nationalverband (top_layer) im SAC Wagon ein mounted_attribute namens `sac_newsletter_mailing_list_id` anlegen, welche im Formular als simples Number angezeigt wird (User geben die ID manuell dort ein), optional validierung das nur auf dem top_layer vorhande MailingListIds vergeben werden können
- [ ] Im Mitglieder-Selbstregistrierungsformular im Schritt Zusatzdaten den Promocode-Input entfernen
- [ ] Ebenfalls im Schritt Zusatzdaten die Logik hinter der Newsletter-Checkbox umstellen, sodass ein Opt-Out für den Newsletter angelegt wird statt ein Tag zu schreiben
- [ ] Sicherstellen dass nichts kaputt geht, wenn der Nationalverband kein Newsletter-Abo oder ein invalides oder nicht existentes eingerichtet hat
- [ ] Feature Specs schreiben
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by sykesonrocks** [comment]
@mtnstar NOK

Wenn ich das "Mitglied werden" Formular abschicke, mit einem Hacken bei "Ich möchte einen Newsletter abonnieren", wird mir das Abo trotzdem nicht zugewiesen.

Beispiel: Antrag mit Newsletter 
![image](https://github.com/hitobito/hitobito_sac_cas/assets/132900428/9cc3f7fe-3ade-477c-a8fa-4847a1318fac)

Beispiel: Antrag ohne Newsletter
![image](https://github.com/hitobito/hitobito_sac_cas/assets/132900428/f6878d02-3ea6-454c-a598-3d7b4b7377dd)

**Comment by daniel-illi** [comment]
Das Problem war, dass auf Integration für den `SAC/CAS Newsletter` die Neuanmeldungen Rollen noch nicht als Empfänger konfiguriert war. Das An-/Abmelden funktioniert nun nachdem ich das auf Integration nachgeführt habe.

**Comment by sykesonrocks** [comment]
@mtnstar Nachfolgend meine Testergebnisse.

- Promocode wird nicht mehr angezeigt, somit ok.
- Beim Newsletter scheint es noch ein Bug zu geben. Ich habe zwei Anträge für SAC Huttwil eingereicht: 1x mit und 1x ohne Newsletter. Selbstregistrierungslink: https://sac-cas.puzzle.ch/de/groups/1014/self_registration. Die Personen wurden wie folgt angelegt:
![image](https://github.com/hitobito/hitobito_sac_cas/assets/132900428/82322d5b-af4d-4add-b225-1391939da54f)

**Comment by mtnstar** [comment]
> @mtnstar Nachfolgend meine Testergebnisse.
> 
>     * Promocode wird nicht mehr angezeigt, somit ok.
> 
>     * Beim Newsletter scheint es noch ein Bug zu geben. Ich habe zwei Anträge für SAC Huttwil eingereicht: 1x mit und 1x ohne Newsletter. Selbstregistrierungslink: https://sac-cas.puzzle.ch/de/groups/1014/self_registration. Die Personen wurden wie folgt angelegt:
>       ![image](https://private-user-images.githubusercontent.com/132900428/313207054-82322d5b-af4d-4add-b225-1391939da54f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3Njg1NDEsIm5iZiI6MTcxMDc2ODI0MSwicGF0aCI6Ii8xMzI5MDA0MjgvMzEzMjA3MDU0LTgyMzIyZDViLWFmNGQtNGFkZC1iMjI1LTEzOTE5MzlkYTU0Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOFQxMzI0MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NzA4YjJmMjhmYzcyMWFiYjkzNGIxMjFhYjY3NjQyZWFkM2VkNzkxZTY1OGUxY2MwMzkwOWExYTFiMzJhMjg5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XioFxguHAW9obdmSgMlc6aRyuy_QIHKsgbbspljUlnY)

@sykesonrocks kannst du das nochmals Testen? Das Problem war das die Mailingliste für den Newsletter nicht richtig konfiguriert war.

wir wollen das Abo für den SAC Newsletter read-only machen damit da nichts verstellt werden kann. Dazu gibt es auch mal ein Ticket als Entwurf: https://github.com/hitobito/hitobito_sac_cas/issues/413

**Comment by daniel-illi** [comment]
Auf Integration war der Newsletter noch falsch konfiguriert, Neuanmeldungsrollen waren noch nicht als Opt-Out Empfänger eingestellt.
Ich habe die Konfiguration korrigiert,  nun funktioniert die Newsletter Anmeldung auch bei Sektions Neuanmeldungen (auch alle bereits angelegten Benutzer welche das Häkchen gesetzt hatten sind nun als Abonnenten aufgeführt).
Mit #413 sollte dann eine Fehlkonfiguration nicht mehr möglich sein.

**Comment by sykesonrocks** [comment]
Newsletter wird ¨nun korrekt abonniert, somit OK.
![image](https://github.com/hitobito/hitobito_sac_cas/assets/132900428/7ff72538-8d13-4067-b2b7-9974b9eeb6da)
