### ISSUE TITLE
PEOPLE: Selbstregistrierung DSE-Feature für Sektionsstatuten

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito_sac_cas#289]
Als verantwortliche Person auf der Sektion/Ortsgruppe möchte ich die Sektionsstatuten meiner Ebene verwalten können, um sie aktuell halten zu können. 

## Neuanmeldungen Sektionen / Ortsgruppen

![image](https://github.com/hitobito/hitobito_sac_cas/assets/655627/448ab672-680f-4ca5-b300-e81b4cb8f6db)

Jede Sektion hat eigene Statuten die bei der Selbstregistrierung akzeptiert werden müssen. Dazu soll das aus dem Core vorhandene DSE-Feature (privacy policy der sektion) (Dokument upload)  welches auf dem Sektions-Layer (auch Ortsgruppe) konfiguriert werden kann. Es gibt auf dem Layer nur 1 DSE Dokument. 

![image](https://github.com/hitobito/hitobito_sac_cas/assets/655627/5c99942f-156f-4ca0-b921-3009d4d21c95)

Den konfigurierten Titel auch gleich übernehmen.

Jede Sektion kann so ihre Statuten als PDF hochladen und diese müssen dann von der Person die sich registriert akzeptiert werden.

Im Selbstregistrierungsformular soll das bei den Neuanmeldungen wieder als Checkbox gerendert werden. 

# Tech-Spec

- Umsetzung im SAC Wagon
- In den Selbstregistrierungsformularen die nicht auf einer Neuanmeldungen-Gruppe sind ist noch das hitobito-Core-Feature im Einsatz
- Vom Styling und Abständen her soll die Checkbox gleich daherkommen wie die anderen Checkboxes im Formular
- In der Sidebar ist noch unklar was mit den drei Links passiert, dies wird zu einem späteren Zeitpunkt noch angeschaut

# ToDo

- [x] Schritt Zusatzdaten im Selbstregistrierungsformular anpassen
- [x] Styling
- [x] Manuell testen dass es korrekt aussieht wenn keine, eine oder mehrere Datenschutzerklärungen im Nationalverband und Sektion und Ortsgruppe hochgeladen sind
- [x] Specs schreiben
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by sykesonrocks** [comment]
@mtnstar OK

- Man muss zwingend ein Titel mit angeben, ansonsten erscheint der Link nicht.
- Ob ein Dokument bereits unter "DSE/Datenschutzerklärung" hochgeladen wurde, kann im Bearbeiten-Modus nicht ausfindig gemacht werden - der Wert ist immer leer (auch wenn ein Dokument hochgeladen wurde)

![image](https://github.com/hitobito/hitobito_sac_cas/assets/132900428/618d6dbd-0aa3-491c-9732-2053b8fda465)

**Comment by daniel-illi** [comment]
@mtnstar die Funktionalität ist OK, es gibt für die UX noch Optimierungspotential (siehe Kommentar von @sykesonrocks).
IMO kann das Ticket als abgeschlossen betrachtet werden, die Opitmierungen können gut zu einem späteren Zeitpunkt angegangen werden.

**Comment by sykesonrocks** [comment]
@mtnstar Das Hochladen und die Anzeige/Verlinkung im Schritt "Zusatzdaten" sieht gut aus, somit ok.

Wie kann ein bereits hochgeladenes DSE Dokument wieder löschen, sodass keine Sektionsstatuten mehr dargestellt werden?

**Comment by mtnstar** [comment]
![image](https://github.com/hitobito/hitobito_sac_cas/assets/655627/1e2b7f73-e924-46c7-8856-e27004c81b4a)

@sykesonrocks das ist etwas versteckt. Beim Editieren der Sektion musst du das Häckchen bei `DSE/Datenschutzerklärung entfernen`  setzen und dann Speichern. Dann sollten die Statuten weg sein.
