### ISSUE TITLE
IMPORT: Migration der Daten aus Navision `NAV` und Tourenportal `WSO2`

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#290]
Dieses Epic beschreibt aus Entwicklersicht die Aufgaben zum Thema SAC/CAS Import.

- Entwicklerdokumentation: https://github.com/hitobito/hitobito_sac_cas/blob/master/doc/import.md
- Übersicht auf Kundenseite: https://saccas.atlassian.net/browse/HIT-490

##  Import umsetzen

- [x] #950
- [x] #812
- [x] #767
- [x] #770 
- [x] PEOPLE: Import `nav2-2_section_roles` implementieren
- [x] PEOPLE: Import `nav2-3_top_roles` implementieren
- [x] PEOPLE: Import `nav2-4_tourenkommission` implementieren
- [x] #742
- [x] #886
- [x] #772
- [x] #905
- [x] #391
- [x] #788
- [x] #934
- [x] #1019
- [x] #899
- [x] #1081
- [x] #1085
- [x] #1130

## Ergänzungen

- [x] #998 
- [x] #1009 
- [x] https://github.com/hitobito/hitobito_sac_cas/issues/1121

## Frühere Issues zum Thema Import

- [x] #193
- [x] https://github.com/hitobito/hitobito_sac_cas/issues/192
- [x] https://github.com/hitobito/hitobito_sac_cas/issues/243
- [x] https://github.com/hitobito/hitobito_sac_cas/issues/291
- [x] https://github.com/hitobito/hitobito_sac_cas/issues/198
- [x] #726 
- [x] https://github.com/hitobito/hitobito_sac_cas/issues/242 
- [x] https://github.com/hitobito/hitobito_sac_cas/issues/154
- [x] #782
- [x] #771 

## Offen

- Schweizer Bergführerverband (SBV) / Bergführer
