### ISSUE TITLE
PEOPLE: Selbstregistrierung Bemerkungen

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito_sac_cas#294]
:warning: noch offen ob es das bemerkungsfeld noch braucht

Als Person die sich für den SAC registriert
möchte ich in Freitext Bemerkungen angeben können,
um den SAC über Spezialfälle betreffend meiner Registrierung oder Mitgliedschaft zu informieren.

Als Mitarbeiter beim Mitgliederdienst des SAC
möchte ich die angegebenen Bemerkungen jederzeit auf der Person einsehen können,
damit sie auch bei vollautomatischer Zuteilung zur Mitgliedschaft noch beachtet werden können.

Neu soll im Selbstregistrierungsformular im Schritt Zusatzdaten ein Feld "Bemerkungen" eingefügt werden, welches den Wert in die additional_information Spalte der Person speichert.

# Mockup

![Screenshot 2024-02-12 at 09-59-09 SAC Hitobito Balsamiq-Mockups pdf](https://github.com/hitobito/hitobito_sac_cas/assets/7566995/6e922c33-9366-424d-a51a-05e5cced2b99)
Quelle: https://raw.githubusercontent.com/hitobito/hitobito_sac_cas/master/doc/SAC%20Hitobito%20Balsamiq-Mockups.pdf#page=8

# Tech-Spec

- Feld ging in #101 vergessen
- Nur im stark angepassten Mehrschritt-Neuanmeldungen-Selbstregistrierungsformular
- Die Bemerkungen sollten später nicht mehr durch die Person selber änderbar sein, aber da das nicht nur für dieses Feld gilt, haben wir dafür ein separates Ticket hitobito/hitobito#2408 wo wir die self-readonly-Felder sammeln und ein System dafür schaffen

# ToDo

- [ ] Feld im Formular hinzufügen
- [ ] Ggf. Logik anpassen sodass dieses Feld in additional_information auf der Person persistiert wird
- [ ] Specs schreiben
- [ ] Mit angemessener Rolle "durchklicken"
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by sykesonrocks** [comment]
@mtnstar Wie heute besprochen, wird das Feld "Bemerkungen" aus den "Mitglied werden" Formularen abgebaut (Entscheid).
