### ISSUE TITLE
PEOPLE: Selbstregistrierung Optionen für "Eintrittsdatum per"

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito_sac_cas#295]
Als Person die sich für eine Mitgliedschaft registriert
möchte ich nur relevante Optionen für das Startdatum der Mitgliedschaft angezeigt bekommen,
um so wenig wie möglich lesen zu müssen und so wenig Fehler wie möglich machen zu können.

Neu soll beim "Eintrittsdatum per" die Logik angepasst werden, welche bestimmt welche Optionen angezeigt werden.

Neue Logik:
- Nur die eine nächste Option im gleichen Jahr anzeigen.
  - Vor dem 1.Juli wird "sofort" und "01. Juli" angezeigt
  - Ab 1. Juli wird "sofort" und "01. Oktober" angezeigt
  - Ab 1. Oktober wird nur "sofort" angezeigt, im besten Fall nur als Text und nicht mehr als Radio Button.
- Beschreibungs-Text auch abhängig vom Datum. Es braucht für die 3 Fälle oben 3 verschiedene Texte welche die verfügbaren Optionen beschreiben.

# Tech-Spec

- Umsetzung im SAC Wagon
- Logik ist in https://github.com/hitobito/hitobito_sac_cas/blob/master/app/models/future_role/form_handling.rb
- Im Selbsteinschreibungsformular gibt es sehr ähnliche Optionen. Falls einfach umsetzbar, diese auch gleich anpassen.

# ToDo

- [ ] Logik für Anzeige der Optionen anpassen
- [ ] Übersetzungstexte (Beschreibungstext unter den Optionen) anlegen und im korrekten Fall anzeigen
- [ ] Specs schreiben
- [ ] **wichtig** Stefan wegen Übersetzungen und deutschen Originaltexten informieren
- [ ] Mit angemessener Rolle "durchklicken"
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by amaierhofer** [comment]
Da noch keine Info Texte definiert sind wurde in Absprache mit @mtnstar der allgemeine Infotext belassen.

**Comment by sykesonrocks** [comment]
@mtnstar NOK

Text heute
![image](https://github.com/hitobito/hitobito_sac_cas/assets/132900428/f0ede4a0-daf2-47b2-a29a-efe3739e518a)
vs. Text in Hitobito
![image](https://github.com/hitobito/hitobito_sac_cas/assets/132900428/16aa9865-a9b6-4b1f-8bc6-c0ff56c2d9c9)
Beschreibungs-Text ist abhängig vom Datum. Es braucht für die 3 Fälle (sofort, 01.07, 01.10) 3 verschiedene Texte

**Comment by mtnstar** [comment]
follow up ticket #350
