### ISSUE TITLE
PEOPLE: Selbstregistrierung für "Die Alpen" und fürs Tourenportal

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito_sac_cas#296]
Als interessierte Person
möchte ich mich selbst für die Alpen oder fürs Tourenportal registrieren können,
um an Informationen und Ressourcen des SAC zu gelangen.

Die Selbstregistrierung in den Gruppentypen `Group::AboMagazin` und `Group::AboTourenPortal` soll durch ein neues Mehrschritt-Formular ersetzt werden. Dabei wird das bisherige Formular imitiert: https://www.sac-cas.ch/de/die-alpen/abonnieren/abo-bestellen/

# Mockup
![Screenshot 2024-02-12 at 11-37-09 Abo bestellen](https://github.com/hitobito/hitobito_sac_cas/assets/7566995/0a5e7ab7-1970-4ff0-8ae5-16645a7cbe79)

# Tech-Spec

- Die Auswahl der Sprache erfolgt nach heutiger Hypothese noch auf der SAC Webseite. Danach kommt man weiter auf das neue Registrierungsformular von diesem Ticket (es gibt pro Sprache eine andere Gruppe in hitobito mit einem eigenen Registrierungsformular)
- Umsetzung der Felder gleich wie im Screenshot vom bisherigen Formular
- Änderungen an den Feldern:
  - Checkbox "Ja, ich möchte die Zeitschrift "die Alpen" kostenpflichtig abonnieren" weglassen
  - Zusätzliches Feld **Telefon**, Pflichtfeld, speichern in phone_number mit Label "Mobil"
  - Zusätzliches Feld Geburtstag, Pflichtfeld, validieren dass nur Personen die 18 Jahre oder älter sind dieses Formular abschicken können (weil da später noch ein Formularschritt für die Bezahlung dazukommt)
  - Je nach dem was einfacher ist: Vorgeschalteter Formularschritt mit Haupt-E-Mail-Prüfung analog Mitglieder-Registrierung
- Entscheidung welches Formular gerendert wird basierend auf dem Gruppentyp passiert bisher hier: https://github.com/hitobito/hitobito_sac_cas/blob/master/app/models/sac_cas/self_registration.rb#L15..L23

# ToDo

- [ ] Neue ActiveModels, Views etc. anlegen
- [ ] Model/View/Controller anpassen
- [ ] Feature Specs für happy path und Validierungen schreiben
- [ ] Kunde wegen Übersetzungen informieren
- [ ] Mit angemessener Rolle "durchklicken"
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by sykesonrocks** [comment]
@mtnstar 
- _Zusätzliches Feld Mobiltelefon, Pflichtfeld, speichern in phone_number mit Label "Mobil"_
Können wir das Feld bitte gleich benennen wie auf dem "Mitglied werden" Formular ("Telefon").
- Dieses Issue deckt gleich beide Komponenten ab, Die Alpen und das Tourenportal. Für Die Alpen werden zusätzlich die Sprache und die Ausgabe abgefragt (siehe https://www.sac-cas.ch/de/die-alpen/abonnieren/abo-bestellen/). Ich habe von dieser Spez verstanden, dass die Sprache noch in Typo3 abgefragt werden soll. Wo wird die Ausgabe abgefragt, in Hitobito?
- Beide Angebote sollten ggü. SAC Mitgliedern blockiert sein, da diese Dienstleistungen bereits in der Mitgliedschaft inbegriffen sind. Heute wird dies z.B. im Webshop wie folgt abgefangen:
![image](https://github.com/hitobito/hitobito_sac_cas/assets/132900428/ba28d726-9c8e-4c7d-b8f5-7e83b4cef3c0)
Ist diese Blockade in den entsprechenden Hitobito Formularen vorgesehen?

**Comment by mtnstar** [comment]
@TheWalkingLeek du bist das ja na am Reviewen. Kannst du noch sicherstellen das das Label Telefon verwendet wird? siehe Kommentar oben

**Comment by mtnstar** [comment]
> @mtnstar
> 
>     * _Zusätzliches Feld Mobiltelefon, Pflichtfeld, speichern in phone_number mit Label "Mobil"_
>       Können wir das Feld bitte gleich benennen wie auf dem "Mitglied werden" Formular ("Telefon").
> 
>     * Dieses Issue deckt gleich beide Komponenten ab, Die Alpen und das Tourenportal. Für Die Alpen werden zusätzlich die Sprache und die Ausgabe abgefragt (siehe https://www.sac-cas.ch/de/die-alpen/abonnieren/abo-bestellen/). Ich habe von dieser Spez verstanden, dass die Sprache noch in Typo3 abgefragt werden soll. Wo wird die Ausgabe abgefragt, in Hitobito?
> 
>     * Beide Angebote sollten ggü. SAC Mitgliedern blockiert sein, da diese Dienstleistungen bereits in der Mitgliedschaft inbegriffen sind. Heute wird dies z.B. im Webshop wie folgt abgefangen:
>       ![image](https://private-user-images.githubusercontent.com/132900428/305887842-ba28d726-9c8e-4c7d-b8f5-7e83b4cef3c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzNTM2MDAsIm5iZiI6MTcwODM1MzMwMCwicGF0aCI6Ii8xMzI5MDA0MjgvMzA1ODg3ODQyLWJhMjhkNzI2LTljOGUtNGM3ZC1iOGY1LTdlODNiNGNlZjNjMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxOVQxNDM1MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZmQ4ODRiNjE0MGNhODZmZWExMmQ5Mzk5NGJhNzgxMmNlZDM3Yjk1NThhZDU2ZWI3M2NmMjYxMjMzZmQ3M2Y2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Gzyp7VH8txudteUYgVft34-YPIPUjOWpVQd1GPJm1ks)
>       Ist diese Blockade in den entsprechenden Hitobito Formularen vorgesehen?

@sykesonrocks können wir die beiden letzten Punkte am MI besprechen?

**Comment by mtnstar** [comment]
@TheWalkingLeek kannst du die Kommentare von Stefan prüfen?
das wurde in vielen Punkten leider nicht so umgesetzt wie spezifiziert bzw. überhaupt nicht ähnlich wie die Registrierung für die Mitglieder.

**Comment by mtnstar** [comment]
offene Punkte werden mit #347 adressiert

**Comment by sykesonrocks** [comment]
Testergebnisse betreffend Reg.formular für Die Alpen: siehe https://github.com/hitobito/hitobito_sac_cas/issues/345
Testergebnisse betreffend Reg.formular für Tourenportal: siehe https://github.com/hitobito/hitobito_sac_cas/issues/347
