### ISSUE TITLE
PEOPLE: Selbstregistrierung für Basis-Login

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito_sac_cas#297]
Als interessierte Person
möchte ich mich selbst für einen kostenfreien SAC-Login registrieren können, um Dienstleistungen des SAC (welche nur mit SAC Login zugänglich sind) zu nutzen.

Die Selbstregistrierung im Gruppentyp `Group::AboBasicLogin` soll durch ein neues Formular ersetzt werden

Es braucht auch keine Preisinformationen bei diesem Formular.

# Mockup

Ähnlich wie #296, aber das Formular in diesem Ticket wird noch etwas vereinfacht

# Tech-Spec

- Umsetzung ausgehend von einer Kopie der Logik von #296
- Änderungen an den Feldern gegenüber #296:
  - Pflichtfelder sind nur die Felder Vorname, Name, Mailadresse, Geburtsdatum
  - Altersbeschränkung (Validierung auf Geburtsdatum) für dieses Formular entfernen
  - Dieses Formular wird soweit ich weiss keinen Bezahl-Schritt enthalten, es wird ein einseitiges Formular gerendert, ohne **Ab Ausgabe**
  - Ohne Preisinformationen
- Entscheidung welches Formular gerendert wird basierend auf dem Gruppentyp passiert bisher hier: https://github.com/hitobito/hitobito_sac_cas/blob/master/app/models/sac_cas/self_registration.rb#L15..L23

# ToDo

- [ ] Neue ActiveModels, Views etc. kopieren und anpassen
- [ ] Model/View/Controller anpassen
- [ ] Feature Specs für happy path und Validierungen schreiben
- [ ] Kunde wegen Übersetzungen informieren
- [ ] Mit angemessener Rolle "durchklicken"
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by mtnstar** [comment]
@TheWalkingLeek da wird irgendwie das falsche Formular gerendert für Basic Login.
könntest du das anschauen?
für Basis Konto sollte ein anderes Formular gerendert werden wie für Magazin Die Alpen

**Comment by mtnstar** [comment]
fixes in follow up ticket: https://github.com/hitobito/hitobito_sac_cas/issues/346

**Comment by sykesonrocks** [comment]
@mtnstar siehe meine Testergebnisse unter https://github.com/hitobito/hitobito_sac_cas/issues/346
