### ISSUE TITLE
PEOPLE: Selbstregistrierungsformular kleinere Anpassungen

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#305]
![image](https://github.com/hitobito/hitobito_sac_cas/assets/655627/b1939006-e8a6-45b2-b313-64d98e85c762)

## E-Mail MV mit @

Die E-Mail mv(at)sac-cas.ch durch mv@sac-cas.ch ersetzen (locale Eintrag)

## Titel Beiträge in der Sektion

Hier den Titel der Sektion (parent, sektions layer) anzeigen.

**Beiträge in der Sektion SAC Matterhorn**

## Telefon anstatt Telefonnummer

- Übersetzung anpassen das anstatt Telefonnummer Telefon auf Deutsch angezeigt wird
- Platzhalter Nummer durch Nr Beispiel ersetzen

![image](https://github.com/hitobito/hitobito_sac_cas/assets/655627/e5a0d78c-5b80-48b9-910a-ef2a494ab244)

# ToDo

- [ ] Locale anpassen (alle Sprachen), specs anpassen/prüfen
- [ ] Titel Beiträge anpassen inkl. Specs
- [ ] Telefon Feld/Bezeichnung anpassen
- [ ] Manuell testen

**Comment by sykesonrocks** [comment]
@mtnstar NOK
![image](https://github.com/hitobito/hitobito_sac_cas/assets/132900428/767e15ff-50ca-4327-a406-729208aab66c)

**Comment by mtnstar** [comment]
@sykesonrocks ich habe gerade mit der Sektion Baldern das durchgespielt, bei mir sieht's gut aus.
wie ist das bei dir passiert das auf der rechten seite die Beitragsinfo doppelt angezeigt wird?
die schwarze Box, ist das so im Browser aufgetreten?

**Comment by sykesonrocks** [comment]
Habe es gerade nochmals getestet: Selbstregistrierungslink aufrufen, Daten ausfüllen, Weiter:
![image](https://github.com/hitobito/hitobito_sac_cas/assets/132900428/8fefdcae-0969-4de6-b7a8-c36c75b5f10a)
Schwarze Box habe ich eingefügt um hier keine Kundendaten auszugeben.

**Comment by daniel-illi** [comment]
Ich kann die doppelte Beitragsinfo reproduzieren durch hinzufügen und wieder entfernen eines Familienmitgliedes.

**Comment by sykesonrocks** [comment]
@mtnstar Nachfolgend meine Testergebnisse:
- E-Mail MV mit @ (mv@sac-cas.ch) wird korrekt ausgegeben.
- Titel Beiträge in der Sektion wird korrekt ausgegeben.
- Label Telefon anstatt Telefonnummer wird korrekt ausgegeben.
- Anforderung _Platzhalter Nummer durch Nr Beispiel ersetzen_: mein Verständnis war, dass ein Beispiel und nicht "Nummer" als String dargestellt werden soll (beim Feld "PLZ" steht bspw. auch nicht "Nummer"):
![image](https://github.com/hitobito/hitobito_sac_cas/assets/132900428/2b5d7f0d-21b8-4b82-9547-d194f90647f1)

**Comment by mtnstar** [comment]
@sykesonrocks seltsam, das mit der Nummer war mal richtig, da hat sich vermutlich ein alter Stand wieder eingeschlichen. Ich habe ein follow-up ticket erstellt: #411
