### ISSUE TITLE
PEOPLE/ROLES: Mitgliedschaft + Abos (Prio 03.24)

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#311]
## Abo (Magazin, Portal)

- [x] https://github.com/hitobito/hitobito_sac_cas/issues/226
- [ ] #447
- [x] hitobito/hitobito_sac_cas#341
- [ ] Verhindern das aktives Mitglied Tourenportal abonnieren kann oder Basis Konto Rolle erhält

## Mitgliedschaft

- [x] https://github.com/hitobito/hitobito_sac_cas/issues/174
- [x] https://github.com/hitobito/hitobito_sac_cas/issues/224
- [x] https://github.com/hitobito/hitobito_sac_cas/issues/150
- [x] https://github.com/hitobito/hitobito_sac_cas/issues/200
- [x] hitobito/hitobito_sac_cas#315
- [x] #445
- [x] #446
- [x] #435
- [ ] #454

## Mitgliederausweis

- [x] https://github.com/hitobito/hitobito/issues/2511
- [x] https://github.com/hitobito/hitobito_sac_cas/issues/78
- [x] #419
- [x] #420

## Self Inscription

- [x] hitobito/hitobito_sac_cas#368
- [ ] hitobito/hitobito_sac_cas#385
- [x] hitobito/hitobito_sac_cas/issues/153

## Mailing Lists (Hitobito Abos)

- [x] hitobito/hitobito_sac_cas#396
