### ISSUE TITLE
ROLES: Austritt Familie, Verbesserung/Styling Bestätigungs-Modal

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#330]
Der Modal-Dialog für den Austritt soll leserlicher gestaltet werden. Ausserdem sollen bei SAC Familien alle Familienmitglieder aufgelistet werden welche bei einem Austritt automatisch mitaustreten.

## Mockup

![image](https://github.com/hitobito/hitobito_sac_cas/assets/655627/102b3187-5694-47b0-adaa-b4466e2ddc0a)

- Generischer Ansatz einfach alle Rollen mit Layer und Gruppe auflisten (ggf. im Core?), Funktion wird auch bei Abos benötigt
- Neue Warning Box
- Austritt erfolgt für: ... anzeigen
- Falls Familie, alle Familien-Mitglieder auflisten (sowie für: ...)

# Tech-Spec

- https://github.com/hitobito/hitobito_sac_cas/blob/master/app/domain/people/sac_family.rb
- https://github.com/hitobito/hitobito_sac_cas/tree/master/app/views/roles/terminations

# ToDo

- [x] Auflisten aller Rollen (affected roles) in neuem Format (im Core falls sinnvoll)
- [x] Warning Box mit Hinweis (core)
- [x] Familien-Mitglieder auflisten falls Familie (im SAC Wagon)
- [x] Vorhandene Specs überprüfen und ggf. anpassen
- [x] manuell Testen

**Comment by sykesonrocks** [comment]
@mtnstar siehe meine Kommentare unter https://github.com/hitobito/hitobito_sac_cas/issues/200
