### ISSUE TITLE
INVOICES: JSON API

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#338]
Als externes System möchte ich den Status von Rechnungen in hitobito aktualisieren, um diese synchron zu halten.

Neu soll eine rudimentäre JSON API über Graphiti für Rechnungen bereitgestellt werden. In einem ersten Schritt steht nur eine einfache Index, Show und Update Action zur Verfügung.

Die Index Action erlaubt folgende Filter: 
- group_id
- recipient_id

Die Attribute der Rechnung sowie (optional oder nur bei der show Action) der zugehörigen Positionen (InvoiceItems) werden serialisiert.

Die Update Action erlaubt das Aktualisieren derselben Attribute wie über den bestehenden Controller (insbesondere den Status).

# ToDo

- [ ] Graphiti Controller erstellen
- [ ] JSON API Dokumentation ergänzen, inkl Update Action
- [ ] Specs schreiben
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen
