### ISSUE TITLE
PEOPLE: Weitere Anpassungen Selbstregistrierungsformular Mitgliedschaft

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#339]
Folgendes Feedback vom SAC soll noch umgesetzt werden:

## 1. Fehlermeldungen (Validierung)

![image](https://github.com/hitobito/hitobito_sac_cas/assets/655627/b902473f-f2e4-48b7-a498-8352c39337ea)

Die Fehlermeldung `Beitragskategorie muss ausgefüllt werden` soll nie angezeigt werden. Auch nicht beim Erstellen einer Rolle ausserhalb des Selbstregistrierungsformulars. Die Beitragskategorie kann nur beim fehlendem Geburtsdatum oder Alter kleiner 6 Jahre nicht assigned werden. Daher reicht in diesem Fall der Hinweis: `Person muss ein Geburtsdatum haben und mindestens 6 Jahre alt sein`

## Styling Einverständnis Erziehungsberechtigte

![image](https://github.com/hitobito/hitobito_sac_cas/assets/655627/5efca697-341e-4018-b2dd-190feb92975e)

Einverständnis Erziehungsberechtigte Checkbox sowie Text sollten das gleiche Styling haben wie die anderen Checkboxen. (Sektionsstatuten usw.)
Text ohne '.' am Schluss

## 2. Bug Missing Buttons «Weiter als Familienmitgliedschaft», Zurück in Schritt 2

![image](https://github.com/hitobito/hitobito_sac_cas/assets/655627/82f5659a-44eb-4196-8c0b-ca545399e19e)

Wenn ich danach den leeren Eintrag entferne (via «Entfernen»), verschwindet der Knopf «Weiter als Familienmitgliedschaft»

- Es soll in diesem Fall der Button «Weiter als Einzelmitglied» angezeigt werden falls keine weiteren Personen erfasst. «Weiter als Familienmitgliedschaft» wenn weitere Personen vorhanden sind.

Ausserdem fehlt der Zurück Button auf Schritt 2 um auf die Eingabe der Haupt-Email zurück zu gelangen
 
## 3. Text SAC Familien anpassen

```
Indem du weitere Personen hinzufügst, wählst du eine Familienmitgliedschaft. Diese ist für max. 2 Erwachsene ab 23 Jahren und beliebig viele Kinder im Alter zwischen 6 und 17 Jahren möglich.

Die Familienmitgliedschaft ist auch für Paare ohne Kinder möglich. Falls du eine Familienmitgliedschaft mit einem bereits bestehenden Mitglied gründen möchtest, kontaktiere bitte die SAC Geschäftsstelle.
```

## 4. Dokumente in neuem Tab

Sicherstellen das alle Dokumente im letzten Schritt sich in einem neuen Tab öffnen. Links entsprechend anpassen sodass Statuten und alle anderen Dokumente in einem neuen Tab geöffnet werden und man nicht die Selbstregistrierung verlässt.

# Tech-Spec
- https://github.com/hitobito/hitobito_sac_cas/tree/master/app/models/sac_cas/role
- https://github.com/hitobito/hitobito_sac_cas/blob/master/app/models/sac_cas/role_beitragskategorie.rb

# ToDo

- [x] Sicherstellen das bei der Mitglieder-Rollen-Validierung die Beitragskategorie nicht mehr als Fehler erscheint (ggf. Exception werfen falls versucht wird Rolle ohne Beitragskategorie zu speichern)
- [x] Styling Einverständnis Erziehungsberechtigte anpassen (core)
- [x] Missing Button Bug fixen, ggf. feature spec dazu
- [x] Dokumente in Tabs öffnen
- [x] Manuelles Testen

**Comment by daniel-illi** [comment]
die verschwindenden Buttons treten immer noch auf

**Comment by sykesonrocks** [comment]
@mtnstar @daniel-illi Nachfolgend meine Testergebnisse inkl. Feedback von Marketing.

- Logo oben rechts anstelle oben links (analog Webseite und CI/CD)
- Buttons eckig gestalten, keine abgerundete Ecken analog Webseite
- Buttons linksbündig analog Textfeld setzen
- Text in Buttons in Grossbuchstaben analog Webseite
- Bei Sprachwechsel muss das Logo entsprechend wechseln
- In der rechten Spalte bei den Beiträgen: Jährlicher Beitrag/einmalige Gebühr und Total sind nicht aufeinander ausgerichtet (Tabstopp setzen)
- In der rechten Spalte bei den Kontaktangaben: Telefonnummer wird mit Tel. angekündigt, Email nicht. Bei Email -> E-Mail: mv(at) → Habe ich bei Puzzle angefragt, siehe mein Kommentar unter 
- Wording Registrierung zu SAC xyz → Anmeldung Sektion SAC Lägern
- "Du hast bereits ein Login?" → entfernen
- "Anmelden und Einschreiben" → entfernen
- Wording Haupt-E-Mail → E-Mail (Haupt-E-Mail ist unklar weshalb Haupt)
- Schritt 1: hinter dem Eingabefeld "E-Mail" ein Info-Icon darstellen. Bei MouseOver ein Text anzeigen.
- Wording Feld "Anrede" → "Geschlecht"
- Feld "Anrede" mögliche Werte → weiblich, männlich, andere (weiblich an erster Stelle anzeigen)
- Wording "Geburtstag" → "Geburtsdatum"
- Feld "Ort" automatisch befüllen, wenn eine PLZ eingegeben wird
- Satz unter Schritt 3 anpassen: “Indem du weitere Personen hinzufügst, wählst du eine Familienmitgliedschaft. Diese ist für max. 2 Erwachsene ab 23 Jahren und beliebig viele Kinder im Alter zwischen 6 und 17 Jahren im gleichen Haushalt möglich. Die Familienmitgliedschaft ist auch für Paare ohne Kinder möglich. Falls du eine Familienmitgliedschaft mit einem bereits bestehenden Mitglied gründen möchtest, kontaktiere bitte die SAC Geschäftsstelle.“ 
- Schritt 3: Ausrichtung Button / Eintrag hinzufügen → senkrecht untereinander ausrichten
- Reihenfolge Buttons nicht userfreundlich. Zurück ist immer links von weiter → entsprechend anpassen
- Wording "Geburtstag" → "Geburtsdatum"
- E-Mail Adresse und Telefon bei erwachsenen Personen immer obligatorisch (Schritt 3)
- Pflichtfelder mit einem * kennzeichnen, siehe im letzten Schritt Checkboxes
- Wording "Ich möchte einen Newsletter abonnieren" → "Ich möchte den SAC-Newsletter abonnieren"
- Statuten, Beitragsreglement und Datenschutz in einen Punkt nehmen → Ich habe die Statuten, das Beitragsreglement und die Datenschutzerklärung gelesen und stimme diesen zu.
- Wording Button "Registrieren" → "Mitgliedschaft abschliessen" oder "Mitgliedschaft beantragen", je nach dem ob Sektion direkte Eintritte erlaubt oder noch ihr ok geben muss.
- Wording "Fehlende Akzeptierung von Felder." statt “Muss akzeptiert werden” → Bitte Kontrollkästchen Statuten, Beitragsreglement, Datenschutzerklärung akzeptieren aktivieren”
- Fehlende Zusammenfassung
