### ISSUE TITLE
PEOPLE: Neuanmeldungen - alle Familien-Mitglieder gleichzeitig annehmen/ablehnen

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#340]
Für die Sektions Gruppe **Neuanmeldungen (zur Freigabe)** haben wir bereits mit #109  einen Mechano umgesetzt mit welchem Neumitglieder angenommen oder abgelehnt werden können. Mit diesem Ticket soll die Anmeldung einer kompletten Familie berücksichtigt werden. Wählt man nur ein einzelnes Familien-Mitglied aus, sollen alle Familien-Mitglieder angenommen oder abgelehnt werden. Das stellt die Integrität der SAC-Familien sicher.

Aktuell sieht dieser Dialog folgendermassen aus:

![image](https://github.com/hitobito/hitobito_sac_cas/assets/655627/64908e5f-bcdc-4597-90d8-aed6f1ebe0d2)

## alle Familien-Mitglieder

- [x] Neu sollen alle Personen mit Namen/Vornamen die ausgewählt wurden aufgelistet werden
- [x] Bei Familien werden alle Familienmitglieder mit aufgelistet, auch wenn nur 1 Person der Familie ausgewählt ist
- [x] Familienmitglieder können nicht einzeln approved werden. 
- [x] Optional kann die Anzahl der ausgewählten Personen wie bisher im Button angezeigt werden

# Tech-Spec

- [x] `People::Neuanmeldungen::Base#applicable_roles` erweitern: auch die Rollen der Familienmitglieder/Household people inkludieren.

  z.B. etwa so:
  ```ruby
  def applicable_people
    Person.where(id: people_ids).flat_map {|person| person.household.people }.uniq
  end

  def applicable_roles
    group.roles.where(type: NEUANMELDUNGEN_ROLE.sti_name, person_id: applicable_people.map(&:id))
  end
  ```
- [x] `People::Neuanmeldungen::HandlerController#count` anpassen: nicht die Anzahl Params `people_ids` sondern die Anzahl betroffener Personen zurückgeben  
  z.B. `def count = handler.applicable_people.count`
- [x] `app/views/people/neuanmeldungen/handler/_modal_form.html.haml` anpassen:  
  nach dem `= ti('text', count: count)` eine Liste mit allen betroffenen Personen (Namen) anzeigen (`handler.applicable_people`)  
  

# ToDo

- [x] Dialog so erweitern das alle Personen aufgelistet werden
- [x] Familien-Mitglieder berücksichtigen und mit auflisten/approven/ablehnen
- [x] ~Alle Mitglieder einer Familie in einer Transaktion approven~ wird schon gemacht
- [x] Manuelles Testen mit Sektions Mitgliederverwaltung User
