### ISSUE TITLE
ROLES: Zusätzliche Abo Magazin Rollen (FAT, CSS, LAV, Buchhand, Gratisabonnent)

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#341]
Für Abo Magazin (Die Alpen) braucht es weitere Rollen da es verschiedene Abos mit anderen Rabatten/Spezialpreisen gibt. Ist man beispielweise Mitglied von FAT oder ein CSS versichertet, so bezahlt man weniger für ein Die Alpen Abo.

## Validierung

Eine Person kann nur EINE aktive Rolle pro Abo Magazin Gruppe haben. Wenn also z.B. eine Person eine aktive Rolle `NeuanmeldungFAT` in `Die Alpen DE` hat, kann sie dort nicht auch noch eine Rolle `Abonnent` haben. Bei der Validierung ebenfalls FutureRoles berücksichtigen, Zeitraum der Rollen dürfen nicht überlappen.

*Eine ähnliche Validierung zum Sicherstellen, dass Mitgliedschaften sich nicht überlappen ist implementiert in `SacCas::Role::MitgliedNoOverlapValidation`*

## Neue Rollen

- AbonnentFAT, NeuanmeldungFAT
- AbonnentCSS, NeuanmeldungCSS
- AbonnentLAV, NeuanmeldungLAV
- AbonnentBuchhand, NeuanmeldungBuchhand
- AbonnentGratis (keine Neuanmeldung da Gratis und daher keine Fakturierung notwendig)

Übersetzung DE jeweils: Abonnent CSS, Abonnent Gratis, Neuanmeldung LAV, usw.

Die Selbstregistrierung muss nicht angepasst werden da diese Rollen/Personen manuell erfasst werden. Das heisst das bei der Selbstregistrierung nur die Neuanmeldung Rolle berücksichtigt wird.

Es gibt den Edge-Case das eine Person das Magazin in zwei Sprachen abonniert hat, sprich in zwei unterschiedlichen Abo-Magazin-Gruppen eine aktive Rolle hat. Dies soll also möglich sein

# Tech-Spec

- https://github.com/hitobito/hitobito_sac_cas/blob/master/app/models/group/abo_magazin.rb
- Neue Rollen sollen von Abonnent sowie Neuanmeldung erben

# ToDo

- [x] Neue Rollen in Group::AboMagazin definieren, DE übersetzungen in locale file ergänzen
- [ ] Validierungen implementieren
- [ ] Development Seeder anpassen und testen
- [ ] Manuell Testen mit Mitglieder-Verwalter NV Person

**Comment by ThomasEllenberger** [comment]
Jira Ticket hierzu existiert nicht mehr.
In Absprache mit Andi Gurtner ist dieses Issue vermutlich überflüssig und wird deshalb geschlossen.
