### ISSUE TITLE
PEOPLE: Verbesserung Selbstregistrierung Abo Magazin (Die Alpen)

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#345]
follow up ticket von: #296

Via die SAC Webseite kann das Magazin die Alpen heute abonniert werden: https://www.sac-cas.ch/de/die-alpen/abonnieren/
Dies wird von Personen genutzt, die das Magazin die Alpen Abonnieren möchten, jedoch keine Mitgliedschaft beim SAC haben.

Mit Hitobito wird dies künftig wie bei der Mitgliedschaft über eine Gruppe und einer Rolle gelöst. Für das Onboarding braucht es dazu ebenfalls eine Selbstregistrierung. Folgende Anpassungen sollen mit diesem Ticket am Selbstregistrierungsformular für das Magazin Abo vorgenommen werden:

## Steps

![image](https://github.com/hitobito/hitobito_sac_cas/assets/655627/5188ac1c-29f3-4584-bedd-21739f125b5a)

### Step 1

![image](https://github.com/hitobito/hitobito_sac_cas/assets/655627/edffd9aa-6777-4242-85e4-e8d9ddf77251)

Wie beim Selbstregistrierungsformular für die Mitgliedschaft soll als erstes die Haupt-E-Mail der Person abgefragt werden. Besitzt die Person bereits ein Login mit der selben E-Mail-Adresse, wird sie auf das Login-Form redirected. Ansonsten gelangt sie zu Schritt 2 wo sie die Personalien angibt und sich dann registriert.  (Analog wie wir das bei den anderen Selbstregforms haben)

![image](https://github.com/hitobito/hitobito_sac_cas/assets/655627/c6e268fd-75e5-4534-ba50-1dab5b2a36b7)

Es werden bei allen Steps die Preisinformationen angezeigt. (aktuell statische Preise, später via Preisinfo Faktura)

### Step 2

![image](https://github.com/hitobito/hitobito_sac_cas/assets/655627/2cf0dd0e-1125-459e-8f2a-7d513022b609)

- Pflichtfelder: Anrede, Vorname, Nachname, Geburtstag, Strasse und Nr, PLZ/Ort, Land, Telefon
- E-Mail aus Form entfernen da bereits bei Step 1 abgefragt und validiert
- Person muss mindestens 18 Jahre alt sein
- Preisinformationen wie bei Step 1
- Link **Zurück**

### Step 3

![image](https://github.com/hitobito/hitobito_sac_cas/assets/655627/e1a2f5db-b579-45d9-8a0c-089871f88c15)

- Datumsfeld ist entweder leer oder auf ein Datum Heute oder in der Zukunft gesetzt
- Preisinformationen wie bei Step 1
- Link **Zurück**

![image](https://github.com/hitobito/hitobito_sac_cas/assets/655627/8a86d162-ac0f-43bf-ba44-5853af6cb565)

#### Checkboxen

Checkboxen für:

- Newsletter
- Statuten
- Datenschutzerklärung

![image](https://github.com/hitobito/hitobito_sac_cas/assets/655627/6c51abf7-9e3a-4130-b347-8cd4d25a3551)

Texte und Links analog Mitgliederselbstregistrierungsformular (ohne Beitragsreglement)

#### Newsletter

Wählt eine Person die Newsletter Checkbox nicht an, so wir diese aus dem SAC Newsletter Abo excluded.
Auf dem Top-Layer gibt es ein Attribut: SAC Newsletter Abo ID welches die ID des entsprechenden Abos definiert.

## Styling

Styling wird noch angepasst sobald sämtliche Selbstregformulare fertigestellt sind. Dazu gibt es ein eigenes Ticket: #320 

# Tech-Spec

- https://github.com/hitobito/hitobito_sac_cas/tree/master/app/models/self_registration_abo_magazin
- Gruppen-Typ: Group::AboMagazin

# ToDo

- [ ] Step 1 implementieren Haupt-E-Mail inkl. Redirect falls Person Entry mit E-Mail bereits vorhanden
- [ ] Step 2 inkl. Zurück Link, inkl. Altersvalidierung
- [ ] Step 3 inkl. Zurück Link, Validierung Ab Ausgabe Datumsfeld, Checkboxen
- [ ] Newsletter Logik implementieren
- [ ] Preisinformationen anzeigen bei allen Steps
- [ ] Manuell Testen
- [ ] CHANGELOG entry

**Comment by mtnstar** [comment]
@sykesonrocks dies ist ein weiteres follow up von #296

wie sieht es hier mit dem Newsletter aus? Gibt es hier keine AGBs oder Reglemente zum akzeptieren?

**Comment by sykesonrocks** [comment]
@mtnstar @daniel-illi Nachfolgend meine Testergebnisse inkl. Feedback aus Marketing.

- SAC Logo oben rechts anstelle oben links (analog Webseite und CI/CD)
- Buttons eckig gestalten, keine abgerundete Ecken analog Webseite
- Buttons linksbündig analog Textfeld setzen, Beispiel:
![image](https://github.com/hitobito/hitobito_sac_cas/assets/132900428/9c046be3-1b3d-46b5-a15a-0126ad0489bf)
- Text in Buttons in Grossbuchstaben analog Webseite
- Bei Sprachwechsel muss das Logo entsprechend wechseln

- Schritt 1: hinter dem Eingabefeld "E-Mail" ein Info-Icon darstellen. Bei MouseOver ein Text anzeigen und erläutern, weshalb eine E-Mail Adresse notwendig ist
- Breite der Preistabelle kürzen, sodass sie dieselbe Breite wie die Eingabefelder ausweisen oder komplett entfernen/löschen
- Dynamische Preisberechnung rechts einblenden, analog "Mitglied werden" auf der rechten Seite
- Kontaktdaten rechts einblenden, analog heutigem Formular
- Wording in der Preistabelle: Versandsland → Versandland
- Schritt 3 umbenennen von “Abo” zu “Abo Gültigkeit“
- Sie-Form, nicht Du-Form
- Geburtstag umbenennen zu Geburtsdatum
- Kunde kennen Erscheinungsdaten nicht, deshalb anstelle Datumauswahl / Auswahl Ausgabe (01/2024 - 02/2024, etc.)
- Im Feld Telefon eine Beispielnummer angeben und nicht "Nummer" als Text
- Feld Telefon optional
- Zusammenfassung der bestellten Leistungen fehlt
- Wording Button Registrieren → Abo kostenpflichtig bestellen
- "Du hast bereits ein Login?" nicht anzeigen
- "Anmelden und Einschreiben" nicht anzeigen
