### ISSUE TITLE
PEOPLE: Verbesserungen Selbstregistrierung Basiskonto

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#346]
follow up ticket von: [#297](https://github.com/hitobito/hitobito_sac_cas/issues/297)

Auf der Website des SAC gibt es aktuell die Möglichkeit ein Gratis-Konto zu erstellen:

![image](https://github.com/hitobito/hitobito_sac_cas/assets/655627/145a6377-7a1a-4b9c-882c-9d06918b5523)

Dies wird in Hitobito via einer Rolle in **Abonnenten > SAC/CAS Login > Basis Konto** abgedeckt. Damit ist ein Login in Hitobito sowie OIDC Authentifizierung für die registrierten Benutzer möglich.

Eine erste Version des Selbstregistrierungsformular dazu wurde bereits implementiert, folgende Anpassungen sollen mit diesem Ticket gemacht werden:

## Steps

![image](https://github.com/hitobito/hitobito_sac_cas/assets/655627/616c1d29-b1d1-464c-a874-51580e5e60eb)

### Step 1

![image](https://github.com/hitobito/hitobito_sac_cas/assets/655627/edffd9aa-6777-4242-85e4-e8d9ddf77251)

Wie beim Selbstregistrierungsformular für die Mitgliedschaft soll als erstes die Haupt-E-Mail der Person abgefragt werden. Besitzt die Person bereits ein Login mit der selben E-Mail-Adresse, wird sie auf das Login-Form redirected. Ansonsten gelangt sie zu Schritt 2 wo sie die Personalien angibt und sich dann registriert.  (Analog wie wir das bei den anderen Selbstregforms haben)

#### Keine Ab Ausgabe, keine Preisinformationen

Für ein Gratis-Konto braucht es weder das aus dem Abo Magazin bekannte 'Ab Ausgabe' noch irgendwelche Preisinformationen

### Step 2

![image](https://github.com/hitobito/hitobito_sac_cas/assets/655627/ed20cc9e-2dfe-43b8-b9b0-9e848cf960fa)

- Pflichtfelder Felder: Vorname, Name, Geburtstag
- ohne E-Mail Feld (da bereits in Schritt 1)
- auch hier keine Preisinformationen
- Link **Zurück** (Analog wie wir das bei den anderen Selbstregforms haben)

![image](https://github.com/hitobito/hitobito_sac_cas/assets/655627/8a86d162-ac0f-43bf-ba44-5853af6cb565)

#### Checkboxen

Checkboxen für:

- Newsletter
- Statuten
- Datenschutzerklärung

![image](https://github.com/hitobito/hitobito_sac_cas/assets/655627/6c51abf7-9e3a-4130-b347-8cd4d25a3551)

Texte und Links analog Mitgliederselbstregistrierungsformular (ohne Beitragsreglement)

#### Newsletter

Wählt eine Person die Newsletter Checkbox nicht an, so wir diese aus dem SAC Newsletter Abo excluded.
Auf dem Top-Layer gibt es ein Attribut: SAC Newsletter Abo ID welches die ID des entsprechenden Abos definiert.

## Styling

Styling wird noch angepasst sobald sämtliche Selbstregformulare fertigestellt sind. Dazu gibt es ein eigenes Ticket: #320 

## Tech-Spec

- https://github.com/hitobito/hitobito_sac_cas/blob/master/app/models/self_registration_abo_basic/main_person.rb
  - in self_registration_abo_basic_login renamen
- Gruppen-Typ: Group::AboBasicLogin
- Newsletter Logik wiederverwendbar machen und auch bei der Mitgliederselbstregistrierung einbauen

## ToDo

- [x] Step 1 implementieren Haupt-E-Mail inkl. Redirect falls Person Entry mit E-Mail bereits vorhanden
- [x] Step 2 implementieren Personendaten inkl Zurück Link, Checkboxen
- [x] Newsletter Logik umsetzen und auch noch in Mitgliederselbstregistrierung einbauen
- [x] Manuell Testen
- [ ] CHANGELOG entry

**Comment by mtnstar** [comment]
@sykesonrocks dieses ticket ist ein follow up auf #297 
haben wir so alles für die selbstregistrierung für das basis konto abgedeckt?

**Comment by daniel-illi** [comment]
Ausschluss von der Mailingliste funktioniert noch nicht

**Comment by sykesonrocks** [comment]
@mtnstar Nachfolgend meine Testergebnisse.

- Pflichtfelder Felder (Vorname, Name, Geburtstag) werden korrekt ausgegeben.
- E-Mail Adresse wird korrekt nur in Schritt 1 abgefragt.
- Es werden korrekterweise keine Preisinformationen mehr ausgegeben und das Feld "Ab Ausgabe" erscheint auch nicht mehr.
- Der Link "Zurück" funktioniert.
- Checkboxen (für Newsletter, Statuten, Datenschutzerklärung) werden korrekt ausgegeben.
- Wählt eine Person die Newsletter Checkbox nicht an, so wir diese aus dem SAC Newsletter Abo korrekt excluded.

- Mein Verständnis ist, dass das Formular nicht mehrsprachig ist. Das würde bedeuten, dass folgende Elemente einsprachig ausgegeben werden: Titel, Feldnamen, Texte bei den Checkboxen, Namen der Buttons (Registrieren, Zurück, Weiter) sowie Fehlermeldungen. Ist mein Verständnis korrekt? 
- Falls wir das Formular wieder anpassen sollten, wäre ich froh, wenn man den Titel ebenfalls anpassen könnte ("Registrierung für ein kostenloses SAC-Konto"). Falls der Titel nur einsprachig ausgegeben werden kann, müsste man die verschiedenen Sprachen berücksichtigen (mit z.B. "/" trennen).
