### ISSUE TITLE
PEOPLE: Anpassungen Selbstregistrierung Touren-Portal

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#347]
follow up ticket von: #296

Aktuell wird das Abo für das Touren-Portal via Webshop auf der SAC Webseite gekauft: https://www.sac-cas.ch/de/shop/sac-tourenportal-abonnement/detail/tourenportal-jahres-abo/8247/. Dies wird von Personen genutzt, die von den Inhalten des Tourenportals sowie dessen App profitieren möchten, jedoch keine Mitgliedschaft beim SAC haben.

Mit Hitobito wird dies künftig wie bei der Mitgliedschaft über eine Gruppe und einer Rolle gelöst. Für das Onboarding braucht es dazu ebenfalls eine Selbstregistrierung. Folgende Anpassungen sollen mit diesem Ticket am Selbstregistrierungsformular für das Touren-Portal Abo vorgenommen werden:

## Steps

![image](https://github.com/hitobito/hitobito_sac_cas/assets/655627/a4253658-9bc8-4266-b0b1-d2df47f5480b)

### Step 1

![image](https://github.com/hitobito/hitobito_sac_cas/assets/655627/edffd9aa-6777-4242-85e4-e8d9ddf77251)

Wie beim Selbstregistrierungsformular für die Mitgliedschaft soll als erstes die Haupt-E-Mail der Person abgefragt werden. Besitzt die Person bereits ein Login mit der selben E-Mail-Adresse, wird sie auf das Login-Form redirected. Ansonsten gelangt sie zu Schritt 2 wo sie die Personalien angibt und sich dann registriert.  (Analog wie wir das bei den anderen Selbstregforms haben)

![image](https://github.com/hitobito/hitobito_sac_cas/assets/655627/cf1c1404-0e88-4bcd-b80b-f59113caf61a)

Es werden bei beiden Steps die Preisinformationen angezeigt. (aktuell statischer Preis, später via Preisinfo Faktura)

### Step 2

![image](https://github.com/hitobito/hitobito_sac_cas/assets/655627/87f74b75-0956-4534-8b32-65fe370a9d67)

- Pflichtfelder: Anrede, Vorname, Nachname, Geburtstag, Strasse und Nr, PLZ/Ort, Land, Telefon
- Person muss mind. 18 Jahre alt sein
- E-Mail aus Form entfernen da bereits bei Step 1 abgefragt und validiert
- Preisinformationen wie bei Step 1
- Link **Zurück**

![image](https://github.com/hitobito/hitobito_sac_cas/assets/655627/8a86d162-ac0f-43bf-ba44-5853af6cb565)

#### Checkboxen

Checkboxen für:

- Newsletter
- Statuten
- Datenschutzerklärung

![image](https://github.com/hitobito/hitobito_sac_cas/assets/655627/6c51abf7-9e3a-4130-b347-8cd4d25a3551)

Texte und Links analog Mitgliederselbstregistrierungsformular (ohne Beitragsreglement)

#### Newsletter

Wählt eine Person die Newsletter Checkbox nicht an, so wir diese aus dem SAC Newsletter Abo excluded.
Auf dem Top-Layer gibt es ein Attribut: SAC Newsletter Abo ID welches die ID des entsprechenden Abos definiert.

## Styling

Styling wird noch angepasst sobald sämtliche Selbstregformulare fertigestellt sind. Dazu gibt es ein eigenes Ticket: #320 

# Tech-Spec

- https://github.com/hitobito/hitobito_sac_cas/tree/master/app/models/self_registration_abo_touren_portal
- Gruppen-Typ: Group::AboTourenPortal

# ToDo

- [ ] Step 1 implementieren Haupt-E-Mail inkl. Redirect falls Person Entry mit E-Mail bereits vorhanden
- [ ] Step 2 inkl. Zurück Link, inkl. Altersvalidierung (18 Jahre)
- [ ] Preisinformationen anzeigen bei beiden Steps
- [ ] Newsletter Logik implementieren
- [ ] Manuell Testen
- [ ] CHANGELOG entry

**Comment by mtnstar** [comment]
@sykesonrocks dies ist ein weiteres follow up von #296

wie sieht es hier mit dem Newsletter aus? Gibt es hier keine AGBs oder Reglemente zum akzeptieren?

**Comment by mtnstar** [comment]
@daniel-illi Selbstregistrierung sieht soweit gut aus, leider funktioniert das mit dem Newsletter nicht wie beschrieben.
Wenn ich die Checkbox nicht auswähle, dann werde ich nicht automatisch unsubscribed vom Abo.

**Comment by daniel-illi** [comment]
Ich kann das reproduzieren:
* Alter wird nicht geprüft
* Newsletter Abmeldung funktioniert nicht in allen Konstellationen
