### ISSUE TITLE
EVENTS: Automatische Zuteilung

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#358]
Als Kursadmin möchte ich auf einem Kurs explizit definieren können, ob Anmeldungen automatisch zugeteilt werden.

# Tech-Spec

Auf dem Kurs werden zwei neue Attribute hinzugefügt, welche im Formular bearbeitet werden können.

- Minimale Teilnehmerzahl / minimum_participants (integer, nullable, direkt nach Maximale TN-Zahl)
- Automatische Zuteilung / automatic_assignment (boolean, not null, default false), Zusatztext: "Anmeldungen werden automatisch zugeteilt, sofern noch freie Plätze verfügbar sind." Erscheint nach "Priorisierung"

Das bestehende Label "Warteliste" wird umbenannt zu "Nationale Warteliste". Im Zusatztext wird ebenfalls "nationalen Warteliste" ergänzt.

Die Methode `Event::ParticipationsController#directly_assign_place?` wird angepasst. Anstelle der Überprüfung der `priorization` wird eine entsprechende Prüfung von `automatic_assignment` vorgenommen.

In der DB Migration wird für alle Events, welche das priorization Attribut verwenden und dieses auf false gesetzt haben, das Attribut automatic_assignment auf true gesetzt.

Falls minimale TN-Zahl ausgefüllt ist, erscheint auf der Show Seite in der rechten Spalte direkt unter "Anmeldungen" die Information "Minimale Teilnehmerzahl"

## Cevi Wagon

Im Cevi Wagon ist momentan das Feld `waiting_list` umbenannt als "Automatisch zugeteilt". Diese Umbenennung soll entfernt werden. Die überschriebene Methode `Cevi::Event::ParticipationsController#directly_assign_place_with_waiting_list?` wird entfernt. Eine Migration setzt `automatic_assignment` für alle Cevi Kurse, welche momentan das Flag `waiting_list` gesetzt haben. 

## PBS Wagon

Im PBS Wagon wird momentan nie automatisch zugeteilt. Die überschriebene Methode `PBS::Event::ParticipationsController#directly_assign_place_with_pbs_courses?` wird entfernt. Eine Migration setzt `automatic_assignment` für alle PBS Kurse auf false (macht quasi die obige Migration aus dem Core rückgängig). 

# ToDo

- [x] Migration erstellen
- [ ] Model/View/Controller anpassen
- [ ] Specs schreiben
- [ ] Mit angemessener Rolle "durchklicken"
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by ThomasEllenberger** [comment]
@nchiapol
Wir würden im Zuge dieses Tickets eure Customization vom letztem Jahr wieder Rückgängig machen und euch zurück auf den Core nehmen.
Dies hätte zur Folge dass ihr wieder zwei verschiedene Auswahlpunkte für "Automatisch Zugeteilt" und "Nationale Warteliste" hättet, anstatt dass dies in einem Punkt zusammengefasst ist. Dafür wärt ihr hier wieder kongruent mit dem Core und würdet keine Funktionalitäten einbüssen.
Gerne können wir das am Hackaton gleich besprechen.

@simfeld 
Die PBS setzt die Automatische Zuteilung aktuell immer auf false, ihr habt hier keine Einstellung dies zu ändern.
Ihr bekämt eine neue Einstellung "Automatische Zuteilung" welche defaultmässig auf deaktiviert ist, die ihr zukünftig aber nutzen könnt wenn ihr möchtet. Auch euch können wir dadurch einen Teil custom Code entfernen und ihr nähert euch ein bisschen dem Core an.
Gerne können wir das am Hackaton gleich besprechen.

@richardjubla
Euer Verhalten ist hier analog dem Core.
Entsprechend der Spezifikation würden eure Punkte umbenannt und ihr bekämt eine Anmeldeoption mehr.
Gerne können wir das am Hackaton gleich besprechen.

**Comment by nchiapol** [comment]
@ThomasEllenberger am Hackaton besprechen tönt super ;-)

**Comment by richardjubla** [comment]
Relevanz und Verbindung für Jubla Inkrement 2/24 https://github.com/hitobito/hitobito_jubla/issues/91

Kursadministration (Bereit für Kurssaison Herbst 2024): Die Automatische Zuteilung muss für Kurssaison Herbst 2024 bereit sein (ideal Release 3/24, maximal 4/24).

**Comment by ThomasEllenberger** [comment]
> Relevanz und Verbindung für Jubla Inkrement 2/24 [hitobito/hitobito_jubla#91](https://github.com/hitobito/hitobito_jubla/issues/91)
> 
> Kursadministration (Bereit für Kurssaison Herbst 2024): Die Automatische Zuteilung muss für Kurssaison Herbst 2024 bereit sein (ideal Release 3/24, maximal 4/24).

Dies ist aktuell in Umsetzung. Plan ist, dass dies mit dem Release 3/24 (02.07.2024) Released wird.

**Comment by tobiasstern** [comment]
Funktioniert meines Erachtens gut mit der automatischen Zuteilung und dem neuen TN-Status "Unbestätigt".

@codez Der Teil der Spezifikation mit der Warteliste bzw. Nationale Warteliste ist für mich nicht nachvollziehbar. Dies ist auf dem UI nicht ersichtlich. Die Besprechungen zu diesem Thema liegen leider zu weit zurück für mich. "Warteliste" ist in der Spezifikation von https://saccas.atlassian.net/browse/HIT-248 drin als Feld unter "Anmeldung". 

Ich denke tendenziell ist dieses Ticket erfüllt. Überlasse es jedoch @sykesonrocks abschliessend zu prüfen.

**Comment by codez** [comment]
Das Flag für die nationale Warteliste wurde für den SAC mit https://github.com/hitobito/hitobito_sac_cas/issues/370 entfernt.

**Comment by tobiasstern** [comment]
Ok dann hat sich das somit erledigt. Danke und -> closed

**Comment by richardjubla** [comment]
Die Jubla hat das Verhalten auf der Stag-Umgebung (Version 2.1.5) getestet und soweit keine Fehler oder Beanstandungen bemerkt.
