### ISSUE TITLE
EVENTS: Kurs Teilnahmestatus

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#369]
Folgende Status sind im SAC Wagon für die Kursteilnahmen möglich:

- Unbestätigt / `unconfirmed`
- Warteliste / `applied`
- Abgelehnt / `rejected`
- Bestätigt / `assigned`
- Aufgeboten / `summoned`
- Teilgenommen / `attended`
- Nicht erschienen / `absent`
- Abgemeldet / `cancelled`
- Annulliert / `annulled`

Folgende Transitionen sind via Buttons auf der Teilnahme möglich (siehe u.a. `EventParticipationYouthHelper`). Die meisten dieser Buttons existieren bereits, ausser "Aufbieten". Die "Von" Status sind potentiell anders:

- Zu Abgemeldet: Von Unbestätigt, Warteliste, Bestätigt, Aufgeboten
- Zu Abgelehnt: Von Unbestätigt, Warteliste
- Zu Aufgeboten: Von Bestätigt (nur wenn Kurs im Status "Bereit zur Durchführung")
- Zu Teilgenommen: Von Nicht erschienen (nur wenn Kurs abgeschlossen ist, bisheriges Verhalten)
- Zu Nicht erschienen: Von Bestätigt, Aufgeboten, Teilgenommen
- Zu Bestätigt: Von Unbestätigt, Warteliste, Nicht erschienen (nur wenn Kurs nicht abgeschlossen ist, bisheriges Verhalten)

Die Ability muss entsprechend angepasst werden, dass alle Statusänderungen möglich sind. 

Um Abgemeldet und Annuliert rückgängig zu machen, wird auf der Participation ein zusätzliches Attribut `previous_state` (string, nullable) geführt, welches bei Ändern des `state` auf `cancelled` oder `annulled` auf den vorigen `state` gesetzt wird. 

# ToDo

- [ ] Migration erstellen
- [ ] Model/View/Controller anpassen
- [ ] Specs schreiben/anpassen
- [ ] Mit angemessener Rolle "durchklicken"

**Comment by sykesonrocks** [comment]
@codez @tobiasstern ich sehe hier diverse Abweichungen zur eingereichten Spezifikation, siehe https://saccas.atlassian.net/browse/HIT-254.

- _Nicht erschienen_: ja, macht Sinn
- _Abgelehnt_: ja, könnte Sinn machen - Alternative: alle im Status _unbestätigt_ mit einem Kursstatus _Bereit zur Durchführung_ = Abgelehnt
-  _Zu Bestätigt: Von Nicht erschienen (nur wenn Kurs nicht abgeschlossen ist, bisheriges Verhalten)_: bin mir gerade unsicher, aber sollte es nicht auch möglich sein von _unbestätigt_, _Warteliste_
- In der Aufstellung fehlt mir noch _Zu annulliert_: wird vom System gesetzt, wenn der Kursstatus auf _Annulliert_ wechselt

**Comment by codez** [comment]
@sykesonrocks Danke für die Rückmeldungen. Die obigen Transitionen sind nicht alle möglichen, sondern nur die, welche explizit über Buttons gemacht werden können. Entsprechend:
- Abgelehnt: Ist bereits in hitobito vorhanden und wird unter [HIT-180](https://saccas.atlassian.net/browse/HIT-180) sogar gewünscht.
- Bestätigt: Von Unbestätigt und Warteliste erfolgt eigentlich über die Ansicht "Anmelden". Nehme das aber noch auf.
- Annuliert: Erfolgt automatisch wenn der Kursstatus geändert wird, nicht über Buttons.

**Comment by tobiasstern** [comment]
Zwischenstand des Testings nach Sprint 1:

- Die Mehrheit konnte erfolgreich getestet werden
- Siehe https://saccas.atlassian.net/wiki/spaces/RDIE/pages/4206919685/Testing+Kursanmeldestatus für Testergebnisse
- Das Abmelden vom Kurs aus Sicht TN konnte noch nicht getestet werden, vgl offenes issue #375 
- Das Rückgängig machen von Abmeldungen gibt es noch nicht, konnte nicht getestet werden
- Das Annullieren von Kursen gibt es noch nicht, konnte nicht getestet werden.

**Comment by tobiasstern** [comment]
Testergebnisse Update

Wenn ein TN im Status **Teilgenommen**, **Nicht erschienen** oder **Abgemeldet** ist, 

- ist auf der Anmeldung keine Aktion möglich 👍 
- ist auf dem Kurs noch der Abmelde-Button da 👎 


@amaierhofer kannst du das bitte beheben? Habe dies vorhin auch hier kommentiert: https://github.com/hitobito/hitobito_sac_cas/issues/375#issuecomment-2095401910

**Comment by tobiasstern** [comment]
Wurde behoben 👍 

Bei weiterem Testing ist mir aufgefallen, dass den Usern auf dem Kurs je nach Status falsche Banner angezeigt werden. Ich erstelle dafür aber ein separates Ticket, da es in diesem Ticket hier vor allem um die Aktionen ging.

-> closed (endlich 🙌 )

**Comment by codez** [comment]
Die Aufnahme eines TN in den Kurs, also die Änderung des Status von Warteliste (unconfirmed) auf Zugeteilt (assigned), muss immer über das Tab "Anmeldungen" erfolgen, da hierbei neben der Statusänderung diverse andere Aktionen ausgeführt werden. Ein simples ändern des Status würde all dies ausser Acht lassen und damit ein nicht nachvollziehbares Verhalten produzieren. Daher wurde dies in [!1601](https://github.com/hitobito/hitobito_sac_cas/pull/1601) entfernt.
