### ISSUE TITLE
EVENTS: Automatische Zuteilung von Anmeldungen

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#372]
Der `Course#default_participation_state` wird im SAC Wagon angepasst, falls der bisherige Return Value `applied` wäre: Falls das Flag `automatic_assignment` (#358) gesetzt ist, wird `applied` zurück gegeben, falls nicht `unconfirmed`. 

Somit sollte via ParticipationsController das folgende Verhalten erfolgen (entsprechende Tests erstellen):
- `automatic_assignment=true`, `places_available` => Status "Bestätigt"
- `automatic_assignment=true`, `no places_available` => Status "Warteliste"
- `automatic_assignment=false`, `places_available` => Status "Unbestätigt"
- `automatic_assignment=false`, `no places_available` => Status "Warteliste"

# ToDo

- [ ] Migration erstellen
- [ ] Model/View/Controller anpassen
- [ ] Specs schreiben/anpassen
- [ ] Mit angemessener Rolle "durchklicken"

**Comment by tobiasstern** [comment]
Erfolgreich getestet. -> closed
