### ISSUE TITLE
PEOPLE: Performance Optimierungen Filter top layer / gesamte DB

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#384]
Eine Personen-Suche durch einen Admin auf Top-Layer dauert zu lange und läuft in ein Time-Out. Mit diesem Ticket soll dieses Problem gelöst werden.

## Tech Spec
- Umsetzung im SAC Wagon
- Die Performance wird beeinträchtigt durch dass zuerst via einen komplexen Query die IDs aller Personen [in Memory geladen](https://github.com/hitobito/hitobito/blob/master/app/domain/search_strategies/base.rb#L69) werden, welche für die eingeloggte Person lesbar sind. Dies ist vermutlich so weil Sphinx kein SQL unterstützt und für die Filterung der Resultate nach Berechtigung eine Liste von IDs braucht. Bevor wir Sphinx ablösen können, wird dieser Schritt also immer nötig sein.
- Für den Root User dauert eine Suche ca. 5 - 10 Sekunden, was noch akzeptabel ist.
- Für den Root User wird bei der Berechnung der IDs der Datenbank-Query bedeutend [vereinfacht](https://github.com/hitobito/hitobito/blob/4176c39cf66e80f68062a1635b2182517638a20b/app/abilities/person_readables.rb#L54..L55).
- Beim SAC sollen daher Admins in PersonReadables wie root behandelt werden. Dies ist beim SAC okay, da die Datenhaltung und -verwaltung sehr zentralisiert verläuft, und keine Spender und keine `visible_from_above: false` existieren, welche vom Nationalverband nicht uneingeschränkt gelesen werden dürfen.
- Da dies nicht eine wirkliche langfristige "Lösung" ist (bei zunehmender Anzahl Personen in der DB wird die ID-Liste irgendwann das verfügbare Memory sprengen) und da sich mit Postgres eine Ablösung von Sphinx und bessere mögliche Lösung des Problems abzeichnet, wird dies für den Moment nur beim SAC umgesetzt.
- Betrifft Personen auf Toplayer mit Admin und ggf. auch Mitarbeiter\*in, Mitarbeiter\*in (lesend)

## TODO
- [x] Im SAC Wagon auf der Rolle ein neues class_attribute (z.B. `read_all_people`) definieren
- [x] Auf den Rollen `Group::Geschaeftsstelle::Mitarbeiter`, `Group::Geschaeftsstelle::MitarbeiterLesend` und `Group::Geschaeftsstelle::Admin` das neue class_attribute auf true setzen
- [x] In der PersonAbility im SAC Wagon Leserechte auf alle Personen vergeben, falls eine Rolle mit `read_all_people` vorhanden ist (sonst kann man später die Person suchen aber beim Klick drauf nicht anzeigen)
- [x] Im SAC Wagon die Methode `PersonReadables#accessible_people` überschreiben, mit folgender Logik:
  - [x] Falls die eingeloggte Person eine Rolle mit `read_all_people` hat, `return Person.only_public_data`
  - [x] Sonst, `return super` (damit das funktioniert muss der Patch im wagon.rb `.prepend`et werden, nicht `.include`t)
- [x] Lokal mit Produktions-Dump manuell testen ob es wirklich die erwünschten Performance Benefits bringt (am besten mit Sphinx falls möglich)
- [x] Tests sind etwas schwierig. Vielleicht könnten wir Tests schreiben die die generierten SQL Queries von `Person.accessible_by(PersonReadables.new(@user)).to_sql` schreiben? Dann testen wir zwar internals, aber ich sehe gerade keinen besseren Weg, und es wäre auch nicht das erste Mal dass wir etwas auf diese Art testen.
- [x] Nach Deployment Stefan informieren

**Comment by codez** [comment]
@carlobeltrame Das Ticket wurde von @sykesonrocks gutgeheissen und kann umgesetzt werden. Kannst du das weiter voran treiben?

**Comment by sykesonrocks** [comment]
Performance verhebt: Treffer werden in unter 1 Sekunde angezeigt. 

Zum Zeitpunkt des Tests hatte ich folgende Rollen:
- SAC/CAS / SAC Geschäftsstelle: Admin 
- SAC Testsektion / Funktionäre: Mitgliederverwaltung 
- SAC Arosa / Mitglieder: Mitglied (Stammsektion) (Einzel) (bis 31.12.2024) 
- SAC/CAS / SAC Ehrenmitglieder: Kontakt
