### ISSUE TITLE
OIDC: Layer group ID und Profilbild-URL in with_roles claim einbauen

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito_sac_cas#389]
Als Drittapplikation beim SAC
möchte ich beim OIDC Login gleich die Sektions-ID zu jeder Rolle der eingeloggten Person bekommen,
um Autorisierung aufgrund der Sektion ausführen zu können, ohne einen separaten API Call zu machen

Neu soll im with_roles Claim bei OAuth/OIDC zu jeder Rolle die layer_group_id mit ausgegeben werden.

# Tech-Spec

- Umsetzung im SAC Wagon
- Der with_roles Claim im Profile Endpoint (OAuth) wird im Core im [`Oauth::ProfilesController`](https://github.com/hitobito/hitobito/blob/master/app/controllers/oauth/profiles_controller.rb#L46..L57) zusammengestellt. Es gibt vermutlich noch keinen Wagon, der das schon mal erweitert hat.
- Die Daten im Userinfo Endpoint (OIDC) werden in einem [Initializer](https://github.com/hitobito/hitobito/blob/master/config/initializers/doorkeeper_openid_connect.rb#L69..L90) konfiguriert. Auch hier gibt es keinen Wagon, der das schon mal angepasst hat, aber für den `:nextcloud` Scope wurde schon ein Weg gefunden, die Scopes und Claims erst nach dem Laden der Wagons zusammenzustellen. Falls ein weitere Initializer im Wagon nicht funktioniert, wäre das noch ein Ausweg.
- Wenn wir schon dabei sind, auch noch gleich die Profile Picture URL einbauen (möglichst permanente S3 URL)

# ToDo

- [x] Ggf. im Core ermöglichen, dass man im Wagon [public_attrs_with_roles](https://github.com/hitobito/hitobito/blob/master/app/controllers/oauth/profiles_controller.rb#L46) erweitert
- [x] Im Wagon role.group.layer_group_id zu jeder Rolle in public_attrs_with_roles hinzufügen (für OAuth Profile-Endpoint)
- [x] Im Wagon den `with_roles` doorkeeper Claim (für OIDC Userinfo-Endpoint) so erweitern, dass bei jeder Rolle `layer_group_id: role.group.layer_group_id` dazugeschrieben wird
- [x] Tests für Profil-Endpoint schreiben ([Beispiel im Core](https://github.com/hitobito/hitobito/blob/master/spec/requests/oauth_profile_spec.rb))
- [x] Tests für Userinfo-Endpoint schreiben ([Beispiel im Core](https://github.com/hitobito/hitobito/blob/master/spec/controllers/oauth/userinfo_controller_spec.rb))
- [x] Permanente Profilbild-URL des Users in beiden Endpoints einbauen
- [x] Mit angemessener Rolle "durchklicken" bzw. mit HTTP Client und oauthdebugger.com / oidcdebugger.com manuell durchtesten
- [x] Payload-Beispiele für Profile-Endpoint und Userinfo-Endpoint im SAC Wagon dokumentieren ([Beispiel im Core](https://github.com/hitobito/hitobito/blob/master/doc/development/08_oauth.md), [Beispiel für Wagon-Doku](https://github.com/hitobito/hitobito_sac_cas/blob/master/doc/import.md))
- [x] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen
- [ ] Daniel Menet und Stefan Sykes informieren
