### ISSUE TITLE
MAILING_LISTS: Newsletter Abo persistieren/read-only machen

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#413]
Der Standard Newsletter "SAC/CAS Newsletter" wird im Selbstregistrierungsprozess referenziert (An-/Abmeldung zum Newsletter bei Neuanmeldungen). Dazu ist die `id` der entsprechenden `MailingList` auf der Gruppe `Group::SacCas` als "mounted_attr" hinterlegt.

Es muss sichergestellt werden, dass die Konfiguration nicht versehentlich verändert werden kann. Dafür soll der Newsletter sowie die Konfiguration auf der `SacCas` Gruppe read-only sein.

Ausserdem soll der Newsletter und die Konfiguration auf der `SacCas` Gruppe mit  den seeds erstellt werden damit wir auf allen Umgebungen Prod/Int/Test/Dev eine konsistente, funktionierende Konfiguration haben.

## Todo

- [x] MailingList setup des "SAC/CAS Newsletter" in seeds integrieren inkl Konfiguration der Abonnenten
- [x] `Group::SacCas#sac_newsletter_mailing_list_id in seeds integrieren (referenziert die "SAC/CAS Newsletter" MailingList)
- [x] MailingList "SAC/CAS Newsletter" read-only machen
- [x] das `Group::SacCas#sac_newsletter_mailing_list_id` mounted_attr read-only machen
