### ISSUE TITLE
ETIKETTEN: Land immer drucken

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito_sac_cas#426]
Als Person beim SAC welche Etiketten exportieren muss
möchte ich die aufgedruckten Informationen leicht angepasst haben,
um den bisherigen Kommunikations-Ansprüchen des SAC gerecht zu werden.

Neu soll auf den exportierten Etiketten **immer** das Land aufgedruckt werden, bzw. einfach die Schweiz falls kein Land gesetzt ist. ~~Das Land soll in der Korrespondenzsprache der adressierten Person gedruckt sein.~~

# Mockup

**Mockup ist veraltet, das Land darf überall in der gleichen Sprache stehen, so wie es im hitobito Core bereits ist.**
![Screenshot 2024-03-26 at 11-15-25 people_1 pdf](https://github.com/hitobito/hitobito_sac_cas/assets/7566995/dd47fa60-2b5c-4cf1-847d-6f6713f303f8)

# Tech-Spec

- Umsetzung im SAC Wagon
- ~~Das Land soll in der Korrespondenzsprache der adressierten Person gedruckt sein. Das heisst, dass auf demselben Etiketten-PDF bei gewissen Personen "Schweiz" und bei gewissen anderen "Suisse" oder "Svizzera" stehen kann.~~
- ~~Es ist denkbar dass diese Übersetzung später auch noch für andere Etiketten-Anpassungen des SAC nötig ist, daher nicht nur minimalistisch das Land übersetzen, sondern gleich einen Weg schaffen wie man die Sprache für die gesamte Etiketten-Adress-Logik (oder falls einfach möglich auch für Briefe und Rechnungen) verwenden kann.~~

# ToDo

- [x] Im SAC Wagon [`Contactable#ignored_country?`](https://github.com/hitobito/hitobito/blob/master/app/models/concerns/contactable.rb#L46) überschreiben und immer `true` zurückgeben
- [x] Falls das nicht reicht, um bei Personen ohne Land "Schweiz" auszugeben, Logik der Adressetiketten vom Core überschreiben
- [x] Specs schreiben, auch für den Fall dass kein Land auf der Person gespeichert ist und trotzdem Schweiz angezeigt wird.
- [x] Mit angemessener Rolle "durchklicken"
- [x] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by sykesonrocks** [comment]
@carlobeltrame Das Ticket muss überarbeitet werden.

Wie in meiner E-Mail vom 15. März 2024 10:00 beschrieben gelten folgende Punkte:

### In Scope
- Etikettenerweiterung um Adresszusatz
- Etikettenerweiterung um Postfach 
- Etikettenerweiterung um Land 

### Nicht in Scope
- Etikettenerweiterung um Anrede
- Umstrukturierung der Anschrift bei Familienmitgliedern (beim Zusammenfassen von Haushalten)
- Mehrsprachigkeit (aktuell werden die Etiketten immer auf Deutsch ausgegeben– unabhängig von der Korrespondenzsprache des Mitglieds oder der festgelegten Sektionssprache, betroffen sind Bindewörter sowie Orts- und Landbezeichnungen)

**Comment by sykesonrocks** [comment]
@carlobeltrame ein Detail: im Screenshot sind die Landbezeichnungen nicht immer deutsch. Ich sehe aber, dass du diese Anforderung in der Spez durchgestrichen hast. Somit OK.

**Comment by carlobeltrame** [comment]
Ticket wurde überarbeitet.
Adresszusatz und Postfach würden dieses Ticket blockieren bis hitobito/hitobito#2226 umgesetzt ist, und vermutlich wird dies sowieso im Rahmen von hitobito/hitobito#2226 bereits im Core umgesetzt.

Mehrsprachigkeit habe ich entfernt, aber dies bietet insgesamt kaum Einsparungen, da wir die Mehrsprachigkeit der Landesbezeichnungen für die Bulletinliste in #427 trotzdem implementieren müssen.

**Comment by sykesonrocks** [comment]
@carlobeltrame ich habe heute kurz vor 16:30 den Etiketten-Export für https://sac-cas.puzzle.ch/de/groups/1237/people gestartet. Seit 30 Minuten sieht es gleich aus:
![image](https://github.com/hitobito/hitobito_sac_cas/assets/132900428/1d685ae7-7c0a-4dea-942a-cb53fdfd3c52)

Hat sich der Prozess "aufgehängt"?

**Comment by carlobeltrame** [comment]
@sykesonrocks 
> Hat sich der Prozess "aufgehängt"?

Ich habe das angeschaut und es ist ein Bug der nichts mit diesem Ticket zu tun hat. In den Mitgliedern beim SAC Lägern hat es eine oder mehrere Personen welche Spezial-Zeichen im Namen oder in der Adresse haben, welche nicht mit den Schriftarten gerendert werden können die von Haus aus im PDF-Format drin sind. Damit das funktioniert müssen wir explizit eine vollwertige Schriftart in alle PDFs einbauen. Dies ist aber ein separates Thema vom Land auf den Etiketten.

Könntest du die Funktionalität dieses Tickets in einer anderen Personenliste (z.B. SAC Lägern Funktionäre) testen, und ggf. noch ein Bugticket für den PDF-Export von nichteuropäischen Zeichen erfassen?

**Comment by sykesonrocks** [comment]
@carlobeltrame @tobiasstern Wenn ich unter https://sac-cas.puzzle.ch/de/groups/886/people?returning=true die Etiketten für die 4 Personen exportiere (via Export-Etiketten-SAC Adressetiketten 3-bahnig), wird der blaue Balken zwar oben dargestellt ("Die Downloads werden vorbereitet, bitte warten.") und ich erhalte danach die Meldung: "Export wird im Hintergrund gestartet und nach Fertigstellung heruntergeladen.". Es passiert aber danach nichts mehr. In meinem Download-Ordner geprüft, finde dort aber keine neu heruntergeladenen Dateien.

**Comment by carlobeltrame** [comment]
@sykesonrocks ich kann das Problem nicht reproduzieren. Bei mir funktioniert es einwandfrei, egal ob ich als Puzzle, als Carlo Beltrame oder als Stefan Sykes (Test) exportiere, und egal ob Haushalte zusammenfassen oder nicht. Wenn du es konsistent reproduzieren kannst, müssten wir mal kurz zusammensitzen und ich schaue in die Logs was genau passiert wenn es bei dir nicht geht.
