### ISSUE TITLE
ABOS: Empfängerliste exportieren

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito_sac_cas#427]
Als Person die ein Sektionsbulletin versendet
möchte ich die dazugehörigen Empfänger aus einem Abo in einem möglichst ähnlichen Format wie bisher aus Navision exportieren können,
um weniger Aufwand bei der Umstellung zu haben.

Neu soll der Navision Excel-Export Bulletinliste auf Abos unter dem Namen "Empfängerliste Einzelpersonen" nachgebaut werden. Zusätzlich wird in einem separaten Issue noch eine weitere Variante "Empfängerliste Haushalte" gebaut.

# Mockup

![empfängerliste-mockup](https://github.com/hitobito/hitobito_sac_cas/assets/7566995/0acd31c4-60f8-4fc1-843c-73ab40780c59)

# Tech-Spec

- Umsetzung im SAC Wagon
- Custom tabular Export
- Haushalte werden in diesem Export nicht zusammengefasst
- Beispiel-Export in PDF-Form ist [hier](https://saccas.atlassian.net/wiki/spaces/RDIE/pages/3883040775/Datenmigrationskonzept) unter "Sektion Bulletinliste (SAC Lägern)" verfügbar (oder @carlobeltrame fragen falls kein Zugriff)
- Spalten gemäss folgender Liste. Spaltentitel genau so wie hier fett aufgelistet:
  - **Navision-Nr.**
    Inhalt: Personen-ID
  - **Anrede**
    Inhalt: leer lassen, müsste ein Legacy-Feld sein das nicht mehr wirklich verwendet wird
  - **Vorname**
  - **Name**
  - **Adresszusatz**
    Vorerst leer lassen, wird in oder nach hitobito/hitobito#2226 ergänzt
  - **Strasse**
  - **Postfach**
    Vorerst leer lassen, wird in oder nach hitobito/hitobito#2226 ergänzt
  - **PLZ**
  - **Ort**
  - **Land**
    Darf auch leer sein wenn Schweiz oder wenn wir keine Information gespeichert haben.
  - **Sektion**
    Inhalt: Navision ID des Layers das am nächsten am exportierten Abo / der exportierten Personenliste ist. Also der Wert ist bei allen Zeilen gleich.
  - **Anzahl**
    Inhalt: Immer den Wert `0` ausgeben
  - **E-Mail**
    Inhalt: Haupt-E-Mail

# ToDo

- [ ] ~Domain-Klasse [`Countries#label`](https://github.com/hitobito/hitobito/blob/master/app/domain/countries.rb#L20) so erweitern dass man eine Sprache von aussen reingeben kann, die dann I18n.locale.to_s überschreibt~
- [ ] ~[`Contactable#country_label`](https://github.com/hitobito/hitobito/blob/master/app/models/concerns/contactable.rb#L38) überschreiben und die Sprache des Contactables (mit Fallback auf `I18n.locale` falls auf dem Contactable keine Sprach-Spalte existiert wie es z.B. bei Gruppen der Fall ist) mitgeben~
- [x] Im SAC Wagon neuen tabular Export "recipient_list" anlegen
- [x] Spalten gemäss Tech Spec
- [x] Export auf Abos anbieten, und optional auch auf Personenlisten (ausser es stellt sich als zu kompliziert heraus, von beliebigen Personenlisten die `layer_group` zu berechnen)
- [x] Manuell mit Beispiel-Export vergleichen, um Kompatibilität zu verifizieren
- [x] Specs schreiben für Export
- [x] Specs schreiben für überschriebene Methoden
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen
