### ISSUE TITLE
EVENTS: JSON API Kursarten

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#430]
Als API User 
möchte ich die verschiedenen Kursarten abfragen,
um beispielsweise entsprechende Filter zu bauen

Neu soll ein API Endpoint `event_kinds` zur Verfügung stehen, wo Kursarten ausgelesen werden können.

# Tech-Spec

Es reichen die lesenden Actions Index und Show. Folgende Attribute werden im JSON ausgegeben:

* label
* short_name
* general_information
* application_conditions
* minimum_age
* created_at
* updated_at

Aus dem SAC Wagon:

* maximum_participants
* minimum_participants 
* training_days
* season (enum key)
* accommodation (enum key)

Die folgenden Assoziationen  können ebenfalls included werden. Dabei werden die entsprechenden Attribute ausgegeben.

`event_kind_category` :

* label

`event_level`:

* label
* code
* difficulty

Es werden nur Einträge geliefert, welche kein `deleted_at` gesetzt haben.

Der `event_kind` und die zugehörige `event_kind_category` und `event_level` sollen zusätzlich bei EventRessource ebenfalls optional included werden können.

# ToDo

- [ ] Domainklasse erstellen oder anpassen
- [ ] Model/View/Controller anpassen
- [ ] Specs schreiben
- [ ] Mit angemessener Rolle "durchklicken"
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by sykesonrocks** [comment]
Ich kann bestätigen, dass die oben aufgeführten Attribute in der Swagger UI ersichtlich sind. Weitere Tests habe ich nicht vorgenommen. Ich schliesse hiermit das Ticket.
