### ISSUE TITLE
ROLES: Personenliste ziehen von Mitgliedern die einen geplanten Austritt ausweisen

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito_sac_cas#454]
Als Person bei der Mitgliederverwaltung
möchte ich Personenlisten nach geplanten Austritten filtern können,
um alle Personen mit geplantem Austritt an einem bestimmten Datum aufzulisten.

Neu soll es bei den Personen-Filtern auch möglich sein, nach Rollen zu filtern die ein terminate_on Datum gesetzt haben.

# Mockup

![Screenshot 2024-04-04 at 16-33-08 hitobito - Personen filtern](https://github.com/hitobito/hitobito_sac_cas/assets/7566995/a5899d0b-4c4a-485c-ac71-39a5b1c62ff0)

# Tech-Spec

- Umsetzung im Core, aber nur wenn im Wagon (oder besser unter den auswählbaren Rollentypen) mindestens ein Rollentyp `terminatable` ist
- sinngebende Zielrichtung
- besondere/bekannte Bedingungen und Grenzfälle
- technische Einschränkungen
- Ein- und Ausgabeformate beschreiben
- Umsetzungsplan ergänzen oder anpassen

# ToDo

- [ ] Ticket fertig refinen
- [ ] Migration erstellen
- [ ] Domainklasse erstellen oder anpassen
- [ ] Model/View/Controller anpassen
- [ ] Neues Feature mit FeatureGate deaktivierbar machen
- [ ] Specs schreiben
- [ ] Kunde wegen Übersetzungen informieren
- [ ] Mit angemessener Rolle "durchklicken"
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen
