### ISSUE TITLE
INVOICES: Parameter Sektion

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#472]
Als Sektionsadmin möchte ich die Parameter für die Mitgliedsrechnungen verwalten können.

Siehe auch #471. Diese Parameter sind versioniert und können pro Kalendarjahr wechseln, müssen aber nicht.

# Model

Der Einfachheit halber halten wir das Model flach in einer Tabelle `section_membership_configs`:

- Sektion / `group_id` (integer, not null, belongs_to, index)
- Gültig ab / `valid_from` (integer, not null, 4 digits, unique über group_id)

Folgende Attribute sind alle Frankenbeträge und entsprechend decimal, 2 Nachkommastellen, not null:
- Sektionsbeitrag, Einzelmitgliedschaft / `section_fee_adult`
- Sektionsbeitrag, Familienmitgliedschaft / `section_fee_family`
- Sektionsbeitrag, Jugendmitgliedschaft / `section_fee_youth`
- Eintrittsgebühren, Einzelmitgliedschaft / `entry_fee_adult`
- Eintrittsgebühren, Familienmitgliedschaft / `entry_fee_family`
- Eintrittsgebühren, Jugendmitgliedschaft / `entry_fee_youth`
- ~~Abogebühr Sektionsbulletin, Einzelmitgliedschaft / `bulletin_fee_adult`~~
- ~~Abogebühr Sektionsbulletin, Familienmitgliedschaft / `bulletin_fee_family`~~
- ~~Abogebühr Sektionsbulletin, Jugendmitgliedschaft / `bulletin_fee_youth`~~

- Porto Ausland Sektionsbulletin / `bulletin_postage_abroad`

Reduktionsparameter: 
- Zentralverbandsgebührenerlass für Ehrenmitglieder / `sac_fee_exemption_for_honorary_members` (bool, not null, default false)
- Sektionsgebührenerlass für Ehrenmitglieder / `section_fee_exemption_for_honorary_members` (bool, not null, default false)
- Zentralverbandsgebührenerlass für Begünstigte / `sac_fee_exemption_for_benefited_members` (bool, not null, default false)
- Sektionsgebührenerlass für Begünstigte / `section_fee_exemption_for_benefited_members` (bool, not null, default false)

- Reduktionsbetrag Mitgliedsjahre/Alter / `reduction_amount`
- Reduktion ab Mitgliedsjahren / `reduction_required_membership_years` (integer, nullable)
- Reduktion ab Altersjahren / `reduction_required_age` (integer, nullable)

# View

Der Titel der Seite ist immer "Parameter für Mitgliedschaftsrechnungen". Die Seite wird als Sheet unterhalb der Gruppe angezeigt, so dass der Gruppenname weiterhin ersichtlich ist.

## Navigation

Da die Parameter nur selten bearbeitet werden müssen, erfolgt die Navigation über das Dropdown des "Bearbeiten" Buttons einer Sektion. Dort gibt es einen neuen Eintrag "Parameter Mitgliedsrechnungen".

## Formular

Die Felder sollen analog dem Mockup aus #471 angeordnet werden. Die Reduktionsparameter erscheinen in der oben definierten Reihenfolge.

## Auswahl Jahr

Die Auswahl des Jahres erfolgt analog zu #471.

# ToDo

- [ ] Migration erstellen
- [ ] Model/View/Controller anpassen
- [ ] Specs schreiben
- [ ] Run annotate for new models
- [ ] Mit angemessener Rolle "durchklicken"

**Comment by mtnstar** [comment]
@codez wer ist denn der Sektionsadmin?
eine Person mit der Rolle Mitgliederverwaltung? Oder Administration?
oder einfach jemand der Schreibrechte auf dem Layer hat?

**Comment by codez** [comment]
Jemand der die Layer Gruppe bearbeiten darf. Das kann wer direkt aus dem Layer sein oder darüber.

**Comment by mtnstar** [comment]
@codez sehe ich es richtig das man diese Parameter auch auf einer Ortsgruppe setzen kann?

**Comment by codez** [comment]
@mtnstar @sykesonrocks Da kenne ich die SAC Strukturen zu wenig. Von der Gruppenstruktur in hitobito würde es gut gehen. Haben Ortsgruppen auch eigene Gebühren? Zählen in diesem Fall nur diese, und nicht diejenigen der übergeordneten Sektion? 

So wie inzwischen der Rechnungscode (#502) gebaut ist, müssten Ortsgruppen eigentlich eigene Parameter haben. Ansonsten bräuchte es da noch Anpassungen, das Ortsgruppenmitglieder die Sektionsgebühren verrechnet erhalten.

**Comment by mtnstar** [comment]
die Sektion Blüemlisalp hat ja die Ortsgruppe Ausserberg, dort sind laut SAC Webseite die gleichen Preise für die Mitgliedschaft.
Ich weiss aber nicht wie das andere Sektionen handhaben.
@sykesonrocks was meinst du?
man könnte beim Auslesen der Parameter auf einer Ortsgruppe es so implementieren das wenn keine Parameter direkt auf der Ortsgruppe vorhanden sind das diese der Parent Sektion übernommen werden

**Comment by sykesonrocks** [comment]
@mtnstar Die Preise auf Stufe Ortsgruppe müssen immer erfasst sein - dürfen nie leer sein. Diese gilt es als eigenständige Sektionen zu betrachten / zu fakturieren. Ortsgruppen derselben Sektion können unterschiedliche Preise ausweisen (ist meist der Fall, siehe z.B. CAS Diablerets, SAC Pilatus).
