### ISSUE TITLE
EVENTS: Sichtbarkeit von Anhängen

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#486]
Als Eventadmin möchte ich im hitobito Core für einzelne Anhänge die Sichtbarkeit konfigurieren.

Neu soll bei jedem Anhang die Sichbarkeit über ein Icon ausgewählt werden können. Diese werden für User angezeigt, welche Anhänge erstellen und löschen können. Es gibt folgende Optionen:

* Leitungsteam / team
* Leitungsteam und Teilnehmende / participants
* Öffentlich / global

Das `Event::Attachment` Model erhält eine neue Spalte `visibility` (string enum, team, participants, global, default nil).

In der DB Migration sollen alle bestehenden Attachments auf die visibility 'global' gestellt werden.

Beim Rendern eines Attachments wird entsprechend geprüft, ob die entsprechenden Berechtigungen/Rollen vorhanden sind:

* nil: nur mit `can?(:update, event)` Berechtigung
* team: nur mit einer Event Rolle mit `kind` leader oder helper
* participants: mit beliebiger Event Rolle
* global: alle

Wenn der Event bearbeitet werden kann, werden die folgenden Icons mit Tooltip hinter jedem Anhang angezeigt:
* user-graduate (team), Tooltip "Nur für Team sichtbar"
* users (participants), Tooltip "Für Team und Teilnehmende sichtbar"
* globe (global), Tooltip "Global sichtbar"

Das jeweils ausgewählte Icon wird in der Primary Color angezeigt, die anderen abgeschwächt / disabled, so dass klar ist, welche Option aktiv ist. Die Icons erscheinen vor dem Trash Icon, welches durch einen zusätzlichen Abstand von dieser Gruppe abgetrennt sein soll.

Beim Klicken auf ein Icon wird die Sichtbarkeit direkt persistiert. Entweder ändert sie auf einen anderen Wert oder, falls das aktive Icon angeklickt wird, wird die Sichtbarkeit auf `nil` gesetzt. Dabei ändern sich auch die Farben der betroffenen Icons

Der Hinweis bei Anlässen mit externen Anmeldungen wird angepasst auf "Global sichtbare Anhänge sind öffentlich, da der Anlass externe Anmeldungen erlaubt."

# ToDo

- [ ] Migration erstellen
- [ ] Model/View/Controller anpassen
- [ ] Specs schreiben
- [ ] Mit angemessener Rolle "durchklicken"
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by sykesonrocks** [comment]
Funktioniert, Upload limitiert auf Dateigröße 10 MB
