### ISSUE TITLE
PEOPLE: Selbstregistrierung Familie Rechnungsempfänger markieren

### ISSUE THREAD

**Issue by daniel-illi** [hitobito/hitobito_sac_cas#493]
Bei Familien soll nur die Hauptperson aka das Familienoberhaupt eine Rechnung erhalten, und nicht alle separat. → Wir nennen dies neu “Rechnungsempfänger*in”. Da die Familie beim Neueintritt als Familienmitgliedschaft entsteht, muss diese an der Stelle im System wie folgt bestimmt werden.

# Anforderungen

* Der Absender oder die Absenderin des Antrags “Mitglied werden” soll - sofern eine Familienmitgliedschaft abgeschlossen wurde - in Hitobito als Familienrechnungsempfänger*in registriert werden.
* Bei Familienmitgliedschaften gilt es den/die Familienrechnungsempfänger*in im Hitobito-Profil auszuweisen. Diese Information kann das Mitglied nicht bearbeiten. 

# Tech-Spec

* auf `Person` neue Spalte `family_main_person` vom Typ `boolean` definieren

* in `SelfRegistration::Sektion::MainPerson#person`das Attribut `family_main_person` auf `true` setzen

* in `SacCas::Role::MitgliedFamilyValidations` validieren, dass **genau eine** der erwachsenen Personen das Attribut `family_main_person` auf `true` hat
  (Code für nachschlagen der erwachsenen Familienmitglieder extrahieren aus `SacCas::Role::MitgliedFamilyValidations#adult_household_people_mitglieder_count`)

* Das Attribut `Person#family_main_person` auf der Person show view anzeigen
    - nur bei Familienmitgliedern (Personen mit `family_id`
    - Label "Familienrechnungsempfänger*in"
    - Value "Ja" wenn `family_main_person == true`, andernfalls Person verlinken welche `family_main_person == true` hat.

* In `Import::Sektion::Membership#import!`
    - Validierung `adult_household_people_mitglieder_count` ignorieren durch setzen des Validierungskontextes 'import' auf `#valid?` und `#save`
    - auf der Person `family_main_person == true` falls in `row[:beitragskategorie] == "FAMILIE"`. 

# ToDo

- [x] `Person#family_main_person` definieren
- [x] Validierung schreiben
- [x] Selbstregistrierung Domainklasse anpassen
- [x] Person show view anpassen
- [x] Specs schreiben
- [x] Mit angemessener Rolle "durchklicken"

**Comment by codez** [comment]
@daniel-illi `mounted_attr` gibt es auf Person nicht. Hier macht wohl ein reguläres Attribut direkt in der people Tabelle mehr Sinn, oder nicht?

**Comment by mtnstar** [comment]
ggf. das Attribut `sac_family_main_person` bezeichnen?
ich dieses Pattern da es sofort klar ist das es sich um eine Wagon-Erweiterung handelt

**Comment by tobiasstern** [comment]
Erfolgreich getestet -> closed
