### ISSUE TITLE
PEOPLE: Filter Qualifikationen - Abgelaufene Qualifikationen

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#500]
Als Gruppenadmin möchte ich Personen mit abgelaufenen Qualifikationen filtern.

Neu soll auf dem Personenfilter im Panel Qualifikationen unterhalb "Keine gültigen Qualifikationen" eine zusätzliche Option "Abgelaufene, aber nicht gültige oder reaktivierbare Qualifikationen" (only_expired) zur Verfügung stehen. Für diese Option erscheinent das Eingabefeld "Stichdatum"

Es werden alle Personen angezeigt, welche über abgelaufene, aber keine aktiven, keine reaktivierbaren Qualifikation der ausgewählten Qualifikationsarten verfügten.

Die Option "Keine gültige, aber reaktivierbare Qualifikationen" wird umbenannt zu "Reaktivierbare, aber nicht gültige Qualifikationen".

# ToDo

- [ ] Domainklasse anpassen
- [ ] View/Controller anpassen
- [ ] Specs schreiben
- [ ] Mit angemessener Rolle "durchklicken"
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen
