### ISSUE TITLE
PEOPLE: Zusätzliche Bemerkungsfelder

### ISSUE THREAD

**Issue by daniel-illi** [hitobito/hitobito_sac_cas#511]
* Auf der Person soll es 6 neue Bemerkungsfelder geben: **"Bemerkung Sektion 1” … "Bemerkung Sektion 5”** sowie **"Bemerkung Geschäftsstelle"** mit max. 255 Zeichen, ohne Zeilenumbrüche
* Die Bemerkungsfelder sollen **nicht** mit Papertrail protokolliert werden
* Das Feld "Bemerkung Geschäftsstelle" darf **nur von Personen mit Rolle in der Gruppe "Geschäftsstelle"** sichtbar und editierbar sein
* Die Felder "Bemerkung Sektion 1” … "Bemerkung Sektion 5” dürfen n**ur für Personen mit Rolle in der "Funktionäre" Gruppe der Sektion** sowie für **Personen mit Rolle in der Gruppe "Geschäftsstelle"** sichtbar und editierbar sein

![image](https://github.com/hitobito/hitobito_sac_cas/assets/636849/dcf98c84-df77-4729-a44c-8dd42cfe9872)

# Tech-Spec

* Auf der `peoples` table neue Felder `remark_geschaeftsstelle`, `remark_sektion_1`, `remark_sektion_2` ... `remark_sektion_6` mit type `string` und `length: 255`
* Im `Person` model validieren, dass die Bemerkungsfelder keine line breaks enthalten:  
  ```ruby
  validates :remark_*, format: {with: /\A[^\n\r]*\z/}
  ```
* Zum Unterbinden des Papertrail loggings die Attribute den `Person::INTERNAL_ATTRS` hinzufügen (app/models/sac_cas/person.rb:13)
* `AllAbility` implementieren
  * `on(:all) { permission(:any).may(:manage_remark_geschaeftsstelle).if_sac_mitarbeiter }`
    Bedingung: user hat eine dieser Rollen:
    + `Group::Geschaeftsstelle::Mitarbeiter` 
    + `Group::Geschaeftsstelle::Admin`
  * `on(:all) { permission(:any).may(:manage_remarks_sektion).if_sektion_mitarbeiter }` 
    Bedingung: user hat eine dieser Rollen: 
    + `Group::SektionsFunktionaere::Praesidium` 
    + `Group::SektionsFunktionaere::Mitgliederverwaltung` 
    + `Group::SektionsFunktionaere::Administration`
* neuen Tab "Bemerkungen" auf dem Person Sheet
  * neuen Controller `Person::RemarksController`
    * param `id` verwenden für Attributname
    * action `#index`: listet alle Bemerkungen für welche der user berechtigt ist.
      + `remark_geschaeftsstelle` mit `can?(:manage_remark_geschaeftsstelle, entry)`
      + `remark_sektion_*` mit `can?(:manage_remarks_sektion, entry)`
    * action `#edit`, `#update`: für Attribut `param[:id]` form rendern resp. Attribut updaten
      Authorisierung: `param[:id] == 'remark_geschaeftsstelle' ? authorize!(:manage_remark_geschaeftsstelle, entry) : authorize!(:manage_remarks_sektion, entry)`
    * Route:

      ```ruby
        resources :groups, only: [] do
          resources :people, only: [] do
            resources :remarks, module: 'person', only: %i[index edit update] 
          end
        end
      ```

  * Remarks Views
    * Index view listet alle Bemerkungen auf, je mit edit icon für inline edit
      * jede Bemerkung in einem TurboFrame.
      * Artikel zu inline edit mit turbo: <https://dev.to/software_writer/inline-edits-using-turbo-frames-1l3a>
    * Edit view mit textfield zum Bearbeiten der Bemerkung mit `maxlength = 255`
> [!WARNING]
> Im mockup ist das form mit text areas dargestellt. Es sollen aber explizit text fields verwendet werden.
  * auf dem Person Sheet ein neues tab "Bemerkungen"
    * neues Sheet `Sheet::Person::Remarks`
    * Core `Sheet::Person` prependen mit neuem Modul `SacCas::Sheet::Person` und da das sheet `Sheet::Person::Remarks` als weiteres tab hinzufügen.
      (dazu reicht ein plain old ruby module, es muss kein `ActiveSupport::Concern` sein)
      Conditional: `if: :manage_remarks_sektion`

# ToDo

* [x] Migration erstellen
* [x] Validierungen auf `Person#remark_*`
* [x] Paper trail logging der remarks attrs von `Person` unterbinden
* [x] Permissions auf `PersonAbility` konfigurieren
* [x] ~Stimulus controller in `core` erstellen~
* [x] Tab "Bemerkungen" auf Person sheet erstellen
* [x] Controller und Views erstellen
* [x] ~Attribut `additional_information` ausblenden in views/TableDisplay/tabular exports~
* [x] Specs schreiben
* [x] Mit angemessener Rolle "durchklicken"

**Comment by tobiasstern** [comment]
@daniel-illi Punkt 2 der Spez "Das bestehende Bemerkungsfeld "Zusätzliche Angaben" soll entfernt werden (Frontend, API und Exporte)" ist obsolet mit #519 , richtig?

**Comment by tobiasstern** [comment]
Hi @hunchr Wenn man Text mit mehr als 255 Zeichen speichern will, dann passiert nichts und es ist nicht ersichtlich, wieso. Kannst du bitte eine Fehlermeldung einbauen?

**Comment by hunchr** [comment]
> Hi @hunchr Wenn man Text mit mehr als 255 Zeichen speichern will, dann passiert nichts und es ist nicht ersichtlich, wieso. Kannst du bitte eine Fehlermeldung einbauen?

Ich habe das Feld jetzt auf 255 Zeichen limitiert, damit man das Limit gar nicht erst überschreiten kann. Wenn das nicht passt, kann ich stattdessen auch eine Fehlermeldung einbauen. Was ist dir lieber?

**Comment by tobiasstern** [comment]
Ja passt so, danke.

**Comment by tobiasstern** [comment]
Mir ist leider verspätet hier noch ein Fehler aufgefallen: MA der Geschäftsstelle können die Bemerkungen S1- S5 nicht sehen, sollen sie aber gemäss Spez können. Ich getestet, indem ich ein Mitglieder der GS imitiere und dann ein Userprofile aufrufe.
