### ISSUE TITLE
PEOPLE: Bemerkungsfelder in TableDisplay

### ISSUE THREAD

**Issue by daniel-illi** [hitobito/hitobito_sac_cas#515]
~blocked by #511~

Mit #511 werden auf Person 6 neue Bemerkungsfelder hinzugefügt: "Bemerkung Sektion 1” … "Bemerkung Sektion 5” sowie "Bemerkung Geschäftsstelle"
Diese Felder sollen in den Personenlisten verfügbar gemacht werden.

* Die Felder "Bemerkung Sektion 1” … "Bemerkung Sektion 5” dürfen nur sichtbar sein, wenn der user die Berechtigung `:manage_national_office_remark` auf der Person hat.
* Die Felder "Bemerkung Geschäftsstelle" dürfen nur sichtbar sein, wenn der user die Berechtigung `:manage_section_remarks` auf der Person hat.

# Tech-Spec

* in `lib/hitobito_sac_cas/wagon.rb:169` Attribute registrieren mit `TableDisplay.register_column(Person, TableDisplays::ResolvingColumn, [...])`
* `TableDisplays::Resolver` erweitern, dass `::exclude?` nur false zurückgibt sofern der user berechtigt ist.
  Parameter von `exclude?` anpassen, dass statt `parent` das `template` übergeben wird und auf diesem Berechtigung mit `template.can?` prüfen für die remark Attribute

# ToDo

* [x] Attribute in `TableDisplay` registrieren
* [x] Attribute in `TableDisplays::Resolver excluden abhängig von Berechtigung
* [x] Specs schreiben
* [x] Mit angemessener Rolle "durchklicken"
