### ISSUE TITLE
PEOPLE: Bemerkungsfelder in API

### ISSUE THREAD

**Issue by daniel-illi** [hitobito/hitobito_sac_cas#516]
Mit #511 werden auf `Person` 6 neue Bemerkungsfelder hinzugefügt: **"Bemerkung Sektion 1” … "Bemerkung Sektion 5”** sowie **"Bemerkung Geschäftsstelle"**
Diese Felder sollen im JSON:API ebenfalls zurückgegeben werden.

* Die Werte der Felder **"Bemerkung Sektion 1” … "Bemerkung Sektion 5”** dürfen nur sichtbar sein, wenn der user die Berechtigung `:manage_remark_head_office` auf der Person hat.
* Das Werte der Felder **"Bemerkung Geschäftsstelle"** dürfen nur sichtbar sein, wenn der user die Berechtigung `:manage_remarks_sektion` auf der Person hat.

# Tech-Spec

* in `SacCas::PersonResource` neue Attribute definieren:
  ```ruby
    with_options(writable: false) do
      attribute :remark_head_office, readable: :can_read_remark_head_office?

      (1..5).each do |num|
        attribute "remark_sektion_#{num}", readable: :can_read_remarks_sektion?
      end
    end
  ```

* guard Methoden:

  ```ruby
    def can_read_remark_head_office?(person) = can?(:manage_remark_head_office, person)
    def can_read_remarks_sektion?(person) = can?(:manage_remarks_sektion, person)
  ```
  
* schema.json aktualisieren: `rails graphiti:schema:generate` und resultierendes `schema.json` einchecken

# ToDo

* [ ] Attribute in PersonResource einbauen
* [ ] schema.json aktualisieren und einchecken
* [ ] Specs schreiben
* [ ] Mit angemessener Rolle "durchklicken"

**Comment by daniel-illi** [comment]
duplicate of #518
