### ISSUE TITLE
PEOPLE: Person#additional_information Übersetzung anpassen

### ISSUE THREAD

**Issue by daniel-illi** [hitobito/hitobito_sac_cas#519]
Das Feld `Person#additional_information` soll mit dem Label “Bemerkungen (z.B. Beruf)” angezeigt werden.

# ToDo

* [x] Übersetzung von `Person#additional_information` anpassen
* [x] Specs anpassen wo nötig
* [x] Mit angemessener Rolle "durchklicken"

**Comment by openscript** [comment]
@daniel-illi folgende Fragen habe ich dazu:
- Die Übersetzung sollen im Wagon `config/locales/wagon.xy.yml` abgelegt werden?
- Macht es Sinn dafür ein Spec zu schreiben?

**Comment by daniel-illi** [comment]
@openscript ja genau die Übersetzungen sollen ins `config/locales/wagon.de.yml`.
Einen Test musst du nicht schreiben, nur kontrollieren ob nach der Anpassung Tests fehlschlagen und allenfalls diese flicken.
