### ISSUE TITLE
PEOPLE: Analoger Mitgliederausweis (PDF)

### ISSUE THREAD

**Issue by daniel-illi** [hitobito/hitobito_sac_cas#530]
Als SAC Mitglied
möchte ich meinen Mitgliederausweis als PDF herunterladen
damit ich ihn selber ausdrucken kann.

Als SAC Mitarbeiter
möchte ich für ein Mitglied seinen Mitgliederausweis als PDF herunterladen
um ihn auszudrucken und dem Mitglied zuzusenden.

Das PDF mit dem Mitgliederausweis soll der Sprache des users entsprechend mit `prawn` generiert werden. Dabei soll das PDF den sprachspezifische Vorlagen entsprechend gebaut werden:

* Anschrift positioniert für das Sichtfenster der SAC Briefumschläge
  * Vorname Nachname 
  * Strasse Nr.
  * PLZ Ort
  * Land
    * Land wird nur aufgedruckt, wenn es nicht die Schweiz ist. 
    * Land muss mehrsprachig DE, FR, IT ausgegeben werden.
* Ausweis Vorderseite
  * Titel
    * DE "Mitgliederausweis"
    * FR "Carte de membre"
    * IT "Tessera di socio"
  * SAC Logo - sprachspezifisch
  * Name `person.person_name`
  * Mitgliednummer
    * DE: "Mitglied: #{person.membership_number}"
    * FR: "Membre: #{person.membership_number}"
    * IT: "Membro: #{person.membership_number}"
  * QR Code mit Link zum Verifizieren der Mitgliedschaft
* Ausweis Rückseite
  * Notrufnummern, Notfallkontakt wie in Vorlage
  * Gegenrecht Logo
  * SAC Partner QR code - sprachspezifisch

Ein Beispieldokument sowie die sprachspezifischen Templates sind im nextcloud abgelegt: https://files.puzzle.ch/f/6265272
![image](https://github.com/hitobito/hitobito_sac_cas/assets/636849/f71c677a-3893-4b4b-9f8d-0bde43aeecbc)

Das Mitgliederausweis PDF soll auf dem Benutzerprofil generiert/heruntergeladen werden können. Dazu wird auf der person#show view ein entsprechender Button angezeigt (responsive):

* DE "Mitgliederausweis herunterladen"
* FR "Télécharger la carte de membre"
* IT "tbdScarica la tessera di socio"

![329987697-8c591d60-f23b-43fc-b683-87c6246c79de](https://github.com/hitobito/hitobito_sac_cas/assets/636849/65d14fe4-6c6f-4a16-abe8-14e71699464d)

mobile:
![329987887-c2551533-d26b-42e3-841f-fd116be97ff3](https://github.com/hitobito/hitobito_sac_cas/assets/636849/fed91b7e-e098-4420-baee-bb1bddcbffc3)

# Tech-Spec

- `Export::Pdf::Passes::Membership` anpassen entsprechend der Vorlage  
   Vorläufig Font Helvetica, size: 10 verwenden
- Sicherstellen, dass `People::MembershipController#show` mit der neuen Implementierung immer noch funktioniert
- Download button auf person#show view einbauen analog mockup  
  `= link_to t('.download'), membership_path(format: :pdf), target: :new`

# ToDo

- [x] `Export::Pdf::Passes::Membership` anpassen
- [x] person#show view anpassen (download button)
- [x] Specs schreiben
- [x] Mit angemessener Rolle "durchklicken"

**Comment by Largo** [comment]
Zu pruefen: 
- Die Masse des Ausweises müssen exakt sein 8,5 x 5.4 cm
- specs fehlgeschlagen?
- commits zusammenfassen

**Comment by Largo** [comment]
PDF wurde nach Vorlage umgesetzt. Warten auf Rückfrage wegen den Massen des Ausweises im PDF.

**Comment by Largo** [comment]
In Absprache mit @daniel-illi: Dieses Ticket wird abgeschlossen. Feature wird in neuem Ticket mit Schriftart und anderen Massen versehen.

Ready for Review.
