### ISSUE TITLE
PEOPLE: Digitaler Mitgliederausweis verify page

### ISSUE THREAD

**Issue by daniel-illi** [hitobito/hitobito_sac_cas#531]
blocked by hitobito/hitobito#2511

Als “Fotograf” resp. als Kontrolleur des digitalen Mitgliederausweises will ich Informationen zur SAC Mitgliedschaft erhalten, sodass ich die Gültigkeit der Mitgliedschaft überprüfen kann. 

Durch Fotografieren des QR-Code gelangt die prüfende Person auf die Verify Membership Seite, welche wie folgt spezifiziert wird. Ausgehend von der bereits implementierten Version.

![f39b238f-e2ce-4009-bd0c-9a37bd164855](https://github.com/hitobito/hitobito_sac_cas/assets/636849/8d2dbc43-e897-40f0-a3c3-21cab44884e6)

* Das Layout soll am mockup angelehnt sein, muss aber nicht pixelgenau übereinstimmen.  
  (Das mockup ist höher als ein mobile screen, es muss also gescrollt werden)

* Schrift:  
Fall möglich "Hind" (analog SAC-CAS App und Tourenportal) - https://fonts.google.com/specimen/Hind  
Ansonsten Standard Schrift wie in hitobito
> [!NOTE]
> Hind ist im SAC wagon bereits als default font hinterlegt und sollte somit automatisch verwendet werden.

* Sprache:   
lokale Sprache des Browsers der prüfenden Person.  
Wenn Browsersprache nicht DE, FR oder IT → DE angezeigt

* Attribute:

  * SAC-Logo:  oben rechts  
    mehrsprachig DE, FR, IT // wenn Browsersprache nicht DE, FR, IT → DE Logo anzeigen

    * DE: https://files.puzzle.ch/f/6265552
    * FR: https://files.puzzle.ch/f/6265553
    * IT: https://files.puzzle.ch/f/6265551

  * Profilbild des Mitglieds: **zentriert**

  * Vorname, Name des Mitglieds: **bold, zentriert**

  * Mitgliedernummer: **bold, zentriert**  
    * DE: "Mitglied: #{person.membership_number}"
    * FR: "Membre: #{person.membership_number}"
    * IT: "Membro: #{person.membership_number}"

  * Anzahl Mitgliedsjahre: **bold, zentriert**
    * DE: "Anzahl Mitgliedsjahre: #{person.membership_years}"
    * FR: "Années de socétariat: #{person.membership_years}"
    * IT: "Anni di societariato: #{person.membership_years}"

  * Gültigkeit der Mitgliedschaft: **bold, zentriert**  
    Datenbasis: Besitzt eine aktive Rolle Mitglied (Stammsektion) für das aktuelle Jahr

    * Mitgliedschaft gültig:

      * Randloser Rahmen mit abgerundeten Ecken in der Farbe (Farbcode grün: cmyk 50 | 0 | 100 | 0)

      * DE "{Icon Gutzeichen} Mitgliedschaft gültig"
      * FR "{Icon Gutzeichen} Affiliation valable"
      * IT "{Icon Gutzeichen} Societariato valido"

    * Mitgliedschaft ungültig
      * Randloser Rahmen mit abgerundeten Ecken in der Farbe (Farbcode rot: cmyk: 0 | 30 | 50 | 0)

      * DE "{Icon X} Mitgliedschaft ungültig"
      * FR "{Icon X} Affiliation non valable"
      * IT "{Icon X} Societariato non valido"

    * Auflistung Mitgliedschaftsrollen:  
      Datenbasis: alle aktiven Mitgliedschaftsrollen in Kombination mit Sektion  

      Ausgegeben wird die volle Rollenbezeichnung inkl. der dazugehörigen Sektion “Mitglied (Stammsektion) (Einzel) SAC Matterhorn”

        Übersetzungen:
        
        | Mitglied Stammsektion Einzel | Membre individuel·le section de base | Socio sezione di base singolo |
        | ----- | ----- | ----- |
        | Mitglied Stammsektion Familie | Membre famille section de base | Socio sezione di base famiglia |
        | Mitglied Stammsektion Jugend | Membre jeune section de base | Socio sezione di base giovane |
        | Mitglied Zusatzsektion Einzel | Membre individuel·le section supplémentaire | Socio sezione secondaria singolo |
        | Mitglied Zusatzsektion Familie | Membre famille section supplémentaire | Socio sezione secondaria famiglia |
        | Mitglied Zuatzsektion Jugend | Membre jeune section supplémentaire | Socio sezione secondaria giovane |

      Rolle jeweils auf 1er Zeile und auf 2er Zeile die Sektion (siehe Bild)

      Reihenfolge: Zuerst Stammsektion, dann Zusatzsektionen

      Stammsektion **bold, zentriert**
        * `person.roles.find_by(type: Group::SektionsMitglieder::Mitglied.sti_name)`

      Zusatzsektionen **normal, zentriert**
        * `person.roles.where(type: Group::SektionsMitglieder::MitgliedZusatzsektion.sti_name)`

      Vor und nach dem Bereich etwas grösseren Abstand halten.

    * Aktiver Tourenleiter: **WEGLASSEN, WIRD IN #533 SPEZIFIZIERT/IMPLEMENTIERT** 

    * Logo Gegenrecht: *1-sprachig*, **zentriert**  
      https://files.puzzle.ch/f/6265403

    * Werbung:
      SAC stellt ein JPG file zur Verfügung, welches im page footer angezeigt wird.  
      SAC braucht von uns eine Angabe, in welcher Auflösung das file sein soll.

      Das Bild soll mit der Partnerwebseite verlinkt werden:
      * DE: https://www.sac-cas.ch/de/der-sac/unsere-partner/
      * FR: https://www.sac-cas.ch/fr/der-sac/unsere-partner/
      * IT: https://www.sac-cas.ch/it/der-sac/unsere-partner/
      * wenn Browsersprache nicht DE, FR, IT → DE Link

      vorläufig soll ein Platzhalter Bild verwendet werden:  
      https://files.puzzle.ch/index.php/f/6266006

# Tech-Spec

- SAC Logo Bilder ablegen unter `app/assets/images/logo_de.svg`/`logo_fr.svg`/`logo_it.svg`
- Gegenrecht logo ablegen unter `app/assets/images/logo_gegenrecht.svg`
- Auf SacCas::Person für Profilbild `variant` definieren:
  ```ruby
  reflect_on_attachment(:picture).variant(:profile, resize_to_fill: [200, 200])
  ```
- file für Werbung `app/assets/images/sponsors_membership_verify.jpg` vorbereiten:  
  als Platzhalter das file https://files.puzzle.ch/index.php/f/6266006 verwenden
- view anpassen: `app/views/people/membership/verify/show.html.haml` aus core überschreiben
  - für Profilbild neu definierte variant `:profile` verwenden
  - Layout und Texte wie oben beschrieben

# ToDo

- [x] Profilbild variant definieren
- [x] View anpassen
- [x] Specs schreiben
- [x] Prüfen, dass tatsächlich der font `Hind` verwendet wird
- [ ] Kunde wegen Übersetzungen informieren
- [x] Mit angemessener Rolle "durchklicken"

**Comment by mtnstar** [comment]
@TheWalkingLeek 

![image](https://github.com/hitobito/hitobito_sac_cas/assets/655627/4cff9568-b737-498e-aa22-a5f1cba7cfd1)

bitte dieses grün verwenden und Schrift weiss (ggf. auch gleich im Core)
