### ISSUE TITLE
PEOPLE: Household management view SAC Anpassungen

### ISSUE THREAD

**Issue by daniel-illi** [hitobito/hitobito_sac_cas#550]
blocked by hitobito/hitobito#2616, #555
blocks hitobito/hitobito#2624

Mit hitobito/hitobito#2616 wurden die views zum Verwalten des Haushaltes im Core implementiert. Für diese braucht es im SAC wagon Anpassungen.

# Mockup

vergleiche auch die mockups des core features in hitobito/hitobito#2616

**Household aside auf Person show view**
![Screenshot from 2024-05-21 14-31-05](https://github.com/hitobito/hitobito_sac_cas/assets/636849/0703a69a-6dab-41bf-a969-4c41f9dc1045)

**Household edit view**
![Screenshot from 2024-05-21 16-36-07](https://github.com/hitobito/hitobito_sac_cas/assets/636849/61db3509-50f0-4ffd-a164-fc8186c51aff)

# Tech-Spec

* **Person show view**
  * "Haushalt" aside muss im SAC wagon "Familie" heissen
  * Im Familie aside soll es neben jeder erwachsenen Person ein Stern icon haben. Erwachsen heisst: `SacCas::Beitragskategorie::Calculator.new(person).adult?`
      * Person ist Familienrechnungsempfänger (`person.family_main_person`) -> ausgefülltes icon (`class="fas fa-star"`), Tooltip "Familienrechnungsempfänger"
      * Person ist NICHT Familienrechnungsempfänger -> outline icon (`class="far fa-star"`)
        - Person hat bestätigte Email UND `can?(:set_sac_family_main_person, person)`:  
          Tooltip `"Zum Familienrechnungsempfänger machen"`
          Icon clickbar, verlinken nach `group_person_family_main_person_path` mit method `PUT`
        - Person hat unbestätigte Email:  
          Icon ausgegraut  
          Tooltip `"Die Email Adresse ist nicht bestätigt, die Person kann daher nicht zum Familienrechnungsempfänger gemacht werden."`
        - Person hat bestätigte Email, aber `cannot?(:set_sac_family_main_person, person)`:  
          Icon ausgegraut  
          Tooltip `"Melde dich bei der Geschäftsstelle um den Familienrechnungsempfänger ändern zu lassen"`

* **Household edit view**
  * Titel "Haushalt verwalten" muss "Familie verwalten" heissen
  * Info zu Haushaltsadresse anpassen zu "Familienadresse", "Familienmitglieder"

# ToDo

- [x] Haushalt aside anpassen
- [x] Haushalt edit view anpassen
- [x] Specs schreiben
- [x] Mit angemessener Rolle "durchklicken"

**Comment by Largo** [comment]
@daniel-illi Ich und AMA haben das angeschaut und waren uns nicht sicher wie Household und Family genau zusammenhaengen sollen. Daher konnten wir es noch nicht mergen.

- Sollen im aside die icons nur bei family members angezeigt werden. Da die Mainperson momentan nur gesetzt werden, kann wenn person in einer Familie ist, vermute ich ja.
- Sollen im aside nur familienmitglieder angezeigt werden? Vermutlich ja, aber kann es Haushaltsmitglieder geben die nicht in einer Familie sind? Wo sieht man die dann.
- Soll der mit buttons verlinkte controller angepasst werden, so das dort nur familienmitglieder erstellt werden koennen?

**Comment by daniel-illi** [comment]
@Largo im SAC sind per Definition alle Haushaltmitglieder auch Familienmitglieder. Wenn eine Person dem Haushalt hinzugefügt wird, wird diese auch automatisch der Familienmitgliedschaft hinzugefügt.
Du musst also hier keine Unterscheidung machen zwischen Familienmitgliedern und Nicht-Familienmitgliedern.
