### ISSUE TITLE
GROUPS: Gruppen und Rollen anpassen

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito_sac_cas#551]
Als Zentralverband beim SAC
möchte ich eine sinnvolle, simple und praxisnahe Gruppen- und Rollenstruktur haben,
um möglichst wenig Wildwuchs und Datenhaltungsaufwand zu haben, und gleichzeitig alle nötigen Informationen zu speichern welche Drittapplikationen für ihre eigene Autorisierungslogik benötigen.

Dazu sollen einige der bestehenden Gruppentypen und Rollentypen angepasst werden. Ausserdem sollen einige bereits bestehende Gruppen im UI gelöscht, neu angelegt oder umbenannt werden. Zwar könnte Stefan das selber tun, aber er hat auch so schon genug zu tun.

# Mockup

```
    * Schweizer Alpen-Club SAC
      * Geschäftsstelle
        * Mitarbeiter*in (schreibend): 2FA [:layer_and_below_full, :read_all_people]
        * Mitarbeiter*in (lesend): 2FA [:layer_and_below_read, :read_all_people]
        * Administration: 2FA [:layer_and_below_full, :admin, :impersonation, :read_all_people]    <-- Rolle umbenennen
        * Andere: 2FA [:layer_and_below_read, :read_all_people]    <-- neue Rolle
      * Geschäftsleitung    <-- neuer Gruppentyp mit static_name
        * Geschäftsführung: 2FA [:layer_and_below_read, :read_all_people]    <-- neue Rolle
        * Ressortleitung: 2FA [:layer_and_below_read, :read_all_people]    <-- neue Rolle
        * Andere: 2FA [:layer_and_below_read, :read_all_people]    <-- neue Rolle
      * Zentralvorstand    <-- neuer Gruppentyp mit static_name
        * Präsidium: []    <-- neue Rolle
        * Mitglied: []    <-- neue Rolle
        * Andere: []    <-- neue Rolle
      * Kommission    <-- neuer Gruppentyp, children wieder Kommission
        * Präsidium: []    <-- neue Rolle
        * Mitglied: []    <-- neue Rolle
        * Andere: []    <-- neue Rolle
      * Externe Kontakte
        * Kontakt: []
      * Touren-Portal
        * Abonnent: []
        * Neuanmeldung: []
        * Administration: []    <-- neue Rolle
        * Autor*in: []    <-- neue Rolle
        * Community: []    <-- neue Rolle
        * Andere: []    <-- neue Rolle
      * AboMagazin
        * Abonnent: []
        * Neuanmeldung: []
        * Autor*in: []    <-- neue Rolle
        * Andere: []    <-- neue Rolle
      * SAC/CAS Login
        * Basis Konto: []
      * Ehrenmitglieder
        * Ehrenmitglied: []
    * Sektion
    * Ortsgruppe
    * Global
      * Sektionsfunktionäre    <-- geänderte Übersetzung
        * Präsidium: [:layer_and_below_read]    <-- angepasste Berechtigung
        * Mitgliederverwaltung: 2FA [:layer_and_below_full]
        * Administration: 2FA [:layer_and_below_full]
        * Administration (nur lesend): 2FA [:layer_and_below_read]
        * ~~Umweltbeauftragte*r: []~~    <-- Rolle löschen
        * ~~Kulturbeauftragte*r: []~~    <-- Rolle Löschen
        * Finanzen: []    <-- neue Rolle
        * Redaktion: []    <-- neue Rolle
        * Andere: []
        * Hütten <-- neuer Gruppentyp
          * Hüttenobmann*frau: 2FA [:group_and_below_read]    <-- neue Rolle, ersetzt in Imports die bisherige Rolle in Hüttenkommission
          * Andere: [:group_read]    <-- neue Rolle, ersetzt in Imports die bisherige Rolle in Hüttenkommission
          * Hütte    <-- Gruppentyp neu in children von "Hütten" statt wie bisher "Sektionsfunktionäre". Gruppentypexistiert bereits, wird aber von rake hitobito:roles nicht ausgewiesen bis #2611 umgesetzt ist
            * Hüttenwart: [:group_read]
            * Hüttenchef: [:group_read]
            * Andere: [:group_read]
        * Touren und Kurse    <-- neuer Gruppentyp mit static_name
          * Tourenchef*in Sommer: 2FA [:layer_and_below_full]    <-- neue Rolle, ersetzt in Imports die bisherige Rolle in Tourenkommission (hat aber andere Berechtigungen)
          * Tourenchef*in Winter: 2FA [:layer_and_below_full]    <-- neue Rolle, ersetzt in Imports die bisherige Rolle in Tourenkommission (hat aber andere Berechtigungen)
          * Tourenchef*in Klettern: 2FA [:layer_and_below_full]    <-- neue Rolle, ersetzt in Imports die bisherige Rolle in Tourenkommission (hat aber andere Berechtigungen)
          * Tourenchef*in Senioren: 2FA [:layer_and_below_full]    <-- neue Rolle, ersetzt in Imports die bisherige Rolle in Tourenkommission (hat aber andere Berechtigungen)
          * Tourenleiter*in (mit Qualifikation): []    <-- neue Rolle, ersetzt in Imports die bisherige Rolle in Tourenkommission (hat aber einen anderen Namen)
          * Tourenleiter*in (ohne Qualifikation): []    <-- neue Rolle
          * JO-Chef*in: []    <-- neue Rolle
          * J+S Coach: []    <-- neue Rolle
          * Andere: []    <-- neue Rolle
        * Kommission    <-- neuer Gruppentyp, children wieder Kommission (technischer Name SektionsKommission)
          * Präsidium: []    <-- neue Rolle
          * Mitglied: []    <-- neue Rolle
          * Andere: []    <-- neue Rolle
        * Vorstand    <-- neuer Gruppentyp (technischer Name SektionsVorstand)
          * Präsidium: []    <-- neue Rolle
          * Mitglied: []    <-- neue Rolle
          * Andere: []    <-- neue Rolle
      * Mitglieder
        * Mitglied (Stammsektion): []
        * Mitglied (Zusatzsektion): []
        * Ehrenmitglied: []
        * Begünstigt: []
      * Neuanmeldungen (zur Freigabe)
        * Neuanmeldung (Stammsektion): []
        * Neuanmeldung (Zusatzsektion): []
      * Neuanmeldungen
        * Neuanmeldung (Stammsektion): []
        * Neuanmeldung (Zusatzsektion): []
      * ~~Tourenkommission~~    <-- Gruppentyp löschen
        * ~~Tourenchef*in Sommer: 2FA [:group_full]~~
        * ~~Tourenchef*in Winter: 2FA [:group_full]~~
        * ~~Tourenchef*in Klettern: 2FA [:group_full]~~
        * ~~Tourenchef*in Senioren: 2FA [:group_full]~~
        * ~~Tourenleiter*in: []~~
      * ~~Hüttenkommission~~    <-- Gruppentyp löschen
        * ~~Hüttenobmann*frau: 2FA [:group_and_below_read]~~
        * ~~Andere: [:group_read]~~
      * Externe Kontakte
        * Kontakt: []
```

# Tech-Spec

- `rake hitobito:roles` verwenden um zu vergleichen ob nichts vergessen gegangen ist
- Bestehende Rollen und Gruppen die ganz verschwinden können auf der Integration auch komplett gelöscht werden, entweder mit Code oder von Hand
- Ein Spezialfall ist die Rolle "Tourenleiter\*in". Diese bisherige Rolle wird durch zwei neue Rollen "Tourenleiter\*in (mit Qualifikation)" und "Tourenleiter\*in (ohne Qualifikation)" abgelöst. Dabei wird es auch einen Automatismus mit nächtlichem Background Job geben, welcher zwischen diesen zwei Rollen hin- und her konvertiert (wird in separaten Issues umgesetzt). Diese Rollen werden vermutlich auch durch den Import angelegt werden. Für den Moment will man aber noch nicht zu viel Zeit in die Imports investieren, und wir passen daher den bestehenden Importer-Code einfach fürs erste so an, dass er immer "Tourenleiter\*in (mit Qualifikation)" vergibt. Der Automatismus wird dann nach einem Tag alle fälschlich angerechneten "mit Qualifikation" Rollen auf "ohne Qualifikation" korrigieren. Das wird zwar in der History nur mässig schön aussehen, aber ist mal so gut wie es möglich ist ohne dass fachlich weiteres spezifiziert ist.

# ToDo

- [ ] Änderungen an den Gruppentypen und Rollentypen gemäss "Mockup" vornehmen
- [ ] Folgende Translations ändern:
  - [ ] `de.activerecord.models.group/sektions_funktionaere.one`: Sektionsfunktionäre
  - [ ] `de.activerecord.models.group/sektions_funktionaere.other`: Sektionsfunktionäre
- [ ] Folgende neuen Gruppen im UI anlegen:
  - [ ] SAC/CAS -> SAC Geschäftsleitung (Gruppentyp Geschäftsleitung)
  - [ ] SAC/CAS -> SAC Kommissionen (Gruppentyp Kommission)
- [ ] Folgende Gruppen im UI umbenennen:
  - [ ] SAC/CAS -> Abonnenten umbennen zu "SAC Abonnenten"
  - [ ] SAC/CAS -> Abonnenten -> Die Alpen DE umbennen zu "Die Alpen"
  - [ ] SAC/CAS -> Abonnenten -> Les Alpes FR umbennen zu "Les Alpes"
  - [ ] SAC/CAS -> Abonnenten -> Le Alpi IT umbennen zu "Le Alpi"
  - [ ] SAC/CAS -> Abonnenten -> Touren-Portal umbennenen zu "SAC Tourenportal"
- [ ] Folgende Gruppen im UI / in der DB löschen:
  - [ ] SAC/CAS -> Kontakte (inkl. allen Untergruppen)
- [ ] Sicherstellen dass alle Imports mit der neuen Struktur zurechtkommen
- [ ] Output von `rake hitobito:roles` in README aktualisieren
- [ ] Ggf. Specs, Fixtures, Fabricators anpassen
- [ ] Mit angemessener Rolle "durchklicken"
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen
