### ISSUE TITLE
ROLES: Sortierung der Rollentypen im Auswahlmenü

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito_sac_cas#552]
Als Person beim SAC welche oft Rollen vergeben muss
möchte ich die Rollentypen nach einem fixen Muster sortiert haben,
um möglichst schnell und konsistent die korrekte Rolle auswählen zu können.

Neu sollen die Rollen im app/views/roles/_type_select.html.haml beim SAC alphabetisch sortiert sein, abgesehen von sämtlichen "Andere" Rollen welche immer am Ende der Liste stehen sollen.

# Mockup

![Kooha-2024-05-16-14-16-41](https://github.com/hitobito/hitobito_sac_cas/assets/7566995/96b2cf93-0f93-4053-9282-0f6028d14580)

# Tech-Spec

- Umsetzung im SAC Wagon
- Sortierung soll nach übersetztem Rollentext sein, nicht nach technischem Rollen-Klassennamen
- Auswahl wird von `Role::List#role_types` berechnet
- Sortierung ist bisher unklar, aber unwichtig. Falls dieselbe Methode noch an anderen Orten verwendet wird dürfte es egal sein wenn die Sortierung dort auch aktiv wird.
- Es gibt Rollen die "Andere" heissen in diversen Gruppen, siehe auch #551

# ToDo

- [x] Im SAC Wagon die Methode `Role::List#role_types` prependen, und `super.sort` mit passender Logik aufrufen
- [x] Specs schreiben
- [x] Mit angemessener Rolle "durchklicken"
- [x] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen
