### ISSUE TITLE
EVENTS: Anmeldebanner je nach TN Status

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#556]
Als Kurs-TN möchte ich auf dem Kurs meinen korrekten TN-Status sehen.

Neu soll im Banner, welcher auf der Event Show Seite angezeigt wird (`Event::ParticipationBanner`), ein Status-abhängiger Text angezeigt werden. Je nach Status erscheint ebenfalls ein Abmeldebutton "(Abmelden)" (Dies sollte bereits so funktionieren). Folgende Texte und Hintergrundfarben werden verwendet:
| **Status**           | **Banner**                                                                                                                                   | **Farbe** |
| -------------------- | -------------------------------------------------------------------------------------------------------------------------------------------- | --------- |
| `unconfirmed` / **Unbestätigt**      | “Du bist für diesen Kurs vorangemeldet. Die Anmeldung ist noch nicht definitiv und muss von der Kursverwaltung bestätigt werden. (Abmelden)“ | Gelb      |
| `assigned` / **Bestätigt**        | “Deine Anmeldung für diesen Kurs ist bestätigt. (Abmelden)“                                                                                | Grün      |
| `applied` / **Warteliste**       | “Du bist für diesen Kurs auf der Warteliste (unverbindlich). Bis zur Durchführung kannst du nachrücken. (Abmelden)“                          | Gelb      |
| `rejected` / **Abgelehnt**        | “Die Aufnahmekriterien sind nicht erfüllt. Deshalb mussten wir deine Anmeldung leider ablehnen.”                                  | Rot       |
| `summoned` / **Aufgeboten**       | “Du bist für diesen Kurs aufgeboten. (Abmelden)“                                                                                           | Grün      |
| `attended` / **Teilgenommen**     | “Du hast an diesem Kurs teilgenommen.“                                                                                                     | Grün      |
| `absent` / **Nicht erschienen** | “Keine Teilnahme an diesem Kurs.“                                                                                                          | Gelb      |
| `canceled` / **Abgemeldet**       | “Du wurdest von diesem Kurs abgemeldet.“                                                                                                   | Rot       |
| `annulled` / **Annulliert**       | “Dieser Kurs wurde abgesagt.“                                                                                                           | Rot       |

# Tech-Spec

- https://github.com/hitobito/hitobito/blob/master/app/views/events/_attrs.html.haml#L7
- https://github.com/hitobito/hitobito/blob/master/app/helpers/event/participation_banner.rb

# ToDo

- [x] prüfen ob Event::ParticipationBanner in eine ViewComponent umgebaut werden kann?
  - [x] ist es customized in einem wagon? (pbs, youth, jubla, cevi) -> nur in youth
  - [x] ~falls viewcomponent möglich, helper durch diesen ersetzen~
- [x] ~event show mit zusätzlichem Banner versehen~
- [x] helper erstellen der text aufgrund von anmelde status (participation) zurück gibt
- [x] Specs schreiben
- [x] Mit angemessener Rolle "durchklicken"
