### ISSUE TITLE
PEOPLE: Validierungen auf Household für SAC

### ISSUE THREAD

**Issue by daniel-illi** [hitobito/hitobito_sac_cas#559]
blocked by #549

Für den SAC braucht es weitere Validierungen auf `Household` und `HouseholdMember`:

# Tech-Spec

## Household Validierungen

+ [x] Household enthält weniger als 1 erwachsene Person (`SacCas::Beitragskategorie::Calculator.new(person).adult?`):  
  `"Eine Familie muss mindestens 1 erwachsene Person enthalten."`
+ [x] Household enthält mehr als 2 erwachsene Personen:  
  `"Eine Familie darf höchstens 2 erwachsene Personen enthalten."`
+ [x] Household enthält weniger als 2 Personen:  
  `"Eine Familie muss mindestens 2 Personen enthalten."`
+ [x] Aus dem Household wurde eine Person entfernt, welche keine bestätigte Email Adresse besitzt.  
  (Diese Validierung sollte nie anschlagen, es sollte schon im UI unterbunden werden dass solche Personen entfernt werden können)
  ```ruby
  removed_people = Person.where(household_key: household_key).where.not(household_members.map(&:id))
  ```
  `"Die entfernte Person besitzt keine bestätigte Email Adresse."`
+ [x] Household muss eine erwachsene Person mit bestätigter Email Adresse enthalten  
  `"Der Household enthält keine erwachsene Person mit bestätigter Email Adresse"`

## HouseholdMember Validierungen

+ Validierungen auf HouseholdMember, welche neu der Familie hinzugefügt werden, also wenn
  ```ruby
  person.household_key != household.household_key
  ```  
  + [x] Person hat bereits einen `household_key`, und `person.household_key != household.household_key`:  
    `"#{name} kann nicht hinzugefügt werden, da die Person bereits einer anderen Familie zugeordnet ist."`
  + [x] Person hat kein Geburtsdatum:  
    "`"#{name} hat kein Geburtsdatum."`
  + [x] Alter der Person entspricht nicht den Familienbedingungen (`SacCas::Beitragskategorie::Calculator.new(person).family_age?`):  
    `"#{name} kann nicht hinzugefügt werden. Es sind nur Personen erlaubt im Alter von 6-17 oder ab 22 Jahren."`
  * [x] Person besitzt bereits eine Familienmitgliedschaft:  
    Entspricht dem `SacCas::Person::Household#assert_no_conflicting_family_membership`, aber validiert auf dem einzelnen `HouseholdMember`  
    i18n key und text ist bereits vorhanden: `errors.messages.conflicting_family_membership`
    ```ruby
    if(person.household_key != household.household_key && person.roles.where(beitragskategorie: :familie).exists?)
      errors.add(:base, :conflicting_family_membership)
    end
    ```

  + [x] Person besitzt eine Hauptmitgliedschaft in einer Sektion != derjenigen der `Household#reference_person`:  
    `"#{name} besitzt bereits eine Mitgliedschaft in einer anderen Sektion."`  
    ```
    Group::SektionsMitglieder::Mitglied.find_by(person_id: id).group_id != 
      Group::SektionsMitglieder::Mitglied.find_by(person_id: household.reference_person.id).group_id
    ```

+ `validate on: :destroy`  
  Diese Validierungen sollen nur geprüft werden, wenn `validate` mit context `:destroy` aufgerufen wird.
  * [x] Email Adresse der Person ist nicht bestätigt:  
    `"#{name} hat keine bestätigte Email Adresse."`
  * [x] Person hat einen Austritt geplant:  
    `"#{name} hat einen Austritt geplant."` 
    ```ruby
    Group::SektionsMitglieder::Mitglied.where(person_id: person.id).where.not(terminate_on: nil).exists?
    ``` 

# ToDo

+ [x] Validierungen implementieren
+ [x] Specs schreiben
+ [ ] Mit angemessener Rolle "durchklicken"
