### ISSUE TITLE
PEOPLE: Household Personensuche SAC Anpassungen

### ISSUE THREAD

**Issue by daniel-illi** [hitobito/hitobito_sac_cas#565]
Die Personensuche zum Verwalten von Haushalt/Familie muss für SAC angepasst werden.

In diesen Personenattributen soll gesucht werden:
* Mitgliedernummer `id`
* Geburtsdatum
* Vorname
* Nachname
* Email

Es sollen nur Personen angezeigt werden, auf welche der user Schreibrechte hat.  
> [!NOTE]
> Vorläufig steht die Haushalts-management Funktion steht nur für Mitarbeiter der Geschäftsstelle zur Verfügung. Diese haben auf sämtliche Personen Schreibrechte.  
Aus Performance Gründen filtern wir also nicht die sichtbaren Personen, sondern erlauben die Suche nur für Mitarbeiter der Geschäftsstelle.
> Mit #564 werden die Berechtigungen angepasst, so dass nur Mitarbeiter der Geschäftsstelle die permission `:create_households` haben. Wir können also diese verwenden, um den user Zugriff zu steuern.

Dafür muss im SAC wagon der `Person::QueryHouseholdController` angepasst werden.

# Tech-Spec

* Modul `SacCas::Person::QueryHouseholdController` erstellen und im `lib/hitobito_sac_cas/wagon.rb` dem `Person::QueryHouseholdController` prependen
* `authorize_action` überschreiben
  ```ruby
  def authorize_action
    authorize!(:create_households, Person)
  end
  ```
* `scope` überschreiben
  ```ruby
  def scope
    Person.only_public_data
  end
  ```
* `seach_columns` Wert überschreiben, Attributliste siehe oben
  ```ruby
  prepended do
    self.search_columns = [:id, :birthday, :first_name, :last_name, :email]
  end
  ```

# ToDo

+ Modul `SacCas::Person::QueryHouseholdController` implementieren
  + [x] `authorize_action` überschreiben
  + [x] `scope` überschreiben
  + [x] `search_columns` anpassen
- [ ] Specs schreiben
- [x] Mit angemessener Rolle "durchklicken"  
      (Person editieren, weitere Personen dem Haushalt hinzufügen)

**Comment by daniel-illi** [comment]
@daniel-illi check https://github.com/hitobito/hitobito_sac_cas/issues/384, https://github.com/hitobito/hitobito_sac_cas/issues/477
