### ISSUE TITLE
ABOS: Empfängerliste Haushaltsexport für physischen Versand

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito_sac_cas#574]
Als Person die ein Sektionsbulletin versendet
möchte ich die dazugehörigen Empfänger aus einem Abo in einem möglichst ähnlichen Format wie bisher aus Navision exportieren können,
um weniger Aufwand bei der Umstellung zu haben.

In #427 haben wir den entsprechenden Empfängerlisten-Export für digitale Versände (1 Exemplar pro Einzelperson) umgesetzt.

In diesem Issue hier soll noch ein gleichwertiger Export mit zusammengezogenen Haushalten umgesetzt werden, unter dem Namen "Empfängerliste Familien".

# Mockup

![Screenshot 2024-05-29 at 13-26-20 hitobito - test](https://github.com/hitobito/hitobito_sac_cas/assets/7566995/a6c3298d-3d3a-48ed-8dc1-3b4905ef5d3d)

# Tech-Spec

- Umsetzung im SAC Wagon
- Custom tabular household Export
- Beim SAC reden wir im UI nicht mehr von "Haushalt", sondern nur noch von Familie.
- Haushalte werden in diesem Export zusammengefasst
- **Achtung:** Auf Zeilen die nur eine einzelne Person repräsentieren soll es genau gleich aussehen wie in #427. Beispiel: Wenn Person A und B in der DB zusammen im Haushalt sind (haben denselben `household_key` gesetzt), aber nur Person B Teil des Exports ist (weil Person A z.B. nicht in der exportierten Sektion Mitglied ist), dann soll die Zeile von Person B genau gleich aussehen wie beim normalen Empfänger-Export von #427. Erst wenn sowohl Person A wie auch Person B exportiert werden, dann greifen die untenstehenden Abweichungen.
- Spalten genau gleich wie beim Empfänger-Export der in #427 umgesetzt wurde. Abweichungen für Haushalte mit mehreren Personen wie folgt:
  - **Navision-Nr.**
    Navision ID eines beliebigen Mitglieds im Haushalt. Sollte dasselbe Mitglied sein von welchem auch die Mailadresse in der untenstehenden Spalte genommen wird (falls so ein Mitglied gefunden wird, sonst eine beliebige Person)
  - **Vorname**
    Falls mehrere Personen in dieser Zeile zusammengefasst werden, dann als Vorname den fixen String "Familie" ausgeben (übersetzbar)
  - **Name**
    Falls mehrere Personen in dieser Zeile zusammengefasst werden, dann als Nachname die zusammengezogenen Namen der Personen ausgeben, nach derselben [Logik](https://github.com/hitobito/hitobito/blob/master/app/domain/export/pdf/labels.rb#L43) wir wir sie bei den Etiketten haben (`Export::Tabular::People::HouseholdRow.new(relevant_household_members).name`)
  - **E-Mail**
    Inhalt: Haupt-E-Mail eines beliebigen Mitglieds im Haushalt (möglichst eine Person heraussuchen welche eine Haupt-E-Mail gesetzt hat, aber nur Personen berücksichtigen welche auch tatsächlich Teil vom Export sind).

# ToDo

- [x] Label des Exports von #427 von "Empfänger" auf "Empfänger Einzelpersonen" ändern
- [x] Im SAC Wagon neuen Tabular Export "recipient_household_list" als Kopie des bestehenden anlegen
- [x] Export haushaltsfähig machen, dabei oben aufgelistete Logik-Anpassungen umsetzen
- [x] Neuen Export im Dropdown-Menü anbieten, mit dem Label "Empfänger Familien"
- [ ] ~Manuell mit Beispiel-Export vergleichen, um Kompatibilität zu verifizieren~ Gibt keinen spezifischen Beispiel-Export
- [x] Specs schreiben für Export
- [x] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen
