### ISSUE TITLE
GROUPS: CMS-Felder auf Sektion für Sektionssteckbrief

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito_sac_cas#575]
Als Sektionsfunktionär\*in
möchte ich die angezeigten Informationen über meine Sektion auf der SAC-Webseite in hitobito managen können,
um keinen Administrations-Zugang zur Typo3-Webseite zu benötigen.

Neu braucht es einige der Felder von Sektionen, die bisher in Typo3 gespeichert und bearbeitet wurden, in hitobito.

# Mockup

[Siehe Miro](https://miro.com/app/board/uXjVKFNM_zw=/)

# Tech-Spec

- Umsetzung im SAC Wagon
- Umsetzung soweit möglich als mounted_attributes, da die Felder nur auf Sektionen relevant sind
- Einige in diesem Ticket spezifizierten Felder müssen mehrsprachig befüllbar sein. Unser bisheriger Approach ist `include Globalized; translates :some_attribute`, und im UI muss man die UI-Sprache umschalten um die anderen Sprachen zu bearbeiten. So etwas muss aber erst mal noch für mounted_attributes eingerichtet werden.
- Nochmals komplizierter wirds dadurch, dass auch ein übersetzbares mounted `nested_attribute` nötig ist
- Falls das zu kompliziert wird, können wir wo nötig auch auf mounted_attributes verzichten und einfach Bordmittel von Rails verwenden.
- Alle hinzugefügten Felder und Werte müssen auch lesend in der API ausgegeben werden, damit die Typo3-Webseite auf diese zugreifen kann.
- Fachliche Beschreibungen der hinzugefügten Felder:
  - Lead und Follow Text: Sind die primären Beschreibungstexte die auf der SAC Webseite über eine Sektion Auskunft geben.
  - 6 URLs: Werden je nach Sektion mit sektionseigenen RSS-Feed-Links befüllt. Die SAC Webseite liest dann diese Feeds und zeigt die Inhalte in schöner Form auf der Webseite an (z.B. die nächsten Touren welche diese Sektion anbietet).
  - Advantages / Vorteile: Werden als Bullet Points unter "Sektionsvorteile" auf der SAC Webseite dargestellt, z.B. "10% Rabatte auf Jahresabonnements in Kletterhalle xy", "Bis zu 50% Ermässigung bei Übernachtungen in den 153 SAC-Hütten", etc.
  - Angebot (wird in separatem GitHub Issue umgesetzt): Kleine Bullet Points, z.B. Jugendorganisation, Seniorengruppe, Umwelt-Ressort, eigenes Ausbildungsprogramm, etc.

# ToDo

- [ ] Im Core den mounted_attribute Mechanismus so erweitern, dass man mehrsprachige / übersetzbare mounted_attributes anlegen kann.
- [ ] Im Core den mounted_attribute Mechanismus so erweitern, dass man auch nested_attributes als mounted_attribute anlegen kann (inkl. übersetzbaren Feldern).
- [ ] Neue mounted_attributes `sac_website_lead` und `sac_website_follow_text` auf Sektion, übersetzbar, textarea (Zeilenumbrüche erlaubt)
- [ ] Neue mounted_attributes `sac_website_tours_url`, `sac_website_tour_reports_url`, `sac_website_appointments_url`, `sac_website_dropnet_tours_url`, `sac_website_dropnet_tour_reports_url`  und `sac_website_dropnet_appointments_url` auf Sektion, (übersetzbar tbd), single line Input-Feld
- [ ] Neues nested mounted attribute `sac_website_advantages`, mit genau einem einzeiligen übersetzbaren Freitextfeld.
- [ ] Alle neu angelegten Felder in der API auf Sektionen exponieren
- [ ] Specs fürs editieren via Controller und lesen via API schreiben, insbesondere auch die Mehrsprachigkeit
- [ ] Kunde wegen Übersetzungen informieren
- [ ] Mit angemessener Rolle "durchklicken"
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen
