### ISSUE TITLE
GROUPS: Sektionsangebot

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito_sac_cas#577]
Als Sektionsfunktionär\*in
möchte ich die angezeigten Informationen über meine Sektion auf der SAC-Webseite in hitobito managen können,
um keinen Administrations-Zugang zur Typo3-Webseite zu benötigen.

Nach #575 braucht es noch ein weiteres Feld auf Sektionen, das bisher in Typo3 gespeichert und bearbeitet wurde, in hitobito.
Dieses Feld ist das Sektions-Angebot. Z.B. Jugendorganisation, Seniorengruppe, Umwelt-Ressort, eigenes Ausbildungsprogramm, etc.
Jede Sektion kann aus einer fixen Auswahl diejenigen Einträge auswählen die auf die Sektion zutreffen, und die ausgewählten Punkte werden dann auf der SAC-Webseite angezeigt.

# Mockup

![Screenshot 2024-05-29 at 14-20-18 SAC - Sektionsprofil](https://github.com/hitobito/hitobito_sac_cas/assets/7566995/4a339215-244a-4f34-82ee-d0b883693307)
[Siehe auch Miro](https://miro.com/app/board/uXjVKFNM_zw=/)

# Tech-Spec

- Umsetzung im SAC Wagon
- Umsetzung falls möglich als mounted_attribute, da dieses Feld nur auf Sektionen (und Ortsgruppen) relevant ist
- Der Inhalt des Felds muss auch lesend in der API ausgegeben werden, am besten mehrsprachig, damit die Typo3-Webseite auf diesen zugreifen kann.
- Die auswählbaren Werte sollen durch Admins in den globalen Einstellungen verwaltet werden können, genau wie wir das für die Eintrittsgründe in #112 bereits umgesetzt haben

# ToDo

- [ ] Neues Model `Offering` o.ä.
- [ ] Nur ein einziges Feld mit einem einzeiligen Text, dieses aber dafür übersetzbar
- [ ] CRUD in den globalen Einstellungen für Admins ermöglichen
- [ ] In der Tabelle anzeigen, wie viele Sektionen / Ortsgruppen dies ausgewählt haben
- [ ] Offering kann nur gelöscht werden, wenn keine Sektionen / Ortsgruppen dies ausgewählt haben
- [ ] Neue Relation auf Sektion / Ortsgruppe `sac_website_offerings`
- [ ] Mit einem tom multiselect im Formular bearbeitbar machen, ähnlich wie wir das schon auf der Kursliste haben. Pro Sektion / Ortsgruppe können von 0 bis n Angebote ausgewählt werden
- [ ] Ausgewählte Werte in der API auf Sektionen / Ortsgruppen exponieren (z.B. als Liste von Strings, oder als has_many, oder wie es am besten geht)
- [ ] In der API sollen am besten gleich alle Sprachen gleichzeitig in der Response mitkommen, die Alternative mit separaten API-Abfragen pro Sprache wäre viel umständlicher für Drittapplikationen zum konsumieren
- [ ] OpenAPI-Spec updaten, sicherstellen dass das neue Attribut ausgewiesen wird
- [ ] Seeds mit Beispieldaten für auswählbare Angebote anlegen
- [ ] Specs fürs editieren via Controller und lesen via API schreiben
- [ ] Kunde wegen Übersetzungen und Befüllung informieren
- [ ] Mit angemessener Rolle "durchklicken"
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen
