### ISSUE TITLE
EVENTS: Kurs absagen mit Grund

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#580]
Als Kursadmin möchte ich beim Absagen eines Kurses eine Begründung angeben können.

# Model

Auf dem Event Model braucht es ein neues Feld `canceled_reason` (Enum: `minimum_participants`, `weather`, `no_leader`; nullable). Labels: "Minimale Teilnehmerzahl nicht erreicht", "Wetterrisiko", "Ausfall Kursleitung".

# Event Show View

Falls das Feld ausgefüllt ist, erscheint das Feld unter "Anmeldung" nach "Mindestalter". Label: "Absagegrund"

# Statuswechsel "Absagen"

Der Statuswechsel erfolgt momentan über einen Button auf der Event Show Ansicht. Dieser öffnet ein Dropdown mit allen möglichen Folgestatus. Für den Folgestatus `canceled` soll, wenn der Eintrag angeklickt wird, neu ein Popover unterhalb des Eintrags erscheinen, wo weitere Angaben gemacht werden können. Dazu kann die Klasse `Dropdown::Events::Courses::State`  angepasst werden und bei `init_items` beispielsweise für jeden state geprüft werden, ob eine Methode `state_item_#{state}` existiert und falls ja, diese anstelle des bisherigen `add_item` Codes aufgerufen werden. Die entsprechende `state_item_canceled` Methode kann dann das angepasste Item hinzufügen.

Im Popover befindet sich ein Formular mit folgendem Inhalt (siehe auch `event/participations/_popover_participant_cancels.html.haml` als Beispiel):
- Hinweistext: "Sagt den Kurs {name} ({nummer}) ab und annulliert alle Teilnahmen. Dabei werden allfällige Rechnungen storniert und bereits bezahlte Beträge rückerstattet. Diese Aktion kann nicht rückgängig gemacht werden." (Storno erfolgt erst später, Hinweis kommt schon hin)
- Select Feld mit Label "Grund", muss ausgefüllt werden.
- Checkbox mit Label "Information" und Caption "Alle Teilnehmenden per E-Mail über Absage informieren". Standardmässig nicht angewählt.
- Submit Button "Definitiv Absagen" mit Confirmation Dialog: "Wollen Sie den Kurs {name} ({nummer}) wirklich absagen? Diese Aktion kann nicht rückgängig gemacht werden."

Im Controller bzw in einer allfälligen Domainklasse (siehe auch #558) wird zusätzlich zur Änderung des Status auch der gewählte Absagegrund persistiert. Danach werden die Teilnahmestatus aller Teilnehmenden auf "Annuliert" gesetzt. Falls die Checkbox "Information" angewählt wurde, wird in einem Backgroundjob die Absageemails für alle Teilnehmenden ausgelöst (siehe Folgeticket: Vermutlich #1145/ #1139).

# ToDo

- [x] Migration erstellen
- [x] Domainklasse erstellen oder anpassen
- [x] Model/View/Controller anpassen
- [x] Specs schreiben
- [x] Mit angemessener Rolle "durchklicken"

**Comment by Largo** [comment]
## Model Changes

- Add canceled_reason field to Event model ✅
  - Enum: minimum_participants, weather, no_leader ✅
  - Nullable  ✅
  - Labels: "Minimale Teilnehmerzahl nicht erreicht", "Wetterrisiko", "Ausfall Kursleitung" ✅

## UI Changes
- Event Show View
  - Display cancellation reason under "Anmeldung" after "Mindestalter" ✅
  - Label: "Absagegrund" ✅

## Status Change UI  ❌
- Modify "Absagen" button to open a dropdown  ❌
- For "canceled" status, show a popover with a form:  ❌
- Warning text about cancellation consequences  ❌
- Required "Grund" select field  ❌
- Optional "Information" checkbox to notify participants  ❌
- "Definitiv Absagen" submit button with confirmation dialog  ❌

=> should the reason be changeable outside of the popover?


## Backend Logic

- Persist chosen cancellation reason
- Set all participant statuses to "Annuliert"
- If "Information" checkbox is selected, trigger cancellation emails in background job

## Implementation Notes

- Adapt Dropdown::Events::Courses::State class
- Use event/participations/_popover_participant_cancels.html.haml as reference
- Consider implementing in a domain class (see #558)

**Comment by hunchr** [comment]
ich komme hier leider nicht mehr weiter..
in #1067 fehlen noch die oben genannten sachen und das:
- [ ] popover am richtigen ort plazieren
- [ ] form an controller senden

**Comment by Largo** [comment]
Nach Absprache mit Leaddev machen wir eine neue Seite anstatt ein popover, da die library die bootstrap verwendet die Positionierung des popovers an einem anderen Ort als die definiton nicht erlaubt:

![Image](https://github.com/user-attachments/assets/2b4f507f-8e53-4466-8ef6-7be8ffe134ed)

**Comment by Largo** [comment]
@codez 
Brauchts hier die Checkbox mit Label "Information" und Caption "Alle Teilnehmenden per E-Mail über Absage informieren" noch? Ich frage, weil momentan diese E-Mails automatisch ausgeloest werden, wenn der Status aendert.

**Comment by codez** [comment]
@Largo Ja die Checkbox braucht es noch und die E-Mails sollen nur noch ausgelöst werden, wenn diese Checkbox gesetzt ist, sonst nicht.

**Comment by Largo** [comment]
Funktionalität ist da. Feature Test muss noch erweitert werden, das das Dropdown korrekt erkannt wird.
Normale Tests müssen noch umgebaut werden, weil nun die mails nicht mehr automatisch versandt werden.

**Comment by tobiasstern** [comment]
Erfolgreich getestet.
