### ISSUE TITLE
EVENTS: Kursjahr duplizieren

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#598]
Als Kursadmin möchte ich alle Kurse eines Kursjahren kopieren können, damit ich nicht jedes Jahr 200 Kurse manuell erfassen muss.

## Frontend

Neu soll es auf der Kursliste einer Gruppe einen Button "Kursjahr duplizieren" geben. Dieser öffnet ein Popover mit einem Formular, welches wie folgt aufgebaut ist:
- Hinweistext: "Es werden alle Kurse dupliziert, welche die Einstellung "Jährlich wiederholend" haben. Beim Duplizieren werden die Teilnehmenden nicht übernommen.""
- Eingabefeld numerisch, 4 Zeichen: "Ursprungsjahr"
- Eingabefeld numerisch, 4 Zeichen: "Zieljahr"
- Button "Duplizieren", Link Abbrechen

Wenn die Aktion ausgeführt wurde, erscheint ein Hinweis (Flash): "{n} Kurse wurden erfolgreich dupliziert. Folgende Kurse konnten nicht dupliziert werden: {Liste (`ul`) mit Name (Nummer): Validierungsfehler}". Der zweite Satz wird nur angezeigt, falls die Liste mit den fehlgeschlagenen Kursen nicht leer ist.

## Backend

Beim Duplizieren werden alle Kurse, deren Nummer mit "[Ursprungsjahr]-" beginnt und die das Flag "Jährlich wiederholend" / `annual` gesetzt haben, dupliziert. Dabei wird von `Event#duplicate` ausgegangen und dann vollständige Kurs (inkl. Daten, Fragen, Anhänge) sowie alle Teilnahmen des Leitungsteams (Role#kind != :participant) kopiert. Der Status wird auf Entwurf zurückgesetzt, die TN und Applicant Counts auf 0. Siehe dazu auch #588. 

FYI: Das Kursjahr stimmt also nicht zwingend mit den Daten des Kurses überein.

Bei der Kursnummer wird der Ursprungsjahr im Prefix durch das Zieljahr ersetzt. Falls diese neue Kursnummer bereits verwendet wird, soll der Kurs in der Liste der Kursen mit Validierungsfehlern angezeigt werden.

Die Daten (dates#start/finish_at) sowie die Anmeldedaten (application_opening_at, application_closing_at) werden einzeln wie folgt neu berechnet, ausgehend von den jeweiligen Ursprungsdaten: 
- Jahr = Jahr des Ursprungsdatums + (Param Zieljahr - Param Ursprungsjahr)
- Monat und Tag: Bestimmen aufgrund Kalenderwoche und Wochentag des Ursprungsdatums

# ToDo

- [ ] Domainklasse erstellen oder anpassen
- [ ] View/Controller anpassen
- [ ] Specs schreiben
- [ ] Mit angemessener Rolle "durchklicken"
