### ISSUE TITLE
PEOPLE: Wizard für Austritt Zusatzsektion

### ISSUE THREAD

**Issue by daniel-illi** [hitobito/hitobito_sac_cas#627]
blocked by #652, #653

_Vor der Umsetzung bitte mit @daniel-illi besprechen._

# Tech-Spec

* Wizard Step `Wizards::Steps::MembershipTerminatedInfo`, Titel: "Mitgliedschaft gekündigt"
  * Step nur anzeigen, falls die Person eine gekündigte Mitgliedschaft besitzt (`Role#terminated?` ist `true`)
  * implementiert in #653

* Wizard Step `Wizards::Steps::NoSelfService`, Titel: "Mitgliederdienst kontaktieren"
  * Step nur anzeigen, falls auf der Sektion/Ortsgruppe das `#mitglied_termination_by_section_only` `true` ist und der `current_user` KEIN SAC Mitarbeiter ist.
  * Infotext anzeigen 
    >Wir bitten dich den Austritt telefonisch oder per E-Mail zu beantragen. Nimm dazu bitte Kontakt mit uns auf.
  * `#valid?` überschreiben und `false` zurückgeben um ein `save!` auf dem wizard zu verhindern
  * kein "next/save" button, dafür "Abbrechen" (Link auf person profile)

* Wizard Step `Wizards::Steps::LeaveZusatzsektion::AskFamilyMainPerson`, Titel: "Familienmitgliedschaft"
  * Step nur anzeigen, sofern die Person eine Familienmitgliedschaft besitzt, aber nicht Familienhauptperson ist
  * Infotext 
    > Der Austritt aus der Zusatzsektion kann nur für die gesamte Familienmitgliedschaft beantragt werden und muss von der Hauptperson in deiner Familienmitgliedschaft angefragt werden. Bitte wende dich an {name der Familienhauptperson}.
  * `#valid?` überschreiben und `false` zurückgeben um ein `save!` auf dem wizard zu verhindern
  * kein "next/save" button, dafür "Abbrechen" (Link auf person profile)

* Wizard Step `Wizards::Steps::ChooseDate`, Titel: "Austrittsdatum"
  * Step nur anzeigen sofern der `current_user` SAC Mitarbeiter ist
  - Falls auf der Sektion/Ortsgruppe das `#mitglied_termination_by_section_only` `true` ist
    Warnung anzeigen:
    >Achtung: der Austritt findet bei einer Sektion statt, bei der die Austrittsfunktion für das Mitglied deaktiviert ist. 
    > Allenfalls musst du den Austritt vorgängig mit der Sektion abklären.
  * Infotext
    > Wann soll der Austritt stattfinden?
  * Radio button: `now` -> "sofort" , `end_of_year` -> "auf 31.12.{year}"
  * "next" button mit label `"Weiter"`

* Wizard Step `Wizards::Steps::LeaveZusatzsektion::SummaryForm`, Titel: "Bestätigung"
  * Infotext anzeigen, falls die Person eine Familienmitgliedschaft besitzt:
    > Achtung: Der Austritt aus der Zusatzsektion wird für die gesamte Familienmitgliedschaft beantragt.  
      Davon betroffen sind: {family_members.names}
  * Infotext
    > Bist du sicher, dass Du per {terminate_on} aus der Sektion xyz austreten möchtest?"
  * Auswahlfeld select für Austrittsgrund `TerminationReason`, Pflichtfeld
  * "next" button mit label `"Austritt beantragen"`

* Wizard `Wizards::LeaveZusatzsektion`
  * `#step_after` implementieren
      ```mermaid
      flowchart LR
      _start -->|terminated?| TerminatedMembershipInfo
      _start -->|mitglied_termination_by_section_only && \n!sac_mitarbeiter| NoSelfService
      _start -->|family_membership? && \n!family_main_person| AskFamilyMainPerson
      _start -->|sac_mitarbeiter?| ChooseDate
      ChooseDate --> SummaryForm
      _start --> SummaryForm
      ```

* `#terminate_on`: Gestern wenn in ChooseDate 'sofort' gewählt ist, sonst 31.12. des aktuellen Jahres
  ```ruby
  def terminate_on
    step(:choose_date).terminate_on == 'now' ? Date.current.yesterday : Date.current.end_of_year
  end
  ```
* ```ruby
  def leave_operation
    @leave_operation ||= 
      Memberships::LeaveZusatzsektion.new(
        role:, 
        terminate_on:
      )
  end
  ```

* in `#valid?` auf dem `last_step` zusätzlich die `#leave_operation` validieren. Falls diese invalid ist, deren errors ins errors des wizards übernehmen.
  ```ruby
  def valid?
    super

    if last_step? && !leave_operation.valid? 
      leave_operation.errors.full_messages.each do |msg|
        errors.add(:base, msg)
      end
    end

    errors.empty?
  end
  ```

* in `#save!` das `leave_operation.save!` aufrufen
  ```ruby
  def save!
    super
    leave_operation.save!
    send_confirmation_mail # siehe MembershipsMailer
  end
  ```

* Mailer `MembershipsMailer#zusatzsektion_leave_confirmation` implementieren  
  Texte in der aktuellen Sprache
  * CC an Geschäftsstelle (Email Adresse von der Gruppe `Group::Geschaeftsstelle`), _nur wenn Email Adresse vorhanden_
  * Subject: "Bestätigung Austritt Zusatzsektion"
  * Body: 
    >Der Austritt aus {name} wurde per {date} vorgenommen

* Ability `on(Wizards::LeaveZusatzsektion).may(:create)`
  - wenn `person == current_user || current_user.sac_mitarbeiter?` (siehe `SacCas::SAC_MITARBEITER_ROLES`)

* Controller `People::ZusatzsektionLeavesController` auf Basis des  `Wizards::BaseController` des POC
  * route 
    ```ruby
    resources :groups do
      resources :people do
        resources :roles do
          get :zusatzektion_leaves, to: 'people/zusatzsektion_leaves#new'
          resources :zusatzektion_leaves, only: [:new, :create], module: 'people'
    ```
  * before action: `authorize!(:create, entry)`
  * `def model_class`: `Wizards::LeaveZusatzsektion`
  * `def redirect_target`: `group_person_path`

* ```ruby
  class Sheet::ZusatzsektionLeave < Base
    self.parent_sheet = Sheet::Person
  ```

* Views `app/views/people/zusatzsektion_leaves/new.html.haml`, `new.js.haml`, `_form.html.haml`, `_fields.html.haml`  
  analog `app/views/people/stammsektion_switches/*.haml` des POC
  
* `Roles::TerminateRoleLink#render_link` im SAC wagon anpassen:  
  wenn `@role` eine `MitgliedZusatzsektion` ist, dann verlinken mit `group_person_zusatzektion_leaves_path`,  
  sonst mit `new_group_role_termination_path` (super)

# ToDo

- [X] Domainklasse erstellen oder anpassen
- [X] Model/View/Controller anpassen
- [x] Specs schreiben
- [x] Mit angemessener Rolle "durchklicken"

**Comment by rnestler** [comment]
Wo kommt dieser Wizard eigentlich hin? Also von wo wird er getriggert?
