### ISSUE TITLE
EVENTS: Bemerkungen bei Kursabschluss

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#638]
Als Kursadmin möchte ich beim Abschliessen eines Kurses eine Bemerkung angeben können.

# Model

Auf dem Event Model braucht es ein neues Feld `closed_remarks` (text).

# Event Show View

Falls das Feld ausgefüllt ist, erscheint das Feld zuunterst in der linken Spalte ausserhalb des grauen Bereichs. Label: "Bemerkungen Kursabschluss". Zeilenumbrüche werden entsprechend dargestellt.  Das Feld wird nur für Personen angezeigt, welche den Kurs auch bearbeiten können.

# Statuswechsel "Abschliessen"

Der Statuswechsel erfolgt momentan über einen Button auf der Event Show Ansicht. Dieser öffnet ein Dropdown mit allen möglichen Folgestatus. Für den Folgestatus closed soll, wenn der Eintrag angeklickt wird, neu ein Popover unterhalb des Eintrags erscheinen, wo weitere Angaben gemacht werden können. Dazu kann die Klasse Dropdown::Events::Courses::State angepasst werden und bei init_items beispielsweise für jeden state geprüft werden, ob eine Methode state_item_#{state} existiert und falls ja, diese anstelle des bisherigen add_item Codes aufgerufen werden. Die entsprechende state_item_application_paused Methode kann dann das angepasste Item hinzufügen (siehe auch #580 oder #582).

Im Popover befindet sich ein Formular mit folgendem Inhalt (siehe auch event/participations/_popover_participant_cancels.html.haml als Beispiel):

- Text Feld mit Label "Bemerkung", optional. 
- Submit Button "Anmeldung pausieren"
- 
Im Controller wird zusätzlich zur Änderung des Status auch die Bemerkung persistiert.

# ToDo

- [ ] Migration erstellen
- [ ] Domainklasse erstellen oder anpassen
- [ ] Model/View/Controller anpassen
- [ ] Specs schreiben
- [ ] Mit angemessener Rolle "durchklicken"
