### ISSUE TITLE
EVENTS: Einstellungen Kursvergütungskategorien

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#641]
blocked by #683

Als Hitobito Admin möchte ich Kursvergütungskategorien /  `CourseCompensationCategory`  in den Einstellungen verwalten können.

In den Einstellungen wird ein entsprechender Menupunkt hinzugefügt, um die Einträge zu verwalten.

Die Tabelle enthält die Spalten Kurzname, Typ, Beschreibung, Bezeichnung Kursleitung und Bezeichnung Klassenleitung. Sortiert nach Kurzname.

# ToDo

- [x] View/Controller anpassen
  - [x] Controller hinzufügen
  - [x] Route hinzufügen
  - [x] Ability hinzufügen
  - [x] Menüpunkt hinzufügen
  - [x] Sheet für neue View hinzufügen
  - [x] Inhaltstabelle hinzufügen
  - [x] Sortierung nach `short_name` hinzufügen
  - [x] Form hinzufügen
- [x] Specs schreiben
- [x] Mit angemessener Rolle "durchklicken"
