### ISSUE TITLE
EVENTS: Einstellungen Kursvergütungsansätze

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#642]
blocked by #683

Als Hitobito Admin möchte ich Kursvergütungsansätze /  `CourseCompensationRate` in den Einstellungen verwalten können.

In den Einstellungen wird ein entsprechender Menupunkt hinzugefügt, um die Einträge zu verwalten.

Die Tabelle enthält die folgenden Spalten, sortiert nach Gültig Ab DESC, Kurzname Vergütungskategorie.
- Gültig ab 
- Gültig Bis
- Kurzname Vergütungskategorie
- Typ Vergütungskategorie
- Beschreibung Vergütungskategorie
- Bezeichnung Kursleitung
- Bezeichnung Klassenleitung
- Ansatz Kursleitung
- Ansatz Klassenleitung

# ToDo

- [x] Model/View/Controller anpassen
  - [x] Controller hinzufügen
  - [x] Route hinzufügen
  - [x] Ability hinzufügen
  - [x] Menüpunkt hinzufügen
  - [x] Sheet für neue View hinzufügen
  - [x] Inhaltstabelle hinzufügen
  - [x] Sortierung `Gültig Ab DESC, Kurzname Vergütungskategorie` hinzufügen
  - [x] Form hinzufügen
- [x] Specs schreiben
- [x] Mit angemessener Rolle "durchklicken"

**Comment by openscript** [comment]
Soll bei den Spaltennamen der Modellname für die Vergütungskategorien wirklich hinzugefügt werden? Die Tabelle wird ziemlich breit.

Falls der Modellname hinzugefügt werden soll, muss dies auch bei

- Bezeichnung Kursleitung
- Bezeichnung Klassenleitung

gemacht werden?
