### ISSUE TITLE
EVENTS: Kursarten Erweiterung Vergütungskategorien

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#643]
blocked by #683, #684

Als Admin möchte ich bei den Kursarten Kursvergütungskategorien (`course_compensation_category`) konfigurieren können.

Neu werden auf der Kursart folgende Felder hinzugefügt (nach Minimale Teilnehmerzahl):

- Ideale Klassengrösse / `ideal_class_size`, integer, nullable
- Maximale Klassengrösse / `maximum_class_size`, integer, nullable
- Maximalalter / `maximum_age`, integer, nullable

Zusätzlich gibt es eine neue has and belongs to many Beziehung zu den Kursvergütungskategorien. Diese sollen analog zu den Qualifikationen als Mehrfachauswahl zugeordnet werden können. Es stehen nur Kursvergütungskategorien vom Typ `day` und `flat` zur Auswahl. Das Eingabefeld erscheint unterhalb Kostenträger.

# ToDo

- [x] Model/View/Controller anpassen
  - [x] Migration für Zwischentabelle hinzufügen
  - [x] `has_and_belongs_to_many` von Kursarten zu Kursvergütungskategorien hinzufügen
- [x] Specs schreiben
- [x] Mit angemessener Rolle "durchklicken"

**Comment by openscript** [comment]
Offene Fragen:

- [ ] Sollen Indizes in der Join-Table gesetzt werden?

**Comment by openscript** [comment]
Hallo @codez 

Ich bin dabei das UI für dieses Issue anzupassen.

Soll die Auswahl der Kompensationskategorien nach den FiVer-Ids und vor den 

![image](https://github.com/user-attachments/assets/1110c0ec-11b1-4128-b50d-57b4f0af4c48)

**Comment by codez** [comment]
@openscript Wie im Ticket erwähnt: "Das Eingabefeld erscheint unterhalb Kostenträger." Es braucht keine Zwischenüberschrift dazu. 

Bitte in der Join-Table Indizes hinzufügen.
