### ISSUE TITLE
PEOPLE: Bug in SAC Household Validierungen

### ISSUE THREAD

**Issue by daniel-illi** [hitobito/hitobito_sac_cas#646]
Im `Household` des SAC wagon wird validiert, dass die Personen keine Mitgliedschaft in einer anderen Sektion als die Referenzperson haben und es wird eine entsprechende Fehlermeldung angezeigt.

Die Fehlermeldung wird fälschlicher Weise auch angezeigt, wenn eine Person gar keine Mitgliedschaftsrolle besitzt.

Beim Analysieren des Bugs haben wir ausserdem bemerkt, dass es noch möglich ist, aus Personen welche keine Mitgliedschaftsrolle haben einen Haushalt zu bilden. Im SAC wagon entspricht ein Haushalt aber immer einer Familienmitgliedschaft, daher darf das nicht möglich sein. Es muss eine Validierung implementiert werden, dass mindestens eine Person bereits eine gültige Mitgliedschaft besitzt.

![Screenshot from 2024-06-17 10-48-15](https://github.com/hitobito/hitobito_sac_cas/assets/636849/d71be434-5675-4b35-b2ff-af53aa429d92)

![Screenshot from 2024-06-17 10-48-36](https://github.com/hitobito/hitobito_sac_cas/assets/636849/e86e84b2-81eb-4728-a005-0723771c9cdf)

# To-Do

- [ ] Validierung korrigieren: `assert_no_membership_in_other_section` nur wenn Mitglied Rolle vorhanden
- [ ] Validierung erstellen: Mindestens eine Person im Household ist Mitglied
- [ ] Specs schreiben
- [ ] Mit angemessener Rolle durchklicken

**Comment by Largo** [comment]
Dauerte eine Weile bis ich das nachstellen konnte. Es scheint das der Fehler nur Auftritt, wenn die andere Person Mitglied einer Stamm UND Zusatzsektion ist. Nur Stammsektion scheint kein Problem.

**Comment by Largo** [comment]
Im Gleichen habe ich nach Hinweis von @daniel-illi  ebenfalls die Validation eingeführt, dass validiert wird wenn keiner eine Mitgliedschaftsrolle in einer Sektion besitzt.
