### ISSUE TITLE
PEOPLE: Austrittsgründe verwalten

### ISSUE THREAD

**Issue by daniel-illi** [hitobito/hitobito_sac_cas#647]
Analog der Eintrittsgründe #112 soll eine neue CRUD Tabelle und View unter Einstellungen implementiert werden für "Austrittsgründe"

# Tech-Spec

Umsetzung im SAC wagon, analog https://github.com/hitobito/hitobito/pull/2223/files?w=1

- Migration:
  analog dem `db/migrate/20231016092502_create_self_registration_reasons.rb` im Core:
  - table `termination_reasons` mit timestamps
  - translation tables für Attribut `text`
  - auf `roles`: `references :termination_reason, foreign_key: true` 

- Neues Model: `TerminationReason` (analog `SelfRegistrationReason`)
  - translates `text`, string (globalize gem)
- Auf Model `Role`:
  - `termination_reason_id`, `belongs_to: :termination_reason`
- Ability `TerminationReasonAbility` analog `SelfRegistrationReasonAbility` (ohne feature gate)
- `TerminationReasonsController` analog `SelfRegistrationReasonsController`
- Sheet `Sheet::TerminationReason` analog `Sheet::SelfRegistrationReason`
- Einbinden in Navigation `app/views/shared/_admin_left_nav.html.haml`

# To-Do

- [x] Migration schreiben
- [x] Model implementieren/anpassen
- [x] Views implementieren/anpassen
- [x] Tests schreiben
- [x] Mit angemesser Rolle durchklicken
