### ISSUE TITLE
PEOPLE: Layout Mitgliederausweis verify page

### ISSUE THREAD

**Issue by daniel-illi** [hitobito/hitobito_sac_cas#673]
Auf der Mitgliederausweis verify page sollen einige Anpassungen vorgenommen werden.

Mockup: 
![f06c7595-99c7-4edc-affe-1fd70ec5baef](https://github.com/hitobito/hitobito_sac_cas/assets/636849/cece0e1b-ee4d-4d26-8ff2-1dfa5fd2714c)

# Tech-Spec

* Im Core:
  - view `app/views/people/membership/verify/show.html.haml` aufteilen:
    - `%header` extrahieren in partial `_header.html.haml`
    - `#details` extrahieren in partial `_details.html.haml`
    - `#footer` extrahieren in partial `_footer.html.haml`
  - in `details.html.haml` partial als erstes Element in `#details` ein `= render_extensions(:member_details_header)` einfügen.
  - Helper Methode schreiben für `membership_verify_logo` und diese im `_header.html.haml` verwenden statt direkt aus Settings lesen.

* Im SAC wagon: 
  - partial `_header.html.haml` mit leerem Inhalt erstellen um header auszublenden
  - partial `_member_details_header_sac_cas.html.haml` erstellen um Logo innerhalb detail block darzustellen. Z.B. so:
    ```haml
    %header
      #logo
        = wagon_image_pack_tag(membership_verify_logo, alt: Settings.application.name)
    ```
  - das `#sponsors` aus dem partial `app/views/people/membership/verify/_footer_sac_cas.html.haml` ins `app/views/people/membership/verify/_member_details_sac_cas.html.haml` verschieben als letztes Element

# To-Do

- [x] im Core Helper accessor schreiben für `membership_verify_logo`
- [x] im Core show view in partials aufteilen
- [x] im SAC wagon Helper accessor überschreiben für sprachspezifische Logos
- [x] im SAC wagon partials anpassen
- [ ] specs schreiben
- [ ] mit angemessener Rolle durchklicken

**Comment by amaierhofer** [comment]
LGTM 👍 , sind noch ein paar whitespaces in den commits drinnen, leerzeilen am ende vom partial die könntest du noch rausnehmen
