### ISSUE TITLE
PEOPLE: Wizard Beitritt Zusatzsektion Selfservice

### ISSUE THREAD

**Issue by daniel-illi** [hitobito/hitobito_sac_cas#708]
In #606 wurde der Wizard für den Beitritt in eine Zusatzsektion implementiert.
Die Spezifikation für den Step zur Sektionswahl enthält einen Fehler:
Bei Wahl einer Sektion mit Untergruppe `SektionsNeuanmeldungenSektion` wird für Mitglieder user eine Fehlermeldung angezeigt, dass kein "self-service" möglich ist und der Mitgliederdienst kontaktiert werden soll.
Diese Einschränkung gilt aber nur bei der Sektionswahl zum Sektionswechsel, nicht für Zusatzsektion Beitritt.

# Tech-Spec

Der Sektionswahlstep ist implementiert in `Wizards::Steps::ChooseSektion`.
Möglich wäre z.B. davon eine Subklasse `ChooseSektionUnrestricted` zu machen und da das `#self_service?` zu überschreiben und immer `true` zurück geben.
Damit dasselbe view partial verwendet wird, muss dann auf dem Step noch das class attribute gesetzt werden, etwa so: `self.partial='wizards/steps/choose_sektion'`

# ToDo

- [x] Domainklasse erstellen oder anpassen
- [x] Model/View/Controller anpassen
- [x] Specs schreiben
- [x] Mit angemessener Rolle "durchklicken"

**Comment by tobiasstern** [comment]
Wird von Stefan getestet, sobald alle HIT-355 related Issues geschlossen sind.
