### ISSUE TITLE
GROUPS: Anpassung Gruppen- und Rollentypen auf Ebene Sektion - the hitobito way

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito_sac_cas#716]
Als Sektion beim SAC
möchte ich andere Gruppen- und Rollentypen zu Verfügung haben,
um organisch und historisch gewachsene Sektionsstrukturen adäquat abzubilden.

Als Mitgliederverwaltung
möchte ich bei einigen spezifischen Rollentypen in der Sektion keine eingebackenen Berechtigungen haben, sondern die Berechtigungen via explizite Leserechts- und Schreibrechts-Rollen vergeben,
um komplexe und zwischen den Sektionen stark variierende Berechtigungskonstrukte abzubilden.

Neu sollen die verfügbaren Gruppen- und Rollentypen auf der Ebene Sektion / Ortsgruppe noch einmal angepasst werden.

# Mockup
<details>

<summary>Beispielhafter Output von `rake app:hitobito:roles`</summary>

```
    * Schweizer Alpen-Club SAC
      * SAC Geschäftsstelle
        * Mitarbeiter*in (schreibend): 2FA [:layer_and_below_full, :read_all_people]
        * Mitarbeiter*in (lesend): 2FA [:layer_and_below_read, :read_all_people]
        * Administration: 2FA [:layer_and_below_full, :admin, :impersonation, :read_all_people]
        * Andere: 2FA [:layer_and_below_read, :read_all_people]
      * SAC Geschäftsleitung
        * Geschäftsführung: 2FA [:layer_and_below_read, :read_all_people]
        * Ressortleitung: 2FA [:layer_and_below_read, :read_all_people]
        * Andere: 2FA [:layer_and_below_read, :read_all_people]
      * SAC Zentralvorstand
        * Präsidium: []
        * Mitglied: []
        * Andere: []
      * Kommission
        * Präsidium: []
        * Mitglied: []
        * Andere: []
      * Externe Kontakte
        * Kontakt: []
      * SAC Tourenportal
        * Abonnent: []
        * Neuanmeldung: []
        * Administration: []
        * Autor*in: []
        * Community: []
        * Andere: []
      * AboMagazin
        * Abonnent: []
        * Neuanmeldung: []
        * Autor*in: []
        * Andere: []
      * SAC/CAS Login
        * Basis Konto: []
      * Ehrenmitglieder
        * Ehrenmitglied: []
    * Sektion
    * Ortsgruppe
    * Global
      * Sektionsfunktionäre
        * Präsidium: []
        * Mitgliederverwaltung: []
        * Administration: 2FA [:layer_and_below_full]
        * Administration (nur lesend): 2FA [:layer_and_below_read]
        * Finanzen: []
        * Redaktion: []
        * Andere: []
        * Hüttenobmann*frau: 2FA []
        * Leserecht: [:group_and_below_read]
        * Schreibrecht: [:group_and_below_full]
      * Clubhütten
        * Leserecht: [:group_and_below_read]
        * Schreibrecht: [:group_and_below_full]
      * Clubhütte
        * Hüttenchef*in: []
        * Hüttenwart*in: []
        * Andere: []
      * Sektionshütten
        * Leserecht: [:group_and_below_read]
        * Schreibrecht: [:group_and_below_full]
      * Sektionshütte
        * Hüttenchef*in: []
        * Hüttenwart*in: []
        * Andere: []
      * Kommissionen
        * Leserecht: [:group_and_below_read]
        * Schreibrecht: [:group_and_below_full]
      * Kommission Hütten
        * Präsidium: [:group_read]
        * Mitglied: [:group_read]
        * Andere: [:group_read]
      * Kommission Touren
        * Präsidium: [:group_read]
        * Mitglied: [:group_read]
        * Andere: [:group_read]
      * Kommission Umwelt und Kultur
        * Präsidium: [:group_read]
        * Mitglied: [:group_read]
        * Andere: [:group_read]
      * Touren und Kurse
        * J+S Coach: []
        * JO-Chef*in: []
        * Tourenleiter*in (mit Qualifikation): []
        * Tourenleiter*in (ohne Qualifikation): []
        * Leserecht: [:group_and_below_read]
        * Schreibrecht: [:group_and_below_full]
      * Touren und Kurse Sommer
        * Tourenchef*in: [:group_read]
      * Touren und Kurse Winter
        * Tourenchef*in: [:group_read]
      * Vorstand
        * Präsidium: [:group_read]
        * Mitglied: [:group_read]
        * Andere: [:group_read]
        * Leserecht: [:group_and_below_read]
        * Schreibrecht: [:group_and_below_full]
      * Mitglieder
        * Mitglied (Stammsektion): []
        * Mitglied (Zusatzsektion): []
        * Ehrenmitglied: []
        * Begünstigt: []
        * Leserecht: [:group_and_below_read]
        * Schreibrecht: [:group_and_below_full]
      * Neuanmeldungen (zur Freigabe)
        * Neuanmeldung (Stammsektion): []
        * Neuanmeldung (Zusatzsektion): []
        * Leserecht: [:group_and_below_read]
        * Schreibrecht: [:group_and_below_full]
      * Neuanmeldungen
        * Neuanmeldung (Stammsektion): []
        * Neuanmeldung (Zusatzsektion): []
        * Leserecht: [:group_and_below_read]
        * Schreibrecht: [:group_and_below_full]
```

</details>

Beispiel wie die Navigation links in einer Sektion ungefähr aussehen könnte:

- Sektionsfunktionäre
  - Clubhütten
    - Hütte A
    - Hütte B
    - Hütte C
  - Sektionshütten
    - Hütte D
    - Hütte E
    - Hütte F
  - Kommissionen
    - Kommission Hütten
    - Kommission Touren
    - Kommission Umwelt und Kultur
  - Touren und Kurse
    - Touren und Kurse Sommer
    - Touren und Kurse Winter
  - Vorstand
- Mitglieder
- Neuanmeldungen
- Ohne Rollen

# Tech-Spec

- Umsetzung im SAC Wagon
- Die Gruppentypen (Klassennamen) sollen diesmal wieder korrekt umbenannt werden, damit die Bezeichnungen im Code und im UI nicht schon von Anfang an zu weit auseinanderdriften. Ein konkretes Beispiel ist der Gruppentyp Touren und Kurse, welcher aktuell im Code noch Tourenkommission heisst - Tourenkommission ist aber etwas anderes als Touren und Kurse.
- Diverse Datenimport-Skripts müssen nach diesem Umbau auch angepasst werden. Dies erfolgt in einem separaten Ticket
- Einige Gruppentypen und Rollentypen werden gelöscht. Diese können natürlich getrost aus der Datenbank gelöscht werden.
- Einige Gruppentypen werden neu in allen Sektionen einmalig angelegt. Existierende Gruppen dieser Typen können via Datenmigration zuerst herausgespült werden (inkl. Rollen in diesen Gruppen, Abos dieser Gruppen, etc.), bevor man dann die neuen Gruppen automatisiert anlegt.
- Die Gruppentypen Sektionshütten und Clubhütten sowie Kommission Hütten werden nach diesem PR noch nirgends präsent sein. Erst wenn das Hütten-Import-Skript angepasst und laufen gelassen wurde werden diese sichtbar und durch den SAC testbar sein.

# ToDo

- [x] Folgende Gruppentypen löschen:
  - [x] `Group::SektionsExterneKontakte` (wird nicht mehr benötigt)
  - [x] `Group::SektionsHuettenkommission` (diese Verschachtelung wird nicht mehr benötigt)
  - [x] `Group::SektionsHuette` (wird später ersetzt durch zwei separate Gruppentypen + erneuter verfeinerter Hütten-Import)
  - [x] `Group::SektionsKommission` (es gibt neu für den Moment keine generische Kommission mehr, nur noch spezialisierte)
  - [x] `Group::Tourenkommission` (diese Klasse ist aktuell eine Mischung von den Konzepten "Kommission Touren" und "Touren und Kurse", und soll daher nochmals abgeräumt und sauber durch die korrekten Gruppentypen ersetzt werden)
  - [x] Alle in diesen Gruppentypen enthaltenen Rollentypen mitlöschen
  - [x] Alle Translations dieser Gruppen- und Rollentypen mitlöschen
  - [x] Datenmigration: Alle Gruppen und Rollen dieser Typen aus der Datenbank löschen
  - [x] Datenmigration: Referenzen zu diesen Gruppen- und Rollentypen in persistierten Personenfiltern aufspüren und die entsprechenden Personenfilter löschen
  - [x] Datenmigration: Referenzen zu diesen Gruppen- und Rollentypen in Abos aufspüren und die entsprechenden Subscriptions löschen 
- [x] Neuer Gruppentyp `Group::SektionsClubhuetten`
  - [x] In children von `Group::SektionsFunktionaere` eintragen (aber nicht in `default_children`)
  - [x] `static_name = true` (Translation: "Clubhütten")
  - [x] Rollentypen:
    - [x] Leserecht (`group_and_below_read`)
    - [x] Schreibrecht (`group_and_below_full`)
- [x] Neuer Gruppentyp `Group::SektionsClubhuette`
  - [x] In children von `Group::SektionsClubhuetten` eintragen
  - [x] Rollentypen:
    - [x] Hüttenchef\*in (keine Permissions)
    - [x] Hüttenwart\*in (keine Permissions)
    - [x] Andere (keine Permissions)
- [x] Neuer Gruppentyp `Group::Sektionshuetten`
  - [x] In children von `Group::SektionsFunktionaere` eintragen (aber nicht in `default_children`)
  - [x] `static_name = true` (Translation: "Sektionshütten")
  - [x] Rollentypen:
    - [x] Leserecht (`group_and_below_read`)
    - [x] Schreibrecht (`group_and_below_full`)
- [x] Neuer Gruppentyp `Group::Sektionshuette`
  - [x] In children von `Group::Sektionshuetten` eintragen
  - [x] Rollentypen:
    - [x] Hüttenchef\*in (keine Permissions)
    - [x] Hüttenwart\*in (keine Permissions)
    - [x] Andere (keine Permissions)
- [x] Neuer Gruppentyp `Group::SektionsKommissionen`
  - [x] In children von `Group::SektionsFunktionaere` eintragen
  - [x] In default_children von `Group::SektionsFunktionaere` eintragen
  - [x] `static_name = true` (Translation: "Kommissionen")
  - [x] Rollentypen:
    - [x] Leserecht (`group_and_below_read`)
    - [x] Schreibrecht (`group_and_below_full`)
- [x] Neue Gruppentypen `Group::SektionsKommissionHuetten`, `Group::SektionsKommissionTouren` und `Group::SektionsKommissionUmweltUndKultur`
  - [x] In children von `Group::SektionsKommissionen` eintragen
  - [x] Rollentypen:
    - [x] Mitglied (`group_read`)
    - [x] Präsidium (`group_read`)
    - [x] Andere (`group_read`)
- [x] Neuer Gruppentyp `Group::SektionsTourenUndKurse`
  - [x] In children von `Group::SektionsFunktionaere` eintragen
  - [x] In default_children von `Group::SektionsFunktionaere` eintragen
  - [x] `static_name = true` (Translation: "Touren und Kurse")
  - [x] Rollentypen:
    - [x] J+S Coach (keine Permissions)
    - [x] JO-Chef\*in (keine Permissions)
    - [x] Tourenleiter\*in (mit Qualifikation) (keine Permissions, Code übernehmen von der vormaligen Rolle in `Group::Tourenkommission`, Referenzen im Repo zu alter Rolle auf neue Rolle ändern)
    - [x] Tourenleiter\*in (ohne Qualifikation) (keine Permissions, Code übernehmen von der vormaligen Rolle in `Group::Tourenkommission`, Referenzen im Repo zu alter Rolle auf neue Rolle ändern)
    - [x] Leserecht (`group_and_below_read`)
    - [x] Schreibrecht (`group_and_below_full`)
- [x] Neue Gruppentypen `Group::SektionsTourenUndKurseSommer` und `Group::SektionsTourenUndKurseWinter`
  - [x] In children von `Group::SektionsTourenUndKurse` eintragen
  - [x] Rollentypen:
    - [x] Tourenchef\*in (`group_read`)
- [x] Neue Rollen `Huettenobmann` (Translation: "Hüttenobmann*frau", keine Permissions), Leserecht (`group_and_below_read`) und Schreibrecht (`group_and_below_full`) in `Group::Sektionsfunktionaere` anlegen
- [x] Neue Rollen Leserecht (`group_and_below_read`) und Schreibrecht (`group_and_below_full`) in `Group::SektionsVorstand` anlegen
- [x] Neue Rollen Leserecht (`group_and_below_read`) und Schreibrecht (`group_and_below_full`) in `Group::SektionsMitglieder` anlegen
- [x] Neue Rollen Leserecht (`group_and_below_read`) und Schreibrecht (`group_and_below_full`) in `Group::SektionsNeuanmeldungenNv` anlegen
- [x] Neue Rollen Leserecht (`group_and_below_read`) und Schreibrecht (`group_and_below_full`) in `Group::SektionsNeuanmeldungenSektion` anlegen
- [x] Rollen Mitgliederverwaltung und Präsidium in `Group::Sektionsfunktionaere` haben neu keine Permissions mehr
- [x] Rollen Mitglied, Präsidium und Andere in `Group::SektionsVorstand` haben neu alle die Permission `group_read`
- [x] Rollen Mitgliederverwaltung und Hüttenobmann\*frau in `Group::Sektionsfunktionaere` brauchen keine erzwungene 2FA mehr
- [x] In allen in diesem Issue erwähnten Rollentypen `basic_permissions_only = true` setzen, wenn die Rolle keine Permissions hat
- [x] Datenmigration: In `Group::Sektion`, `Group::Ortsgruppe` und `Group::SektionsFunktionaere` die default_children anlegen (siehe [diese Migration](https://github.com/hitobito/hitobito_sac_cas/blob/master/db/migrate/20240605120000_move_more_groups_into_sektionsfunktionaere.rb#L41..L50) wo das schon mal gemacht wurde)
- [x] Datenmigration: In `Group::SektionsKommissionen` je eine Untergruppe vom Typ `Group::SektionsKommissionTouren` und `Group::SektionsKommissionUmweltUndKultur` anlegen. Diese sind nicht default_children, aber müssen jetzt einmalig bei allen Sektionen angelegt werden.
- [x] Datenmigration: In `Group::SektionsTourenUndKurse` je eine Untergruppe vom Typ `Group::SektionsTourenUndKurseSommer` und `Group::SektionsTourenUndKurseWinter` anlegen. Diese sind nicht default_children, aber müssen jetzt einmalig bei allen Sektionen angelegt werden.
- [x] OIDC Claim `user_groups` folgendermassen anpassen:
  - [x] `section_commission_member` wird neu ausgegeben, wenn man eine beliebige Rolle in einer beliebigen Untergruppe von Kommissionen hat
  - [x] `huts_functionary` wird neu ausgegeben, wenn man eine Rolle Hüttenchef\*in, Hüttenwart\*in oder Hüttenobmann\*frau hat
  - [x] `section_tour_functionary` wird neu ausgegeben, wenn man eine Rolle J+S Coach, JO-Chef\*in oder Tourenleiter\*in (mit oder ohne Qualifikation) hat
- [x] Manuelles Testen der Datenmigrationen mit Produktionsdatendump, um sicherzustellen dass es auch funktioniert
- [x] Bestehende Specs anpassen bis grün
- [x] Gruppenstruktur im README des Wagons aktualisieren
- [ ] Kunde wegen Übersetzungen informieren
- [ ] Mit angemessener Rolle "durchklicken"
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen
