### ISSUE TITLE
IMPORT: Anpassung Hütten-Import-Skript auf Ebene Sektion

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito_sac_cas#717]
Blocked by #716

Als Sektion beim SAC
möchte ich alle Hütten der Sektion auf hitobito verfügbar haben,
um diese Daten verwalten zu können.

Neu soll das bestehende Hütten-Datenimport-Skript an die in #716 angepassten Gruppentypen angepasst werden.

# Tech-Spec

- Umsetzung im SAC Wagon
- Es gibt bereits einen [Import für Hütten und einige Funktionäre innerhalb und ausserhalb der Hütten](https://github.com/hitobito/hitobito_sac_cas/blob/master/app/domain/import/huts_importer.rb)
- Teils werden in #716 die Klassennamen angepasst, teils auch die Gruppenstruktur (welche Gruppentypen wo erlaubt sind)
- Es wurde inzwischen eine neue Import-Datei mit einer zusätzlichen Spalte Hüttenkategorie zu Verfügung gestellt, mit welcher wir den Import von nun an durchführen sollen. Datei ist auf [Confluence](https://saccas.atlassian.net/wiki/spaces/RDIE/pages/3883040775/Datenmigrationskonzept#Export%2FImport-Dateien) unter dem Namen "Hütten_Beziehungen_Export_20230704_überarbeitet.xlsx", oder alternativ @carlobeltrame fragen
- Wir müssen anhand der neuen Spalte jetzt verschiedene Typen von Hütten unterscheiden. Privathütten sollen momentan noch ganz ignoriert werden, diese gehören zum Dachverband und werden erst in späteren Issues behandelt. Auf der Ebene Sektion gibt es Clubhütten und Sektionshütten.

# ToDo

- [x] `Import::Huts::HutComissionRow` ~~so anpassen, dass sie stattdessen nach Verteilercode `4000V` sucht~~
  - [x] In `self.can_process?` zusätzlich noch überprüfen, ob die Spalte "Hüttenkategorie" den Wert SAC Sektionshütte oder SAC Clubhütte hat. Zeilen mit Wert Privat werden für den Moment ignoriert.
  - [x] ~~4000V ist die umgekehrte Beziehung von 4000, daher statt der Spalte `contact_navision_id` neu die Spalte `related_navision_id` verwenden~~
  - [x] Die Gruppe die in diesem Importer erstellt werden soll ist neu `Group::SektionsKommissionHuetten`, statt wie bisher `Group::SektionsHuettenkommission`, und sie hängt nicht mehr an Sektion -> SektionsFunktionaere, sondern neu an Sektion -> SektionsFunktionaere -> SektionsKommissionen
- [x] `Import::Huts::HutRow` ~~so anpassen, dass sie stattdessen nach Verteilercode `4000V` sucht~~
  - [x] In `self.can_process?` zusätzlich noch überprüfen, ob die Spalte "Hüttenkategorie" den Wert SAC Sektionshütte oder SAC Clubhütte hat. Zeilen mit Wert Privat werden für den Moment ignoriert.
  - [x] ~~4000V ist die umgekehrte Beziehung von 4000, daher statt der Spalte `contact_navision_id` neu die Spalte `related_navision_id` verwenden~~
  - [x] Die Gruppe die in diesem Importer erstellt werden soll ist neu entweder `Group::Sektionshuette` oder `Group::SektionsClubhuette` (je nach Spalte Hüttenkategorie), statt wie bisher `Group::SektionsHuette`, und sie hängt nicht mehr an Sektion -> SektionsHuettenkommission, sondern neu an Sektion -> SektionsFunktionaere -> Sektionshuetten oder an Sektion -> SektionsFunktionaere -> SektionsClubhuetten (je nach Spalte Hüttenkategorie)
  - [x] Der Parent (Sektionshuetten oder SektionsClubhuetten) soll dynamisch beim Importieren der Hütte erstellt werden, sodass er nur in denjenigen Sektionen vorhanden ist wo es auch wirklich Hütten dieser Kategorie hat
- [x] Die restlichen Rows importieren alles einzelne Rollen. Diese folgendermassen anpassen:
  - [x] In `self.can_process?` zusätzlich noch überprüfen, ob die Spalte "Hüttenkategorie" den Wert SAC Sektionshütte oder SAC Clubhütte hat. Zeilen mit Wert Privat werden für den Moment ignoriert.
  - [x] Die Rollen die in diesen Importern erstellt werden sollen existieren alle weiterhin, aber sind an neuen Gruppentypen angehängt. Unter anderem gibt es mit #716 separate Gruppentypen für Sektionshuette und SektionsClubhuette, der korrekte Gruppentyp hängt somit von der Spalte Hüttenkategorie ab.
- [ ] Import-Skript manuell testen
- [x] Specs für die Importer anpassen
- [ ] Nach Merge Import auf sac-cas.puzzle.ch durchführen
