### ISSUE TITLE
PEOPLE: Memberships::LeaveZusatzsektion erweitern

### ISSUE THREAD

**Issue by daniel-illi** [hitobito/hitobito_sac_cas#718]
blocked by #627

In #652 wurde `Memberships::LeaveZusatzsektion` implementiert. Diese soll erweitert werden, um auf den gekündigten Rollen den Austrittsgrund zu speichern.
Dasselbe wurde bereits in `Memberships::TerminateSacMembership` implementiert, es soll hier gleich gelöst werden.

# Tech-Spec

* In `Memberships::LeaveZusatzsektion`:
  * `attribute :termination_reason_id, :integer` und Validierung wie in `TerminateSacMembership`
  * in `#roles` die `termination_reason_id` auf Rollen assignen
* In `Wizards::Memberships::LeaveZusatzsektion`:
  * in `#leave_operation` die `termination_reason_id` als named param dem `Memberships::LeaveZusatzsektion::new` übergeben

# ToDo

- [x] `Memberships::LeaveZusatzsektion` anpassen
- [x] `Wizards::Memberships::LeaveZusatzsektion` anpassen
- [x] specs schreiben
- [x] mit angemessener Rolle durchklicken

**Comment by tobiasstern** [comment]
Wird von Stefan getestet, sobald alle HIT-355 related Issues geschlossen sind.
