### ISSUE TITLE
ROLES: Import aller aktiven und inaktiven Stammsektions-Rollen

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#726]
## Source File

Aktuell wird der Import folgendermassen gestartet: `rails import:memberships FILE=tmp/xlsx/mitglieder_aktive.xlsx REIMPORT_ALL=true)`

- den FILE Parameter komplett entfernen rake import:people REIMPORT_ALL=true
    - Verwendet automatisch das erste File das RAILS_CORE_ROOT/tmp/xlsx/NAV2_*.xlsx matched
    - Siehe auch [import.md](https://github.com/hitobito/hitobito_sac_cas/blob/master/doc/import.md#source-files)

## Importieren aktive/inaktive Mitgliedschaften

Wir importieren neue alle Mitgliedschaften die im Export File (NAV2) vorhanden sind.
Also auch Mitgliedschaften die in der Vergangenheit liegen (von und bis in der Vergangenheit). Dies wird benötigt damit die korrekte Anzahl Mitgliederjahre berechnet werden kann. Siehe auch #742 

## Anpassungen Sac Family (Household)

Wir vertrauen das die zu importierenden Daten richtig daher kommen und machen keine Validierungen wie beim manuellen erstellen von Familien. 

- Verwenden der neuen Household Domain class (anstatt Person::Household, models/household.rb) 
  - maintain_sac_family: false (Rollen werden via Importer angelegt)
  - familiy_main_person ebenfalls via Importer setzen (beitragskategorie Familie, nicht Frei Fam, nicht Frei Kind)

## CSV Report

![image](https://github.com/user-attachments/assets/8fb99667-485d-4c38-b9fc-9d7936223f15)

Der in https://github.com/hitobito/hitobito_sac_cas/issues/742 eingeführte CSV Report soll auch für diesen Import hier verwendet werden.

# Tech-Spec

- https://github.com/hitobito/hitobito_sac_cas/blob/master/app/domain/import/sektion/memberships_importer.rb
- https://github.com/hitobito/hitobito_sac_cas/blob/master/app/domain/import/sektion/membership.rb
- Beim Editieren der XLSX Dateien mit LibreOffice werden diese korrupt, die meisten Specs verwenden aus diesem Grund mocking

# ToDo

- [ ] FILE parameter entfernen und NAV2 File als Input verwenden
- [ ] CSV Report implementieren
- [ ] Sicherstellen das alle Aktiven/Inaktiven Rollen sauber importiert werden
- [ ] Sicherstellen das Familien richtig angelegt werden
- [ ] Updaten [import.md](https://github.com/hitobito/hitobito_sac_cas/blob/master/doc/import.md)

**Comment by mtnstar** [comment]
wird durch #757 erledigt
@openscript ggf. möchtest du Inhalte von hier noch übertragen?
ich schliesse dieses Ticket hier mal
