### ISSUE TITLE
PEOPLE: Import `6_membership_years_report` erstellen 

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#742]
Die Anzahl Mitgliederjahre eines Mitglieds wird heute als eigenes Integer Attribut geführt welches jährlich vom System inkrementiert wird. 
In Hitobito wird die Anzahl Mitgliederjahre aufgrund der Dauer der Stammsektions-Mitgliedrolle berechnet. siehe #85 
Dieser neue Report soll die Differenz zwischen der in Navision vorhandenen und der in Hitobito berechneten Anzahl Mitgliederjahre ausgeben.

CSV Report

![image](https://github.com/user-attachments/assets/0baa6e8f-70f6-4e00-9f13-320435952e5a)

`rake import:membership_years_report`

Benötigt Export File ~NAV2~ NAV1 [import.md](https://github.com/hitobito/hitobito_sac_cas/blob/master/doc/import.md)

Verwendet automatisch das erste File das `RAILS_CORE_ROOT/tmp/sac_imports_src/NAV1_*.csv` matched.

CSV Report wird laufend appended:  `RAILS_CORE_ROOT/log/sac_imports/membership_years_report_2024-07-31-10:42.csv`

Datum/Zeit im Dateinamen wird mit dem Start des Scripts definiert.

# Tech-Spec

- Neue Klasse: SacImports::CsvLog
  - append_row(row)
  - initialize(import_name, headers)
  - Creates and appends CSV file: `RAILS_CORE_ROOT/log/sac_imports/membership_years_report-2024-07-18-14:42.csv`
  - creates `RAILS_CORE_ROOT/log/sac-imports/` directory if it does not exist
  - `RAILS_CORE_ROOT/log/sac_imports/`  will be mounted to PV in int/prod

# ToDo

- [x] CSV Log Klasse erstellen und Funktionalität implementieren
- [x] Report Mitgliederjahre implementieren
- [x] Updaten [import.md](https://github.com/hitobito/hitobito_sac_cas/blob/master/doc/import.md)

**Comment by mtnstar** [comment]
@openscript könntest du hier mal als Einstieg in die Import-Thematik ein Review machen?

auch doc/import.md mal studieren. 

Auf Basis dieser Änderungen werden wir dann die weiteren Imports implementieren

**Comment by openscript** [comment]
Wie wird dieser Import benutzt? Via Rake Tasks oder wird es später noch ein UI geben?
