### ISSUE TITLE
PEOPLE:  Import `1_people` umstellen auf CSV-Report und CSV-Source

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#767]
Seit #750 gibt es `SacImports::CsvReport` für einen Import-Report sowie `SacImports::CsvSourceFile` um Exporte aus Navision einzulesen. Neu wechseln wir von `xlsx`-Dateien Source zu `csv`-Dateien.

Der Import `1_people` existiert bereits und wird mit diesem Ticket angepasst:

- Es wird neu ein CSV Report während dem Import generiert der dem SAC zugestellt werden kann. So sieht der SAC welche Personen nicht importiert werden konnten
- Als Basis für diesen Import dient neu eine CSV Datei (NAV1)
- Geburtsdatum nur importieren falls Person nicht älter als 110 Jahre alt !

Siehe dazu auch die Dokumentation [`import.md`](https://github.com/hitobito/hitobito_sac_cas/blob/master/doc/import.md).

**User Stories**:

- Als Systemintegrator möchte ich einmalig alle Personen von einer aus Navision exportierten `csv`-Datei einmalig importieren können, damit die Daten aus dem Vorgängersystem migriert werden können.
- Als Systemintegrator möchte ich vom Importvorgang einen Bericht (Report) erhalten, damit die Daten bereinigt werden können.

# Tech-Spec

Die angehängten Beispieldaten sollen als Fixture eingefügt werden. Mit den Spaltennamen und dem bestehenden Modell, soll das Attribut-Mapping `NAV1` erstellt werden. Anschliessend soll in `person_entry.rb` das Mapping der Inhalte kontrolliert und ggf. angepasst werden. Es soll ein Rake Task für `1_people` erstellt werden. Schlussendlich sollen die zugehörigen Tests angepasst werden:
  - [x] `spec/domain/sac_imports/csv_source_file_spec.rb`
  - [x] `spec/domain/sac_imports/csv_report_spec.rb`
  - [x] `spec/domain/sac_imports/sektion/additional_membership_importer_integration_spec.rb`
  - [x] `spec/domain/sac_imports/people_importer_spec.rb`
  - [x] `spec/domain/sac_imports/person_entry_spec.rb`

## Attribut-Mapping

 Der folgende Hash beschreibt das Attribut-Mapping, wobei der `key` das Modell-Attribut und die `value` die CSV-Spalte beschreibt:

```ruby
{
      navision_id: "No_", # Früher Mitgliedernummer
      person_type: "Personentyp", # Entfernen
      salutation: "Salutation Code", # Entfernen
      name: "Name", # Entfernen
      first_name: "First Name", # Früher Vorname
      last_name: "Surname", # Früher Nachname
      postbox: "Postfach", # Adresse 2
      address: "Address", # Entfernen
      street: "Street Name", # Neu
      housenumber: "Street No_", # Neu
      country: "Country_Region Code", # Früher Länder-/Regionscode (falls nicht gesetzt -> CH)
      town: "City", # Früher Ort
      zip_code: "Post Code", # Früher PLZ
      email: "E-Mail", # Unverändert
      phone_private: "Telefon", # Phone No_, wird in Hitobito phone_number Privat
      phone_direct: "Telefon direkt", # Entfernen
      phone_mobile: "Mobiltelefon", # Entfernen
      birthday: "Date of Birth", # Früher Geburtsdatum (Nur importieren falls Person nicht älter als 110 Jahre)
      gender: "Geschlecht", # Achtung: Inhalt-Mapping verändert (0 ist m und 1 ist w)
      language: "Language Code" # Früher Sprachcode,
      sac_remark_section{1,2,3,4,5}: "Sektionsinfo {1,2,3,4,5} Bemerkung", Datums-Spalte ignorieren
      sac_remark_national_office: "Geschäftsstelle Bemerkung"
}
```

## `csv`-Report

Vom Import soll ein `csv`-Report mit folgenden Spalten und Inhalten erstellt werden, wobei pro importierter Zeile einen Eintrag erstellt wird, der bei Fehlern in der `errors` Spalte eine Beschreibung des Fehlers enthält:

- `membership_number`: `navision_id`
- `person_name`: `name`
- `errors`: ActiveRecord::RecordInvalid mit Custom Message

# ToDo

- [x] Fixture als `hitobito_sac_cas/spec/fixtures/files/sac_imports_src/NAV1.csv` einfügen (**Anonymisieren!**)
- [x] `NAV1` Attribut-Mapping in `SacImports::CsvSourceFile` umsetzen/anpassen
- [x] FILE param im Rake task entfernen
- [x] Personeneinträge importieren (Inhalts-Mapping) in `app/domain/sac_imports/person_entry.rb` anpassen
- [x] `csv`-Report `1_people` umsetzen
- [x] Rake Task in `lib/tasks/sac_imports.rake` erstellen/anpassen
- [x] Rake Task mit Fixture ausprobieren
- [x] Rake Task mit `REIMPORT_ALL` und Fixture ausprobieren
- [x] import.md aktualisieren
- [x] Specs anpassen
- [x] Aufräumen
  - [x] `kontakte.xlsx` löschen
