### ISSUE TITLE
GROUPS: Anpassungen Gruppenstruktur Toplayer > Abonnenten

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#768]
Mit diesem Ticket sollen einige Anpassungen an der Gruppenstruktur der Abonnenten auf dem Toplayer vorgenommen werden. Aktuell sieht die Struktur folgendermassen aus:

![image](https://github.com/user-attachments/assets/054b907d-268e-4df4-87e8-eea8decf6f4e)

## Neue Gruppenstruktur

- SAC/CAS
  - SAC Abos (ohne Newsletter)
    - SAC-Magazin
      - Die Alpen DE
      - Le Alpi IT
      - Les Alpes FR
    - SAC-Tourenportal
    - SAC/CAS Login

Die bestehenden Gruppen können einfach manuell hard-deleted werden auf der Integrationsumgebung, es braucht also keine DB-Migration für diese Änderungen.

SAC Tourenportal renamen in SAC-Tourenportal (translation anpassen)

## Neue Rollen / Anpassungen Rollen

Alle Rollen ohne Berechtigungen.

- SAC Abos (ohne Newsletter)
  - SAC-Magazin (Autor\*in, Andere, Übersetzer\*in)
    - Die Alpen DE (bestehende + Autor\*in entfernen)
    - Le Alpi IT (bestehende + Autor\*in entfernen)
    - Les Alpes FR (bestehende + Autor\*in entfernen)
  - SAC-Tourenportal (bestehende + Gratisabonnent)
  - SAC/CAS Login (keine Änderungen)

# Tech-Spec

- https://github.com/hitobito/hitobito_sac_cas/blob/master/app/models/group/abonnenten.rb
- https://github.com/hitobito/hitobito_sac_cas/blob/master/app/models/group/abo_magazin.rb
- Neue Gruppenstruktur in Seeds (auch für nicht Development)

# ToDo

- [x] Anpassungen Gruppen/Rollen wie oben beschrieben (Klassennamen können angepasst werden, Translations anpassen, nicht mehr verwendete Translations löschen)
- [x] Seeds sowie Test Fixtures entsprechend anpassen
- [ ] Löschen der bestehenden Gruppen auf der Integrationsumgebung (rails console, group.really_destroy!)
- [x] Neuanlegen der Gruppen (ggf. in Seeds?)
- [ ] Infos an die Devs das die Entwickler-DB gespühlt werden soll
