### ISSUE TITLE
PEOPLE: Import `nav2-1_membership_roles` implementieren

### ISSUE THREAD

**Issue by openscript** [hitobito/hitobito_sac_cas#770]
Der existierende Import `4_memberships` wird neu implementiert als `nav2-1_roles`

- Es wird ein CSV Report während dem Import generiert der dem SAC zugestellt werden kann. So sieht der SAC welche Rollen nicht importiert/zugewiesen werden konnten.
- Als Basis für diesen Import dient neu eine `csv`-Datei (NAV2). Dieses File enthält alle Rollen aus Navision, z.B.  
  >Mitglied (Stammmsektion), Mitglied (Zusatzsektion), Ehrenmitglied, Begünstigt, Administration, Finanzen, Mitgliederverwaltung, Präsidium, Redaktion, J+S Coach, JO-Chefin, Tourenchefin, Tourenleiterin (mit Qualifikation), Tourenleiterin (ohne Qualifikation), Andere, Hüttenobmannfrau, Hüttenchefin, Hüttenwartin, Geschäftsführung, Ressortleitung, Mitglied Vorstand, Mitglied Kommission, Präsidium Vorstand, Präsidium Kommission, Autorin, Abonnenten, Community usw.

  Zu jeder Rolle steht im file 
    - Person ID
    - Gruppenhierarchie
    - Rollenbezeichnung
    - Start- und Enddatum der Gültigkeit

- Es werden alle Rollen importiert, zu welchen wir die Gruppenhierarchie und die Rollenbezeichnung auf das Pendant bei Hitobito mappen können. Gruppen und Rollentypen die wir nicht mappen können müssen im import log aufgelistet werden.

- Einige Rollentypen haben Validierungen, welche die Existenz einer entsprechenden Mitgliedschaftsrolle prüfen. Zudem muss bei Familienmitgliedschaften die Familienhauptperson markiert werden. Falls die Famlienhauptperson historisch gewechselt hat, darf nur die Hauptperson nach dem letzten Stand markiert werden. Daher soll mehrmals über das file iteriert werden und diese Aktionen ausgeführt werden:
  1. Rollen vom Typ `Mitglied (Stammsektion)` importieren, dabei die Familiennummern zu allen Familienmitgliedschaften merken. Familienmitgliedschaften auf Personen welche keine Familiennummer haben überspringen und im import log loggen
  2. alle anderen Rollentypen importieren
  3. Zu allen Familiennummern aus Schritt 1 die letztgültige `Mitglied (Stammsektion) (Familie)` finden und Person als `family_main_person` markieren

Siehe dazu auch die Dokumentation [`import.md`](https://github.com/hitobito/hitobito_sac_cas/blob/master/doc/import.md).

**User Stories**:

- Als Systemintegrator möchte ich einmalig alle Mitgliedschaften von einer aus Navision exportierten `csv`-Datei einmalig importieren können, damit die Daten aus dem Vorgängersystem migriert werden können.
- Als Systemintegrator möchte ich vom Importvorgang einen Bericht (Report) erhalten, damit die Daten bereinigt werden können.

# Tech-Spec

- Angehängten Beispieldaten als Fixture eingefügen 
- Attribut-Mapping in `SacImports::CsvSourceFile::SOURCE_HEADERS['NAV2']` nachführen.
- `SacImports::RolesImporter` implementieren:
  - jede row als Rolle importieren
  - mehrmals iterieren und selektiv Rollen importieren wie oben beschrieben
  - Gruppe und Rollentyp auf hitobito mappen, loggen falls keine Entsprechung gefunden werden kann
  - Start- und Enddatum: mit hitobito/hitobito#2775 läuft die Umstellung auf explizite Gültigkeit der Rollen. Sobald das umgesetzt ist, entsprechen die Daten den Attributen `start_on`, `end_on`. Falls die Umstellung noch nicht implementiert ist, sollen die Daten wie bisher auf `created_at`/`deleted_at` übernommen werden.
- Rake task `sac_imports:4_memberships` umbenennen nach `sac_imports:4_roles`
  - FILE param entfernen
  - neuen `RolesImporter` verwenden
- obsolete files entfernen:
  - `app/domain/sac_imports/sektion/*`
  - `spec/domain/sac_imports/sektion/*`

## Attribut-Mapping

 Der folgende Hash beschreibt das Attribut-Mapping, wobei der `key` das Modell-Attribut und die `value` die CSV-Spalte beschreibt:

```ruby
{
        navision_id: "Kontaktnummer", # Früher Mitgliedernummer
        start_on: "GültigAb",
        end_on: "GültigBis",
        layer: "Layer",
        group_lvl1: "Gruppe_Lvl_1",
        group_lvl2: "Gruppe_Lvl_2",
        group_lvl3: "Gruppe_Lvl_3",
        group_lvl4: "Gruppe_Lvl_4",
        description: "Zusatzbeschrieb"
}
```

## `csv`-Report

Vom Import soll ein `csv`-Report mit folgenden Spalten und Inhalten erstellt werden, wobei pro importierter Zeile einen Eintrag erstellt wird, der bei Fehlern in der `errors` Spalte eine Beschreibung des Fehlers enthält:

- `navision_id`: `navision_id` (Person#id)
- `navision_name`: `name` (Person#id)
- `layer`: `layer`
- `group`: [group_lvl1, group_lvl2, group_lvl3, group_lvl4].compact.join('/')
- `errors`: ActiveRecord::RecordInvalid mit Custom Message, weshalb kein Import der Zeile möglich war
- `warnings`: Alles Messages der Validierung

# ToDo

- [x] Fixture als `spec/fixtures/files/sac_imports_src/NAV2_memberships_2024-01-04.csv` einfügen
- [x] `NAV2` Attribut-Mapping in `SacImports::CsvSourceFile` umsetzen/anpassen
- [x] `SacImports::RolesImporter` implementieren
- [x] obsolete files entfernen
- [x] Rake Task anpassen `rails sac_imports:nav2-1_membership_roles`
- [x] `SacImports::MembershipRolesImporter` implementieren
- [x] import.md aktualisieren
- [ ] Weitere Tickets für nicht Mitglieder-Rollen erstellen

# Fälle

- [x] Zeilen mit TODO
- [x] Person nicht gefunden
