### ISSUE TITLE
PEOPLE: QR Code Mitgliederausweis auf Profil

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#78]
>Als SAC Mitglied  
will ich den Mitgliederausweis auf meinem Hitobito Profil anzeigen   
um mich auszuweisen.

>Als SAC Hüttenwart will ich  
den Mitgliederausweis QR Code eines Kunden scannen  
um zu prüfen, ob die Mitgliedschaft gültig ist.

Der PDF Ausweis wie er im Prototyp vorhanden ist wird entfernt und es soll direkt ein QR-Code angezeigt werden. 

![329987697-8c591d60-f23b-43fc-b683-87c6246c79de](https://github.com/hitobito/hitobito_sac_cas/assets/636849/d99ed968-e89b-465c-a809-bfb4101d0e24)

Smart-Phone view:

![329987887-c2551533-d26b-42e3-841f-fd116be97ff3](https://github.com/hitobito/hitobito_sac_cas/assets/636849/02364a0d-7f2c-494a-9d2d-945ae6d8cc83)

> [!IMPORTANT]
> In den Mockups wird auf dem QR Code ein SAC Logo angezeigt.
> Für das MVP rendern wir den QR Code aber OHNE Logo.

# Tech-Spec

* Sektion "Dokumente" und Link auf Mitgliederausweis entfernen
* Domain Klasse implementieren zum Rendern des QR Codes, z.B. `app/domain/people/membership/verify_qr_code.rb`  (neu aus dem Core)
  code kann von `https://github.com/hitobito/hitobito_sac_cas/blob/4e7f1a5e2d4159d0f400ff0d0c32858161df1606/app/domain/export/pdf/passes/membership/person.rb#L45 extrahiert werden
* QR code auf person#show view anzeigen analog mockup
* https://github.com/hitobito/hitobito/blob/master/doc/modules/people.md#qr-code
* QR Code wird angezeigt wenn die Person eine aktive Mitgliedschaft hat oder eine in der Vergangenheit hatte (any membership methode)

# ToDo

- [ ] Sektion "Dokumente" und Link auf Mitgliederausweis entfernen (inkl. PDF domain class entfernen)
- [x] QR Code rendering implementieren
- [x] QR Code auf person#show view anzeigen analog mockup
- [x] Specs schreiben
- [x] Mit angemessener Rolle durchklicken

**Comment by tobiasstern** [comment]
@daniel-illi für den Button ist "+" das falsche icon. Bitte das download icon verwenden.

**Comment by Largo** [comment]
PDF domain class lasse ich  wegen #530 drin
