### ISSUE TITLE
INVOICE: Jahresinkasso Background Job

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#803]
Als SAC Backoffice MA möchte ich für alle SAC Mitglieder einen automatischen Jahresinkassolauf Job laufen lassen können.

Im Dialog aus #802 werden die Parameter für den Jahresinkassolauf abgefragt. In diesem Ticket wird der zugehörige Background Job `Invoices::Abacus::CreateYearlyInvoicesJob` umgesetzt (Entwurf existiert bereits teilweise).

## Argumente

Der Job nimmt folgende Argumente entgegen:
- `invoice_year`: Rechnungsjahr
- `invoice_date`: Rechnungsdatum
- `send_date`: Versanddatum
- `role_finish_date`: Rollen verlängern bis Datum, optional

## Ablauf

Falls bereits ein solcher Job existiert (egal welche Argumente, jedoch ohne failed_at), wird der vorliegende direkt beendet.

### Rollen verlängern

Falls `role_finish_date` leer ist, wird dieser Schritt übersprungen.

Die Domainklasse `Invoices::SacMembership::ExtendRolesForInvoicing.new(role_finish_date).perform` (#869) wird aufgerufen.

#### Relevante Personen

Für alle Personen, welche
 
- eine Mitglied-Stammsektion Rolle (`Group::SektionsMitglieder::Mitglied`) haben, welche am 1.1. des Rechnungsjahres gültig ist, *UND*
- keine Datenqualitätsfehler haben (`Person#data_quality != :error`, #791), *UND*
- eine Abacus Subject ID (`abacus_subject_key`) haben, *UND*
- keine Mitgliedschaftsrechnung im gewählten Rechnungsjahr haben (`ExternalInvoice::SacMembership#year`)

werden die Mitgliedschaftrsrechnungen erzeugt und an Abacus übermittelt.

#### Übermittlung (Prototyp existiert bereits)

Als Stichdatum für den `Invoices::SacMemberships::Context` dient der 1.1. des Rechnungsjahres (nicht das Rechnungsdatum wie im Prototyp).

Für die obigen Personen werden in Batches vom 1000 die IDs sortiert geladen. Diese Batches werden in Slices zu 25 IDs aufgeteilt und in 4 parallelen Threads (nicht Prozessen) abgearbeitet. Pro Slice werden die Personen inklusive den Mitgliedschaftsjahren (`context.people_with_membership_years`,per 31.12. des Vorjahres des Rechnungsjahres) und allen Rollen geladen, damit keine n+1 Queries entstehen.

Pro Person einer Slice wird eine MembershipInvoice generiert, basierend auf den `member.active_memberships`. Falls für die Person keine Rechnung generiert werden soll (`!MembershipInvoice#invoice?`), wird diese einfach ausgelassen. Aus den resultierenden MembershipInvoices werden zugehörige External Invoices erstellt, mit `issued_at = invoice_date` und `sent_at = send_date`. Damit lassen sich dann die Abacus Sales Order erzeugen, welche als gesamte Slice über `SalesOrderInterface#create_batch` erstellt werden. 

INFO: Die POC Klasse `Invoices::Abacus::MembershipInvoiceBatcher` diente als Grundlage für die Implementation des Job Prototyps. Die zugehörigen Tests können noch als Grundlage für die Job Spec übernommen werden. Danach kann die POC Klasse gelöscht werden.

### Fehlerbehandlung

Grundsätzlich soll dieser Job so aufgebaut sein, dass jederzeit, insbesondere natürlich bei den API Requests, Fehler auftreten können oder der Job Server terminiert wird. Die sich gerade in Bearbeitung befindenden Rechnungen sollen dabei sauber aufgeräumt werden. Danach wird der Job über Delayed Jobs retried. Bei einem Retry sollen bereits abgearbeitete Schritte und Rechnungen nicht erneut verarbeitet werden, die Rechnungen, welche während dem Fehler in Bearbeitung waren, aber schon. Diese Grundsätze sind in jedem Moment zu prüfen.

Im folgenden die offensichtlichen Fehlerquellen:

Falls in der SalesOrderInterface BatchResponse einzelne SalesOrder (Parts) nicht den Status `created?` haben, wird für diese je ein Hitobito Log Entry erstellt:
- Subject: Die entsprechende ExternalInvoice (`part.context_object.entity`)
- Kategorie: Rechnungen, 
- Level: Fehler
- Message: "Mitgliedschaftsrechnung konnte nicht in Abacus erstellt werden"
- Payload: `Part#error_payload` 
Der Status der ExternalInvoice wird auf `error` gestellt. Die Verarbeitung der weiteren Rechnungen läuft weiter.

Bei allfälligen Exceptions (insbesondere komplett failende Batch Requests bei gröberen Abacus/Netzwerk Problemen) soll der Job regulär via Delayed Job Mechanismus retried werden. Diese Exceptions können auch innerhalb der parallelen Threads auftreten und müssen entsprechend korrekt abgefangen werden, die parallele Verarbeitung gestoppt werden und die ursprüngliche Exception propagiert werden. Die in diesem Fall nicht übermittelten ExternalInvoices (Status == draft) müssen wieder gelöscht werden, damit diese Personen bei einem Retry wieder berücksichtigt werden.

Via das error Callback von Delayed Job wird ein HitobitoLogEntry erstellt (category: "Stapelverarbeitung", kein Subject, Level Error, Message "MV-Jahresinkassolauf: Mitgliedschaftsrechnungen konnten nicht an Abacus übermittelt werden. Es erfolgt ein weiterer Versuch.", Payload exception.message). Falls alle Versuche fehlschlagen, wird über das failure Callback ein letzter HitobitoLogEntry mit der Message "MV-Jahresinkassolauf abgebrochen" erstellt.

### Gracefull Termination

Abhängig von hitobito/hitobito#2772

Die Methode `check_terminated` wird dann zu Beginn jeder Iteration aufgerufen (z.B. bevor eine neue Slice mit Rechnungen zusammengestellt und übermittelt wird). So kann der aktuelle Schritt noch beendet werden. Sobald der Prozess wieder gestartet wird, fährt die Verarbeitung dort weiter, wo sie aufgehört hat.

### Max Run Time

Siehe https://github.com/hitobito/hitobito/pull/2786

Nach aktuellen Hochrechnungen dauert das übermitteln von 135'000 Rechnungen an Abacus ca 7 Stunden. Die `max_run_time` von Delayed Job muss entsprechend auf `24.hours` erhöht werden. Idealerweise wird im BaseJob diese auf den Default von `4.hours` reduziert und in diesem Job wieder mit `24.hours` überschrieben (Jobs können maximal die globale `max_run_time` konfigurieren).

### Fortschrittsanzeige

Für HitobitoLogEntry wird eine zusätzliche Kategorie 'stapelverarbeitung'  erstellt.

Wenn der Job startet, wir ein HitobitoLogEntry erstellt:

- Kategorie 'stapelverarbeitung' 
- Level: Info
- Message: "MV-Jahresinkassolauf: Fortschritt 0%"
- Subject: leer

Danach wird nach jeweils 10% aller berücksichtigten Personen ein weiteres, analoges HitobitoLogEntry erstellt. Dieses kann im Haupt-Loop beim Laden der 500-er Batches von Personen erfolgen und muss nicht bei jeweils genau 10% erfolgen, sondern sobald dort mindestens weitere 10% erledigt sind. In der Message stehen immer die vollen Intervalle (also 10%, 20%, ...), auch wenn effektiv z.B. bereits 11.05% abgearbeitet sind. 

Das Verlängern der Rollen sollte relativ schnell gehen wird dabei nicht extra berücksichtigt, der 0% Eintrag wird davor erstellt.

Am Ende des Jobs soll auf jeden Fall die Meldung mit 100% erscheinen.

# ToDo

- [x]  Jobklasse anpassen
- [x] Specs schreiben
- [x] Mit angemessener Rolle "durchklicken"
- [ ] Dokumentation in `doc/abacus.md` anpassen / ergänzen
- [x] Zum Review @codez zuweisen

**Comment by rnestler** [comment]
> Falls bereits ein solcher Job existiert (egal welche Argumente, jedoch ohne failed_at), wird der vorliegende direkt beendet.

Das ist mir nicht ganz klar.

**Comment by rnestler** [comment]
> Falls bereits ein solcher Job existiert (egal welche Argumente, jedoch ohne failed_at), wird der vorliegende direkt beendet.

Sollte das schon beim `enqueue` oder so gemacht werden? Beim `perform` ist ja eigentlich zu spät?

**Comment by rnestler** [comment]
Small issues:
 * There may be two "100%" progress log entries
 * Before failing the job there will be an additional "MV-Jahresinkassolauf: Mitgliedschaftsrechnungen konnten nicht an Abacus übermittelt werden. Es erfolgt ein weiterer Versuch." error log entry.

**Comment by codez** [comment]
- Falls via `update_progress` zuverlässig 100% ausgegeben wird, braucht es natürlich das andere log_progress(100) nicht mehr. In dem Fall könnte auch das log_progress(0) gleich ins start_progress verschoben werden.
- Mit dem error log entry vor dem failing log entry leben wir.
-  https://github.com/hitobito/hitobito/issues/2772 ist inzwischen gemerged und sollte noch integriert werden.
