### ISSUE TITLE
GROUPS: Hüttengruppen auf ebene Dachverband

### ISSUE THREAD

**Issue by amaierhofer** [hitobito/hitobito_sac_cas#807]
Unter dem Dachverband sollen neu Hütten erscheinen und von der Geschäftsstelle verwaltet werden. Dabei gibt es 2 spezifische Hütten Typen (Privat, Club). Diese werden jeweils durch eine spezifische Parent Gruppe zusammengefasst werden. Die Verwaltung erfolgt durch vergeben der "Schreibrecht" Rolle in den Parent Gruppen. 

Folgende Gruppen müssen angelegt werden

- `Group::SacCasPrivathuetten` (static_name: "Privathütten", rollen: "Schreibrecht")
  - `Group::SacCasPrivathuette`(rollen: "Hüttenchef*in, Hüttenwart**in, Andere", alle ohne Berechtigung)
- `Group::SacCasClubhuetten` (static_name: "Clubhütten", rollen: "Schreibrecht)
  - `Group::SacCasClubhuette` (rollen: "Hüttenchef*in, Hüttenwart**in, Andere", alle ohne Berechtigung)
  
Die Struktur orientiert sich an den Hütten aus (https://saccas.atlassian.net/browse/HIT-405 bzw https://github.com/hitobito/hitobito_sac_cas/issues/716). Der tatsächliche Hütten datenimport wird mit https://github.com/hitobito/hitobito_sac_cas/issues/808 umgesetzt

# ToDo

- [ ] spezifische Gruppen und Rollen erstellen
- [ ] spezifische Gruppen und Rollen in den locales ergänzen
- [ ] lokales Testing via UI (gruppen erstellen, rollen vergeben)
