### ISSUE TITLE
PEOPLE: Wizard Step ValidatePersonAttributes

### ISSUE THREAD

**Issue by daniel-illi** [hitobito/hitobito_sac_cas#825]
Verschiedene Wizards zur Mutation von Mitgliedschaften sollen nur durchgeführt werden können, wenn auf der Person keine `data_quality_issues`s mit `severity=error` vorhanden sind. Bei Familienmitgliedschaften sollen sämtliche Familienmitglieder berücksichtigt werden.

Es soll ein neuer Wizard Step `CheckDataQualityErrors` implementiert werden mit einer Validierung, die auf der Person (und allfälligen Familienmitgliedern) die `data_quality_issues` prüft und falls solche mit severity error vorhanden sind ein validation error hinzufügt: 
> Die Aktion kann wegen ungültigen Daten nicht durchgeführt werden. Bitte nach dem Korrigieren der Daten die Aktion nochmals starten.

Das dazugehörige view partial soll zu jeder Person mit data quality errors den Namen (verlinkt mit der Person) anzeigen und die errors auflisten:

> #### [Jonas Meier](#)
> * Telefonnummer fehlt
> * Email ist ungültig
> 
> #### [Lena Meier](#)
> * Telefonnummer fehlt

Anzeige der data quality errors wie in `app/views/people/_data_quality_sac_cas.html.haml`

Der neue Step `CheckDataQualityErrors` soll in den Wizards `SwitchStammsektion` und `JoinZusatzsektion` eingebaut werden. Der Step wird als einziger Step angezeigt wenn er invalid ist. Wenn er valid ist, wird er nicht angezeigt.

# Tech-Spec

* Wizard Step `Wizards::Steps::CheckDataQualityErrors` implementieren
  * custom validation method `validate :check_data_quality_errors`: 
    - über `wizard.person.household.people` iterieren und Vorhandensein von `Person#data_quality_issues` mit severity `error` prüfen
    - wenn auf einer beliebigen Person des household eine solche vorhanden ist, error hinzufügen:  
      ```ruby
      errors.add(:base, :data_quality_error)
      ```
    - in `config/locales/wagon_de.yaml`:  
      ```ruby
      activemodel:
        errors:
          models:
            wizards/steps/check_data_quality_errors:
              base:
                data_quality_error: "Die Aktion kann wegen ungültigen Daten nicht durchgeführt werden. Bitte nach dem Korrigieren der Daten die Aktion nochmals starten."
      ```

  * für die specs kann der wizard gestubbt werden, es wird nur der `person` accessor gebraucht. z.b. so:
    ```ruby
    let(:person) { ..... }
    let(:wizard) { double(person: person) }
    subject(:step) { described_class.new(wizard) }
    ```
* view partial `app/views/wizards/steps/_check_data_quality_errors.html.haml`
  ```ruby
  = c.form_error_messages
  # <-- Personen und ihre data quality errors auflisten
  = c.cancel_link_back_to_person
  ```
  Anzeige der data quality errors wie in `app/views/people/_data_quality_sac_cas.html.haml`

* `Wizards::Memberships::SwitchStammsektion` anpassen: 
  - `::steps` mit `Wizards::Steps::CheckDataQualityErrors` ergänzen
  - `#handle_start` anpassen:  
    als letztes `elsif` den neuen step zurückgeben falls dieser step invalid ist:  
    ```ruby
    elsif Wizards::Steps::CheckDataQualityErrors.new(self).invalid?
      Wizards::Steps::CheckDataQualityErrors.step_name
  - `#step_after` anpassen:  
    ```ruby
      when Wizards::Steps::CheckDataQualityErrors then nil
    ```
* `Wizards::Memberships::JoinZusatzsektion` anpassen:
  - `::steps` mit `Wizards::Steps::CheckDataQualityErrors` ergänzen
  - `#handle_start` anpassen:  
    als letztes `elsif` den neuen step zurückgeben falls dieser step invalid ist:  
    ```ruby
    elsif Wizards::Steps::CheckDataQualityErrors.new(self).invalid?
      Wizards::Steps::CheckDataQualityErrors.step_name
  - `#step_after` anpassen:  
    ```ruby
      when Wizards::Steps::CheckDataQualityErrors then nil
    ```

# ToDo

- [ ] Step Klasse erstellen
- [ ] View parial erstellen
- [x] translations in `config/locales/wagon_de.yaml`
- [x] `Wizards::Memberships::SwitchStammsektion` anpassen
- [x] `Wizards::Memberships::JoinZusatzsektion` anpassen
- [ ] Specs schreiben
