### ISSUE TITLE
GROUPS: Neue Gruppe SAC Kurskader auf ebene Dachverband

### ISSUE THREAD

**Issue by amaierhofer** [hitobito/hitobito_sac_cas#829]
Neue Gruppe auf Ebene Dachverband: 

-  `Group::SacCasKurskader` (static_name: "SAC Kurskader", rollen: “Kursleiter\*in”, “Klassenlehrer\*in”)
-  beiden Rollen haben leere permissions und `basic_permissions_only: true`
  
# ToDo

- [x] Gruppe und Rollen erstellen
- [x] Gruppe und Rollen in den locales ergänzen
- [x] lokales Testing via UI (gruppen erstellen, rollen vergeben)
