### ISSUE TITLE
 GROUPS: Neue Gruppe Verbände & Organisationen und weitere Untergruppen auf ebene Dachverband

### ISSUE THREAD

**Issue by amaierhofer** [hitobito/hitobito_sac_cas#830]
Neue Gruppen auf Ebene Dachverband: 

-  `Group::SacCasVerbaende` (static_name: "Verbände & Organisationen")
 - `Group::SacCasVerband` (rollen: "Präsidium", "Mitglied", "Andere", basic_login_only, keine permissions)

# ToDo

- [x] Gruppen und Rollen erstellen
- [x] Gruppen und Rollen in den locales ergänzen
- [x] lokales Testing via UI (gruppen erstellen, rollen vergeben)
