### ISSUE TITLE
GROUPS: Anpassungen auf Ebene Sektion

### ISSUE THREAD

**Issue by amaierhofer** [hitobito/hitobito_sac_cas#831]
In der Gruppe SektionsFunktionäre sollen zwei neue Rollen ohne permissions (basic_login_only) verfügbar sein
- Kulturbeauftragter (label: "Kulturbeauftrage\*r”)
- Umweltbeauftragter (label: "Umweltbeauftragte\*r")

In der Gruppe SektionsTourenUndKurse sollen zwei neue Rollen ohne permissions (basic_login_only) verfügbar sein
- Kibechef (label: "KiBe Chef\*in”)
- Fabechef (label: "FaBe Chef\*in")

In der Gruppe Sektionsfunktionäre/Komissionen soll einen neue Gruppe Komission mit folgenden Rollen verfügbar sein 
- Leserecht (permission: `group_read` )
- Schreibrecht (permission: `group_full`)
- Mitglied  (kein Berechtigungen, basic login only)
- Präsidium  (kein Berechtigungen, basic login only)
- Andere  (kein Berechtigungen, basic login only)Mitglied  (kein Berechtigungen, basic login only)

# ToDo

- [ ] spezifische Gruppen und Rollen erstellen
- [ ] spezifische Gruppen und Rollen in den locales ergänzen
- [ ] lokales Testing via UI (gruppen erstellen, rollen vergeben)
