### ISSUE TITLE
GROUPS: Erweiterung/Specs Sektions-Import

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#84]
Import aus #73 soll mit folgenden Attributen/Attribut-Importen ergänzt werden:

- Gründungsjahr (foundation_year), Gründungsjahr
- Jugend Webseite (als neuer Social Account)
- Kanton, enum mit allen 24 Kantonskürzel, Anzeige auf Group#show, Editierbar auf Group#edit, Spalte in Tabular (CSV, XLSX, ...)

# Tech-Spec

- https://github.com/hitobito/hitobito_sac_cas/blob/master/lib/hitobito_sac_cas/import/sections_importer.rb

# ToDo

- [x] Gründungsjahr (foundation_year), Gründungsjahr
- [x] Jugend Webseite (als neuer Social Account)
- [x] Kanton, enum
- [x] Spec erstellen für Import Script
  - Werden Sektionen richtig angelegt
