### ISSUE TITLE
PEOPLE: SAC Eintritt Wizard für bestehende user

### ISSUE THREAD

**Issue by daniel-illi** [hitobito/hitobito_sac_cas#859]
Der Wizard für den SAC Eintritt soll angepasst werden, dass er auch von eingeloggten usern verwendet werden kann.

Wenn ein eingeloggter user den Wizard verwendet, dann fehlt der Schritt "Haupt-E-Mail" und Schritt 1 ist direkt "Personendaten", die Felder sind vorausgefüllt mit den Werten des eingeloggten users. 
Wenn der User die Felder editiert, sollen nach Abschluss des Wizards die Werte auf den bestehenden User persistiert werden.

Ansonsten soll sich der Wizard identisch verhalten wie bisher.

# Tech-Spec

- im **Core**:  
  Plumbing anpassen, damit wir in den wizard steps Zugriff auf die `current_ability` resp. den eingeloggten user haben:
  - `Groups::SelfRegistrationController#wizard` anpassen: wizard initialisieren mit `current_ability` Argument
  - `Wizards::Base#current_user` public machen
  - Auf `Wizards::Step`: `delegate :current_user, to: :wizard`
- im **SAC wagon**:
  - **`SacCas::Groups::SelfRegistrationController`**
    - `#redirect_to_memberships_tab` implementieren:  
      Wenn eine eingeloggte Person, welche bereits eine SAC Mitgliedschaft hat, die self registration benutzt, dann soll sie auf das Register “Mitgliedschaften / Verlauf” ihres Personenprofils weitergeleitet werden und eine Meldung soll im Flash angezeigt werden:
      > “Du besitzt bereits eine SAC-Mitgliedschaft. Wenn du diese anpassen möchtest, kontaktiere bitte die SAC Geschäftsstelle.“  
      ```ruby
      redirect_to history_group_person_path(group_id: current_user.primary_group_id, id: current_user.id)
      ```
    - `#create` anpassen:  
      - `redirect_to_login` aufrufen, falls eine `person` vorhanden ist und der user KEINE eingeloggte Person ist.
      - `redirect_to_memberships_tab` aufrufen, falls der `current_user` bereits eine Mitgliedschaft/Neuanmeldung hat
      ```ruby
      def create
        return redirect_to_login if person && !signed_in?
        return redirect_to_memberships_tab if member_or_applied?

        super
      end

      # ev. direkt in People::SacMembership implementieren
      def member_or_applied?
        current_user.sac_membership.stammsektion_role || 
          current_user.sac_membership.neuanmeldung_stammsektion_role
      end
      ```  
    - `#redirect_to_group_if_necessary` von super überschreiben ohne die `signed_in?` condition.  
    Es soll immer _self_registration_ verwendet werden auch für eingeloggte user statt der _self_inscription_:
      ```ruby
      def redirect_to_group_if_necessary
        redirect_to group_path(group) unless group.self_registration_active?
      end
      ```
    - `#redirect_to_login` anpassen:  
      `group_self_registration_path` statt `group_self_inscription_path` damit devise nach dem Login wieder auf die self registration umleitet
  - **`Wizards::Signup::SektionWizard`**:    
    - `#build_person`:  
      Wenn wizard von eingeloggter Person verwendet wird, den `current_user` zurückgeben und diesem die Attribute assignen:   
      ```ruby
      def build_person
        return current_user.tap { _1.assign_attributes(person_attributes) } if current_user.persisted?

        super
      end
      ```
    - `#email` implementieren statt dem `delegate :email`:  
      Wenn wizard von eingeloggter Person verwendet wird, deren `email` zurückgeben, ansonsten den Wert vom `main_email_field` step. 
      - `current_user` kann auch ein NICHT eingeloggter user sein, dann ist email=nil
      - `step(:main_email_field)` ist nil falls current_user nicht eingeloggt ist
      ```
      def email = current_user&.email || step(:main_email_field)&.email
      ```
    - `#step_after` anpassen:  
      Wenn der Wizard von einer eingeloggen Person verwendet wird, dann gibt es keinen email step und es soll direkt das Personendaten Form angezeigt werden: 
      - eingeloggte Person: `current_user.persisted?`
      - wenn der user eine eingeloggte Person ist, dann `Wizards::Steps::Signup::Sektion::PersonFields` zurückgeben.
    - `#operations` anpassen: für "main person" `current_user` statt `person_attrs` übergeben falls eingeloggter user
  - **`Wizards::Signup::SektionOperation`**: anpassen, damit anstatt der `person_attrs` eine `Person` Instanz übergeben werden kann

# ToDo

- [x] Core Anpassungen
- [x] `SacCas::Groups::SelfRegistrationController` anpassen
- [x] `Wizards::Signup::SektionWizard` anpassen
- [x] `Wizards::Signup::SektionOperation` anpassen
- [x] Specs schreiben
- [x] Mit angemessener Rolle "durchklicken"

**Comment by Largo** [comment]
@daniel-illi `#operations anpassen: für "main person" current_user statt person_attrs übergeben falls eingeloggter user`:
Warum nur fuer sac family main person? Das klappt nicht? 🤔

**Comment by daniel-illi** [comment]
> @daniel-illi `#operations anpassen: für "main person" current_user statt person_attrs übergeben falls eingeloggter user`: Warum nur fuer sac family main person? Das klappt nicht? 🤔

@Largo sorry für meine späte Antwort. Das war so gemeint:
* die alte Implementation der `SektionOperation` kriegt `person_attrs` als Argument und erstellt anhand von diesen eine `Person`. Die angepasste Implementation akzeptiert auch eine `Person` Instanz und aktualisiert diese statt eine neue zu erstellen.
* der `SektionWizard` übergibt der ersten `SektionOperation` falls der user eingeloggt ist die entsprechende `Person` Instanz

**Comment by Largo** [comment]
Hier fehlt im Moment nur noch das die Personendaten nicht eingefüllt werden, wenn der Personen Felder Schritt angezeigt wird. Man müsste dies vermutlich im Step  anpassen.

**Comment by Largo** [comment]
Ticketumfang ist nun umgesetzt. Wer Zeit hat, darf noch weitere Specs entwicklen.

Im Zusammenhang mit Turboframe koennen Probleme auftreten. Bei mir half im PeopleController testweise `format.turbo_stream { render formats: :html } ` zu ergaenzen.

**Comment by Largo** [comment]
Feature specs failen leider. Dies ist aber vermutlich auf flakyness zurueckzuführen.
