### ISSUE TITLE
PEOPLE: Umgang mit WSO2 Legacy Passwörter implementieren

### ISSUE THREAD

**Issue by openscript** [hitobito/hitobito_sac_cas#886]
Aktuell verwendet der SAC WSO2 als Idenity Provider. Künftig wird Hitobito diese Funktion übernehmen.
Damit die Benutzer nicht alle nach der Umstellung ein neues Passwort setzen müssen, sollen die Password Hashes aus WSO2 übernommen werden. 

Bei einem ersten erfolgreichen Login über den aus WSO2 übernommenen Password-Hash soll ein Standard Hash für das Userpasswort auf der Person in Hitobito gespeichert werden. Sprich der WSO2 Password Hash wird nur einmalig verwendet.

Setzen eines neuen Passworts z.B. via Passwort vergessen Funktion löscht allfällige Werte in `wso2_legacy_password_hash`, `wso2_legacy_password_salt`

https://github.com/hitobito/hitobito_sac_cas/blob/master/doc/import.md#7-sac_imports7_wso2_password_hashes

# Tech-Spec

## 1. Neue Felder auf Person

```ruby
change_table :people, bulk: true do |t|
  t.string :wso2_legacy_password_hash
  t.string :wso2_legacy_password_salt
end
```

## 2. Authentifizierung mit Legacy WSO2 in Hitobito

<details>
<summary>Implementation im alten System des Kunden</summary>

```bash
#!/bin/bash

preparePassword() {
    local password="$1"
    local saltValue="$2"
    
    local digestInput="$password"
    if [ ! -z "$saltValue" ]; then
        digestInput="$password$saltValue"
    fi

    # Using openssl to compute the SHA-256 hash
    local hash=$(echo -n "$digestInput" | openssl dgst -sha256 -binary | openssl base64)
    echo "$hash"
}

main() {
    local password="$1"
    local saltValue="$2"
    
    if [ -z "$password" ]; then
        echo "Usage: $0 <password> [saltValue]"
        exit 1
    fi
    
    local encodedPassword
    encodedPassword=$(preparePassword "$password" "$saltValue")
    echo "$encodedPassword"
}

main "$@"
```

</details>

Devise method `#valid_password?` überschreiben in `SacCas::Person`: 
- falls `Person#encrypted_password` gesetzt ist, authentifizieren mit Devise (`super`)
- falls `#encrypted_password` blank ist und `#wso2_legacy_password_hash` vorhanden ist:
  + authentifizieren mit legacy algorithmus:
    ```ruby
    digest_input = "#{password}#{wso2_legacy_password_salt}"
    Base64.encode64(Digest::SHA256.digest(digest_input)).strip == wso2_legacy_password_hash
    ```
  + Passwort mit Devise aktualisieren
  + `#wso2_legacy_password_*` Attribute nil setzen

**WSO2 Password/Hash Beispiel** zum Testen:

```
clear text password: fGgu56dfmoP
hash: YfVCNCik1IQnGrRNcxlsNpJl6rCKmOFb3wGISEB81l0=
salt: xwQcHLXumdiO3O22lSX6Jw==
```

(Dies wurde zuvor in #756 dokumentiert.)

## 2.1. Korrespondenzart Regel anpassen

| Regel HIT-79 | Neu mit HIT-127 |
|---|---|
| Setzt ein bestehendes Mitglied ein initiales Passwort, muss das Flag auf “digital” gesetzt werden. | Setzt ein bestehendes Mitglied ein initiales Passwort, muss das Flag auf “digital” gesetzt werden,  falls das Mitglied eine verifizierte Email Adresse hat. |

## 2.2 Passwortvalidierung

Diese Validierung für WSO2 importierte Kontakte ausschalten und sie weiterhin ein Passwort mit einer kürzeren Länge als 12 Zeichen benutzen lassen, bis sie ein neues Passwort setzen.

## 3. Legacy Passwort Attribute nil setzen beim Zurücksetzen des Passworts

`SacCas::Person#password=` überschreiben:
* super aufrufen
* `#wso2_legacy_password_*` Attribute nil setzen
* Testen, dass dies bei der "reset password" Funktion korrekt funktioniert

# ToDo

- [x] Migration erstellen
- [x] `SacCas::Person#valid_password?`
- [x] `SacCas::Person#password=()`
- [x] Devise Validierung bei Übernahme des Legacy Passworts ausschalten
- [x] Korrespondenzart `digital` nur, wenn verifizierte Email
- [x] Specs schreiben
- [x] Ausnahme für GitGuardian (wer kann das einstellen?)

**Comment by openscript** [comment]
- [ ] Ausnahme für GitGuardian (wer kann das einstellen?)
- [ ] Antworten auf Fragen an Kunden abwarten
