### ISSUE TITLE
PEOPLE: Mitgliedernummer

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#89]
Die Mitgliedernummer soll auf Basis der Navision ID (contact id) weitergeführt werden. So können alle Mitglieder ihre bisherige Mitgliedernummer behalten.
Für in Hitobito neu erstellte Personen wird eine neue Nummer oberhalb des bestehenden Range erstellt. 

- Die Nummer wird immer automatisch vergeben und kann nicht manuell editiert werden
- Jede Person (Person entity) in Hitobito, egal ob Mitglied, Kontakt oder Mitarbeiter, erhält eine solche eindeutige Nummer (z.B. auch Hüttenwarte, Autoren, Athleten, usw.)

# Tech-Spec

- Nummer-Range: 100000 - 999999 (Validierung)
- Die aktuell höchste Nummer in Navision ist ~478'554~ 503'353
- Personen werden mit rake import:mitglieder nur importiert falls eine mitglieder-nr vorhanden ist
- In Hitobito neu erstellte Personen erhalten eine Nummer >= 600'000

# ToDo

- [x] Rename des Person Attributs navision_id -> membership_number
  - alle XLSX/Navision Importe anpassen (navision_id ist dort zentral)
  - Validierung ergänzen
- [x] Sicherstellen das dieses Attribut in allen Exporten vorhanden ist (tabular)
- [x] Anzeige der Mitgliedernummer auf Person#show
- [x] Validation und Auto-Inkrement für die Mitgliedernummer erstellen
- [x] In allen Importen Nummerformat validieren und sicherstellen das Nr < 500'000
- [x] Mit angemessener Rolle durchclicken
- [x] Changelog Eintrag

**Comment by mtnstar** [comment]
[Tuesday 08:54] Stefan Sykes

Super, danke dir! Grundsätzlich bini mit dere spetz iverstande - hett folgendes feedback:

Nummer ist aktuell 6-stellig ? 

--> korrekt
Die aktuell höchste Nummer in Navision ist 478'554

--> Die höchste Nummer in Navision per 26.09.2023 ist 478'554
In Hitobito neu erstellte Personen erhalten eine Nummer > 500'000

--> gute Idee; einverstanden

Ich gehe davon aus, dass die Familiennummer, die bei einem Familienmitglied ("Fam", "Frei Fam", "Frei Kind") zwingend gesetzt sein muss, in einem separaten Ticket abgedeckt wird.

[Tuesday 08:55] Stefan Sykes

Jede Person in Hitobito, egal ob Mitglied, Kontakt oder Mitarbeiter, erhält eine solche eindeutige Nummer

--> Mitglied, Mitarbeiter sind Rollen einer Person/Kontakts. Wenn du das so spezifizieren möchtest, dann sollten die als Beispiele gelten. Es gibt viele weitere solche Rollen: Autoren, Athleten, Hüttenwart, Hüttenchef etc.
