### ISSUE TITLE
PEOPLE: Wizard JoinZusatzsektion Texte anpassen

### ISSUE THREAD

**Issue by daniel-illi** [hitobito/hitobito_sac_cas#924]
In den Views des `Wizards::Steps::JoinZusatzsektion::Summary` Wizard Steps sollen die Texte angepasst werden.
Diese sind neu abhängig davon, ob die Sektion Neuanmeldungen selber verwaltet.

Ausserdem muss sichergestellt werden, dass die Beitragskategorie korrekt dargestellt wird. Diese wird mit dieser Methode gerendert: `Wizards::Memberships::JoinZusatzsektion#human_role_type`  
Anscheinend ist die `beitragskategorie` manchmal `nil` und für den i18n lookup wird dann der parent key verwendet:

![Screenshot from 2024-09-06 17-13-19](https://github.com/user-attachments/assets/5ab6cdbd-6612-4a11-aee7-e5539cf1afa0)

# Tech-Spec

* Das view partial `app/views/wizards/steps/join_zusatzsektion/_summary.html.haml` muss angepasst werden:

  * Wenn `c.model.wizard.choose_sektion.group.decorate.membership_admission_through_gs?`:
    > Die Zusatzmitgliedschaft bei <_Sektionsname_> wird als <_Beitragskategorie_> beantragt. Die Sektion umfasst einen manuellen Freigabeprozess. Hiermit wird noch keine Rechnung ausgelöst, erst mit erteilter Freigabe. Die Zusatzmitgliedschaft wird nach Begleichung der Rechnung aktiviert.”
  * Andernfalls:
    > ”Die Zusatzmitgliedschaft bei <_Sektionsname_> wird als <_Beitragskategorie_> beantragt. Hiermit wird eine Rechnung ausgelöst. Die Zusatzmitgliedschaft wird nach Begleichung der Rechnung aktiviert.”

* `Wizards::Memberships::JoinZusatzsektion#human_role_type` debuggen, sicherstellen dass die Beitragskategorie immer richtig aufgelöst wird

# ToDo

- [x] view partial anpassen
- [x] `#human_role_type` debuggen, fixen
- [x] Specs schreiben
- [x] Mit angemessener Rolle "durchklicken"
