### ISSUE TITLE
PEOPLE: Wizard SwitchStammsektion Texte anpassen

### ISSUE THREAD

**Issue by daniel-illi** [hitobito/hitobito_sac_cas#928]
Im view partial des `Wizards::Steps::SwitchStammsektion::Summary` Wizard Steps sollen die Texte angepasst werden.
Diese sind neu abhängig davon, ob die Sektion Neuanmeldungen selber verwaltet.

# Tech-Spec

* Das view partial `app/views/wizards/steps/switch_stammsektion/_summary.html.haml` muss angepasst werden:

  * Wenn `c.model.wizard.choose_sektion.group.decorate.membership_admission_through_gs?`:
    > ”Die Stammmitgliedschaft bei <_Sektionsname_> wird als <_Beitragskategorie_> beantragt. Die Sektion umfasst einen manuellen Freigabeprozess. Kläre bitte vorgängig die Mitgliederaufnahme mit <_Sektionsname_> ab. Nimm die Fakturierung bitte nach nach dem Bestellen vor, sofern eine neue Rechnung ausgestellt werden muss. Die Mitgliedschaft in der neuen Stammsektion ist per sofort gültigt.”
  * Andernfalls:
    > ”Die Stammmitgliedschaft bei <_Sektionsname_> wird als <_Beitragskategorie_> beantragt. Hiermit wird keine Rechnung ausgelöst. Nimm die Fakturierung bitte nach nach dem Bestellen vor, sofern eine neue Rechnung ausgestellt werden muss. Die Mitgliedschaft in der neuen Stammsektion ist per sofort gültig.”

# ToDo

- [x] view partial anpassen
- [x] i18n keys ergänzen, Text anpassen
- [x] Specs schreiben
- [x] Mit angemessener Rolle "durchklicken"
