### ISSUE TITLE
PEOPLE: `3_qualifications` Import Qualifikationen (aus NAV3)

### ISSUE THREAD

**Issue by openscript** [hitobito/hitobito_sac_cas#934]
Es geht darum die Qualifikationen von Personen aus Navision zu importieren.

Dies ist blockiert durch [#905](https://github.com/hitobito/hitobito_sac_cas/issues/905).

# Tech-Spec

## 1. Arbeitsvorbereitung

- [x] Quelldaten `NAV3_Qualifikationen_20240815.csv` von NextCloud herunterladen (**ACHTUNG: Sensitive Daten**)
- [x] Fixture erstellen
- [x] Testdatensatz für die Entwicklung ableiten. Bspw.: 
  ```bash
  head -n 1 NAV3_Qualifikationen_20240815.csv > output.csv && tail -n +2 NAV3_Qualifikationen_20240815.csv | shuf -n 2000 >> output.csv
  ```

## 2. CSV Datei lesen

- [X] `app/domain/sac_imports/csv_source.rb` Mapping anpassen
- Vorschlag für Mapping:

| **Ruby Hash Attribut** | **NAV3 CSV Export Spaltenname** |
|---|---|
| navision_id | Kontaktnummer |
| active | Ist aktiv |
| start_at | Gültig von |
| finish_at | Gültig bis |
| qualification_kind | Qualifikation |

## 3. Report vorbereiten

- [x] In `app/domain/sac_imports` neue `QualificationsImporter` Klasse erstellen
- [x] Zu jedem Import wird ein Report zu handen des Kunden erstellt.
- Folgende Header hat der Report in diesem Fall:
  ```ruby
  REPORT_HEADERS = [
    :navision_id,
    :hitobito_person,
    :navision_qualification_active,
    :navision_start_at,
    :navision_finish_at,
    :navision_qualification_kind,
    :errors
  ]
  ```

## 4. Import umsetzen

- [x] In `app/domain/sac_imports` neue `QualificationEntry` Klasse erstellen
- [x] Falls `navision_id` nicht gefunden, im Report als Fehler erfassen
- [x] `qualification_kind` nachschlagen und passende ID für `qualification_kind_id` setzen
  - Falls nicht gefunden, im Report einen Fehler erfassen
- [x] Falls NAV3 'Ist aktiv' nach dem Erstellen der Qualifikation in Hitobito diese dort nicht aktiv ist (und umgekehrt), ~~Quali wieder löschen und Error-Eintrag im csv report~~ eine Warnung im Report erfassen

## Hinweise

 * ~~ist_aktiv ist redundant, da die Information schon in Gültig von / bis enthalten ist. Wird zur Plausibilisierung verglichen.~~ Das ist_aktiv Flag wird manuell gesetzt und sagt ob eine Person Kurse geben will oder nicht. Es korreliert auch mit den eigentlichen Qualifikationen, weil diese dann nicht aktualisiert werden. Deshalb einfach als Warnung im Report ablegen.
 * Hauptgrupppe (QUAL-1,2,3) kann ignoriert werden

## Fragen

 * Sistiert ab / Reaktivierbar bis kann auch ignoriert werden nehme ich an? -> Ignorieren.
 * Was soll in `  :hitobito_person,` im CSV report rein? -> Name, also `to_s`
 * Was soll in "Development Seed erstellen" geseeded werden? Irgendwelche Qualifikationen?
    * Einzelnen Personen geben
    * z.B. Allen Tourenleitern Tourenqualifikation geben.
    * (Seeder kann nicht Valide Objekte seeden...)
 *  "Falls NAV3 'Ist aktiv' nach dem Erstellen der Qualifikation in Hitobito diese dort nicht aktiv ist, Quali wieder löschen und Error-Eintrag im csv report". Soll das auch umgekehrt gelten?
    * Auch umgekehrt prüfen und als Warnung reporten.
 * Wie sollen wir fehlende `start_at` / Gültig von handeln?
    * Z.B. Wenn `finish_at` in der Zukunft liegt mit `Time.zone.now` ersetzen? Sonst mit `finish_at.yesterday`?
    * Fehler?
    * -> Fehler. Wird dann gefixt in den Daten.

# ToDo

- [x] Fixture erstellen
- [x] Importer schreiben
- [x] Import lokal laufen lassen und erster Report an Kunden übergeben
- [x] Specs schreiben
- [ ] Development Seed erstellen

**Comment by openscript** [comment]
@ThomasEllenberger Bei den Quelldaten fehlt der Header, was es schwierig macht die Spalten zuzuordnen. Ich habe nachgefragt.

**Comment by openscript** [comment]
@ThomasEllenberger Wir haben hier die Header abgeleitet und können es umsetzen.
