### ISSUE TITLE
PEOPLE: Anpassung Gruppe Neuanmeldungen

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#96]
Nachdem der Onboarding Prozess weiter spezifiziert wurde, sind folgende Anpassungen an den Gruppen und Importscripts nötig:

**Gruppen Neuanmeldungen**

- Group::SektionsNeuMitgliederSektion -> Group::SektionsNeuanmeldungenSektion renamen, übersetzung: Neuanmeldungen (zur Freigabe) / Nouvelles inscriptions (pour contrôler)
- Group::SektionsNeuMitgliederZv -> Group::SektionsNeuanmeldungenNv renamen, übersetzung: Neuanmeldungen / Nouvelles inscriptions
- Damit wir nur noch den Begriff Neuanmeldung verwenden
- Neu gibt es nur noch eine Rolle 'Neuanmeldung' anstatt Einzel, Familie, Jugend
- Titel des Selbstregistrierungs-Formulars: 'Registrierung SAC Blüemlisalp' (Registrierung sektion.name)
  - custom_self_registration_title ist eine Group Translation,  Franz übersetzung

Vordefinierter Filter auf dem top_layer 'Neuanmeldungen' welcher sämtliche neu angemeldeten Personen auflistet (in Gruppen SektionsNeuanmeldungenNv)

![image](https://github.com/hitobito/hitobito_sac_cas/assets/655627/d383aa60-c0dc-421f-94a5-7ecf47b6e197)

# Tech-Spec
- https://github.com/hitobito/hitobito_sac_cas/tree/master/app/models/group
- https://github.com/hitobito/hitobito_sac_cas/blob/master/lib/hitobito_sac_cas/import/sections_importer.rb#L199

# ToDo

- [x] Renamen der Neuanmeldungsgruppen inkl. Keys im locale
- [x] Neue Rolle Neuanmeldung, Entfernen: Einzel, Jugend, Familie (inkl. locales)
- [x] Tests fixen, Fixtures anpassen, Development Seeders anpassen
- [ ] Vordefinierter Personen Filter auf top_layer
- [x] Import-Script Sektionen entsprechend anpassen
  - verwenden richtige STI Gruppen Klasse
  - custom_self_registration_title group translation ergänzen
  - self_registration_role_type auf jeder Neuanmeldungen Gruppe wird auf Neuanmeldung gesetzt
- [ ] Spec für den Import-Script Sektionen:  Neuanmeldungen Gruppen werden richtig angelegt
- [x] Gruppen Struktur neu dokumentieren: https://github.com/hitobito/hitobito_sac_cas/blob/master/README.md
