### ISSUE TITLE
PEOPLE: Selbstregistrierungsformular Anmeldung ab

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#97]
Blocked by: #95, hitobito/hitobito#2237
Siehe auch #109 

Eine neue Anmeldung beim SAC erfolgt per sofort, per 1. Juli oder per 1. Oktober. Je nach gewähltem Eintrittsdatum wird der zu bezahlende Jahresbeitrag fürs laufende Jahr reduziert.

Dies soll auch beim Selbstregistrierungsformular berücksichtigt werden.

### Mockup
Siehe #95 das PDF mit allen Mockups und UI Prototyp unter Schritt 3 "Zusatzdaten"

### Was wann anzeigen

- Wenn sich Jemand am 02. Juli registriert, dann kann er/sie die Option ab 01. Juli nicht mehr auswählen. Es stehen dann nur noch die Optionen per sofort und per 01. Oktober zu verfügung.
- Entsprechendes Verhalten bei Registrierung nach dem 01. Oktober

Preisinformationen/Rabatte werden mit #115 umgesetzt

### Neuanmeldungen Auflisten

In den beiden Grupen Neuanmeldungen NV und Neuanmeldungen Sektion sollen die Rollen mit Datum in der Zukunft aufgelistet werden. Ausserdem sollen diese Rollen auf der Person und dem Verlauftab der Person sichtbar sein.  

Ausserdem gibt es auf dem root_layer einen Filter welche sämtlichen Neuanmeldungen sämtlicher Sektionen auflistet. Dort sollen diese Rollen ebenfalls sichtbar sein.

# Tech-Spec

## Core
Mit diesem Ticket sollen Rollen mit Startdatum in der Zukunft eingeführt werden. Dazu soll wie bereits mit End Datum in der Zukunft. 

- Neue Attribute `convert_on` auf der Rolle, neues class_attribute `convert_to` auf der Rolle 
- DelayedJob welcher die Rollen mit `convert_to` durcharbeitet und role entries erstellt
- class_attribute :list_people_with_future_roles, default: false
  - wenn gesetzt, werden in der Listenansicht und auch bei Exporten die Personen mit künftigen Rollen aufgelistet
- Personen mit künftigen Rollen können via globalem Suchfeld gesucht werden

## SAC Wagon
- In allen Neuanmeldungen Gruppen sollen auch Rolleneinträge mit Startdatum in Zukunft angezeigt werden

# ToDo
- [ ] Zukünftige Rolle ohne Callbacks erfassen
- [ ] Zukünftige Rolle als eigene Sektion auf der Personen Seite anzeigen
- [ ] Zukünftige Rolle als eigene Sektion auf dem Verlauf der Person anzeigen (ev. in eigener Sektion)
