### ISSUE TITLE
PEOPLE: Familien abbilden/validieren

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#98]
Beim SAC sind Familien wiefolgt definiert:

```
für max. 2 Erwachsene und beliebig viele Kinder im Alter zwischen 6 und 17 Jahren.

Die Familienmitgliedschaft ist auch für Paare ohne Kinder möglich. Eine Person wird als Hauptkontakt definiert.
```

- Erwachsene in einer Familie sind mind. 22 Jahre alt, Kinder zwischen 6-17 Jahre
- ~wie lässt sich der Hauptkontakt abbilden? Braucht es das überhaupt noch? kann das nicht einer der beiden Erwachsenen sein~ Braucht es vorerst nicht
- Jede Familie braucht eine eindeutige **Familen-ID** welche auch z.b. in Tabular/CSV/XLSX usw. mit exportiert wird
  - Familien ID aus Haushalts-ID ableiten, z.b. wird aus 4242 -> F4242
  - Familien ID auf Person nur anzeigen in Exporten (tabular) falls Person eine aktive Mitglied Rolle mit Beitragskategorie 'familie' hat
- https://github.com/hitobito/hitobito_sac_cas/blob/master/app/domain/sac_cas/beitragskategorie/calculator.rb
- Beitragskategorie 'familie' ist nur möglich auf Hauptsektion (primary_group)
- Anpassen mitglieder_import sodass Familien beim Import richtig erstellt werden
  - https://github.com/hitobito/hitobito_sac_cas/blob/master/lib/hitobito_sac_cas/import/sektion/mitglieder_importer.rb
- Es soll sichergestellt werden das diese Validierung im Selbstregistrierungsformular gemacht wird und der Benutzer entsprechend informiert wird. Die Validierung soll auch bereits aktiv im UI stattfinden, sodass ein Benutzer z.b. gar kein Kind das jünger als 6 Jahre ist erfassen kann. blocked_by #95 

# Tech-Spec
- Umsetzung im SAC Wagon
- Erwachsene sind Personen die mind. 22 Jahre alt sind
- PartnerIn wird als wohnt im Haushalt mit abgebildet
  - ~~Im SAC Wagon Validierung einführen das max. 2 Erwachsene Personen in einem Haushalt sein können~~
  - Im SAC Wagon bei der Selbstregistrierung Validierung einführen das max. 2 Erwachsene Personen gleichzeitig registriert werden können (via SAC-Haushalts-Registration) -> blocked by hitobito/hitobito_sac_cas#95, daher in einem Follow-up Issue umsetzen
  - Im SAC Wagon auf Rolle Mitglied/Neuanmeldung validieren, dass maximal 2 (erwachsene) Personen (Rollen) im selben Haushalt die Beitragskategorie "familie" haben können
  - Es können beliebig viele Kinder dem Haushalt hinzugefügt werden
  - Auch WGs können als Familienmitgliedschaften geführt werden
  - Auch Personen zwischen 17 und 22 Jahren können im Haushalt sein. Aber diese bekommen halt keine Familien-Beitragskategorie. Das selbe gilt die 3. Erwachsene, diese erhält dann die Beitragskategorie 'einzel'
- Immer nur die aktiven Rollen für die Berechnung der Beitragskategorie berücksichtigen (Beitragskategorie wird einfach beim erstellen der Rolle assigned/validiert)
- Kinder in einem Haushalt werden automatisch als Elternzugangsfeature-Kinder hinzugefügt (im SAC Wagon)
- Im SAC Wagon können Kinder nicht direkt via Kinder hinzugefügt werden (ausblenden Form-Elemente)
- Kinder werden parallel allen Erwachsenen in einer Familie assigned/entfernt
- Hitobito Familienmitglieder-Feature wird für den SAC nicht verwendet (relations_to_tails)
- https://github.com/hitobito/hitobito/blob/master/app/domain/person/household.rb
- Beitragskategorie Familie ist nur möglich auf Rolle Mitglied der Hauptsektion (primary_group), siehe #106 
- https://github.com/hitobito/hitobito_sac_cas/blob/master/lib/hitobito_sac_cas/import/sektion/mitglieder_importer.rb
- Beitragskategorien sind möglich auf den Rollen Mitglied/Neuanmeldung, diese beiden Rollen werden vorerst gleich behandelt 
  - https://github.com/hitobito/hitobito_sac_cas/blob/master/app/models/sac_cas/role/mitglied.rb
- Familien ID auf person#show als Attribut sowie im json:api anzeigen (read-only)

# ToDo

- [x] Haushalts-Domainklasse `Person::Household` im Wagon anpassen um Elternzugang und Haushalte zu linken
  - [x] Nach Bedarf Methoden `assign` `save`, `remove` anpassen
- [ ] ~Familien-ID als weitere Spalte (table_displays im wagon.rb) anbieten~
- [x] In Tabular Personen Exports die Haushalts-ID mit ausgeben
- [x] In der neuen JSON:API die Haushalts-ID mit ausgeben (read-only)
- [ ] ~Manuelle Elternzugangs-Zuweisung auf Formular deaktivieren, vorzugsweise via Entziehen der Berechtigung `:change_managers`~
- [x] Auf Rolle validieren, dass maximal 2 (erwachsene) Personen (Rollen) im selben Haushalt die Beitragskategorie "familie" haben können, Familie ist nur auf Hauptsektion möglich
- [x] Im Mitglieder Sektion Personen-Import die alte Spalte "Familien-ID" verwenden, um Personen in Haushalte zusammenzufügen. Erwartungsgemäss dürften dabei keine Haushalte mit mehr als 2 Erwachsenen entstehen, die Validierungen auf der Rollen stellen dies auch gleich sicher
- [x] youth wagon als dependency im Gemfile hinzufügen
- [ ] manuelles Testen
- [ ] CHANGELOG entry
