### ISSUE TITLE
PEOPLE: Eigene Berechtigung für Tab Sicherheit 

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#990]
Neu soll es eine eigene Berechtigungsaktion `:security` für das Tab Sicherheit auf der Person (`Person:SecurityToolsController`) geben. Dafür wird im Core auf der Person Ability eine neue Aktion `:security` eingeführt und überall vergeben, wo bisher auch die `:update` Aktion vorhanden ist. 

Der authorize Action Check im Controller prüft neu :security anstelle von :update, ebenso das Person Sheet beim Rendern des Links.

Im SAC Wagon wird darauf die Ability für die :security Aktion angepasst, dass nur noch Mitarbeitende der Geschäftsstelle (SAC_BACKOFFICE_ROLES, bzw. :layer_and_below_full auf dem Root Layer) darauf Zugriff haben. Alle anderen im Core definierten Permissions sollen für diese Aktion entfernt werden (`permission(:any / :group_full / ...).may(:security).none` )

# ToDo

- [x] Domainklasse anpassen
- [x] View/Controller anpassen
- [x] Specs schreiben
- [x] Mit angemessener Rolle "durchklicken"
- [x] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by ThomasEllenberger** [comment]
Was geschieht hier bei allen anderen Bestandeskunden? 
Erwartungshaltung wäre, dass sich die Berechtigungen nicht ändern, und alle Personen welche das Security Tab vorher sehen konnten, dies auch weiterhin können.

**Comment by hunchr** [comment]
> Was geschieht hier bei allen anderen Bestandeskunden? Erwartungshaltung wäre, dass sich die Berechtigungen nicht ändern, und alle Personen welche das Security Tab vorher sehen konnten, dies auch weiterhin können.

neu sind es ja nur noch mitarbeitende der geschäftsstelle, also gehe ich davon aus, dass vorher mehr personen darauf zugreifen konnten. sonst hätte diese änderung gar nichts gebracht.

**Comment by Largo** [comment]
@ThomasEllenberger fuer bestandskunden bleibt alles gleich. Ich habe extra manuell im generic wagon getestet.
