### ISSUE TITLE
EVENTS: Kurse PDF Eckdatenblatt

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#993]
Als Kursadmin möchte ich für die Kursleitungen und die Klassenleitungen ein Eckdatenblatt erzeugen können, um relevante Informationen zu einem bestimmten Zeitpunkt abzuspeichern.

## Frontend

Dazu gibt es zwei mögliche Einstiegspunkte. Diese sind nur für Kurse und dort nur für die Kursadmin sichtbar, also falls `can?(:create, event)`.

- [x] Auf dem Kurs Info Tab wird zuhinterst ein neuer Button "Alle Eckdatenblätter erzeugen" hinzugefügt. Mit diesem wird für alle Teilnehmenden Personen, welche entweder die Rolle Hauptleitung/Kursleitung oder Leitung/Klassenleitung haben, je ein Eckdatenblatt erzeugt.
- [x] Auf der Seite der Teilnahme wird zuhinterst ein neuer Button "Eckdatenblatt erzeugen" hinzugefügt, falls die Person entweder die Rolle Hauptleitung/Kursleitung oder Leitung/Klassenleitung hat.

- [x] Als Icon für die Buttons kann ein PDF Dokument (file-pdf) verwendet werden.

Die Darstellung der Anhänge eines Anlass soll im Core in eine Tabelle überführt werden, damit die Sichtbarkeits-Icons und das Löschen Icon über alle Anhänge ausgerichtet sind. Die Breite der Tabelle soll dynamisch sein, kann also bei kurzen Dateinamen relativ schmall sein, bei längeren Dateinamen breiter. Ansonsten soll kein Styling auf der Tabelle sein (kein Rand, kein zusätzliches Padding, keine Hintergrundfarben), so dass die Liste bis auf die Ausrichtung der Icons gleich aussieht wie bisher.

## Backend

Es kann ein neuer Controller Event::Courses::KeyDataSheetsController mit einer create Action erstellt werden, welcher beide obigen Fälle abhandelt. Als Berechtigung wird ebenfalls `:create, event` geprüft.

Die Eckdatenblätter werden als PDF erzeugt und als Anhang dem Kurs hinzugefügt, welcher nur für das Leitungsteam sichtbar ist. Der Dateiname ist "Eckdatenblatt_['Kursleiter' | 'Klassenleiter']_[Vorname]_[Nachname]_[YYYY_MM_DD_hhmm].pdf "

Danach erfolgt ein Redirect auf die Event Show Seite mit der Flash Message "Das Eckdatenblatt / Die Eckdatenblätter wurden erzeugt und dem Kurs als Anhang hinzugefügt." Falls keine Personen mit den entsprechenden Rollen vorhanden sind, wird als Fehlermeldung "Es konnte kein Eckdatenblatt erzeugt werden, da keine Kursleitung definiert ist." angezeigt.

## PDF

[Eckdatenblatt.pdf](https://github.com/user-attachments/files/17056534/Eckdatenblatt.pdf)

Das PDF wird mit Prawn erzeugt und soll ungefähr der obigen Vorlage entsprechen. Dazu eine entsprechende Klasse `Export::Pdf::Participation::KeyDataSheet` erstellen. Es kann mit einer einfachen Prawn Table aufgebaut werden, die Masse müssen dabei nicht 100% übereinstimmen. Der Seitenumbruch kann beliebig erfolgen. Die Fusszeile soll auf allen Seiten angezeigt werden.

Als Sprache wird die im Kurs eingestellte Sprache verwendet. Falls diese "Deutsch/Französich" ist, wird das PDF auf Deutsch erzeugt.

Im folgenden die Information zu den vorhandenen Inhalten. Falls nichts anderes angegeben ist, werden Texte als fixe Bausteine ins Locale File übernommen.

- Das Logo muss in allen Sprachen aus den entsprechenden SVG Dateien in app/assets/images in ein PNG mit einer passenden Grösse konvertiert werden und ebenfalls ins Git eingecheckt werden. Achtung, ein PNG sollte etwa doppelt so viele Pixel haben, wie es im PDF in Punkten gerendert wird. Wir verzichten hier auf den Einbau vom prawn-svg Gem.
- "SAC Kurse / Touren [Jahr]": Jahr entspricht dem Jahr des ersten Kursdatums.
- "Hallo [Vorname]": Vorname der Person, für welche das Eckdatenblatt generiert wird.
- *Veranstaltungs-Nr.*: Kursnummer
- *Bezeichnung / Titel*: Kursname
- *Angebot / Stufe*: Label Kursstufe (level via event kind)
- *Leitung*: Name aller Personen mit Rolle Hauptleitung, kommagetrennt
- Block mit "Tageshonorar" usw: siehe unten
- *Durchführungsdatum*: Alle Kursdaten, pro Bereich eine Zeile
- *Durchführungsort*: Alle Orte aus den Kursdaten, pro Ort eine Zeile
- *Unterkunft*: Falls Flag `reserve_accommodation` true: "Wird reserviert durch SAC"; sonst "Wird reserviert durch Kursleitung"
- *Unterkunft Budget*: siehe unten
- *Unterkunft Kategorie*: Übersetztes Label aus Kurs Accommodation
- *Durchführungssprache*: Übersetztes Label aus Kurs Sprache
- *Inhalt / Programm*: Fixtext, übersetzt
- *Teilnehmeranforderungen*: Fixtext, übersetzt
- *Detailprogramm Teilnehmer Kurse*: Fixtext, übersetzt
- *Detailprogramm Teilnehmer Touren*: Fixtext, übersetzt
- *Anmeldeschluss*: Datum aus Kurs Anmeldeschluss (nicht wie PDF "28 Tage vor ...")
- *Minimale Teilnehmerzahl*: Attribut Kurs
- *Maximale Teilnehmerzahl*: Attribut Kurs
- *Durchführung - ja/nein?*: Fixtext, übersetzt
- *Durchführung – Absage*: Fixtext, übersetzt
- *Ideale Klassengrösse*: Attribut Kurs
- *Maximale Klassengrösse*: Attribut Kurs
- *Klassenlehrer*: Fixtext, übersetzt

### Tageshonorar Block

In der Kursart sind Vergütungskategorien (`course_compensation_categories`) zugewiesen. Falls diese am Datum des ersten Kurstages einen gültigen Vergütungsansatz haben, werden sie hier angezeigt, sonst nicht. Jede Kategorie wird auf einer eigenen Zeile dargestellt. Die Spalten aus dem PDF werden beibehalten, ausser "à CHF" wird zusammengeführt. Die Spaltenbreiten können so gewählt werden, dass es ausser in der ersten Spalte keine Zeilenumbrüche gibt (Achtung unterschiedliche Sprachen, allenfalls Text Width in Prawn berechnen (`cell.natural_content_width`)).

Je nach der Rolle der Person, für welche das Eckdatenblatt erzeugt wird, wir als Label in der ersten Spalte das Attribut `name_leader` oder `name_assistant_leader` in der entsprechenden Sprache angezeigt. Als Betrag wird die entsprechende `rate` auf dem gültigen Vergütungsansatz verwendet.

Zuerst werden die Kategorien mit Art Tag  (kind day) aufgelistet. Die Anzahl Tage wird als Summe aller Tage aller Kursdaten berechnet. Falls ein Kurs am Abend beginnt (`start_point_of_time == :evening`), wird ein halber Tag abgezogen. Die Zeiten der Kursdaten sind also nicht relevant. 

Danach werden die Kategorien mit Art Pauschal  (kind flat) aufgelistet. Die Anzahl Tage ist immer 1.0

Pro Art werden die Kategorien nach dem `short_name` sortiert.

### Unterkunft Budget Block

Ahnlich wie im Tageshonorar Block werden hier die zugeteilten Kategorien mit Art Budget (kind budget) aufgelistet, welche einen gültigen Ansatz haben. Dies ist neu ebenfalls möglich. Anders als in der Vorlage wird pro Kategorie eine Zeile gerendert (aus der Vorlage wären "SAC Hütte" und "Hotel / Pension" je eine Zeile). Entsprechend hat jede Zeile 3 Spalten. Die Kategorien werden nach dem `short_name` sortiert.

# ToDo

- [x] Domainklasse für PDF erstellen
- [x] View/Controller anpassen
- [x] Specs schreiben
- [x] Mit angemessener Rolle "durchklicken"

**Comment by tobiasstern** [comment]
Hallo, wurde dieser Teil bewusst nicht gemacht?:

`Die Darstellung der Anhänge eines Anlass soll im Core in eine Tabelle überführt werden, damit die Sichtbarkeits-Icons und das Löschen Icon über alle Anhänge ausgerichtet sind. Die Breite der Tabelle soll dynamisch sein, kann also bei kurzen Dateinamen relativ schmall sein, bei längeren Dateinamen breiter. Ansonsten soll kein Styling auf der Tabelle sein (kein Rand, kein zusätzliches Padding, keine Hintergrundfarben), so dass die Liste bis auf die Ausrichtung der Icons gleich aussieht wie bisher.`

**Comment by tobiasstern** [comment]
Im Block Tageshonorar gibt es noch zu verbessern.

Vorlage ist so:
![Image](https://github.com/user-attachments/assets/ae9a3a6f-8c29-4e6f-928b-20ed3ba7b4b3)

Umgesetzt ist es aktuell so:
![Image](https://github.com/user-attachments/assets/2ccf438f-55cb-4995-a40c-a8b2c4a57e1b)

1. Die Extra-Zeile Tageshonorar braucht es mMn nicht.
2. Die Breiten der Spalten/Zellen so wählen, dass die drei rechts immer gleich breit und untereinander aligniert sind.

**Comment by tobiasstern** [comment]
Warum wurde das so umgesetzt, sie Bild?
![Image](https://github.com/user-attachments/assets/e263596d-bd26-4ba0-94a8-f6549651a6fa)

Eine extra Spalte für den Knopf ist nicht sinnvoll, das braucht nur Platz.

Besser wäre wie hier spezifiziert auf den Anmeldungen selber ein entsprechender Button, vgl Spez:

`Auf der Seite der Teilnahme wird zuhinterst ein neuer Button "Eckdatenblatt erzeugen" hinzugefügt, falls die Person entweder die Rolle Hauptleitung/Kursleitung oder Leitung/Klassenleitung hat.`

**Comment by Largo** [comment]
@TheWalkingLeek 

Wenn man das Fenster etwas zusammenschiebt sieht es so aus. Vielleicht sollte man das noch verbessern.
![image](https://github.com/user-attachments/assets/6b32b454-d1ac-4cf5-8897-6b8abecfd4cf)

**Comment by tobiasstern** [comment]
@Largo Du musst die Spalte dafür noch anwählen in der Spalten-Auswahl und dann wird der Button nur für Personen mit Leitungs-Rolle angezeigt, siehe z.b. hier https://sac-cas.puzzle.ch/de/groups/1/events/65/participations?returning=true

**Comment by tobiasstern** [comment]
Es gibt noch ein Fehler. Auf dem Kurs hier https://sac-cas.puzzle.ch/de/groups/1/events/9 kann man den Kurs nicht mehr sehen (Error 500), weil ich ein Eckdatenblatt erzeugt habe.

Niklas hatte mir vorhin da das Attachment weggelöscht, damit der Kurs wieder angezeigt werden konnte aber nachdem ich wieder den Button fürs Eckdatenblatt geklickt habe, ist der Kurs wieder kaputt :(

**Comment by codez** [comment]
Mit der Gefahr, dass ich nochmals reingrätsche, obwohl ihr das jetzt anders abgemacht hat: 

Der Button für um das Eckdatenblatt zu erzeugen sollte nur in der Button Liste auf der Info Seite einer Leitungsperson angezeigt werden (dort wo u.a. Bearbeiten, Drucken oder Kontaktdaten ändern sind. Die Spalte auf der Tabelle braucht es nicht und macht imho auch überhaupt nicht Sinn. Ändert das doch bitte noch und entfernt die Spalte auf der Liste.

Bitte lest doch jeweils die Spez etwas genauer durch und meldet euch beim Lead Dev, falls noch Unklarheiten bestehen. Z.B. hier: "Auf der Seite der Teilnahme" -> Das ist Einzahl, also geht es nicht um die Liste, sondern um die Show Seite. "ein neuer Button" -> In der Liste wurde jetzt ein Icon umgesetzt, und nicht ein Button. hitobito verwendet grundsätzlich für Aktionen Buttons und nicht einfach Icons.

**Comment by tobiasstern** [comment]
> Es gibt noch ein Fehler. Auf dem Kurs hier https://sac-cas.puzzle.ch/de/groups/1/events/9 kann man den Kurs nicht mehr sehen (Error 500), weil ich ein Eckdatenblatt erzeugt habe.
> 
> Niklas hatte mir vorhin da das Attachment weggelöscht, damit der Kurs wieder angezeigt werden konnte aber nachdem ich wieder den Button fürs Eckdatenblatt geklickt habe, ist der Kurs wieder kaputt :(

Hier wurde mittlerweile in einem anderen Ticket gearbeitet: #1188  Ev. löst dies den Punkt?

**Comment by Largo** [comment]
- [x] Eckdatenblatt auf der Teilnahme
