### ISSUE TITLE
PEOPLE: Import `7_wso2_people` Nachbesserungen

### ISSUE THREAD

**Issue by rnestler** [hitobito/hitobito_sac_cas#998]
Dies ist ein follow up von https://github.com/hitobito/hitobito_sac_cas/issues/772 um die offenen Punkte abzuschliessen

# Tech-Spec

## Telefonnummern

Offene Frage an SAC:
Im WSO2 Export gibt es die Felder TelefonMobil und TelefonG. Beim NAV1 haben wir nur noch ein Telefonattribut, welches wir auf Hauptnummer in Hitobito mappen. Sollen wir TelefonMobil auf Hauptnummer und TelefonG auf Arbeit mappen?

Antwort:
> WSO2 TelefonMobil wird auf Hauptnummer und TelefonG auf Arbeit gemappt.

## Gruppen

Offene Frage an SAC:
Vor dem WSO2 Import wird ein Import aus NAV1 gemacht. Diese Personen werden in die Primärgruppe Externe Kontakte / Navision Import abgelegt. Wenn später eine Rolle beim NAV2 Import festgelegt wird, wird diese Rolle entfernt. Soll dies beim WSO2 Import auch geschehen?

Antwort:

> Ja, sofern aus dem WSO2 Import eine Rolle festgelegt wird, kann die Person analog NAV1 aus der Gruppe Navision Import entfernt werden

## Warnung nicht verifizierte E-Mail

Falls die E-Mail Adresse nicht verifiziert ist, importieren wir das WSO2 Passwort denoch, erstellen aber einen Logeintrag (Report) als Info (spezielle Fehlermeldung)..

# ToDo

- [x] Abklären wie Telefonnummern importiert werden sollen und anpassen
- [x] Telefonnummern mappen
- [x] Abklären wie Gruppen importiert werden sollen und anpassen
- [x] Gruppen ggf. entfernen
- [x] Warnung im Report bei nicht verifizierter E-Mail Adresse
